### ISSUE TITLE
Support view-property like in the angular ui router module

### ISSUE THREAD

**Issue by bastienJS** [aurelia/router#104]
I haven`t found any information how to do that in aurelia.

if you regard that image you see that only when welcome-state is active the navbar has other elements visible.

The other elements does not need to be in the root navbar. They could also be put at the bottom or somewhere... Therefore I want to define for a certain state to render multiple html files at different positions of the screen.

In angularjs ui router this is possible with the views-property of the ui router.

see https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views

And No, I do not want to put the documents and favorites buttons in the content side under the welcome navbar button. I do NOT want to have hierarchy in the UI NAVIGATION.

And No the compose binding does not help here. I want to put e.g. 3 different xxx.html files at 3 different locations.

![image](https://cloud.githubusercontent.com/assets/5945955/7783340/8f8ce248-013f-11e5-971f-7708178408f4.png)

**Comment by tomasbonco** [comment]
Based on [Gitter discussion](https://gitter.im/Aurelia/Discuss?at=55605db1c13de0840ffc2e1d) this is propose to name `route-view`:
```
<route-view name="first"></route-view>
<route-view name="second"></route-view>
```

Then router might like like this (I guess):
```
{ route: ['', 'home'], moduleId: { first: './home/index', second: './home/second' },
```

**Comment by bastienJS** [comment]
You can play around with this old angular bug fiddle to get a feeling what I mean.

http://run.plnkr.co/GvXSO5CxcH8FQMES/#/projects

Just open a project via selecting a project and click open button.  Then the dateplanner is loaded. ONLY when the dateplanner is loaded I have the navigation on the top-right div.

This is what I wanna do with aurelia too.

**Comment by EisenbergEffect** [comment]
The router supports this already. First, add multiple router-view elements, each with a name. Then, you need to configure your router with view ports:

```
{
route: 'someRoute'
viewPorts = {
        'default': {
          moduleId: instruction.config.moduleId
        }
}
```

Above is what ends up getting generated by default. To add your own view ports, just provide the `viewPorts` property on a route config and then one key per named router view. The value of each key should be a config object that specifies the moduleId minimally.

**Comment by bryanrsmith** [comment]
Added basic docs for this in aurelia/documentation#96
