### ISSUE TITLE
Routing generate will encode keys

### ISSUE THREAD

**Issue by jadrake75** [aurelia/router#108]
Many web-services that support frameworks like ODATA Queries using "$" in the keys.   This is getting incorrectly encoded. 

For example:
```javascript
this.router.navigate(this.router.generate('stamp-list', { $filter: opts.$filter }));
```

In this case `opts.$filter` would be something like `(countryRef eq 5056)` so I expect this to be encoded to `(countryRef%20eq%205056)` but the key $filter should still be $filter I believe.  Using an expressJS backend, the request.query object will contain the raw objects (it does not decode keys) but it does decode the values.  Thus the query is not found since the server is receiving the query parameter as `%24filter` instead of `$filter`

**Comment by jadrake75** [comment]
Out of curiosity - I looked up the Query specification in W3C http://www.w3.org/TR/url/

* 3.For each byte in buffer run these subsubsteps: 
    * 1.If byte is less than 0x21, greater than 0x7E, or is one of 0x22, 0x23, 0x3C, 0x3E, and 0x60, append byte, percent encoded, to url’s query. 
    * 2.Otherwise, append a code point whose value is byte to url’s query. 

So as you can see the "$" should not be encoded.

**Comment by bryanrsmith** [comment]
Hmm. We're just using `encodeURIComponent`, which encodes `$`. From what I can tell it's standard behavior in an HTTP client. A quick Google search reveals a lot of people using ODATA complaining about it, though, and having to use string concatenation to build their query strings. As you suggest, it does look safe to include unencoded. We can probably just make an exception for `$` and replace it's encoded value of `%24` back to `$`.

**Comment by jadrake75** [comment]
The key would be only for keys though.  You'd still likely want to encode values as %24, although there likely would not be a lot of harm.

encodeURI and encodeURIComponent as you say are inherently grumbled about.  Over the past 15 years I have probably introduced a custom encoder at least a few times at various companies for these kinds of issues.
