### ISSUE TITLE
Router only adds querystring parameters that are defined in the route to lifecycleArgs

### ISSUE THREAD

**Issue by tyrsius** [aurelia/router#11]
The router does not deserialize the entire querystring, which would allow for dynamic viewmodel activation arguments.

**Comment by tyrsius** [comment]
So I think the issue is [here](https://github.com/aurelia/router/blob/master/src%2Frouter.js#L117-L124)

The `results` object is an array which also has a `queryParams` property on it with the properly parsed queryString object. However, the `NavigationInstruction` is being created with `queryParams` from the first result in the `results` array. I think the correct thing to do is use the `results.queryParams`, but I am not sure if that would cause a breaking change.

**Comment by EisenbergEffect** [comment]
What if we did this: `first.queryParams || results.queryParams` ?
