### ISSUE TITLE
double // in routes when fragment contains / in it.

### ISSUE THREAD

**Issue by jadrake75** [aurelia/router#111]
Using 0.8.1 of Router, I was noticing some // showing up in the router paths.  Things seemed to be working correctly but I had a tingling feeling something was off.

in Router.prototype.createRootedPath I am seeing the following with these inputs.... 
baseUrl; "details/"
fragment: "/some-dynamic-name"

The output is

"/details//some-dynamic-name"

I believe another condition is needed below the lines

if( path[path.length-1] != '/' && fragment[0] != '/') { // shouldn't these be !== ?
   path += '/';
}
// new line proposed
else if (path[path.length-1] === '/' && fragment[0] === '/' ) {
   fragment = fragment.substring(1); // prune off first "/"
}

**Comment by bryanrsmith** [comment]
What API were you using to build the path? Or were you calling it directly? I thought that method was only used with fragments that are known to be relative. That is, that fragment shouldn't make it into the method because it's an absolute path.

**Comment by jadrake75** [comment]
Just realized I never got back to you on this.  

```
that.router.navigateToRoute( 'details-view', { name: name} );
```
where 'details-views' is 
```
configureRouter(config, router) {
        this.router = router;
        config.map([
            {route: ['',':name'], moduleId: './details-view', name: 'details-view', nav: false, title: 'General Information'}
        ]);
    }
```
and the name is just the models name (for example "IQ Analyzer")
