### ISSUE TITLE
Router can't generate correct fragments before navigation is committed

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#113]
Reported by @jadrake75 in #110:

Also if you need to redirect a route in activate (for example, detect a "last visited object and set that on the route path" you have to call the navigateToRoute( ) in a timeout after activate completes or it will remove the current route path.

ie. if the current view-model is mapped to

/details

and has a sub-route that is dynamic such as :name then if you attempt to call navigateToRoute inside Activate instead of getting a full route path of

/#/details/some_name

You get

#/some_name

Placing it in a timeout works, but ideally there should be away to redirect before or during activation.

**Comment by bryanrsmith** [comment]
This happens because the router's baseUrl doesn't get set until the navigation has been committed. I had to work around this issue in [#109](https://github.com/aurelia/router/pull/109#discussion_r30994603), but we really need it to work right here.

@EisenbergEffect can we set the router's baseUrl earlier in the pipeline so it's correct when we reach activation?

**Comment by EisenbergEffect** [comment]
@bryanrsmith We should be able to do that. You'll need to add that calculation at some point earlier in the navigation pipeline.

**Comment by Mordred** [comment]
Is there any progress with this issue? Because of this bug I have to manually write urls using `href.bind`

**Comment by heruan** [comment]
Same here, @Mordred. In #306 it was declared as high-priority, I'm looking for updates too.

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung With the merge of the recent PRs around url calculation, how difficult would it be to implement this fix?

**Comment by EisenbergEffect** [comment]
Closing this as a duplicate.
