### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by maxgrv** [aurelia/router#121]
After updating aurelia today my app does not work anymore: when the main router starts, I get the following error:

    Unhandled promise rejection Error: History must implement activate().
    at History.activate (http://localhost:9000/jspm_packages/github/aurelia/history@0.5.0/index.js:18:17)
    at AppRouter.activate (http://localhost:9000/jspm_packages/github/aurelia/router@0.9.0/app-router.js:187:24)
    at http://localhost:9000/jspm_packages/github/aurelia/router@0.9.0/app-router.js:170:24
    at run (http://localhost:9000/jspm_packages/npm/core-js@0.9.15/modules/es6.promise.js:83:43)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.15/modules/es6.promise.js:97:11
    at module.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.15/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.15/modules/$.task.js:42:9)
    at Number.run (http://localhost:9000/jspm_packages/npm/core-js@0.9.15/modules/$.task.js:29:7)
    at listner (http://localhost:9000/jspm_packages/npm/core-js@0.9.15/modules/$.task.js:33:9)

Am I doing something wrong?

Thanks

**Comment by PWKad** [comment]
@maxgrv Is this a public repo you can share?  Been trying to reproduce this morning with no luck.

**Comment by maxgrv** [comment]
Unfortunately not, it is a company project su the repo is private. I can send you a zip file with a stripped version privately if it is of any use to you .

**Comment by maxgrv** [comment]
I have prepared a zip file with a version which still shows the error but does not contain much company code. Can I send you a drobpox link privately?

**Comment by EisenbergEffect** [comment]
I believe it's a configuration issue. There was a breaking change that was accidentally left out of the blog post. I've updated it to include notes on how to fix this I believe. Please read the breaking changes section here: http://blog.durandal.io/2015/06/09/aurelia-early-june-release/

**Comment by PWKad** [comment]
@maxgrv Thanks for taking the time to put the zip together, after I asked for the repro Rob did identify that change and update the post like he mentioned so it should be good to go!  If not let us know, thanks again.

**Comment by maxgrv** [comment]
It was the missing config :)

**Comment by shaunluttin** [comment]
We're experiencing this problem and are using `.standardConfiguration`.

**Comment by EisenbergEffect** [comment]
Check to see if you have version forks. Jspm can do this sometimes and it results in this type of erroneous behavior.

**Comment by shaunluttin** [comment]
What is a version fork?

**Comment by EisenbergEffect** [comment]
It means you have two versions of the same library somehow. I believe `jspm -forks` will show them to you.

**Comment by shaunluttin** [comment]
```
 "jspm": {
    "dependencies": {
      "aurelia-animator-css": "npm:aurelia-animator-css@^1.0.0-beta.1.1.2",
      "aurelia-auth": "npm:aurelia-auth@^3.0.1",
      "aurelia-bootstrapper": "npm:aurelia-bootstrapper@^1.0.0-beta.1.1.4",
      "aurelia-fetch-client": "npm:aurelia-fetch-client@^1.0.0-beta.1.1.1",
      "aurelia-framework": "npm:aurelia-framework@^1.0.0-beta.1.1.4",
      "aurelia-history-browser": "npm:aurelia-history-browser@^1.0.0-beta.1.1.4",
      "aurelia-loader-default": "npm:aurelia-loader-default@^1.0.0-beta.1.1.3",
      "aurelia-logging-console": "npm:aurelia-logging-console@^1.0.0-beta.1.1.4",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@^1.0.0-beta.1.1.4",
      "aurelia-polyfills": "npm:aurelia-polyfills@^1.0.0-beta.1.0.3",
      "aurelia-router": "npm:aurelia-router@^1.0.0-beta.1.1.3",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@^1.0.0-beta.1.1.2",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@^1.0.0-beta.1.1.3",
      "aurelia-templating-router": "npm:aurelia-templating-router@^1.0.0-beta.1.1.2",
      "fetch": "github:github/fetch@^0.11.0",
      "jquery": "npm:jquery@^2.2.3",
      "shaunluttin/aurelia-leaflet": "github:shaunluttin/aurelia-leaflet@^0.1.2",
      "text": "github:systemjs/plugin-text@^0.0.3",
      "twbs/bootstrap": "github:twbs/bootstrap@4.0.0-alpha.2"
    },
```

**Comment by shaunluttin** [comment]
```
$ jspm inspect --forks
     Installed Forks

         npm:aurelia-dependency-injection 1.0.0-beta.1.2.3 1.0.0-beta.2.1.0
             npm:aurelia-event-aggregator 1.0.0-beta.1.2.1 1.0.0-beta.2.0.0
                      npm:aurelia-history 1.0.0-beta.1.2.1 1.0.0-beta.2.0.0
                      npm:aurelia-logging 1.0.0-beta.1.2.1 1.0.0-beta.2.0.0
                         npm:aurelia-path 1.0.0-beta.1.2.2 1.0.0-beta.2.0.0

     To inspect individual package constraints, use jspm inspect registry:name.
```

**Comment by EisenbergEffect** [comment]
Yes, you've got multiple versions loading there. You need to resolve the forks be removing the old versions. Try a `jspm clean` first to see if it does that for you. If not, go into the config.js and update the version numbers to only use the latest. Sorry about this...it's a problem with jspm we're not fond of.

**Comment by shaunluttin** [comment]
Does `jspm resolve` help with this?

**Comment by EisenbergEffect** [comment]
That sounds reasonable. I haven't tried that myself.

**Comment by shaunluttin** [comment]
It seems to work.

# Find Forks

```
$ jspm inspect --forks
     Installed Forks

         npm:aurelia-dependency-injection 1.0.0-beta.1.2.3 1.0.0-beta.2.1.0
             npm:aurelia-event-aggregator 1.0.0-beta.1.2.1 1.0.0-beta.2.0.0
                      npm:aurelia-history 1.0.0-beta.1.2.1 1.0.0-beta.2.0.0
                      npm:aurelia-logging 1.0.0-beta.1.2.1 1.0.0-beta.2.0.0
                         npm:aurelia-path 1.0.0-beta.1.2.2 1.0.0-beta.2.0.0

     To inspect individual package constraints, use jspm inspect registry:name.
```

# Resolve Forks

```
$ jspm resolve --only npm:aurelia-dependency-injection@1.0.0-beta.2.1.0
$ jspm resolve --only npm:aurelia-event-aggregator@1.0.0-beta.2.0.0
$ jspm resolve --only npm:aurelia-history@1.0.0-beta.2.0.0
$ jspm resolve --only npm:aurelia-logging@1.0.0-beta.2.0.0
$ jspm resolve --only npm:aurelia-path@1.0.0-beta.2.0.0
```
