### ISSUE TITLE
There was no router-view found in the view for ./index

### ISSUE THREAD

**Issue by dpinart** [aurelia/router#122]
Hi,
I have created a 3 child routing navigation hierarchy:
1)Main router contains 2 routes: 
     app(default)
     login
2) app contains a child router that defines 2 routes
    module 1(default)
    module 2
3) module1 contains another child router that defines 3 routes: route1(default), route2 and route3

at app view, I have a navigation bar with 2 links:
    #app/module1
   #app/module2
After login, app navigates to default route (#) so app/module/view1 view is displayed.
I can navigate to module2 by clicking on 2nd link in navigation bar, but as soon I navigate back or click on first link in navigation bar I get the following error : "There was no router-view found in the view for ./index" (index is the default view for #app/module/1

Any idea about why I'm getting this error?

**Comment by bryanrsmith** [comment]
@dpinart This sounds like it might be a duplicate of #27-- we currently have some issues with using child routers under "default" or empty string routes. If you think that sounds like the problem you're having, I'll go ahead and close this one. If not, would you be able to provide a plunker that demonstrates the problem you're seeing?

**Comment by dpinart** [comment]
@bryanrsmith thanks for your response. To be honest, I'm not quite sure this issue might be a duplicate of #27. I have tried to get rid of default or empty string routes but the problem persists. I've been able to reproduce the error in a plunker: http://plnkr.co/edit/XJRDlN?p=preview. Just run the plunker and clik on 'module2' link. That's enough to reproduce the error

**Comment by bryanrsmith** [comment]
Thanks a lot for the repro; that's very helpful. I'll try to dig in soon.

**Comment by dpinart** [comment]
Hi, it seems this bug still persists in latest version of aurelia-router plugin. Can you supply a workaround for this issue?

Thanks

**Comment by dpinart** [comment]
I finally found the issue. I had the 3 level router-view inside a div with an if.bind. Changing if.bindby show.bind fixed the issue.

So there's no a bug but my mistake!

**Comment by bryanrsmith** [comment]
Great! Glad it was an easy fix.

**Comment by TheOnlyJohnHancock** [comment]
Hi,

This same issue is plaguing me at the moment. I don't know what I have broken because it was working initially. It only happens on child-route.

Any suggestions would be greatly appreciated?

![image](https://cloud.githubusercontent.com/assets/20421142/16769414/7663a972-47fd-11e6-8059-2885b9066088.png)

**Comment by EisenbergEffect** [comment]
This literally means that in your view, you forgot to add a `router-view` element to indicate where to render the route.

**Comment by TheOnlyJohnHancock** [comment]
of course!!! Thanks very much, I did not pick up on that one.
