### ISSUE TITLE
router.navigate('route') doesn't return a promise anymore

### ISSUE THREAD

**Issue by flieks** [aurelia/router#123]
in old release i had this working
```
router.navigate("machine");
.then(function () {
         ea.sendMessage("loadItems", "loadItems");
});
```
i jspm installed all packages and it doesn't work anymore

**Comment by bryanrsmith** [comment]
@flieks I'm not seeing this behavior-- I still get a promise. Would you be able to provide a [Plunker](http://plnkr.co/edit/sak5db) that demonstrates the problem you're seeing?

**Comment by flieks** [comment]
indeed, it works now.  Thanks and sorry for the issue
