### ISSUE TITLE
route-href doesn't work for child routes

### ISSUE THREAD

**Issue by flieks** [aurelia/router#128]
```
<a route-href="route:parent/child;  params.bind:{id:item.id}"></a>
```
this doesn't work. 
error `Unexpected token` in chrome
maybe it's not implemented yet so it's a feature request..

**Comment by EisenbergEffect** [comment]
You will need to add a name property to the route in your route config. Then you should reference that from the route-href: `route-href="route: theNameYouChose; params.bind:{id:item.id}"`

**Comment by flieks** [comment]
@EisenbergEffect but if the child router isn't loaded yet (because we didn't navigate yet to the page) then the routes aren't registered yet and the name can't be found. I just tested: 
`Error: There is no route named contactdetail`

**Comment by bryanrsmith** [comment]
#89 is open for that issue. There is currently no way to generate using routes by sibling or child routers.

**Comment by flieks** [comment]
thanks bryan
