### ISSUE TITLE
Consider adding a templateUrl property to the router configuration to override the convention

### ISSUE THREAD

**Issue by petermorlion** [aurelia/router#131]
I know you can provide your own convention via `ConventionalViewStrategy.convertModuleIdToViewUrl`, but would it not be interesting to be able to override the view url for specific views?

Similar to the `templateUrl` property in Angular, where you can do:

    $routeProvider.
      when('/phones', {
        templateUrl: 'partials/phone-list.html',
        controller: 'PhoneListCtrl'
      }).
      when('/phones/:phoneId', {
        templateUrl: 'partials/phone-detail.html',
        controller: 'PhoneDetailCtrl'
      }).
      otherwise({
        redirectTo: '/phones'
      });

In Aurelia, I would like to do something like:

    router.configure(config => {
            config.map([
              { route: ['','page1'],  moduleId: './page1' },
              { route: ['page2'],  moduleId: './page2', templateUrl: './api/page2 }
            ]);
        });

Page1 would be found at http://www.example.com/page1.html, but page2 at http://www.example.com/api/page2

In my case, when using Aurelia with ASP.NET, I could call a standard Controller/View combination and have some rendering already done at the server-side.

My current alternative is to have something like this in the convention function:

    ConventionalViewStrategy.convertModuleIdToViewUrl = function(moduleId){
        if (moduleId === 'page2') {
            return 'api/page2';
        }  

           return moduleId + '.html';
    }

**Comment by EisenbergEffect** [comment]
You can use the `viewStrategy` property on a route config object. It can be either a relative url to the view or it can be an instance of a view strategy.

**Comment by petermorlion** [comment]
I'm not sure I understand exactly where I find this property.

I have found the possibility to add a `getViewStrategy` function to the viewmodel. But I find that is coupling my VM to much to my View. Plus it puts the mapping of a route to its view URL in multiple locations in my app:

 - In app.js where I configure my router
 - In my viewmodels where I want to override the default behavior

Having a viewStrategy on my route config object would be nice, but I can't get it to work. I've tried this for example:

    export class App {
        configureRouter(config, router){
        config.title = 'Aurelia';
        config.map([
          { route: ['','welcome'],  moduleId: './welcome',      nav: true, title:'Welcome' },
      
          { route: 'flickr',        
            moduleId: './flickr',       
            nav: true, title:'Flickr',      
            viewStrategy:'./new-flickr.html'},
        
          { route: 'child-router',  moduleId: './child-router', nav: true, title:'Child Router' }
        ]);
    
        this.router = router;   
      }
    }

Here, I would want Aurelia to use `./new-flickr.html` as the template for the Flickr page.

So I'm guessing I'm looking in the wrong place?

**Comment by EisenbergEffect** [comment]
No, that should work. Let me double check.

**Comment by petermorlion** [comment]
I've made a [Plunker for this](http://plnkr.co/edit/K9qUjS?p=info).
