### ISSUE TITLE
Error using viewPorts and child router

### ISSUE THREAD

**Issue by ceoaliongroo** [aurelia/router#134]
Hi,  

I have a router with viewPorts:
__app.js__ 
```javascript
  ...
  config.map([
      {
        route: ['', 'home'],
        name:'home',
        viewPorts:{
          content: {
            moduleId: 'dashboard/cockpit'
          },
          menu: {
            moduleId: 'menu/menu-options'
          }
        },
        title:'Home'}
    ]);
 ...
```
app.html
```html
   ...
  <div class="page-host menu">
    <router-view name="menu"></router-view>
  </div>
  <div class="page-host content">
    <router-view name="content"></router-view>
  </div>
  ...
```

and a child route:
__cockpit.js__
```javascript
    ...
    config.map([
      {
        route: ['', 'subscribers'],
        name:'subscribers',
        viewPorts: {
          test: {
            moduleId: 'dashboard/subscription/list'
          }
        },
        title:'Subscribers'
      }
    ]);
   ...
```
__cockpit.html__
```html
  ...
  <router-view name="test"></router-view>
  ...
```

I receive the error 
```javascript
There was no router-view found in the view for dashboard/subscription/list
```

if you want to check [all the code](https://github.com/ceoaliongroo/sandbox-aurelia/tree/issue-router-viewPorts%2BchildRoute)

**Comment by bryanrsmith** [comment]
@ceoaliongroo I'm not sure I understand the problem. I can't seem to get any error to appear by using your sample app. Also, it looks like your dashboard/subscription/list.html has a `<router-view>` element, but the view model in list.js does not configure a router that uses it.

Could you tell me the steps to reproduce the error in your app?

**Comment by ceoaliongroo** [comment]
Yes, i think i had an error in dependencies, sorry. 
I'll fixed  https://github.com/ceoaliongroo/sandbox-aurelia/commit/fe6b6dc5b3a05fed95d3394a84d856a6041f25f0

try, again with:

```bash
git checkout issue-router-viewPorts+childRoute
git pull
jspm install -y
```
You could see something like this:
![screen shot 2015-06-29 at 10 23 26 am](https://cloud.githubusercontent.com/assets/2622152/8403031/d351f83e-1e49-11e5-91e0-c1521b5a7c5a.png)
![screen shot 2015-06-29 at 10 24 28 am](https://cloud.githubusercontent.com/assets/2622152/8403075/066a5b1c-1e4a-11e5-8407-6e8e3743c9a6.png)
