### ISSUE TITLE
childRouter is instantiated again if you navigate away from the child router and return back on a singleton VM

### ISSUE THREAD

**Issue by npelletm** [aurelia/router#139]
From the gitter :
I have a child router in a decorated @singleton() VM class, the VM is not recreated, the View is created again but it doesn't matter.
The main issue is the child router is instantiated again if you navigate away from the child router and return back to this VM.
How avoid this child router to be instanciated again, and reset by configureRouter function call ?

**Comment by bryanrsmith** [comment]
@EisenbergEffect We could probably solve the problem of configuring routers in singleton VMs by caching routers in a `WeakMap`. Should we consider ways to support caching child routers configured by transient VMs? Perhaps a static `configureRouter` method could indicate that the configuration will not change between activations, and is safe to cache?

**Comment by bryanrsmith** [comment]
#90 will let us avoid reconfiguring child routers. I'm going to close this issue in favor of that one.
