### ISSUE TITLE
activate() multiple resolvs

### ISSUE THREAD

**Issue by Serhioromano** [aurelia/router#14]
I cannot figure out how I would resolve few HTTP requests? I return only one right?

```js
activate(){
  return this.http.jsonp(url).then(response => {
    this.images = response.content.items;
  });
}
```

But what if I need to resolve 4 `http` get requests before show navigation? I need to get items, categories, user parameters, ... all before display route.

**Comment by EisenbergEffect** [comment]
You are in luck :smile: There are lots of ways to compose promises together and the Promise spec has a helper method to do exactly what you want. First make each http request and store the returned promise in an array. Then return the aggregate by using the `Promise.all()` helper. This will create a promise that resolves when all supplied promises have resolved.
Something like this:

```javascript
return Promise.all([
    this.http.get().then(response = > { ... }),
    this.http.get().then(response = > { ... }),
    this.http.get().then(response = > { ... }),
    this.http.get().then(response = > { ... })
]);
```

You can create the promises any way you want, then just pass the array of them to the `all` helper.
