### ISSUE TITLE
PushState throwing security error

### ISSUE THREAD

**Issue by mttmccb** [aurelia/router#141]
I've updated my depedencies and have pushState enable. now I'm getting this error

    Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http://mentions/' cannot be created in a document with origin  'http://localhost:9000'.
    navigate @ index.js:195
    handleLinkClick @ index.js:1621

**Comment by EisenbergEffect** [comment]
@bryanrsmith Looks like push state may have had a regression...

**Comment by boxofnotgoodery** [comment]
I ran into this as well.
All was working as expected until the latest full update.

**Comment by Vheissu** [comment]
Experiencing the same issue here as well. There has definitely been a regression in the current update. I might dig deeper and see if I can help submit a PR to fix it when I get the time (if someone doesn't beat me to it).

**Comment by doeck** [comment]
I ran into this too when trying to set up pushstate.
The fix by @Vheissu worked for me, thanks!
