### ISSUE TITLE
Implement route navigation reorder method

### ISSUE THREAD

**Issue by ktomala** [aurelia/router#144]
I would like to discuss adding a method for reordering navigation. This method would be especially useful when dynamically loading routes from the server. When defining a set of routes that should always be available, you can load additional routes e.g. after user login. Since the user may have different ACL classes (like admin, editor, normal user, etc.), different sets of routes may be loaded from the server. 

Inside the router.addRoute method there is a mechanism for ordering based upon ```navModel.order``` variable which takes into account numeric ```nav``` property key from route config. However if the ```nav``` key is set to boolean, there is a router.fallbackOrder applied. This however causes routes loaded from the server to be appended to navigation, which is not always desirable. There is also one fact, that you could use ```nav``` key with numeric value inside the routes configuration loaded from the server, this would however interfere with already existing routes ordering. The ```fallbackOrder``` begins with 100. If there are existing routes with order from 100 to 105, and you load three routes from the server with ordering from 100 to 102, the router ```addRoute``` method won't take this into account and won't interpolate those numbers, resulting in a messed up navigation, unless you manually update the ```navModel.order``` for each route. 

I'd like to discuss the best approach for implementing the routes reordering method. One of the proposals is to have a method navigationReorder() that would take a list of route names as a first parameter, and an optional parameter for ordering start. Here's an example:
```
router.navigationReorder(['home', 'login', 'dashboard', 'logout'], 100);
```
In this case if any routes with ```nav: true``` are left out of this list, they would be reordered alphabetically and their order appended after the specified list of routes. However the sorting order of left out routes may also be taken in the order of their declaration. This is one case for the discussion. 

I believe that the approach for allowing specifying partial list of routes may be more flexible than requiring specifying all routes with positive ```nav``` value.

The other approach to implementing ```navigationReorder``` may be to pass a dictionary with key-value pairs, where key is a route name, and value is a numeric order like this:
```
router.navigationReorder({'home': 100, 'login': 101, 'dashboard': 102, 'logout': 103})
```
However I believe this approach is reduntant and not really necessary. Any left out routes would have the behavior as stated before.

I'd like to help with implementing this method, but before I do, I'd like to know opinions for the best approach to be taken. Discussion is very much welcome.

**Comment by bryanrsmith** [comment]
I think we discussed this a bit on gitter, but the router's nav model isn't well suited for more complicated scenarios.  I think it'd be best to add custom logic to the application to handle this and avoid adding too much specialized support to the core router. Closing for now, but happy to discuss further.
