### ISSUE TITLE
RouterConfiguration in aurelia-router.d.ts is missing properties.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/router#146]
Using TypeScript, I have a function like
```ts
public configureRouter(config: RouterConfiguration, router: Router) {
	config.title = 'foo';
}
```

The TypeScript compiler errors on `config.title` because the `RouterConfiguration` class doesn't have a `title` property on it.  In https://github.com/aurelia/router/blob/master/src/router-configuration.js#L63 we can see that title is an optional parameter, so it should be included in the d.ts as such.

I'm guessing that the d.ts auto-generator doesn't have the ability to see properties, so perhaps the right solution is to just add a set method like `setTitle(title)`.  This way, those using TypeScript can get some amount of static typing and don't have to resort to using `any` for their `configureRouter` method.

On a related note, ES6 supports the TypeScript type syntax without error.  For example, you could write an ES6 function that looks like this:
```js
exportToRouter(router: Router) {
	...
}
```
And it will compile just fine in ES6, with the type information simply ignored.  Perhaps in order to get better TypeScript typings the Aurelia ES6 source code could be annotated with type information where it is easy/reasonable.  Then the auto-generated d.ts files could have extended type information.

Alternatively, Aurelia could simply be migrated to TypeScript source base and transpiled to ES6.  ;)  I'm personally a big fan of this, though I'm guessing ES6 source was an intentional choice.

**Comment by Zoltu** [comment]
Now that I am using the Aurelia typings I'm likely going to run into a number of these situations.  Is this the appropriate way to communicate missing type information or is there another place I should bring up such concerns?

**Comment by EisenbergEffect** [comment]
Yes, this is a fine way to address that. Also, sending PRs is welcome.

**Comment by Zoltu** [comment]
I can submit a PR for this.  What is the preferred solution?  Adding a `set*` method in order to expose the title?  Are the d.ts files auto-generated (I am operating under the assumption that they are, but if not I can simply update them to be more accurate)?

**Comment by EisenbergEffect** [comment]
The d.ts files are auto-generated from the source. We've also set up the repos to use ES7 property initializers, so those can be used to solve this.
