### ISSUE TITLE
Dynamic Routes 

### ISSUE THREAD

**Issue by Serhioromano** [aurelia/router#15]
What I like about this framework is ability to load JS on the fly when you need it. Very good for large application as the one I plan to create.

In my mind I have modular application. And each module has it's own set of routes. But it always start with module name. Lets say I have module `acl`. Then routes will be `acl/rules`, `acl/rule/:id` and so on. 

So I always know where to look. I can analyze first element of the current route and know what module routes lo load. But.

1. How can create event where I do something before any route even analyzed so I can grub route, analie and load routs of that module that supposedly have to be in `acl/routes.js`.

2. How can I load and append to list of all routes before route is processed?

I think of some global main route and all the rest rotes make a children. Then in that route on `canActivate()` I can do something. But I am not sure if I am on the right track.

**Comment by EisenbergEffect** [comment]
To handle this you call this api:

```javascript
router.configure(config => {
      config.mapUnknownRoutes(instruction => {
        //read the instruction.fragement to get acl/rules...
        //set instruction.config.moduleId to the module you want to handle the request.

        return instruction;
      });
    });
```

If you need to do this asynchronously, you can also return a Promise for the instruction. Finally, by ultimately combining this with a bundling config via jspm you can put all your "acl" modules in a bundle and minimize on round trips for related functionality.

**Comment by Serhioromano** [comment]
Perfect. Thank you. Now I see how I can create router based application easily extendable by convention. Like you create URL like 

    [module name]/[moduleId]/[params]

where `moduleId` is 2 segment value for better organization.

    acl/users/list/role/10

This will be JS in `modules/acl/routes/users/list.js` and `role/10` will be a parameters. 

I like it so far.

**Comment by EisenbergEffect** [comment]
Yep. If you can decide on a convention for your app, you can easily to the interpretation dynamically just like that.

**Comment by shabanamukhtar** [comment]
Hello,

I was trying on the same lines. That is,
1. Different bundles for different modules (aurelia-bundling)
2. Use dynamic routing to load routes

It seemed to work initially. But with new skeleton-navigation, the instruction.config is null.
