### ISSUE TITLE
Please add router.activeRoute

### ISSUE THREAD

**Issue by lukehutch** [aurelia/router#153]
Currently (as far as I can tell) the only way to get the active route in declarative syntax is by using a repeat.for="route of router.routes" expression with the "route.isActive" binding expression. This is fine if you need to do something with all the routes, but it's wasteful when you need a property from only the active route, such as the title:

```html
<p repeat.for="route of router.routes" if.bind="route.isActive">${route.title}</p>
```

A better option would be:

```html
<p>${router.activeRoute.title}</p>
```

The current router.routes and router.navigation arrays are also harder to use in combination with route.settings when you want to extract a setting from only the currently-active route:

```html
<div repeat.for="route of router.routes" if.bind="route.isActive"
      css="background: ${router.activeRoute.settings.color};">...</div>
```

This creates a different div for each route, as long as the route is shown, which means you have to nest the content ("...") you want to show in each "virtual copy" of the div. There's no easy way (that I have been able to find) to do something like:

```html
<div css="background: ${router.activeRoute.settings.color};">...</div>
```

**Comment by EisenbergEffect** [comment]
Have a look at `router.currentInstruction`. I believe you will find what you need there. If not, let me know.

**Comment by lukehutch** [comment]
Ah! Sorry, I didn't notice that currentInstruction had a link to settings. That does work, thank you. For anyone else's reference that comes across this, the path needed is 

```javascript
router.currentInstruction.config.settings
```

(This would be another useful thing to have in the docs, if you're keeping a list..)  Much appreciated.
