### ISSUE TITLE
Router navigation failed, and no previous location could be restored.

### ISSUE THREAD

**Issue by nojaf** [aurelia/router#154]
Hi,

Sorry to be so pushy on this problem but it's really starting to get quite blocking.
I'm doing a very simple route config with pages in sub folders.
Example: https://github.com/nojaf/aurelia-router-issue
Is this a bug or is my setup wrong?
I've asked this on the gitter channel but no solution yet.

Thanks,
nojaf

**Comment by JeroenVinke** [comment]
It works for me when I change two lines: 
```
// index.html
<body aurelia-app="src/main">
to
<body aurelia-app>

// config.js
"*": "*.js",
to
`"*": "src/*.js",
```

**Comment by EisenbergEffect** [comment]
I don't really know what the details of the problem are. You aren't giving me much to go on. I do know that there were a couple of router bugs reported on Friday. Fixes for those are going out in a patch release today. My guess would be that your configuration is incorrect. See the answer from @JeroenVinke

**Comment by nojaf** [comment]
@JeroenVinke thanks, that partially solves the problem.
However by changing 
```
aurelia-app="src/main" to aurelia-app
```
you are not executing the plugins in the main function.
So certain plugins would not be executed.

**Comment by EisenbergEffect** [comment]
Set it to `aurelia-app="main"`. That should do it.

**Comment by JeroenVinke** [comment]
Yes, and change `aurelia.start().then(a => a.setRoot("./src/app", document.documentElement));` to `aurelia.start().then(a => a.setRoot());` in `main.ts`

**Comment by nojaf** [comment]
Thanks you guys!! Really appreciate this!
