### ISSUE TITLE
Is it possible to add a route to the router inside the config callback of a plugin.

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/router#156]
In my view, aurelia plugins can serve as a nice container for cross cutting concerns, but they could be used also for application modularization.
Now, I'm thinking of app modules that register themselves in the app. One aspect of that would be that the app modules (in the form of an aurelia plugin) let the main app know what there route info is vis-à-vis the main app. (of course the plugin can have it's own child routes as well, but that's part of the plugin)
I think the best place would be inside the configure function ?
Please take a look at following configure function.
```
export function configure(aurelia) {

	aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css')
    .plugin('./modules/welcome/index', ()=>{
 //is it possible to access here the router????
    	});
    
    aurelia.start().then(a => a.setRoot());
}
```
Suggestion welcome for alternatives...

**Comment by EisenbergEffect** [comment]
Your plugin's configure method will get an instance of the `aurelia` object as its first parameter, so you can do this:

```
var router = aurelia.container.get(Router);
router.addRoute({ ... });
```

**Comment by cornillemichiel** [comment]
Sorry for necroing this very old thread, but I was wondering if this also works when not calling .plugin('my-plugin-name') explicitely, i want to group some code in features / plugins, but I don't necessary want to include all of the plugins files,.. I do however want the routes to be present. Or is that crazy
