### ISSUE TITLE
When using pushState configuration a direct link throws an error.

### ISSUE THREAD

**Issue by digitzfone** [aurelia/router#157]
When pushState is enabled according to the docs, local navigation works great. But if I refresh a page other than the index page I get an error. A refresh of `http://localhost:9000/showcase/freddies` causes the following error. `GET http://localhost:9000/showcase/jspm_packages/github/aurelia/bootstrapper@0.14.0.js 404 (Not Found)` Notice that "showcase" is in the address.

**Comment by EisenbergEffect** [comment]
Did you set a base in your index.html?

**Comment by digitzfone** [comment]
Yes sir I did... This is in my index page.

```html
<head>
    <title>Aurelia</title>
    <!-- REQUIRED FOR PUSHSTATE -->
    <base href="/">

    <link rel="stylesheet" type="text/css" href="jspm_packages/npm/font-awesome@4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="styles/styles.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
```

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you take a look at this top priority?

**Comment by bryanrsmith** [comment]
Looks like you also need to configure JSPM with a `baseURL`. I have added a note to the docs-- see aurelia/documentation#127. Sorry for the delay in looking into this, @digitzfone.

**Comment by digitzfone** [comment]
Hey Bryan,

This is exactly what I needed!!

Thank you

EJ

**Comment by sew810i9** [comment]
Hello. I have the same problem with routing. 
**My index.html** 
````
<!DOCTYPE html>
<html>
<head>
    <title>ToDo</title>
    <link rel="stylesheet" href="styles/styles.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base href="/">
</head>
<body aurelia-app>
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script>
    SystemJS.import('aurelia-bootstrapper');
</script>
</body>
</html>
```
**my config.js**
```
System.config({
    defaultJSExtensions: true,
    transpiler: "babel",
    babelOptions: {
        "optional": [
            "es7.decorators",
            "es7.classProperties"
        ]
    },
    baseURL: "/",
    paths: {
        "*": "src/*",
        "github:*": "jspm_packages/github/*",
        "npm:*": "jspm_packages/npm/*"
    },
    map: {
        //some code...
    }
});
```
When I am going from  http://localhost:8080 to http://localhost:8080/login everything works well but when I reload a page I have an empty page and a message "GET /login" Error (404): "Not found" in my console.
I have my index.html and config.js in root of project. My models and views located in src/. I'm trying to solve this problem for a second day. Help me please

**Comment by EisenbergEffect** [comment]
Is your server configured correctly? For push state, you also have to configure your server.

**Comment by sew810i9** [comment]
I don't know. I didn't find an information to configure a server for pushState. What should I configure? Maybe I should configure my .htaccess which located at root directory of my project?

**Comment by EisenbergEffect** [comment]
Depending on what server-side web framework you are using, you will need to configure it to serve your Aurelia app for routes that it doesn't recognize so that those can be handled on the frontend.

**Comment by sew810i9** [comment]
I am using node js + express but I don't understand how to configure my server for Aurelia. Now I start server using a command  http-server -c-1 it means that I don't use node js on server-side. I don't know how to start aurelia and node js jointly. I've never used frameworks similar to Aurelia but I want try it. If you can help me to do it I will be very grateful to you.

**Comment by EisenbergEffect** [comment]
Please ask in the community gitter channel: gitter.im/aurelia/discuss

**Comment by seishin4real** [comment]
How do I configure this with aurelia-cli project?

**Comment by VSG24** [comment]
Also 404 with webpack.
