### ISSUE TITLE
addRoute method doesn't allow to specify the route as an array for defining both 'named' and 'default' route.

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/router#158]
Using the router map function allows to do the following (so using an array with both a named and default route):
```
config.map([
	{ route: ['','welcome'],  moduleId: './welcome',      nav: true, title:'Welcome' },
	{ route: 'flickr',        moduleId: './flickr',       nav: true, title:'Flickr' }, 
...
```

adding a route with the addRoute method does NOT allow:

```
router.addRoute({ 
            route:  ['', 'welcome'], 
            name: 'welcome',  
            fa:'fa-bed' , 
            moduleId: './modules/welcome/welcome', 
            nav: true, 
            title:'Welcome' });
```
Any reason for this ?

**Comment by EisenbergEffect** [comment]
Actually, `map` has a convenience for adding two routes that share the same navModel object. (addRoute has a second arg for passing a shared nav model). The best way to handle this it co create an instance of `RouteConfigration`. Then you can use its `map` API. It's the same as the one your are used to normally using. Then, you can call `config.exportToRouter(router)` to configure a router instance from a configuration object.
