### ISSUE TITLE
child router with multiple sections/views

### ISSUE THREAD

**Issue by cezgit** [aurelia/router#161]
Hi,
Is it possible to have a child-router with more than one config map? I want to be able to split my side navigation menu in multiple sections like this:

Section A
  Link1
  Link2

Section B
  Link3
  Link4

So ideally I would want to use repeat.for for each section:
Section A: repeat.for="row of router1.navigation
Section B: repeat.for="row of router2.navigation

I'm not sure how configure 2 separate maps, one for each section and also, how would I bind the router view for each section.
<router1-view>
<router2-view>

**Comment by EisenbergEffect** [comment]
You can add a settings property to your route config. That will be copied over to the nav model so you can provide a custom property or properties there which you could use to filter and render the nav into different areas.

**Comment by cezgit** [comment]
Of course...that would work. Thank you!
