### ISSUE TITLE
Aurelia not working inwindows 10 Internet explorer 

### ISSUE THREAD

**Issue by devmondo** [aurelia/router#162]
hi, i am running windows 10 and Aurelia works fine with Chrome, Firefox except in IE and no matter if i chose between version 11 or 10, nothing happens, console dont show errors, but sometimes i get htis error.

```TypeError: Assignment to read-only properties is not allowed in strict mode```

**Comment by EisenbergEffect** [comment]
Can you determine where that error  is coming from? In the past when we've seen similar errors it has been from inside one of the polyfills, rather than Aurelia itself. I can't think of anything in Aurelia that would raise that error, which is why I'm asking.

**Comment by devmondo** [comment]
@EisenbergEffect , the problem is that is the only message i get from IE :(

what polyfills i must remove exactly ? i am not including any now

**Comment by devmondo** [comment]
@EisenbergEffect  i think i narrowed down the problem  it is when i use this
``` this.router.navigateToRoute('profile');```

**Comment by devmondo** [comment]
@EisenbergEffect  i think i found the cause, it happens if i add ```containerless``` to a ``` composes ``` element!

**Comment by EisenbergEffect** [comment]
Fixed in 7764774cf6621d25a111759cbe1217dfae64812d

**Comment by devmondo** [comment]
:+1:
