### ISSUE TITLE
router.navigate change url but not activating viewmodel

### ISSUE THREAD

**Issue by kdeberni** [aurelia/router#168]
In couple of places in our code we have `router.navigate` which works fine till recent. However, on days we updated aurelia to latest version with router version 0.10.2 and now `router.navigate` does not do it's job (I tried to use Router and AppRouter from aurelia-router). Url is changing but viewmodel is not activated and there are no errors. However if I use location.href with same route fragment everything works fine.
I saw that there was a problem with throwing errors in router and you fixed it but I did some debugging in  routers index.js and I noticed that route which I am giving is not recognized as absolute route so line with code `window.location.href = fragment;` in line 162 (third line in function BrowserHistory.prototype.navigate) of mentioned file is not fired but function goes through line `updateHash(this.iframe.location, fragment, options.replace)` and I think that's why url is changing but no activation of viewmodel is fired. Of course this are my suspicions but it could be something totally else.
Navigation is used like this `this.router.navigate('#/app/admin')` and I am navigating from one child router to another. To clarify I have one 'main' router on app.js and two child routers of this main router.

**Comment by bryanrsmith** [comment]
@kdeberni Wow, looks like this one slipped through the cracks. Sorry about that! Are you still seeing this problem? We've made several changes that relate to this recently.

**Comment by kdeberni** [comment]
@bryanrsmith I just checked that out and it looks like it's OK now.At least in version 0.12.0 of aurelia-router. So I think this issue can be closed. Though it would be good to check this on version 0.13.0 but we can't do it now. Worse case scenario I will open it again if in version 0.13.0 this will be again an issue.

**Comment by davismj** [comment]
@EisenbergEffect @bryanrsmith This issue is resolved.

**Comment by kdeberni** [comment]
This issue returned in version 1.0.0-beta.1.1.2 of aurelia-router. Before update we had version 1.0.0-beta.1 and it was OK - I just rechecked that by reverting our project to previous revision.
So issue occurred between version beta.1 and beta.1.1.2.
