### ISSUE TITLE
route-href sets wrong url on viewmodel from child route after page refresh

### ISSUE THREAD

**Issue by kdeberni** [aurelia/router#169]
This is something we noticed from very beginning. If you have navigated to some child route and then refresh the page all hrefs in views generated from route-href are generated from baseUrl and not from main route url. Example, I navigated to 'http://localhost:9000/#/app/new' where 'app' is route from my main route and 'new' is route from my child route. On view 'new' in html I have `route-href="route: contractor-new"` which in first place generates url 'http://localhost:9000/#/app/new/contractor-new' and this is OK. However, if I refresh page in this moment href will have url 'http://localhost:9000/#/contractor-new'. As we can see it omits 'app/new' fragment.
After some debugging I found out that router's function `generate` is generating this "bad" URL. Or I am doing something wrong? By the way, couldn't find anything on gitter descussion.

**Comment by bryanrsmith** [comment]
I believe this is due to #113, but will leave this open until I can confirm.

**Comment by kdeberni** [comment]
While debugging I noticed that baseUrl was not set in moment when  router's generate function was called to calculate route-href. So probably it is connected to this issue.

**Comment by peisenmann** [comment]
I've noticed this for a while and finally plunked it http://plnkr.co/edit/JoT6Qw

**Comment by kdeberni** [comment]
@bryanrsmith Any news about this issue. In version 0.12.0 it still don't work. And It is really a big issue for us because our application is based on child routers.

**Comment by kdeberni** [comment]
I just wanted to notice that it seams like in beta version this issue has been fixed.

**Comment by EisenbergEffect** [comment]
Excellent. Thank you!

**Comment by peisenmann** [comment]
I updated my above-mentioned plunk and agree that it appears to be correct in the beta: http://plnkr.co/edit/t5fkfcmSL9CIj7umKrKS

**Comment by kdeberni** [comment]
This issue returned in version 1.0.0-beta.1.1.2 of aurelia-router. Before update we had version 1.0.0-beta.1 and it was OK - I just rechecked that by reverting our project to previous revision.
So issue occurred between version beta.1 and beta.1.1.2.
