### ISSUE TITLE
how to reset scroll position after navigating to a new route

### ISSUE THREAD

**Issue by jdanyow** [aurelia/router#170]
This has come up in the gitter a couple times:

You've scrolled down the page, then you navigate to a different page/route, the developer/user expects the scroll position to be reset to the top.  What's the best way to accomplish this?

Here's some code that was shared:

``` javascript
eventAggregator.subscribe('router:navigation:complete', payload => window.scrollTo(0, 0));
```

Here's how durandal handled this:
https://github.com/BlueSpire/Durandal/blob/master/src/transitions/js/entrance.js#L69

Would be nice to include this feature in the router somehow or document how to manage this when we add the narrative style docs @EisenbergEffect mentioned in the meeting.

**Comment by bryanrsmith** [comment]
Scrolling to the top when the navigation is committed should be simple enough.

**Comment by fopsdev** [comment]
just when you are working on this anyway. why not optionally restore the scroll position as it was when the route was left. 
or even better, is there a way to restore state on a route as it was when it was left without jumping through hoops? for example when the user selects an item in a select control it should be selected again when moving back. possible solution would be a additional  property on the route like:
cache:yes
then the html as it was gets displayed again when entering the route...
not sure if i'm simplifying this too much but i would be really interested in how you guys would solve an requirement like that.

**Comment by TommiGustafsson** [comment]
I got it working as follows (from my app.js):

    import $ from 'jquery';
    import 'bootstrap';
    import 'bootstrap/css/bootstrap.css!';

    export class App {
      configureRouter(config, router){
        config.title = 'Admin';
        config.addPipelineStep('postcomplete', PostCompleteStep)
        config.map([
          { route: '',                      name: 'instructions',           moduleId: 'welcome',               nav: true,  title:'Instructions' },
          { route: 'conference-settings',   name: 'conference-settings',    moduleId: 'conference-settings',   nav: true,  title:'Conference Settings' },
          { route: 'transmission-settings', name: 'transmission-settings',  moduleId: 'transmission-settings', nav: true,  title:'Transmission Settings' },
          { route: 'user-settings',         name: 'user-settings',          moduleId: 'user-settings',         nav: true,  title:'User Settings' },
          { route: 'control-room',          name: 'control-room',           moduleId: 'control-room',          nav: true,  title:'Control Room' },
          { route: 'test',                  name: 'test',                   moduleId: 'test',                  nav: false, title:'Test Page' }
        ]);

        this.router = router;
      }
    }

    class PostCompleteStep {
      run(routingContext, next) {
          $(".page-host").scrollTop(0);

          return next();
      }
    }

In effect, I created a pipeline step for the postcomplete event, and scrolled the page host to top there. I had to delve down to https://github.com/aurelia/router/blob/master/src/pipeline-provider.js to find the supported pipeline steps. :-\

**Comment by jdanyow** [comment]
New browser API that could help with this in the future:  https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration

**Comment by TommiGustafsson** [comment]
Great! But can it scroll up the div with page-host class, not the document or the window?

**Comment by antonmos** [comment]
IMHO, it's a bit surprising that this doesnt happen out of the box.

**Comment by EisenbergEffect** [comment]
I'm not sure if we should build this in because I've seen apps that need this behavior but in very app-specific ways. What I would like to have is a recipes article for the router that shows all sorts of different tips/tricks like this. That enables someone to have a starting point that they can work with to build what they need for their specific app.

**Comment by eikaramba** [comment]
IMHO: i would default to scroll to top. Just because this is how it is for regular links. And then i can opt-out if i want to keep my scroll position

**Comment by nathanchase** [comment]
I'd like to be able to have each of my views ensure they are scrolled to the top of the viewport except one (or maybe, a few). I'd also prefer the opt-out to keep scroll position, rather than assume I want the previously stored scroll position.

**Comment by rmja** [comment]
@nathanchase You can relatively simply do that using the approach from https://github.com/aurelia/router/issues/170#issuecomment-134948900. Simply use the following `PostCompletionStep`:

```
class PostCompleteStep {
    run(instruction: NavigationInstruction, next: Next) {
        if (!instruction.config.settings.noScrollToTop) {
            window.scrollTo(0, 0);
        }

        return next();
    }
}
```

Then in your route config, simply add a `settings: {noScrollToTop: true}` to the routes that should not scroll to top.

**Comment by nathanchase** [comment]
Excellent I didn't realize we could add custom settings to routes like that. Nice approach! Thanks!

**Comment by gheoan** [comment]
To emulate the native scrolling behaviour, when the user clicks the back or forward button the previous scroll position should also be restored.

**Comment by gheoan** [comment]
https://github.com/aurelia/router/pull/459 added APIs that can help decide when to scroll to top.
Using the code below the page scrolls to top on new routes, allowing the user agent to restore scroll position on the routes already visited:

```typescript
  configureRouter(config: RouterConfiguration, router: Router) {
    config.addPostRenderStep({
      run(navigationInstruction: NavigationInstruction, next: Next) {
        if (navigationInstruction.router.isNavigatingNew) {
          window.scroll(0, 0);
        }
        return next();
      }
    });
}
```

**Comment by michaelbull** [comment]
@gheoan I'm using the snippet you pasted above, however it resets the scroll position as I *start* to navigate away, not as the route is loaded. The route I'm navigating to returns a `Promise` in its `activate` method and does some data-loading before finishing, therefore I don't want to reset the scroll position until this has happened. Do you have any suggestions on addressing this issue?

**Comment by gheoan** [comment]
@michaelbull The `postRender` step should be called by the router after the `activate` promise has completed. Might be a bug in the router.

Maybe queueing the scroll reset in the [task queue ](http://aurelia.io/docs/api/task-queue/class/TaskQueue)will help:
```js
run(navigationInstruction: NavigationInstruction, next: Next) {
  if (navigationInstruction.router.isNavigatingNew) {
    this.taskQueue.queueMicroTask(() => window.scroll(0, 0));
  }
}
```

**Comment by michaelbull** [comment]
Ah, it seems my router link to the base route (that gets resolved to `href="#/"`) forcefully scrolls to the top of the page when clicked. I don't think the `taskQueue` solution is necessary as I put in a bunch of debug statements to confirm that the `run` method was indeed only being called after `activate`.

The `#/` href seems like a separate issue.
