### ISSUE TITLE
Inconsistent activate parameters order

### ISSUE THREAD

**Issue by jimmyps** [aurelia/router#174]
In one module, the activate parameter order is correct per the documentation, which is `activate(params, routeConfig, navigationInstruction)`. While in some other modules, the activate method signature unexpectedly becomes `activate(model, params, routeConfig, navigationInstruction)`. When accessing routeConfig, the code may become unreliable as its order could change (i.e., from 2nd to 3rd), and ultimately leading to bugs and maintenance complexity in the future.

I suggest that optional or dynamic parameters to be added to the last parameters, allowing static parameters stay in its order unchanged.

The suggested activate method that promote consistency and extensibility would be: `activate(model, routeConfig, navigationInstruction, params)`.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can  you look into this? I'm wondering if there's some old code hanging around from an earlier refactory.

**Comment by bryanrsmith** [comment]
@jimmyps It should definitely use the documented order. Are you able to either provide a plunkr demonstrating the issue, or post steps to reproduce the incorrect parameters? I don't see it happening in my test app.

**Comment by jimmyps** [comment]
@bryanrsmith Thanks for responding. When looking at the issue again, I just realize that I was testing on an outdated sample that I downloaded from the Github. I have to copy the config.js from the skeleton repo to this problematic sample, then perform jspm update. Afterward, this issue no longer appear.

You may close this issue now.

For all Aurelia contributors, I highly suggest to always update the examples to latest version when a new release is available (by updating the config.js). We should also include an information in the readme.md that the current sample may need update for better reliability, then also provide the steps how they can do the update.
