### ISSUE TITLE
nested routing produces incorrect routes when fall through for default '/' route

### ISSUE THREAD

**Issue by monkeyhouse** [aurelia/router#185]
When I use a base route of <code>'/'</code>, I have to use a redirect so that my inner routes are generated properly Either way, not sure if its an issue.
Setup:

I have a router nested inside another router.

The outer router has routes defined for '['', 'Seasons']', 'Elements', 'Cloud Types'

For Seasons, the inner router has routes are defined ['',All], Winter, Summer, etc.

If I am at the url `/Seasons, ` then the following urls are generated in the links for the inner router
`/Seasons/Winter `, `/Seasons/Summmer `

If am at the url ` / ` then the following urls are generated in the child menu `/Winter `, `/Summer`

When the app normally loads, I am at the route `/` and then when links generated by the inner router are clicked, they dont work because they point to `/Winter` instead of `/Seasons/Winter ` )

A quick fix is to have a seperate page for `/` that redirects to ` /Seasons `
eg. `/` links to redirect  model 
```
import {Router} from aurelia-router;
import {inject} from aurelia-framework;

@inject(Router)  
export class SeasonsRedirect{
    constructor(router){
       router.navigate(#/seasons);    
    }
} 
```
I have to do this in a few place so far - whenever my router has a default page has a nested router - so it might be convenient to have some shortcut for this? not sure if bug, expected behavior or enhancement.

**Comment by Magrangs** [comment]
+1 Having the same issue with child routes defined in a viewmodel that itself is accessed via a default route.

**Comment by monkeyhouse** [comment]
Hi Magrangs, I think the redirect property solves this issue.
In the example above I would set up the route

```
 config.map([
      { route: ['Seasons'],    name: 'seasons',       moduleId: 'seasons',      nav: true, title:'Seasons' },
      ...
      { route: '', redirect: 'seasons' }
    ]);
```

Let me know if it works for you. I will try it out tonight. I think this is the expected workaround

**Comment by Magrangs** [comment]
Yep, that works! Thanks very much.
