### ISSUE TITLE
Need help with implementing 404 page and mapUnknownRoutes.

### ISSUE THREAD

**Issue by valichek** [aurelia/router#195]
It looks like easy thing with `mapUnknownRoutes`, but it's getting complicated when adding authorization workflow.
The main idea is:
1. go to the `/notfound` url (notice that there are no known route in config for it).
2. if not authorized show login form (we still at `/notfound`)
3. process login, get navigation, and refresh `/notfound` to show 404 page
```javascript
config.mapUnknownRoutes(instruction => {
        
        if(this.auth.authorized) {
          instruction.config.moduleId = './pages/err404';
        } else {
          instruction.config.moduleId = './pages/login';
        }
        
        return instruction;
});
```
But the problem here is that it updates instruction with new moduleId but does not switch model-view to the err404.

**Comment by valichek** [comment]
Upd: Noticed that `instruction.viewPortInstructions.default` property is undefined

**Comment by valichek** [comment]
Found workaround for that.
Added `redirect` route to router config:
```javascript
{ route: 'redirect', moduleId: './pages/home', auth: true, nav: false},
```
Save instruction when not authorized
```javascript
this.state.authRedirect = instruction;
instruction.config.moduleId = './pages/login';
```
After auth I get saved instruction, add route for unknown fragment and do redirect
```javascript
let fragment = this.state.authRedirect.fragment;
this.state.authRedirect = null;
this.router.addRoute({route: fragment, moduleId: './pages/err404', nav: false, auth: true});
this.router.navigate('/redirect?'+fragment);
```

Handle redirect in router pipeline step:
```javascript
run(routingContext, next) {
    let redirectIndex = _.findIndex(routingContext.nextInstructions, 'fragment', '/redirect');
    if(redirectIndex >= 0){
      let r = new Redirect(routingContext.nextInstructions[redirectIndex].queryString);
      return next.cancel(r);
    }
}
```

**Comment by bryanrsmith** [comment]
In your original setup it may not be activating because the location isn't changing. Try setting `instruction.config.activationStrategy = activationStrategy.invokeLifecycle;` to get the router to process the change.

**Comment by valichek** [comment]
@bryanrsmith , If I remove `this.router.addRoute({route: fragment, moduleId: './pages/err404', nav: false, auth: true});` and add `instruction.config.activationStrategy = activationStrategy.invokeLifecycle;` to `mapUnknownRoutes ` it doesn't help. Noticed that it stops and does not proceed to the pipeline step.

**Comment by valichek** [comment]
My workaround does not really work as expected
when doing
```javascript
this.router.addRoute({route: fragment, moduleId: './pages/err404', nav: false, auth: true});
```
 I override already dynamically loaded routes, so tried to check that with `this.router.hasRoute(...)`,
but it turned out that `this.router.recognizer.names` is empty after `this.router.ensureConfigured()`, is it correct?

**Comment by bryanrsmith** [comment]
@valichek Sorry for the delay on this. This is a problem because the router doesn't let you navigate to the location that's already active. In the next release you'll be able to use the `{ replace: true }` navigate option to force the router to navigate to the same URL.

I'm going to close this because I think this will solve your problem. Please feel free to reopen it if this change isn't working out for you.
