### ISSUE TITLE
bubble rejected activation promises

### ISSUE THREAD

**Issue by jdanyow** [aurelia/router#2]
It would be nice if there was a way to give the router a handler for activation promise rejections.  This would reduce boilerplate error handling code in activate methods.  

Code like this:

    public activate(...): Q.Promise<any> {
        var deferred = Q.defer();

        doSomething()
            .then(() => deferred.resolve())  // yay
            .fail(reason => {
                deferred.reject(reason);     // cancel activation.
                return Q.reject(reason);     // "rethrow"
            })
            .done();  // terminate the promise.  ensure error bubbles up to the unhandled exception handler  (Q.onerror).

            return deferred.promise;
    }

Could be simplified to something like this:

    <hook error handler to router>

    public activate(...): Q.Promise<any> {
        return doSomething();
    }

**Comment by tyrsius** [comment]
In chat we discussed the possibility of providing a navigation-error hook, to allow the module to subscribe to errors instead of bubbling them up.

**Comment by EisenbergEffect** [comment]
@tyrsius Was this the idea of adding a new navigation callback that view models can subscribe to? Such as `activationFailed`? Or is that a different idea?

**Comment by jdanyow** [comment]
If there's a way provide a hook for rejected activation lifecycle promises it would make the user code simpler.  This is the use case I was thinking of:

Often code in the activate method fails- required data is no longer on the server, the user's internet connection is down, or maybe a modal popped during activation and the user cancelled rather than continue with opening the screen.  Maybe it's a real error that should be logged, etc.  With durandal, if you wanted to handle these scenarios you needed to do two things: 

1. make sure the activate promise rejects
2. terminate the promise chain yourself with `.done` to ensure the exception bubbled to Q's unhandled rejection handler.  In this central location you'd handle well known activation issues and maybe show a message "the record no longer exists" or "cannot connect to EvilCorp servers".

I wouldn't say this was a bug in durandal, `.done` was non-standard plus how is durandal supposed to know the difference between canceled nav and a real error.

In a broader sense, in any situation where Aurelia eats a rejected promise, it would be nice if this was bubbled along with any contextual information available to allow user code to handle (or ignore) in a central location.

**Comment by jdanyow** [comment]
right- since I'm unable to return a terminated promise chain from my activate method I have to do the little dance with the deferred you see in my first note in this issue.

**Comment by jdanyow** [comment]
Didn't explain that well- here's what I meant:

The code above shows how I ensure the promise chain is terminated while still returning an un-terminated promise to the durandal framework from my activate method.  The reason I have to do this is the promise chain doesn't really end in my activate code, it ends in the durandal framework code and the durandal framework does not call `done`.  Without this bit of logic an error in my activate would only cancel the activation.  It wouldn't bubble up to Q's unhandled rejection handler or to window.onerror.

**Comment by tyrsius** [comment]
I'm a bit confused. Do you just want to see the error in the console? Who is getting the rethrown error?

If you just want to see it in the console, you can drastically simplify by doing this:

```
public activate(...): Q.Promise<any> {
    return doSomething().catch(function(error) { console.error(error)});
}
```

**Comment by jdanyow** [comment]
sorry, I'm butchering the explanation of this.  Let me take another shot at it...

The aurelia/durandal activation lifecycle interprets a rejected promise as the signal to cancel activating/deactivating or as "no" when calling canactivate/candeactivate.  

Neither framework does anything with the rejection reason.  How could they?  The framework has no way to tell whether the promise was rejected due to an unexpected error or if was rejected intentionally to cancel the activation event.

This issue is to request a hook so that app developers can handle the rejections centrally instead of needing to put error handling code in every activate/canactivate/etc/etc method.

With durandal I needed to terminate any promise chain using code like what's in my first comment in this issue.  This would ensure a promise in the correct state was returned to durandal AND the errors would bubble up to the Q.onerror where they could be handled by the applications centralized error handling and logging system.

**Comment by tyrsius** [comment]
So you are just trying to involve your global error handler from `activate`. That makes sense. This has been discussed a few times, but until support is added you could at least de-duplicate the bulk of your code like this

```
//In some global definition
function handleGlobalError(error) {
    window.onerror(error); //Or whatever, raise an event
    throw error;
}

//your viewmodel
activate() {
    return doSomething().catch(util.handleGlobalError); //Or whatever namespace you put it in
}
```

It's not ideal, but it's still much cleaner that your original code.

Also, I realized I never responded to @EisenbergEffect: yes, that was the idea.

**Comment by jdanyow** [comment]
Good point, that is much cleaner.

**Comment by EisenbergEffect** [comment]
Perhaps someone wants to submit a pull request to add this....

**Comment by EisenbergEffect** [comment]
@tyrsius Any interest in tackling this and submitting a PR?

**Comment by tyrsius** [comment]
@EisenbergEffect Yes, I will try to get this done this week. I'm in the middle of buying a house though, so my after-work-coding-time is a bit restricted. It might slip into the weekend.

**Comment by EisenbergEffect** [comment]
I understand. No worries. I'll assign it to you, that way I know we know who's working on it. When you get it done, just send a PR. Thanks!

**Comment by bryanrsmith** [comment]
Is there any remaining work to be done on this? It appears the nav failure event has since made it into the router, along with other navigation events. Do we still want to add support for an `activationFailed ` callback on the VM?

**Comment by EisenbergEffect** [comment]
I would like to avoid adding any additional callbacks to the vm, if we can. I'm not sure if anything else needs to be done. @jdanyow You originally opened this issue. Are we good or do we need something else?

**Comment by jdanyow** [comment]
the router event covers my use-case, from my perspective this can be closed.

**Comment by EisenbergEffect** [comment]
Ok. Closing it out then.

**Comment by matik12** [comment]
I think @jdanyow had a good point with an idea to add global handler for activation promise rejections. 

In my understanding, router navigation error event does not cover all use cases, especially case when we want to navigate to error page on activate route rejection (i.e. not found, unexpected error pages). 
Navigation to another route in the function that subscribe to router navigation error event is not a good idea I believe - it is not working well with router pipeline when router is in navigating state.
From my experience much better solutions is to catch errors in activate method and return rejected promise with **RedirectToRoute** object to work seamlessly with router activation pipeline. Sample code as below:

```js
  activate(params) {
    return this.sampleService.findData(Number(params.id))
      .then(data => ... )
      .catch(reason => {
        if (reason.status && reason.status === 404) {
          return Promise.reject(new RedirectToRoute('not-found'));
        } 

        return Promise.reject(new RedirectToRoute('unexpected-error'));
      });
  }
```

Of course, we can put this catch logic in another code component i.e. error handler module and exported function handleRejection:

```js
export default function handleRejection(reason) {
  if (reason.status && reason.status === 404) {
    return Promise.reject(new RedirectToRoute('not-found'));
  } 

   return Promise.reject(new RedirectToRoute('unexpected-error'));
}
```

But still you have to import this function and provide catch using this function in every screen VM activate method to have you app work properly. I was following this approach, but an improvement would be helpful such as global activation rejection handler within router activation pipeline. So something similar to code below for AppRouter configuration - **onActivationRejection** :

```js
  configureRouter(routerConfig, router) {

    routerConfig.map(items);
    routerConfig.fallbackRoute(config.page.default);

    routerConfig.onActivationRejection(reason => handleRejection(reason));

    this.router = router;
  }
```

What do you think about this?

**Comment by MJSanfelippo** [comment]
@EisenbergEffect @bigopon Any thoughts on @matik12 's comment? the config.onActivateRejection sounds great.

**Comment by EisenbergEffect** [comment]
Adding @jwx who is working on our vNext router so he can gather the use case for the new router. Also adding @davismj who knows the most about the current router.
