### ISSUE TITLE
better documentation of absolute vs relative module ids

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [aurelia/router#20]
starting at the examples i got bitten by just using a absolute module id in a router for a app that was actually being renamed

it took a while to figure i need to use ./about instead of about as module id

the matter was worse, because i serve a spa shell at all non-static non-api locations, and all i got was a strange syntaxerror

**Comment by EisenbergEffect** [comment]
I fixed up the examples and add some emphasis in the documentation. It will go out with the next doc release today or tomorrow.
