### ISSUE TITLE
Better error message when the router is unable to find a parameter because the underlying data has not yet been loaded

### ISSUE THREAD

**Issue by jeremy-holt** [aurelia/router#203]
My model retrieves the `arrival` object and then fills in the view.

My view has a link `<a if.bind="arrival.id" class="btn btn-primary" route-href="route:rawmaterial-new-drying; params.bind: {arrivalId:arrival.id}">Go to dryer</a>`

The router is
```
{
    route:"entra-secador/novo/:arrivalId",
    moduleId:"rawmaterial/enter-dryer",
    title:"Alimenta o secador",
    name: "rawmaterial-new-drying"
}
```

If I don't include the `if.bind="arrival.id"` I get an error:
```
Unhandled promise rejection Error: A value is required for route parameter 'arrivalId' in route 'rawmaterial-new-drying'.
    at RouteRecognizer.generate (http://localhost:63293/jspm_packages/github/aurelia/route-recognizer@0.6.2/aurelia-route-recognizer.js:331:17)
    at Router.generate (http://localhost:63293/jspm_packages/github/aurelia/router@0.11.0/aurelia-router.js:1218:34)
    at http://localhost:63293/jspm_packages/github/aurelia/templating-router@0.15.0/route-href.js:33:33
    at run (http://localhost:63293/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:63293/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:63293/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:63293/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:63293/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:63293/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:31:9)
```
On gitter I suggested that what's happening is that the router is looking to generate the route before the view is complete. Putting in the `if.bind` clearly delays the creation of the route until the page has loaded. This seems like a hack. I would expect the router to wait for everything to have loaded before trying to generate the route.

@bryanrsmith replied with
> that it does wait, but if you load data asynchronously there's no way for it to know. The binding expression just evaluates to undefined. route-href could ignore those errors, but they're often legitimate bugs that shouldn't fail silently. I don't think the if.bind is a hack at all.

I then went on to ask for a better error message explaining that the parameter can not be found since it "is possible that the data has not yet been loaded".

Nonetheless, the behaviour is extremely inconsistent using `if.bind` to prevent the route being created before the data is loaded. There definitely seems to be some kind of timing issue between the view realizing that the link should not be created because of the `if.bind` and throwing the exception.

**Comment by EisenbergEffect** [comment]
@bryanrsmith We may need to push off the generation of the route by scheduling a micro task. I think that should solve the problem.

**Comment by bryanrsmith** [comment]
@jeremy-holt Would you mind posting your view model code? My understanding is that the view model is loading the required data asynchronously without blocking activation. If that is the case then the `if` is indeed required, but we could possibly improve the error message.

**Comment by bryanrsmith** [comment]
I've made some recent changes to route-href that should reduce this issue in the next release. I believe route-href is now handling this as well as it can. Please feel free to reopen if that's not correct.

**Comment by vbartolini** [comment]
I have problem with Aurelia binding. My class is as following:

    import {inject} from 'aurelia-framework'
    import {HttpClient, json} from 'aurelia-fetch-client';

    @inject(HttpClient)
    export class AppleList{
	constructor(client){
				this.apples = [];
				this.client = client;
	   }

	   created(){
		this.client.fetch('http://localhost:50165/api/values')
        .then(response => response.json())
        .then(data => {this.apples = data});
     	}

	   select(apple){
		this.selectedId = apple.id;
		return true;
	   }
      }

and my html file is like this:

   

    <template>
	<div>
		<ul>
			<li repeat.for="apple of apples">
				<a route-href="route: appledetails; params.bind: {id:apple.Id}" click.delegate="$parent.select(apple)">
				<h4>${apple.Name}</h4>
			</li>
		</ul>
	</div>
    </template>

The problem is message from browser console: A value is required for route parameter 'id' in route 'appledetails'.

When I put:
   
    if.bind="apple"

in 

    <a if.bind="apple" route-href="route: appledetails; params.bind: {id:apple.Id}" click.delegate="$parent.select(apple)"> 

it is working like a charm but documentation and many examples don't say about this solution.

Do you have idea what is wrong or maybe it is still valid solution?

**Comment by EisenbergEffect** [comment]
Is your property named `Id` or should it be `id`. The error you are getting is because you have null items in your array or an id that isn't defined. There's literally no way to generate the route without the required info.

**Comment by vbartolini** [comment]
Thank you Rob for fast response.
My property "Id" is coming from server and it is "Id". When it is "id" I'm getting the error. To be sure, I've changed property name for "id" but the problem still exists. If I add "if.bind="apple" everything is going properly.
The more interesting thing is that I have seven items in apples collection but I'm getting only three errors in scenario without "if.bind". In the another scenario when I have "Id" in object and "id" reference  in {id: apple.id" then I'm getting seven errors. Every error is "A value is required ...."

**Comment by EisenbergEffect** [comment]
It sounds like your array has holes in it.

**Comment by vbartolini** [comment]
If you mean hole as empty object or null then my answer is "I don't think so". I've checked whole array (length == 7), and every object has filled by proper id and name. All names are displayed in browser and every href for every link has proper value.

**Comment by EisenbergEffect** [comment]
Is the array being filled after rendering? The error you are getting is literally indicating that when the route-href behavior runs, the data isn't all present.

**Comment by vbartolini** [comment]
OK, I understand my fault after debugging vendor-bundle.js. The data are loaded from server before rendering, but resolver is working ansychronously and errors are coming when Promises collection is preparing. 
Am I right?

**Comment by vbartolini** [comment]
I'm blind as hell, my fault. It took me very long time but the reason of this error is ... not close <a> tag :). Now, it is working like charm. Thanks a lot for patience!!!

**Comment by coder8keyboard** [comment]
if.bind works(which it doesn't exist in doc) as Aurelia has rendered my HTML before data has loaded. It'd be nice if Aurelia takes care of this in the background.
