### ISSUE TITLE
Breadcrumb feature

### ISSUE THREAD

**Issue by heruan** [aurelia/router#209]
I'm trying to create a `<breadcrumb>` custom element, which would `repeat.for` the navigation stack of the router hierarchy. Since the router already builds the page title with the same hierarchy, it would be useful to have the same logic exposed for other purposes (such as a breadcrumb feature).

**Comment by heruan** [comment]
Also, the custom element would likely be placed on a parent VM, but needs to bind to the entire navigation stack being aware of the entire router tree.

**Comment by bryanrsmith** [comment]
Exposing some of the page title logic should be easy enough, but at the moment child routers are not referenced by parents so you have to start at the bottom and work your way up. We can probably add the necessary structure as part of #90.

**Comment by bryanrsmith** [comment]
I'm going to close this for now, since we have other issues to track the page title and child router refactor work.

**Comment by heruan** [comment]
I managed to develop an `aurelia-breadcrumbs` plugin (https://github.com/heruan/aurelia-breadcrumbs).

It is basically a custom element which crawls the router hierarchy and builds a navigation chain and relative breadcrumbs list.

So I think this can be closed and if better ways to handle this will emerge from other issues, I'll update the plugin accordingly. Thank you @bryanrsmith!

**Comment by mikeobrien** [comment]
Beautiful, thx @heruan!

**Comment by corneliutusnea** [comment]
Any chance to resolve the hash from the navigation instruction? I'd prefer to have a correctly generated `<a href="#/route/view/sub-view"` then use click.delegate to navigate.
The correct href allows Open in New window to work correctly.
I can't find a way to generate the route hash from the navigationInstruction.

**Comment by rmrustem** [comment]
@corneliutusnea you can build the path by passing route name and params to `route-href`. Route name can be found in `instr.config.name`.
