### ISSUE TITLE
ViewModels Singleton Instance

### ISSUE THREAD

**Issue by jaimerivera** [aurelia/router#21]
When navigating between views the viewmodel always gets instantiated.  Need a way to make view models singletons to preserve state when a user navigates various routes.  This will give the app more of a desktop feel.

The documentation currently states to use Metadata.singleton() but this does not work either.

**Comment by jaimerivera** [comment]
Was looking at the router-loader under the templating-router and the function could be changed to the following to get this functionality.  Would need to add a isSingleton property to the router config.  Just an idea.  This would cache the instruction per module id.

```
loadRoute: {
                        value: function loadRoute(router, config) {
                            var _this = this;
                            var childContainer = router.container.createChild(),
                                instruction = {
                                    viewModel: relativeToFile(config.moduleId, Origin.get(router.container.viewModel.constructor).moduleId),
                                    childContainer: childContainer,
                                    view: config.view,
                                    moduleId: config.moduleId, //can module id's repeat in child routers??
                                    isSingleton: config.isSingleton
                                },
                                childRouter;

                            childContainer.registerHandler(Router, function (c) {
                                return childRouter || (childRouter = router.createChild(childContainer));
                            });

                            if (config.isSingleton && this.cache[config.moduleId]) {
                                return Promise.resolve(this.cache[config.moduleId]);
                            }
                            else {

                                return this.compositionEngine.createViewModel(instruction).then(function (instruction) {
                                    instruction.executionContext = instruction.viewModel;
                                    instruction.router = router;

                                   if(instruction.isSingleton)
                                      _this.cache[instruction.moduleId] = instruction;

                                    return instruction;
                                });
                            }
                        },
```

**Comment by EisenbergEffect** [comment]
Ok, I've improved the singleton metadata to allow you to specify that you want the view model to be a singleton in the root container. This should allow the router to re-use the same instance across requests. The release is coming today or tomorrow. Once it hits, please give this a try and let me know. You would need to add the metadata to your view model:

```javascript
static metadata(){ return Metadata.singleton(true); } //true indicates to register in the root container
```

**Comment by jaimerivera** [comment]
Thank you the metadata works as expected now and the same view model instance is re-used.  I did notice two possible issues with the bindings as follows:

1.  The <select> element when bound to a simple property does not update the selection when returning to the view.  The view model property has the last selected value, however the select element displays the default.  

Markup: 
```
<div class="form-group inline-group-seperator">
                            <label>Quality</label>
                            <select value.two-way="selectedQualityFilter" class="form-control">                                
                                <option repeat.for="quality of qualityFilterOptions" value.bind="quality">${quality}</option>
                            </select>
                        </div>
```

View model Code is:
```
qualityFilterOptions = ["All", "Good", "Bad"];
get selectedQualityFilter() {
        return this._selectedQualityFilter;
    }

    set selectedQualityFilter(value) {
        if (this._selectedQualityFilter != value) {
            this._selectedQualityFilter = value;
            this.filterItems();
        }
    }
```

However when I navigate back to the view "All" is displaye and "Good" or "Bad" may actually be the value in the property.

2.  The second issue which is smaller, is when using the selected item binding, the view model property is read from the view model as expected and the view is updated.  However, on the update the "setter" for the property is called.  This is easy to work with as I just check the value and if the same I just ignore the update.  However, the behavior is a bit unexpected.

**Comment by fopsdev** [comment]
wouldn't it be possible to add a property like 'cacheDOM' to the route properties?
in this case the exact DOM as it was left will be recreated from cache when hitting the route again
(aslo firing the activate() etc. lifecycle events)
sorry if i i see this a bit too simplistic...

**Comment by EisenbergEffect** [comment]
@fopsdev We are planning to introduce a general template instance caching capability across the entire system soon. I believe this would dover you.

**Comment by fopsdev** [comment]
yeah sounds good. keep us posted :)

**Comment by peebles** [comment]
I too am looking for an equiv. to what I did in Durandal:

<div id="page-content" class="page-content"  data-bind="router: { transition:'entrance', cacheViews:true, alwaysTriggerAttach: true }"></div>

Esp. the cacheViews.  I've tried your metadata trick above, but it does not seem to cause anything to be cached, altho I must admit I am into ES6 by about 2 days!  

export class App {
    static metadata(){ return Metadata.singleton(true); } //true indicates to register in the root container
    (...)
}

does not seem to do anything, nor does:

export class Welcome {
    static metadata(){ return Metadata.singleton(true); } //true indicates to register in the root container
    (...)
}

**Comment by joelkinzel** [comment]
@EisenbergEffect - Any word on the template caching? Or related issue number perhaps? Looked through both the templating and templating-router repos and didn't see anything?

**Comment by jods4** [comment]
@peebles in current code you need to use `singleton(false)`, because the flag changed from `registerInRoot` to `registerInChild` <_<. With that it's working for me.

@EisenbergEffect :+1: for caching views. Singleton ViewModels only persist the state that is in your singleton. Complex bindings may have state that you also want to preserve but not bind to the VM. Example: a DataGrid custom element may want to preserve its sort order, displayed page; a Tab control may want to preserve its selected tab. But you don't really want to bind all those things to your VM.

**Comment by a2345sooted** [comment]
Is there a painless config for this yet?  I have a simple set up where there is app.js and it has a router-view element with several routes configured.  I'm using aurelia-authentication also.  I want to have the different 'pages' of the app be cached so scroll positions, etc stay the same as the user browses around the application.  I'm not having much luck searching all the answers I can find.  In most cases, I'm left with the understanding that I need to implement my own router-view that caches views, but I'm not really sure how to start doing this.  Any pre-made stuff or walkthroughs out there would be helpful.  Anybody got any updates on this?

**Comment by stefan-gisworks** [comment]
I have the same problem with ag-grid-aurelia which loses its datasource when coming back from another route. The singleton ViewModel persists the state of the VM, but the ag-grid-aurelia reconfigures and hat to reload all data, set pages and so on
