### ISSUE TITLE
Feature: suppress handling on tagged links

### ISSUE THREAD

**Issue by jbellsey** [aurelia/router#210]
I'm building a plugin, a wrapper library around Google's [MDL](http://getmdl.io). Like Bootstrap before it, it has a set of components, some of which use JavaScript to manage interactions.

The tab component links the tab button (`<a href="#panel1">`) with the tab panel (`<section id="panel1">`) by installing its own click handler. This means I can't use `click.bind` to bypass the router unless I rewrite Google's JS.

Unfortunately, the Aurelia router intercepts those clicks and throws a "route not found" error. I suspect this would also be a problem for Bootstrap tab controls, which are structured similarly and also install a private click handler.

I would like a way to indicate that a given link should not be processed by the router. 

#### Option 1: a custom attribute
For example, `<a href="#panel1" au-router-suppress>`. 

#### Option 2: middleware
Easy and stackable middleware processing via a handler in the router. The current handler (`mapUnknownRoutes`) is not named properly for this use case, but that's less important than the fact that it's not treated as stackable middleware. I.e., there's only one handler, which means my plugin will conflict with the application if it also installs a handler onto `mapUnknownRoutes`.

There may currently be a way to do something like `router.intercept()` in a plugin, but I'm not familiar enough with the library. That would let me look at the address (and the source element), look for a custom attribute that I install to flag this as a link to be handled internally, and either process the click or let it through to the router.

I've tried `addPipelineStep`, but my handler is not called. Code below, in case I'm doing it wrong.

```javascript
import {RouterConfiguration} from 'aurelia-router';

export function configure(config) {
    
    var routerConfig = config.container.get(RouterConfiguration);

    routerConfig.addPipelineStep('my-handler', MyRouterHandler);
}
```

**Comment by bryanrsmith** [comment]
Thanks, @jbellsey. The work for #80 should let us handle this use case.

**Comment by huochunpeng** [comment]
@bryanrsmith could you elaborate on how to bypass Aurelia router on an anchor href?
I am not sure how to use #80 on this.

Here is my context:
I am migrating an app into using Aurelia progressively. From the Aurelia app, I would need to be able to jump out to a legacy non-aurelia page.

Thx very much.

**Comment by bryanrsmith** [comment]
@huochunpeng You can register a custom `LinkHandler` that inspects your anchor and either navigates, or exits without handling the click. The issue you linked includes a comment with the default handler that you can use for reference.

**Comment by CasiOo** [comment]
@bryanrsmith Will the `DefaultLinkHandler` be overriden by the one we provide, or are they somehow chained?

If we only want to override the default routing behaviour for one anchor, it is a bit much with a custom LinkHandler?
A use case could be an anchor to logout that should be doing a location refresh (to clear all data). It would probably be noticeable to first navigate to the route and then refresh `window.location.refresh()` <- not a good user experience.

**Comment by bryanrsmith** [comment]
> Will the DefaultLinkHandler be overriden by the one we provide, or are they somehow chained?

No, you will register your custom handler in the DI container and the default one will not be used at all.

> If we only want to override the default routing behaviour for one anchor, it is a bit much with a custom LinkHandler?

Maybe, but the current implementation doesn't provide a way to override the behavior on a case-by-case basis. I'm sure that could be discussed if you'd like to open a new issue for it. A couple workarounds:

* The current implementation will only handle relative links, so you could use an absolute href and the default link handler will ignore it.
* The default implementation adds a delegated event handler to the document. You could add a click handler to the anchor that runs your custom behavior and then stops propagation on the event so the handler won't see it.

> A use case could be an anchor to logout that should be doing a location refresh (to clear all data).

I may be misunderstanding, but that sounds like a job for a button; not an anchor.

**Comment by CasiOo** [comment]
@bryanrsmith Interesting you mention absolute URLs will be ignore, which means we could write a logout function like:
```
logout() {
    // TODO Clear localStorage
    // TODO Clear sessionStorage
    // TODO Clear auth cookie if present
    
    // Navigating to an absolute url bypasses Aurelia's router
    // Clear all app data by refreshing the location
    window.location = window.location.origin + '#login';
}
```
I manually typed in the path `#login`, but we might be able to get the route/path from a moduleId. That would solve my issue ^^ Thanks.

**Comment by huochunpeng** [comment]
Thanks, it is actually easy to do case by case with a customised LinkHandler.

Here is what I did, make a exact copy of DefaultLinkHandler, just modifiy getEventInfo with two lines

```
static getEventInfo(event: Event): AnchorEventInfo {
    let info = {
      shouldHandleEvent: false,
      href: null,
      anchor: null
    };

    let target = BcxLinkHandler.findClosestAnchor(event.target);
    if (!target || !BcxLinkHandler.targetIsThisWindow(target)) {
      return info;
    }

    if (event.altKey || event.ctrlKey || event.metaKey || event.shiftKey) {
      return info;
    }

    let href = target.getAttribute('href');
    let legacy_link = target.getAttribute('data-legacy-link'); // use what ever attr you want

    info.anchor = target;
    info.href = href;

    let leftButtonClicked = event.which === 1;
    let isRelative = href && !(href.charAt(0) === '#' || (/^[a-z]+:/i).test(href));

    info.shouldHandleEvent = !legacy_link && leftButtonClicked && isRelative; // ignore anchor being marked
    return info;
  }
```

@bryanrsmith should this be considered as a new feature of DefaultLinkHandler?

**Comment by qraynaud** [comment]
I found a solution I find quite pleasing to handle anchors for now:

```js
eventAggregator.subscribe('router:navigation:complete', () => {
  const doc = DOM.getElementById(window.location.hash.substr(1));
  if (doc)
    doc.scrollIntoView();
});
```

You obviously need to inject DOM and EventAggregator to get this working. I put anchors after a final `/` to make this work reliably (eg `page/#anchor` and not `page#anchor`).

I'm pretty sure there should be better solutions but right now this works perfectly.
