### ISSUE TITLE
RouteConfig does not declare navModel

### ISSUE THREAD

**Issue by ctoran** [aurelia/router#211]
`RouteConfig` interface should declare `navModel: NavModel` that is being used in code like in [here](https://github.com/aurelia/app-contacts/blob/master/src/contact-detail.js#L16).

It took me few hours today to figure this out. Unfortunately babel does not do type checking and it's a real pain to manually type check the sources. Even though babel will output .d.ts definition files, I guess they are unverified and prone to errors. If you don't want to switch to TypeScript, it would be great to have at least some sort of TypeScript verification step in Aurelia's build process.

**Comment by EisenbergEffect** [comment]
We do have a verification process in place, but no TS process (including switching to TS for everything) would be able to verify this particular pattern. The `RouteConfig' only has a `NavModel` after it is configured and it only mattersfrom the perspective of user code.

**Comment by ctoran** [comment]
OK, so it is optional: `navModel?: NavModel`. Can I make a PL for it or did you reject the issue? I don't want to set it as `any` in my code when there is good typing in there.

**Comment by ctoran** [comment]
I see, if I understood correctly you mean it should not come in route maps. In that case why not make it a method like `getNavModel()`? Another way I can think of is to declare `navModel` in another interface that extends `RouteConfig`.

**Comment by ctoran** [comment]
I went with extending the interface:

```typescript
declare module 'aurelia-app' {
  import {RouteConfig as RouteMap, NavModel} from 'aurelia-router';

  export interface RouteConfig extends RouteMap {
    /**
      * Navigation model. The [[RouteConfig]] only has a [[NavModel]] after it is configured.
      */
    navModel?: NavModel;
  }

}
```

then `import {RouteConfig} from 'aurelia-app'` and define `activate` like below:

```typescript
  activate(params: any, config: RouteConfig) {
      config.navModel.setTitle("new title");
  }
```
