### ISSUE TITLE
Multiple viewports cause duplicate routes

### ISSUE THREAD

**Issue by AStoker** [aurelia/router#213]
I'm trying to setup multiple viewports with Aurelia (http://aurelia.io/docs.html#rendering-multiple-view-ports). However, when I setup the router config to tell which ```<router-view>``` which module to load, the result is that now, ```router.navigation``` has an additional entry for each viewport added.  

For example (modified from the skeleton project):
``` javascript
configureRouter(config, router) {
        config.map([
      { route: ['','welcome'],  name: 'welcome',      viewPorts: {test: {moduleId: 'welcome'}, 		test2: {moduleId: 'welcome'}},      nav: true, title:'Welcome' },
      { route: 'users',         name: 'users',        viewPorts: {test: {moduleId: 'users'}, 		test2: {moduleId: 'users'}},        nav: true, title:'Github Users' }
    ]);
        this.router = router;
}
```
``` html
<div class="page-host">
    <router-view name="test"></router-view>
    
    <router-view name="test2"></router-view>
  </div>
```

The result is now ```router.navigation``` contains duplicate navigations (one duplicate for each router-view)
<img width="714" alt="screen shot 2015-09-18 at 9 52 27 am" src="https://cloud.githubusercontent.com/assets/2907279/9960839/0a7017b6-5deb-11e5-9e52-f7e2cdafb70e.png">
<img width="499" alt="screen shot 2015-09-18 at 9 53 33 am" src="https://cloud.githubusercontent.com/assets/2907279/9960858/27a66a10-5deb-11e5-8e44-98a7e3ea94e2.png">

Any ideas on this one? Could it be bad configuration? Or is it something wrong with the router?...

**Comment by jdanyow** [comment]
@AStoker try it like this:

```javascript
    configureRouter (config, router) {
        config.map([
            {
                route: '',
                viewPorts: {
                    menu: {
                        moduleId: 'static/menu',
                        nav: false  // <----------
                    },
                    default: {
                        moduleId: 'static/homepage',
                        nav: true,  // <----------
                        title: 'Homepage'  // <----------
                    },
                    footer: {
                        moduleId: 'static/footer',
                        nav: false  // <----------
                    }
                }
            }
        ]);
```

**Comment by AStoker** [comment]
Perfect, thanks @jdanyow! I figured it was a configuration thing, but when I asked on the Aurelia Gitter, no one knew. Didn't realize that each viewport's navigation object works that way (configurable like it's own route). Might be worth putting a note in the documentation about that?

**Comment by AStoker** [comment]
(Sorry for the late responses too, I've been gone for a bit). That actually didn't seem to work @jdanyow. It's still probably configuration, however, when I have what you have, there is no ```nav: true``` on the route as a whole, and so it doesn't appear at all in the navigation array. If I include ```nav: true``` on the route, and then specify which viewPort has the ```nav: false``` property, I get the same behavior as before. Updated config based off skeleton:

``` javascript 
   config.map([
     	{ route: ['','welcome'],  
			name: 'welcome',      
			viewPorts: {
				test: {
					moduleId: 'welcome',
					nav: true,
				}, 
				test2: {
					moduleId: 'welcome',
					nav: false
				}
			},
	      
			nav: true,  //When removed this whole route is gone from navigation
			title:'Welcome' 
	    },
		{ route: 'users',
			name: 'users',
			viewPorts: {
				test: {
					moduleId: 'users',
					nav: true,
				},
				test2: {
					moduleId: 'users',
					nav: false
				}
			},        
			
			nav: true, //When removed this whole route is gone from navigation
			title:'Github Users' }
   ]);
```

That configuration produces the same issue as before. If I drop the ```nav: true``` on the route as a whole, then I get no navigation at all.

**Comment by AStoker** [comment]
Bumping this one...

**Comment by bryanrsmith** [comment]
@AStoker Sorry for the slow response time on this. Looks like a bug in the view port registration code. We look for a `configureRouter` method on the view model when a router-view element is found in the root view. The router isn't marked as configured until *after* configuration runs, and since it's Promise-based they're both running and configuring the router. I should be able to get a fix in this weekend for the next release.

**Comment by AStoker** [comment]
Gotcha. Thanks for looking into it! Much appreciated.
