### ISSUE TITLE
Refresh the navigation routes

### ISSUE THREAD

**Issue by heruan** [aurelia/router#216]
I'm writing a Security Manager for my project in Aurelia and I'm trying to fit it well with Aurelia's router. Instead of dealing with `if`s in HTML views, I'd like to use the `nav` property of routes configuration to include/exclude routes from the `navigation` array; i.e.
```javascript
config.map([
  {
    name: "home",
    route: "",
    moduleId: "./home",
    nav: true // always visible
  }, {
    name: "login",
    route: "login",
    moduleId: "./login",
    nav: !this.securityContext.isUserAuthenticated(), // if user is not authenticated
    title: 'Sign-in'
  }, {
    name: "private",
    route: "private",
    moduleId: "./private",
    nav: this.securityContext.isUserInRole("canAccessPrivate"),
    title: "Private area"
  }
]);
```
When the user login successfully, the `navigation` array should be rebuilt; I tried with `router.refreshNavigaiton()` but then I checked the source and got it's not its purpose.
How can I efficiently rebuild the `navigation` array of the routers in the router hierarchy?

**Comment by EisenbergEffect** [comment]
Is the `nav` property the only property you need to udpate?

**Comment by heruan** [comment]
In this scenario, it is. Since—for what I undestand—it's the property defining the presence of the route in the navigation array, I'd like to use that instead of adding another, if that's possibile and correct.

**Comment by heruan** [comment]
P.S. Of course, I also have an `AuthorizationStep` added to the navigation pipeline to authorize the user to access the route.

**Comment by EisenbergEffect** [comment]
One way would be to manipulate the router's `navigation` array directly. Just add/remove NavModel instances from that, based on the router's `routes` array.

Another thing you could so is mark every route as `nav: true` during configuration, then simply update the `nav` properties dynamically at a later point in time.

I think you should be able to do this from a pipeline step.
