### ISSUE TITLE
Combining parameter and wildcard doesn't match route correctly

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/router#220]
Referencing Issue : https://github.com/aurelia/templating/issues/180

**Comment by zewa666** [comment]
so in order for your example of order/112/summary to work you'd need something like this: `order/:id/*s` the important part is that you need to give it at least something behind the star sign. Not sure if that is intended but might help you in the meanwhile

**Comment by bryanrsmith** [comment]
@devteamexpress Can you provide more info about what you're trying to do? The router already sets up wildcard routes internally to handle child routers, so you shouldn't need to worry about that. A single route parameter can't be both dynamic (`:`) and wildcard (`*`).

Does `order/:id/*path` do what you want?

**Comment by bryanrsmith** [comment]
I'm going to close this for now. Please feel free to reopen it if there's something I need to look into.
