### ISSUE TITLE
Is there any way to bind the route value in route-href custom attribute?

### ISSUE THREAD

**Issue by shabalin** [aurelia/router#222]
We have, I guess, pretty simple usage scenario of `route-href` custom attribute.
We have a navigation structure defined in the ViewModel and we want to render simple menu this way: 
```html
<a route-href="route: ${item.route}" repeat.for="item of navItems"
      <i class="fa ${item.icon}"></i>
</a>
```

which triggers this error

```
A route with name 'undefined' could not be found. Check that `name: 'undefined'` was specified in the route's config.
``
`
The `route` is defined, I see that in the console:
```
0: Object
__observer__: OoObjectObserver
__observers__: Object
icon: "fa-crosshairs"
route: "ROUTE_1"
title: "Route 1"
```
I also tried to do `route-href="route: item.route"`, that cause another error

```
Unhandled promise rejection Error: A route with name 'item.route' could not be found. Check that `name: 'item.route'` was specified in the route's config.
```

**Comment by nathanchase** [comment]
Try **route.bind** instead of just route:
```
<a route-href="route.bind: ${item.route}" repeat.for="item of navItems"
      <i class="fa ${item.icon}"></i>
</a>
```

**Comment by bryanrsmith** [comment]
Half way in between :-)

```
<a route-href="route.bind: item.route" repeat.for="item of navItems"
      <i class="fa ${item.icon}"></i>
</a>
```

`${}` is for string interpolation.
