### ISSUE TITLE
Binding route title to an object property

### ISSUE THREAD

**Issue by heruan** [aurelia/router#229]
During a VM activate I use the `routeConfig.navModel.setTitle("Title")` to set the route/page title; i.e.
```javascript
activate(params, routeConfig) {
  return this.http.get("/entity").then(success => {
    this.entity = success.content;
    routeConfig.navModel.setTitle(entity.name);
  });
}
```
 I'd like to bind the route title to `entity.name` so that when the name changes it would be reflected on the browser window title and where the route title is referenced (e.g. a breadcrumb custom element). Is it possible such a binding?

**Comment by EisenbergEffect** [comment]
The binding system can let you execute code when properties change. So, on that side of things it is possible. @bryanrsmith Is it possible to call `setTitle` at any time?

**Comment by bryanrsmith** [comment]
Yes, but I believe it's only exposed via the activate method, so you'll
need to grab it there and store it on the view model somewhere.

**Comment by EisenbergEffect** [comment]
Ok, cool. So, if @heruan grabs the navModel instance and stores it, he can use it later to update the title. Cool. @heruan Take a look at the bindingEngine, if you have the latest. It's going to chance a bit in the next release, but it lets you observe properties and respond to changes easily.

**Comment by heruan** [comment]
Following your advice and using the `bindingEngine` I did this and it's working like a charm:
```javascript
activate(params, routeConfig) {
    return this.retrieveEntity(params).then(entity => {
      if (routeConfig.title) {
        routeConfig.navModel.setTitle(routeConfig.title.replace(/\{(\w+)\}/g, (match, field) => {
          bindingEngine.propertyObserver(entity, field).subscribe(value => {
            routeConfig.navModel.setTitle(routeConfig.title.replace(`{${field}}`, value));
          });
          return entity[field];
        }));
      }
    });
  }
```
This will update routes in the form:
```javascript
{
  route: "/entities/:id",
  moduleId: "./entityViewModel",
  title: "Entity {id}: {name}"
}
```
and when `entity.name` changes, the page title and wherever `navModel.title` is used (e.g. breadcrumbs) its values updates accordingly. Awesome!

**Comment by EisenbergEffect** [comment]
Excellent. Heads up...the binding engine usage is going to change a bit in the next release. You will need to import BindingEngine and then have it injected into your class. We made it a singleton object in your version...which we thought better of almost immediately afterwards. So, be on the lookout for that.
