### ISSUE TITLE
Passing data for bindings via route model. 

### ISSUE THREAD

**Issue by treasonx** [aurelia/router#23]
I was trying to add some additional attributes to the route model so they could be exposed in the HTML bindings. 

Here is a simple example:

```javascript
{
  route: ['', 'home'],
  moduleId: 'home',
  styles: 'fa-home',
  nav: true
}
```

```html
<a href.bind="item.href" class="fa ${item.config.styles}"></a>
```

It at first I tried to access the `styles` attribute via the route model directly in the bindings like `item.styles`. That didn't work and after looking through the code I found that the config is saved as part of the route model under the `config` key. 

There should be some way to pass custom application data via a route config to make it easier to customize the route bindings. Maybe a route model attribute of `data` could be reserved for application specific route metadata.

**Comment by SAAirey** [comment]
This should be explicitly supported via a `data` property:

```js
{
  route: ['', 'home'],
  moduleId: 'home',
  nav: true,
  title: 'Home',
  data: {
    styles: 'fa-home'
  }
}
```

**Comment by PWKad** [comment]
Currently each route has a config object that supports what you are looking for - 

In your VM -
```
import {Router} from 'aurelia-router';
import {Parent} from 'aurelia-framework';

export class Welcome{
  static inject() {
    return [Parent.of(Router)];
  }
  constructor(router){
    this.router = router;
  }
  attached(){
    console.log(this.router.currentInstruction.config);
  }
```

And when you define your route -
```
    this.router.configure(config => {
      config.title = 'Aurelia';
      config.map([
        { route: ['','layout'],  moduleId: 'layout',      nav: true, title:'Compose', someProperty: 'rocks'}
      ]);
    });
```

Now you have access to anything you set as custom on your route in your view-model.  In your example if you are looking to add it to the navigation you can do so like this (pseudo-code) -

```
<ul>
 <li repeat.for="route in routes"><i class="${config.styles}"></i></li>
</ul>
```

**Comment by treasonx** [comment]
Yup thats what I ended up doing. I just thought it might be nice if there were an area reserved for this type of metadata. It would reduce the amount of conflict with the official route config names. 

For example if I added `fooBar: 'thinger'` to my route config. And then in the future aurelia decided to update its API to use `fooBar` for something else we would have a bad day.  If there is a special `data` attribute for custom metadata it would be safer in the long run.

**Comment by EisenbergEffect** [comment]
I've had this request before...and we had it in Durandal. So, I think we
should add a dedicated place for this. It should be pretty easy.

On Thu, Feb 5, 2015 at 10:15 AM, James Morrin <notifications@github.com>
wrote:

> Yup thats what I ended up doing. I just thought it might be nice if there
> were an area reserved for this type of metadata. It would reduce the amount
> of conflict with the official route config names.
>
> For example if I added fooBar: 'thinger' to my route config. And then in
> the future aurelia decided to update its API to use fooBar for something
> else we would have a bad day. If there is a special data attribute for
> custom metadata it would be safer in the long run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/router/issues/23#issuecomment-73062388>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by EisenbergEffect** [comment]
Unless there are any serious complains, we will call the property `settings`. That's basically what we supported in Durandal, so I think it would be nice to keep that the same. Working on this now.

**Comment by treasonx** [comment]
:+1:

**Comment by EisenbergEffect** [comment]
Just put a `settings` property on your route config now. It will be propagated to the nav model as well.

**Comment by treasonx** [comment]
Thanks so much!

**Comment by douglasdeodato** [comment]
work's for me using settings:

```
{
    route: '/home',
    moduleId: '/home/home',
    name: 'home',
    title: 'Home',
    settings: 'fa-file-o',
    nav: true
  }
```

`<i class="fa ${row.settings}" aria-hidden="true"></i><br>
`

**Comment by avril-verhaeghen** [comment]
What about passing an object into a navigate method?

**Comment by davismj** [comment]
That is a different use case. You can ise params and navigateToRoute. https://aurelia.io/docs/api/router/class/AppRouter/method/navigateToRoute/

**Comment by nenadvicentic** [comment]
@davismj When using `navigateToRoute`, passing object instance by attaching it to `parameters` property gets it serialized in the URL. Is there valid way to pass object without it being serialized?

**Comment by davismj** [comment]
@nenadvicentic passing objects is a bad idea in vCurrent. The router handles mapping urls to pages. That means each route should have a unique url and entering that url into the browser should get you the same page. Passing state or object to the router isn't supported because it would violate that principle.
