### ISSUE TITLE
Transclusion / @ContainerLess with Router-View

### ISSUE THREAD

**Issue by chrismbeckett** [aurelia/router#232]
I need multiple layouts in my application. The easiest way seems to be to use child routers/nested and  named views, but the router-view element actually gets added to the DOM as a container element and it is making layout CSS with flexbox, and the use of external frameworks like material design lite which expect DOM structure to be a certain way.

I noticed on custom elements there is a @ContainerLess property that describes how the element transcludes the custom element container. Is there any way (or plans) to allow this on router-view so the loaded template replaces the element?

**Comment by EisenbergEffect** [comment]
Place the `containerless` attribute on the `router-view` or `compose` element and you will get the behavior you want. In other words, do this:

```
<router-view containerless><router-view>
```

**Comment by chrismbeckett** [comment]
Thanks, that's awesome.

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect Is this possible on HTML-only custom elements? I know that we can use the `bindable` keyword. A `containerless` keyword would be great.
