### ISSUE TITLE
Feature Request: Better support for Layouts

### ISSUE THREAD

**Issue by chrismbeckett** [aurelia/router#233]
Using the default router schema with the default App view, but binding doesn't seem to work between the App template and the view controller when binding to a property on the router?

```html
<template>
  <div>${router.title}</div>
  <router-view></router-view>
</template>
```

```js
export class App {
  configureRouter(config, router) {
    config.map([
      {
        route: ['', 'home'],
        name: 'home',
        moduleId: './components/home/index',
        nav: false,
        title: "Hello World"
      },
    ]);
    this.router = router;
  }
}
```

**Comment by chrismbeckett** [comment]
UPDATE: Ok, getting router vs routeConfig object mixed up between App controllers and sub-view controllers. A little trial and error and I think I figured out what was wrong.

**Comment by chrismbeckett** [comment]
Ok, figuring out stuff, but there does seem to be a hole in the router here somewhere. In the App controller, I am configuring my routes as per the docs, but in the template, I need to have conditional logic based on flags on the current route:

```html
<template>
  <router-view if.bind="router.public" class="public-layout"></router-view>
  <router-view if.bind="router.secure class="secure-layout"></router-view>
</template>
```

```js
export class App {
  configureRouter(config, router) {
    config.map([
      {
        route: ['', 'home'],
        name: 'home',
        moduleId: './components/home/index',
        nav: false,
        public: true
      },
    ]);
    this.router = router;
  }
}
```

The real scenario is not this straight-forward because the public and secure layouts require more markup than just the router-view but this is the gist of it.

I am just trying to setup what is a very normal app scenario. One set of public routes (with a layout) for account screens like login, register, and then another layout that has as sidebar, header, etc.

In an actual view, I can have the activate function which gives me the routeConfig that tells me the current route:

```js
  activate(params, routeConfig, navigationInstructions) {
    this.router = routeConfig;
  }
```

This will give me the properties I put on the route, but this means I have to duplicate all my layout markup in every view. I am not sure what I am asking for, the fact that child routers have to be bound to a sub-view with another nested router-view element is very difficult to work with. With Angular's UI-Router there is a separation between states and url's and view templates that is much more flexible.

**Comment by chrismbeckett** [comment]
One more piece of information, in the activate callback on the App controller, the routeConfig parameter is undefined.

```js
  activate(params, routeConfig, navigationInstructions) {
    this.router2 = routeConfig; //<= undefined
    console.log("App activated", );
  }
```

**Comment by EisenbergEffect** [comment]
There are lots of ways to solve this issue. For example, you could use the `compose` element to dynamically render based on data. That's it's main purpose. To find the exact solution, I would need more information on your scenario. The best place for questions like these is our gitter channel though. We use GitHub primarily for tracking bugs and feature enhancements.

**Comment by chrismbeckett** [comment]
I had read the docs on compose, but I guess I didn't really get how to use it. This article has helped - http://www.sitepoint.com/composition-aurelia-report-builder/. What I really want is something like what they have on the MeteorJS Iron Router - the ability to specify the layout as part of a route. This is what it would look like:

```js
export class App {
  configureRouter(config, router) {
    config.map([
      {
        route: ['', 'home'], name: 'home',
        layout: './layouts/public',
        viewPorts: {
          default: { moduleId: './components/home/index' },
        }
      },
      {
        route: ['someFeature'], name: 'someFeature',
        layout: './layouts/app',
        viewPorts: {
          default: { moduleId: './components/someFeature/index' },
          sidebar: { moduleId: './common/sidebar' },
          header: { moduleId: './common/header' }
        }
      },
    ]);
    this.router = router;
  }
}
```

Basically, on a route, I want to be able to define different layout templates, and then fill the named views on the same route, without having to use a child router with a nested template. Based on the blog post I linked, it seems like I might be able to wire this up with layouts view controller and a compose block. I will work on it. Thanks for the suggestion.

**Comment by chrismbeckett** [comment]
FYI - Thx, I figured it out. I just needed to get my head around the potential for compose. I was able to create layout view-models with compose sections, and my custom version of 'viewPorts' on the route to bind to them achieving what I needed.
