### ISSUE TITLE
No navModel after passing a RouteConfig to mapUnknownRoutes

### ISSUE THREAD

**Issue by mattyellen** [aurelia/router#234]
Tried to set up a default route like this:
```
    config.mapUnknownRoutes({route: ["error"], moduleId: "error", title: "(404) Page not found"});
```

But when trying to navigate to an unknown route it fails with:
ERROR [app-router] TypeError: Cannot set property 'isActive' of undefined

Looks like the navModel never gets created in the route config.

Reproduced the issue here:
https://github.com/mattyellen/skeleton-navigation

Which you can see in action by going here:
http://mattyellen.github.io/skeleton-navigation/#/blahblah

**Comment by dfsq** [comment]
I think this is still the issue with aurelia-router@1.0.0-beta.1. With the following configuration

```
{
	route: 'stats/:userId/:startDate',
	name: 'stats',
	moduleId: './stats/stats'
}
```

and later when attempting to navigate to route with 

    this.router.navigate('stats', {userId: this.config.userId, startDate: this.config.startDate});

It throws the error

> ERROR [app-router] TypeError: Cannot set property 'route' of undefined(…)
