### ISSUE TITLE
Refresing router

### ISSUE THREAD

**Issue by VladCherniavsky** [aurelia/router#238]
Hello everyone!

I have problem with refreshing  the router.
```
config.map([
      { route: ['','welcome'],  name: 'welcome',      moduleId: 'welcome', nav: !this.authCheck.isLoggedIn(), title:'Register' },
      { route: 'login',         name: 'login',        moduleId: 'login', nav: !this.authCheck.isLoggedIn(), title:'Login' },
      {route : 'dashboard', name: 'dashboard', moduleId : 'dashboard', nav : this.authCheck.isLoggedIn(), title:'Dashboard'},
      {route : 'logout', name : 'logout', moduleId :'logout', nav : this.authCheck.isLoggedIn(), title : 'Logout'}
    ]); 
```

I have " isLoggedIn "method wich check if the item is in localstorage -its returns "true", if not "false"

At first all is ok. I see "Register" and "login" in nav-bar.
But when user is authorized - nothing change. I also have this two routes in nav-bar.
It will change only if I run   window.location.reload(); - but I don't want to reload whole page.
Also I tried this.theRouter.refreshNavigation(); - but nothing help

How to refresh router correclly?

**Comment by didenkov** [comment]
Hi Vlad. Have you tried custom authorize step approach described at http://aurelia.io/docs.html#customizing-the-navigation-pipeline ?

**Comment by VladCherniavsky** [comment]
@didenkov Hi Dmitry, thanks for  your help, it was useful:  I've manually changed "nav" propetry so the  code  works as I wanted, but I think there must be more convinient way to do the same
