### ISSUE TITLE
href in router is undefined

### ISSUE THREAD

**Issue by VladCherniavsky** [aurelia/router#239]
I tried to configure me route as follow:
```
this.dynamicMap=[ {route : 'dashboard', name: 'dashboard', moduleId : 'dashboard', nav : true, title:'Dashboard'},
        {route : 'logout', name : 'logout', moduleId :'logout', nav : true, title : 'Logout'}];
this.theRouter.configure(config=>{
                      config.map(this.dynamicMap);
                  });
```
I have the same situation if try this one:
```
this.theRouter.addRoute({route : 'dashboard', name: 'dashboard', moduleId : 'dashboard', nav : true, title:'Dashboard'});
```

It  works, I see  items in nav-bar, but when I try to click on link I get "undefined " in url.
The console shows me that 'href' property for this items  is "undefined "
Maybe somebody knows what is the problem?

**Comment by bryanrsmith** [comment]
It looks like `href`s in the navigation array aren't set until the router actives & determines its current location, so my guess is that you're trying to render nav links before the router has been activated.

The root router will activate automatically when a viewport is registered (when you render a `<router-view>` element). I would suggest using a `configureRouter()` method on your root view model and a `<router-view>` element in your view. If you can't do that for some reason, you could try calling `router.active()` manually, but I'm not sure it will work right without any viewports to render to.

If my guess is incorrect then I'll need a little more context to help. Let me know if that solves your problem.

**Comment by VladCherniavsky** [comment]
Unfortunately it didn't solve my problem.
Thanks for help

**Comment by bryanrsmith** [comment]
Are you able to post a more complete code sample? Seeing the whole view
model & view would be helpful.

**Comment by Lakerfield** [comment]
@VladCherniavsky I had the same issue. You can fix it with with a refeshNavigation call to update the href property which in used in the nav-bar.
```
this.router.configure(config);
this.router.refreshNavigation();
```

**Comment by stoffeastrom** [comment]
@bryanrsmith I got the same issue when trying to register a route from a feature/plugin following @EisenbergEffect [suggestion](https://github.com/aurelia/router/issues/156)

```javascript
import {AppRouter, RouterConfiguration} from "aurelia-router";

export function configure(aurelia) {
  const router = aurelia.container.get(AppRouter);
  const routerConfig = aurelia.container.get(RouterConfiguration);
  routerConfig.map([
    { route: "parts", moduleId: "features/parts/parts", name: "parts", nav: true, title: "parts" }
  ]);
  routerConfig.exportToRouter(router);
  router.refreshNavigation();
}
```

However this yields in a
```javascript
ERROR [app-router] Error: Route not found: /parts(…)
```

when clicking on the `href`. Looking in the `AppRouter` when debugging the `recognizer` hasn't registered it so I guess I have multiple instances of `AppRouter`

**Comment by EisenbergEffect** [comment]
@stoffeastrom Are you on the latest versions? There was a bug that could enable multiple instances of AppRouter. That was fixed in the last release.

**Comment by stoffeastrom** [comment]
Good question, let me verify that :)

**Comment by stoffeastrom** [comment]
:+1: works
