### ISSUE TITLE
Add Router events like in Durandal

### ISSUE THREAD

**Issue by zewa666** [aurelia/router#24]
I liked the emitted events from the Durandal Router, as in certain situations, especially for E2E tests, those were quite helpful to understand what the current state of page routing is.

Just for the sake of completeness I'll post them here again:
- router:navigation:complete
- router:navigation:cancelled
- router:navigation:processing
- router:route:activating
- router:route:before-config
- router:route:after-config
- router:navigation:attached
- router:navigation:composition-complete
- router:route:not-found

In case of E2E tests I'd be specially interested in the `router:navigation:complete` and `router:navigation:composition-complete` event, as they would allow to work easier with scenarios like Page transitions and dynamic composition.

**Comment by tyrsius** [comment]
the `before-config` and/or `after-config` be raised if no configuration is provided, or should they be skipped?

**Comment by EisenbergEffect** [comment]
Actually, let's leave those two events out of the new router for now. I think the events we probably need in the end are something like this:

* router:navigation:complete
* router:navigation:cancelled
* router:navigation:processing
* router:route:activating
* router:route:deactivating
* router:route:not-found

**Comment by tyrsius** [comment]
I made the pull request, but these events did not make it in. They will require a lot more thought

router:route:activating
router:route:deactivating
router:route:not-found

**Comment by zewa666** [comment]
Regarding not-found what about this place? https://github.com/aurelia/router/blob/master/src/router.js#L149

**Comment by EisenbergEffect** [comment]
Yes, that could be done there.

**Comment by tyrsius** [comment]
I didnt want to make modifications to the base router, so that another implementation could avoid using events. @EisenbergEffect, when I asked you agreed that changes should be kept to the app-router.

**Comment by EisenbergEffect** [comment]
That's true. It's probably the only way to raise that event though. We could detect the failed promise in the app router and if it has the correct message or starts with the correct indicator, raise the event I suppose.

**Comment by tyrsius** [comment]
Yea, that should work. I will give that a try later today. PWkad had another suggestion that I will add as well, but it will be after work
