### ISSUE TITLE
Weird problem with router and value converter if inside if.bind

### ISSUE THREAD

**Issue by BruceL33t** [aurelia/router#240]
I've made a plunkr here which replicates the problem.

http://plnkr.co/edit/dnCtpI?p=preview

Eg. this does not work:
```
<div show.bind="auth.isNotAuthenticated()">
	<require from="login" ></require>
	<login router.bind="router"></login>
</div> 
<div if.bind="auth.isAuthenticated()">
    <require from="../styles/blah.css"></require>
    <div class="container" id="banner">
        <img src="images/logo.png" />
    </div>
    <require from="nav-bar"></require>
    <nav-bar router.bind="router"></nav-bar>
    <div class="page-host">
        <router-view></router-view>
    </div>
</div>
```

But if I remove the ```<div if.bind="auth.isAuthenticated">``` it does work.

What works? (or not)

```
export class RouteLanguageFilterValueConverter {
    toView(routes) {
        console.log(routes) // this return [] on if.bind="xxx"
        //return routes; // this will not return any routes
        return routes.filter(r => r.config.languageId === 13); // this return [] on if.bind="xxx"
    }
}
```
even ```<div if.bind="true">``` doesn't make a difference - the if.bind seems to somehow be the problem

**Comment by BruceL33t** [comment]
A last resport made me try to replace if.bind with show.bind, and although I must admit I was surprised, it did seem to get the job done. Logically it just doesn't make much sense to me, since I should show was just kinda like jquery.show/hide to toggle visibility on the divs. Here I'd actually use it to either show the login page with no styles or other static assets, vs displaying the fullblown page container with site-wide styles, scripts etc :/ show.bind did work, but it doesn't feel right :/

**Comment by bryanrsmith** [comment]
Configuration of the root router is kicked off when the `router-view` element is created. Maybe the `if` binding is causing the the `nav-bar` to read `router.routes` before configuration completes? I'm not sure why the filter breaks it.

@EisenbergEffect Any ideas?

Looks like the key pieces of the repro are:

1. The `if` binding in the `app.html`.
2. The `route-language-filter` used to filter the routes array in `nav-bar` returns a new array each time.

if you remove either one of those two, the problem doesn't appear.

**Comment by EisenbergEffect** [comment]
The router-view itself cannot be conditionally included.
