### ISSUE TITLE
Expose history action type

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#243]
We should attach the history action type (push or pop) to the navigation instruction so activation code can read it.

**Comment by EisenbergEffect** [comment]
Great idea!

**Comment by Alexander-Taran** [comment]
http://aurelia.io/docs/routing/configuration#basic-configuration  
Navigation States
kinda covers the idea behind issue to be able to know weather app is navigating back or forward

can be closed

**Comment by davismj** [comment]
I think the idea was different, but I'm not sure where Bryan was going with this.
