### ISSUE TITLE
NavigationInstruction TS definitions

### ISSUE THREAD

**Issue by jods4** [aurelia/router#247]
`NavigationInstruction::params, queryParams, config, addViewPortInstruction` are all typed as `Object`.
same for `NavModel.config` and probably others.

This is unhelpful because TS will raise errors whenever you try to do anything remotely useful, such as `instruction.config.moduleId`.

`Object` should be replaced by `any`, or ideally with a strongly typed model where applicable (e.g. `config`).

**Comment by bryanrsmith** [comment]
Thanks. I've updated those annotations, and several others in the project.
