### ISSUE TITLE
TS definition: mapUnknownRoute

### ISSUE THREAD

**Issue by jods4** [aurelia/router#248]
`mapUnknownRoute` is declared to accept a function returning `void | Promise<void>` but it should be `string | Promise<string>` (I think).

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you confirm?

**Comment by StrahilKazlachev** [comment]
Isn't it actually `string | Promise<string> | RouteConfig | Promise<RouteConfig>`?

**Comment by StrahilKazlachev** [comment]
Also can you replace in the definitions `Object` with `any` where appropriate? Like in `NavigationInstruction.params`, `NavigationInstruction.config`, `NavigationInstruction.queryParams`. Casting to `any` to use them is ... uncomfortable.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Would be great to get this addressed by Friday so we can have it for the beta.
