### ISSUE TITLE
Regression: route-href binding + pushState

### ISSUE THREAD

**Issue by jods4** [aurelia/router#251]
My app uses 
`RouterConfiguration.options.pushState = true`.

I have links throughout the application similar to this: 
`<a route-href="route: dashboard">`.

Before pre-beta release it worked fine and looked like this: 
`<a href="/my/dashboard/url">`

After beta release it generates this:
`<a href="#/my/dashboard/url">`

Which of course doesn't work anymore.

**Comment by EisenbergEffect** [comment]
@bryanrsmith If possible to fix by tomorrow, please do. I would categorize this has a high priority bug.

**Comment by EisenbergEffect** [comment]
@bryanrsmith If it can't be done in time, let me know. We can plan a fast hotfix after release.
