### ISSUE TITLE
confirm: calling navigate with the same route but different params does not reload browser pane

### ISSUE THREAD

**Issue by jadrake75** [aurelia/router#255]
I was working on some refactoring of how I am handling some code that modifies a query string parameter in one of my routes for my application.  Currently the route url might look like the following

```
http://somehost:9005/stamp-web#stamp-list?$filter=(countryRef eq 5)
```

if I call the router with `navigate()` like the following:

```
this.router.navigate(this.router.generate('stamp-list', {$filter: '(countryRef eq 7)'}));
```

Is it safe to assume this will *not* cause a browser page reload (it will reload the route `stamp-list` only)?  I also did *not* see the change in the query string cause the route to

* re-execute attached()
* re-execute activate()
* re-execute bind()

I am *perfectly* happy with this, however I wanted to verify this is indeed correct and modifying the query string and calling navigate on the *same* route will not cause a re-execution of the route's view-model lifecycle.

**Comment by jadrake75** [comment]
(this was phrased as a question - but I can not set labels on the issues)

**Comment by bryanrsmith** [comment]
That's correct. By default a query string change won't run lifecycle methods. You can control this behavior by implementing a `determineActivationStrategy` method on your view model.

```js
import {activationStrategy} from 'aurelia-router';
...
class MyViewModel {
  determineActivationStrategy() {
    return activationStrategy.replace; //replace the viewmodel with a new instance
    // or activationStrategy.invokeLifecycle to invoke router lifecycle methods on the existing VM
    // or activationStrategy.noChange to explicitly use the default behavior
  }
}
```
