### ISSUE TITLE
Dynamic Routing- Alter Title

### ISSUE THREAD

**Issue by ClareBear85** [aurelia/router#256]
{ 
route: 'content/:id',
name: 'Details', 
title: 'Details',
viewPorts: { main: { moduleId: './admin/content/details' }, aside: { moduleId: './admin/content/aside' } }, 
settings: { menu:menuSection.content, access: { controller: 'content', action: 'get' } }
},
{ 
route: 'content/:id',
name: 'Add', 
viewPorts: { main: { moduleId: './admin/content/details' }, aside: { moduleId: './admin/content/aside' } }, 
settings: { menu:menuSection.content, access: { controller: 'content', action: 'get' } }
title: 'Add',
href: 'content/0',
nav: true
}

import {Router} from 'aurelia-router'; 

activate(){
    if (this.id === 0) {
        this.router.title = "Add";
    } else {
        this.router.title = "Edit";
    }
}
I am trying to alter the Title as its currently saying 'Add' for both new and updated content. I've tried routeConfig (routeConfig.navModel.title = 'Edit';) as well (Unhandled promise rejection TypeError: Cannot read property 'navModel' of undefined), just wondering if I am close, to finding the right code? Do I need to do some sort of push this.router.push?

**Comment by StrahilKazlachev** [comment]
Check the `Router` [API doc](http://aurelia.io/docs.html#/aurelia/router/1.0.0-beta.1/doc/api/class/Router)
```
updateTitle( ): void
Updates the document title using the current navigation instruction.
```

**Comment by ClareBear85** [comment]
class UpdateTitle {
    run(routingContext, next, routeConfig) {
        var instr = routingContext.nextInstructions.find(i => i.params.id !== undefined && i.params.id !== 0 && i.params.id !== '');
        if(instr !== undefined) {
            routeConfig.navModel.title("TEST");
            debugger;
        }

        return next();
    }
}

result = Object {status: "rejected", context: NavigationContext, output: TypeError: Cannot read property 'navModel' of undefined at UpdateTitle.run

**Comment by bryanrsmith** [comment]
You'll need to use the navModel's `setTitle` method in `activate`.

```js
activate(params, routeConfig) {
  routeConfig.navModel.setTitle(params.id === '0' ? 'Edit' : 'Add');
}
```

Also note that the router does not parse route params, so your ID will be a string, not a number. I.e., a matched path of `/content/0` will result in a params object of `{ id: '0' }`, not `{ id: 0 }`.

**Comment by ClareBear85** [comment]
Sorry for the deploy, was pulled onto something else. This is the code I have:

import {inject} from 'aurelia-framework';
import {Router, activationStrategy} from 'aurelia-router';

@inject(Router)
export class HeaderSplashesDetails {
    constructor(router) {
        this.router = router;
    }

    activate(params){
        this.id = params.id;
        this.router.navModel.setTitle(params.id === '0' ? 'Edit' : 'Add');
    }

    get IsLocked() {
        return true;
    }

    Pin() {
        alert('Pin');
        var payload = { Id: this.id, Name: this.basecontent.widget.currentViewModel.baseContent.Name };
        this.eventAggregator.publish('PinVariable', payload);
    }
    
    determineActivationStrategy(){
        return activationStrategy.replace;
    }
}

ERROR [app-router] TypeError: Cannot read property 'setTitle' of undefined

**Comment by bryanrsmith** [comment]
navModel is a property on the second parameter to the activate method, not
the router. Take a second look at the code I posted.

**Comment by ClareBear85** [comment]
whoops sorry, this can be closed now
