### ISSUE TITLE
Windows 10 mobile edge Routing not working

### ISSUE THREAD

**Issue by Cedware** [aurelia/router#257]
On the edge Browser on windows 10 mobile the routing isn't working, it doesn't matter if Iuse the navigate function of the Router or if I enter the url manually. the page just displays the default route (route: ["","/somePath"])

**Comment by bryanrsmith** [comment]
I don't have access to a device to test this on, so I'd be grateful for any help.

**Comment by activebiz** [comment]
@bryanrsmith you dont need an access to the device. If you have VS 2015 you can install the app locally (without debug)

**Comment by EisenbergEffect** [comment]
Is this still an issue? or was it resolved? Are all the proper polyfills being used for IE10?

**Comment by Cedware** [comment]
I'm going to try it in the next few days

**Comment by martonsagi** [comment]
Hi,

I've just tested the most recent [skeletion-webpack](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-webpack), and I was unable to reproduce any of these issues with aurelia-router 1.0.0-beta.2.0.1. It works without any problem on Windows 10 Mobile.

**Test environment 1:**
Microsoft Lumia 640
Windows 10 Mobile, OS Build 10.0.10586.71 (2016-02-01)
[VorlonJS](https://github.com/MicrosoftDX/Vorlonjs) as debugger

**Test environment 2:**
Windows 10 Desktop, OS Build 10586.318
Microsoft Edge 25.10586.0 with Windows 10 Mobile emulation mode

**Comment by EisenbergEffect** [comment]
Thanks @martonsagi Perhaps it was a system.js issue?
On another note, I see you are using VorlonJS. How so you like it?
