### ISSUE TITLE
bootstrapping Aurelia app routing from within an ASP.NET MVC route

### ISSUE THREAD

**Issue by stefan505** [aurelia/router#259]
I've setup ASP.NET 5 MVC to route to http://localhost:12345**/app** that serves as my Aurelia app. From here, I bootstrap the router:

```
        config.map([
            { route: 'link-a', name: 'link-a', moduleId: 'features/link-a', nav: true, title: 'Link A', settings: { auth: true } },
            { route: 'link-b', name: 'link-b', moduleId: 'features/link-b', nav: true, title: 'Link B', settings: { auth: true } }
        ]); 
```

It seems that the Aurelia router doesn't seem to work properly when trying to generate the route from within another VM (**BTW** `route.href` is undefined, so I use `route.relativeHref`, also seems strange...):

``<li><a ${activeText} href="/app/#${route.relativeHref}"><i class="fa fa-circle-o"></i> ${route.title}</a></li>``

When accessing that generated link, the browser does a full server request and ignores the Aurelia router completely. Is this a bug or am I missing something?

**Comment by EisenbergEffect** [comment]
@bryanrsmith I think this is the same issue we discussed the other day related to `config.options.root`. Can you confirm?

**Comment by bryanrsmith** [comment]
Is `/app` the root of the aurelia app, or a page of it? You need a route entry for the page you're starting on. Probably either `/`, or `app`. The router can't activate without a matching route for the current page. The navModel's `href` is not set until after the router activates with a valid current route, which is probably why your nav links are not working.

**Comment by stefan505** [comment]
`/app` is the result of a razor view being served. That view is an HTML page (`<html>..</html>`), with the `body` tag containing `aurelia-app="main" es5`. Inside `main` (static content served from wwwroot) it resolves to `aurelia.start().then(a => a.setRoot('shell/shell'));`. Inside `shell`, I have this:

```
    configureRouter(config: RouterConfiguration, router: Router)
    {
        config.map([
            { route: 'link-a', name: 'link-a', moduleId: 'features/link-a', nav: true, title: 'Link A', settings: { auth: true } },
            { route: 'link-b', name: 'link-b', moduleId: 'features/link-b', nav: true, title: 'Link B', settings: { auth: true } },
        ]); 

        this.router = router;
    }
```

Inside the html template for `shell`, I perform this:

```
   <compose view-model="./menu-tree.js"
                         model.bind="router"></compose>
```

Inside `menu-tree`, the markup is dynamically build up for the `InlineViewStrategy`. The reason for using `menu-tree` is to sub-select from the router's routes, i.e. dynamic menu build up depending on what the user has access to. In hindsight, I guess its better to try and  configure the `router` dynamically inside `shell` based on the user's privs?

**Comment by bryanrsmith** [comment]
And is there a `<router-view></router-view>` in your shell template? You will need to add a default route at `''` so the router has something to activate.

**Comment by stefan505** [comment]
@bryanrsmith yeah, `<router-view></router-view>` inside `shell` template. Changed my first route to include the default route and that renders. 

I'm still having no luck with this, so I decided to bypass my own `shell` root component and go back to basics and created a new root component called `bla`. The contents are copied from `app` from the [Aurelia docs](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.3/doc/article/getting-started), with my own routes applied as per earlier comment:

When setting an MVC route to `[Route("abc")]` (http://localhost:60751/abc), it renders the default route, but the nav fails for all Aurelia routes. Generated nav URL sample: `http://localhost:60751/app#/link-a`. The same thing happens when removing the route `[Route("")]`(http://localhost:60751/).

The puzzling part is the `/app` in the generated URLs. I can't figure out where this comes from? I have no physical `app` component or route path both on MVC and Aurelia's routing. Its a plain vanilla Aurelia component.

**Comment by bryanrsmith** [comment]
Well that's progress :-)

@EisenbergEffect Does the `<compose>` use look right to you? I think you can drop the `.js` extension, but I'm not sure if that would break it.

**Comment by stefan505** [comment]
When dropping the `.js` extension, the URL ends up being `http://localhost:60751/shell/menu-tree`. Don't know if this is because I'm using RequireJS, will have to step through Aurelia's code, just haven't had much time. 

I've replaced the `InlineViewStrategy` based `menu-tree` with helper functions on the `shell` to achieve my menu requirements. I take two points away:

1) Utilising the router in an `InlineViewStrategy` call as part of the "bootstrapping" phase is a bad idea, since the router hasn't finished "activating" itself yet.
2) We need documentation illustrating more complex router uses including, templating, view parts, etc. especially in terms of do's and dont's. I've spent many an hour figuring out where Aurelia's router limitations are that are not documented.

**Comment by EisenbergEffect** [comment]
A couple of notes:

I don't understand your first point above. You don't show  how you are using that in any of the preceding examples. Using InlineViewStrategy should work in any scenario. If it doesn't, there's a bug...but I can't exactly tell what you are doing from the details above. There's a lot of missing information in the descriptions.

While we do need much more documentation, I don't see what your issue above has to do with any of the things you are asking about for templating in point 2. The router doesn't have much to do with templating, view-parts, etc.

Please try to put together a simplest possible solution that reproduces your issues. The above information isn't thorough enough for me to understand what you are doing.

Note: You should not have a `.js` file extension in your compose usage.
@bryanrsmith Should he be setting `config.root` ?

**Comment by bryanrsmith** [comment]
Setting `router.config.root = 'app';` when the root router is configured would tell the router to handle everything under /app. So navigating to '/' would map to /app, '/about' would map to '/app/about', etc. I'm not sure if that's the desired behavior or not, but from what I can tell none of the problems described are symptomatic of a misconfigured router root.

@stefan505 Does this help? As Rob notes, we can certainly help work through some of this, but will probably need to see a complete code sample.

We do need more and better documentation and samples. Is there a specific use case that you've found lacking? I think the docs do have basic info on viewports and templating.
