### ISSUE TITLE
Add an API to the PipelineProvider to enable the adding of pipeline steps

### ISSUE THREAD

**Issue by SAAirey** [aurelia/router#26]
Add an API to add pipeline steps to the router's pipeline provider.

For example, an authentication step might be added as the very first step in the pipeline.

**Comment by Alxandr** [comment]
I've implemented a proposal of this over at https://github.com/Alxandr/router/tree/feature-route-filters.

Sample usage:

```js
import {Router, RouteFilterContainer} from 'aurelia-router';
import {Container} from 'aurelia-dependency-injection';
import bootstrap from 'bootstrap';

export class App {
  static inject() { return [Router, RouteFilterContainer]; }
  constructor(router, routeFilterContainer) {
    routeFilterContainer.addStep('authorize', AuthorizeStep);
    this.router = router;
    this.router.configure(config => {
      config.title = 'Aurelia';
      config.map([
        { route: ['', 'welcome'],     moduleId: 'welcome',      nav: true, title:'Welcome' },
        { route: 'flickr',        moduleId: 'flickr',       nav: true, auth: true },
        { route: 'child-router',  moduleId: 'child-router', nav: true, title:'Child Router' }
      ]);
    });
  }
}

class AuthorizeStep {
  static inject() { return [Container]; }
  constructor(container) {
    // this is simply to test that injection works
    this.container = container;
  }

  run(routingContext, next) {
    if (routingContext.nextInstruction.config.auth) {
      console.log('running auth...');
      return next();
    } else {
      return next();
    }
  }
}
```

Here, the `AuthorizeStep` is added to the pipeline, at a named point (namely `authorize`). These named points can be seen here: https://github.com/Alxandr/router/blob/feature-route-filters/src/pipeline-provider.js#L22,L24

These named "filters" (as I've chose to call them) act as their own mini-pipelines, an can be added/depend on each other. So I can easily define my own (simply by calling `addStep('myfilter', MyFilterStep);`, and then I can add the `myfilter` pipeline to the `authorize`-pipeline by calling `addStep('authorize', 'myfilter');`.

**Comment by EisenbergEffect** [comment]
I'd really be interested to have this as part of the config api, so you could do something like this:

```javascript
this.router.configure(config => {
      config.title = 'Aurelia';
      config.addPipelineStep('authorize', AuthorizeStep);
      config.map([
        { route: ['', 'welcome'],     moduleId: 'welcome',      nav: true, title:'Welcome' },
        { route: 'flickr',        moduleId: 'flickr',       nav: true, auth: true },
        { route: 'child-router',  moduleId: 'child-router', nav: true, title:'Child Router' }
      ]);
    });
```

**Comment by Alxandr** [comment]
That's definitely doable, I just think it's kind of illogical. Given that you app can have several instances of router, and if you config this at the innermost router, it's going to apply to all of them.

**Comment by EisenbergEffect** [comment]
We would disallow this on child routers. We could even throw if someone tries to do this. Mainly, I want to have a unified config api.

**Comment by Cedware** [comment]
How do I add a additional Step like:

`config.addPipelineStep('isconfigured', IsConfiguredStep);`

**Comment by jedd-ahyoung** [comment]
@Cedware The router has a specific set of slots to which you can add a step. They are defined by the framework (as part of the routing lifecycle) and so one can only add steps to certain slots; 'authorize' and 'modelbind' are two of these slots.

In your case, if you want to do something after your router is configured, you can simply use a promise callback, like so:

```
router.configure((config) => {
	// configuration ...
})
	.then(() => {
		// my post-configuration steps
	});
```
