### ISSUE TITLE
Allow view-models to be "stateful" by having a "cache" flag on the route

### ISSUE THREAD

**Issue by gregoryagu** [aurelia/router#262]
It would be useful to have a "cache" flag on a route.  This would tell the router to reuse an existing view-model if it already exists.

For example: I have a search page where the user search for a list of items.  Each item in the list has a button to go to details.  From the details, the user should be able to hit the "back" button and return to the List Page.  The list page should be in exactly the same state as it was before.  

My current workaround is to save the search-parameters in a class stored the DI container.  Then the the search is performed against the database and the results displayed again.  All of that is really unnecessary - the user just want's to go back to where he was before.

If the view-model were cached by the router, then it could simply pull the view-model from the cache and call the lifecycle events in case parameters had changed.  (It would be up to the viewmodel to check the parameters and if they had changed, to take the appropriate action.)

```javascript
 { route: ['open-cases'], moduleId: "./cases/open-cases/open-cases", cache:true}
```

An alternative way to implement this would be to add a screen lifecycle event called cache().  It would be called after deactivate().  If it returns true, it would cache the view-model for the next time it is called.  If not, it would be discarded.  This would allow the app to decide if the view-model should be cached.

**Comment by EisenbergEffect** [comment]
You can simply decorate your view model with the `@singleton()` decorator and your view model will be kept around and re-used when navigating back to the same screen.

**Comment by gregoryagu** [comment]
Awesome :)
