### ISSUE TITLE
 route-href error or incorrect format

### ISSUE THREAD

**Issue by OutOfTouch** [aurelia/router#263]
I have the following `<a route-href="route:details; params.bind{id:movie.id}" 
                       class="btn btn-default">Details</a> ` and I am not sure what I am doing wrong to make this work with 1.0.

**Comment by bryanrsmith** [comment]
What is the problem or error you're seeing? Try params.bind:{id:movieid}

**Comment by OutOfTouch** [comment]
I see this : ERROR [route-href]
Error: A route with name 'details' could not be found. Check that `name: 'details'` was specified in the route's config

**Comment by OutOfTouch** [comment]
OK I tried this ` <a route-href="route:details; params.bind:{id:movieid}" 
                       class="btn btn-default">Details</a>` because it looked like I was missing a colon after bind, although I get the same error, I tried what you sugessted and same thing.

**Comment by OutOfTouch** [comment]
Is this the correct syntax? `<a route-href="route:details; params.bind:{id:movieid}" class="btn btn-default">Details</a>`

**Comment by bryanrsmith** [comment]
Yes.

**Comment by OutOfTouch** [comment]
I don't know what is wrong then because that is not working for me.
> Yes.
> …
>

**Comment by OutOfTouch** [comment]
Is this route correct `{ route:"details/:id", moduleId:"movies/details" }` or does it need to have the name `{ route:"details/:id", moduleId:"movies/details", name:"details" }`

**Comment by bryanrsmith** [comment]
Yes, it will need the name that you're using in `route-href`.

**Comment by OutOfTouch** [comment]
Ok thank you, that was my problem.
> Yes, it will need the name that you're using in `route-href`.
> …
