### ISSUE TITLE
Root router in plugin - TypeScript

### ISSUE THREAD

**Issue by tomasbonco** [aurelia/router#264]
Hello,

As I'm trying to use Aurelia Flux, it gives me error:
`Pipeline steps can only be added to the root router`

When I was reading files, I found that it tries to use RouterConfiguration.addPipelineStep() whitch results in given error.

Because orignal repo (of Aurelia Flux) doesn't seem to be maintained for a some time, I forked PR that should support Beta 1 and created release myself (so I can add it into JSPM). Can be found at:
https://github.com/tomasbonco/aurelia-flux

Tomas

**Comment by EisenbergEffect** [comment]
Great work!

**Comment by tomasbonco** [comment]
Well, I'm saing it's not working, and it's throwing an error message (in latest version possible) :D Maybe there's a problem with Router, or maybe APi changed ...

**Comment by EisenbergEffect** [comment]
Ok, I don't know anything about what the Flux library is doing. So, I can't really say what the bug might be. We haven't made any breaking changes that I'm aware of since our Beta launch.

**Comment by tomasbonco** [comment]
I believe problem is pre-beta, but my question is - when I add plugin in bootstrap phase, and that plugin uses `RouterConfiguration.addPipelineStep()` shoud it work or not? Won't I get error message?

**Comment by EisenbergEffect** [comment]
You can only add a pipeline step to the root router. Instead of running the config against a Router instance resolved from the container, try resolving AppRouter.
