### ISSUE TITLE
AuthorizeStep shows TSC errors like Property 'auth' does not exist on type 'RouteConfig'.

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/router#265]
There is the following code in the cheat sheet (typescript). I have similar code borrowed from the cheat sheet.

http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.6/doc/article/cheat-sheet

```
class AuthorizeStep {
  run(navigationInstruction: NavigationInstruction, next: Function): Promise<any> {
    if (navigationInstruction.getAllInstructions().some(i => i.config.auth)) {
      var isLoggedIn = /* insert magic here */false;
      if (!isLoggedIn) {
        return next.cancel(new Redirect('login'));
      }
    }

    return next();
  }
}
```

tsc shows the following errors.

    Property 'auth' does not exist on type 'RouteConfig'.
    Property 'cancel' does not exist on type 'Function'.

How do I fix?

**Comment by bryanrsmith** [comment]
Looks like we need to adjust the type annotations on the next parameter. It's a function with a `cancel` property tacked on, but it's declared as a function right now.

**Comment by HIRANO-Satoshi** [comment]
I see.

**Comment by bryanrsmith** [comment]
@cmichaelgraham I believe that [this line](https://github.com/aurelia/router/blob/master/src/pipeline.js#L24) needs to use a type annotation like

```typescript
run(instruction: NavigationInstruction, next: { (): Promise, cancel: (result: any) => Promise, reject: (result: any) => Promise, complete: (result: any) => Promise }): void;
```

but the dts generator doesn't appear to support it. Is this something we can add easily, or is there alternative syntax that might work?

**Comment by bryanrsmith** [comment]
Thanks, @cmichaelgraham. Looks like your change worked great.

**Comment by HIRANO-Satoshi** [comment]
Thank you very much!
