### ISSUE TITLE
CSS via require not disposed

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/router#267]
Not sure which repo to post this to, but the router makes the most sense.

Styles imported via `<require>` are not disposed properly, while styles via `<style>` tags are. Is this expected?

Plunkr: http://plnkr.co/edit/gwgBLSLV6OUMHWO7DolL

**Comment by bryanrsmith** [comment]
ping @EisenbergEffect

**Comment by EisenbergEffect** [comment]
I actually don't quite understand this issue. What do you mean by "disposed"? What is it that you are expecting?

**Comment by JeroenVinke** [comment]
Sorry. By disposed I mean removed from the `<head>` after the view that contains the `<require>` tag has been unloaded.

I have updated the plunker to hopefully make this more clear: http://plnkr.co/edit/dh3ia6AkB7ZHRvy4m27

**Comment by EisenbergEffect** [comment]
I'll look into this and see if it's something we can do.

**Comment by bryanrsmith** [comment]
@EisenbergEffect Can this be closed or moved? It doesn't seem like a router issue.

**Comment by EisenbergEffect** [comment]
Yes. We aren't going to do anything with this for the immediate future.
