### ISSUE TITLE
Let child routers run off empty URL fragments

### ISSUE THREAD

**Issue by SAAirey** [aurelia/router#27]
As part of implementing authentication, I was trying to have a login page that looked different to the authenticated part of the application. To do this I set up a default route that went to a layout page which then had a child router that contained the other routes; for example, 'dashboard', 'orders', 'returns' etc.

In my main router configuration I had a default route and a login route:

``` js
{ route: '', moduleId: './layout', nav: false },
{ route: 'login', moduleId: './login', nav: false }
```

Then in the `layout` module I had defined a child router with a 'dashboard' route:

``` js
{ route: 'dashboard', moduleId: './dashboard', nav: true, title: 'Dashboard' }
```

When trying to navigate to `#dashboard` I was receving the following error: `Route Not Found: dashboard`.

I think this is a fairly common scenario and may not even be used for authentication, somebody could have a landing page that looked completely different to the rest of their site and expect something like this to work.

Perhaps the framework could check the root router for the route first, then do the child checks taking into account an empty fragment for the default route and then go through the same logic it currently uses to find child routes now and then if no route is found, it throws a "Route not found" error.

**Comment by lan3jur** [comment]
I can relate to this.. My landing pages usually look totally different to the rest of my site ..

**Comment by EisenbergEffect** [comment]
So the logic would be that if we find no match for routes...then look for an empty route, load that if present and see if it has a child router that matches the next segment?

**Comment by SAAirey** [comment]
Yeah, that would work.

**Comment by cmenke** [comment]
I'm looking to accomplish the same thing. Nesting my main application router at the second level for the sole purpose of having a login page with a different layout feels a bit workaround-ish though (to me anyways).

Wouldn't it also be possible to dynamically override / replace the current (i.e. root) view for specific routes? For example by setting an `overrideView` flag on the route config:
```js
// app.js
{ route: 'login', moduleId: './login', overrideView: true }, //  view (e.g. app.html)
{ route: 'dashboard', moduleId: './dashboard', nav: true, title: 'Dashboard', auth: true },
{ ... }
```

If `getViewStrategy()` was re-evaluated on navigation – even when the module is already activated – it could also be done in there, I think.

**Comment by EisenbergEffect** [comment]
So, perhaps what we need to do is this:

* process the route matching like normal on the parent router
* if a no match is found, check to see if there is an empty route
* if there is an empty route, select that route and assume there's a child router that will match

Maybe something along those lines?

**Comment by bryanrsmith** [comment]
I think that sounds good. There might still be some weirdness if child routes overlap parent routes, like in the skeleton where it recursively registers child routers. In that case we'll always match the parent's route. It seems like a reasonable limitation. We might be able to reduce that case by adding special handling for child routes that specify alternate non-empty paths. Eg, `{ route: ['', 'layout'], moduleId: './layout', nav: false }`, we could prefer the non-empty alternative `'layout'` for the child router's baseUrl, so that its nav model would correctly generate unambiguous paths. That's probably a more extensive code change, and I'm unsure what it might break, though.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you look into that and see what would be involved and estimate how long it might take to do?

**Comment by bryanrsmith** [comment]
Yep.

**Comment by jaimerivera** [comment]
Would the functionality be recursive.  That is if there are three levels of child routers with default routes will it work?  

I had also thought of the possibility of the framework automatically assigning a route fragment to routes contained in child routers.  This would be much like the existing fragment which gets added to routes where the child router is not the default.

**Comment by bryanrsmith** [comment]
Yes, I would think so. We'll just need to make sure we don't infinitely match against child routes for cases like the skeleton that recursively register child routers using the same module.

**Comment by The1nternet** [comment]
+1

**Comment by The1nternet** [comment]
As an alternative to the proposed logic, you could instead encapsulate some logic into a getter for the href property, which would check if it's parent route is represented in the current route, and if not, prepend it.

**Comment by The1nternet** [comment]
Is there a work-around for this, for now?  Should we manually prepend the parent route to the hrefs of the child router?  How else can we get to the child routes, if the app is currently at the default route of the parent router?

**Comment by The1nternet** [comment]
If anyone is struggling with this issue, I have discovered the only current work-around is to setup a redirect route as your default route, so that your child routes will work when the default route is navigated to.  There is a code example (no documentation yet) of setting up a redirect route here:  http://aurelia.io/docs.html#customizing-the-navigation-pipeline

**Comment by avitex** [comment]
:+1:

**Comment by nomack84** [comment]
Hi @bryanrsmith Do you have any update about this?

**Comment by bryanrsmith** [comment]
Sorry, I haven't had time yet.

**Comment by Jaans** [comment]
For those requiring a workaround, the following is a stop-gap workaround I've been using until this has been implemented.
```
config.map([
            { route: "", redirect: "Dashboard" },
            { route: "Dashboard",     name: "Dashboard",     moduleId: "Dashboard/index",            nav: true, title: "Dashboard" }
]);
```

**Comment by jedd-ahyoung** [comment]
For all of you using this for a "landing page" - it's worth noting that there is a better way than using router defaults; use aurelia's `setRoot` method to accomplish this. There's an excellent question-and-answer [here on StackOverflow](http://stackoverflow.com/a/33458652/677526).

**Comment by johnmanko** [comment]
@Jaans That doesn't seem to work. I start having problems using Redirect from an auth filter. Same error. I'm not ready to file a new bug for this one.

```
ERROR [app-router] Error: Route not found: /browse
Stack trace:
_createNavigationInstruction@http://localhost:3000/vendor/npm/aurelia-router@1.0.0-beta.1.1.3/aurelia-router.js:927:29
loadUrl@http://localhost:3000/vendor/npm/aurelia-router@1.0.0-beta.1.1.3/aurelia-router.js:1459:14
_loadUrl@http://localhost:3000/vendor/npm/aurelia-history-browser@1.0.0-beta.1.1.4/aurelia-history-browser.js:281:42
activate@http://localhost:3000/vendor/npm/aurelia-history-browser@1.0.0-beta.1.1.4/aurelia-history-browser.js:185:16
activate@http://localhost:3000/vendor/npm/aurelia-router@1.0.0-beta.1.1.3/aurelia-router.js:1514:7
registerViewPort/_ret5</_ret6</<.v.v<@http://localhost:3000/vendor/npm/aurelia-router@1.0.0-beta.1.1.3/aurelia-router.js:1485:23
```

and `$ jspm inspect`

```
                  github:components/jquery 2.2.1
                       github:github/fetch 0.10.1
               github:jspm/nodelibs-assert 0.1.0
                   github:jspm/nodelibs-fs 0.1.2
                 github:jspm/nodelibs-path 0.1.0
              github:jspm/nodelibs-process 0.1.2
                 github:jspm/nodelibs-util 0.1.0
        github:nakupanda/bootstrap3-dialog 1.34.9
                github:systemjs/plugin-css 0.1.20
               github:systemjs/plugin-json 0.1.0
               github:systemjs/plugin-text 0.0.4
                     github:twbs/bootstrap 3.3.6
                                npm:assert 1.3.0
                  npm:aurelia-animator-css 1.0.0-beta.1.1.2
                       npm:aurelia-binding 1.0.0-beta.1.2.2
                  npm:aurelia-bootstrapper 1.0.0-beta.1.1.4
          npm:aurelia-dependency-injection 1.0.0-beta.1.1.5
              npm:aurelia-event-aggregator 1.0.0-beta.1.1.1
                  npm:aurelia-fetch-client 1.0.0-beta.1.1.1
                     npm:aurelia-framework 1.0.0-beta.1.1.4
                       npm:aurelia-history 1.0.0-beta.1.1.1
               npm:aurelia-history-browser 1.0.0-beta.1.1.4
                        npm:aurelia-loader 1.0.0-beta.1.1.1
                npm:aurelia-loader-default 1.0.0-beta.1.1.3
                       npm:aurelia-logging 1.0.0-beta.1.1.2
               npm:aurelia-logging-console 1.0.0-beta.1.1.4
                      npm:aurelia-metadata 1.0.0-beta.1.1.6
                           npm:aurelia-pal 1.0.0-beta.1.1.1
                   npm:aurelia-pal-browser 1.0.0-beta.1.1.4
                          npm:aurelia-path 1.0.0-beta.1.1.1
                     npm:aurelia-polyfills 1.0.0-beta.1.0.1
              npm:aurelia-route-recognizer 1.0.0-beta.1.1.3
                        npm:aurelia-router 1.0.0-beta.1.1.3
                    npm:aurelia-task-queue 1.0.0-beta.1.1.1
                    npm:aurelia-templating 1.0.0-beta.1.1.4
            npm:aurelia-templating-binding 1.0.0-beta.1.1.2
          npm:aurelia-templating-resources 1.0.0-beta.1.1.3
             npm:aurelia-templating-router 1.0.0-beta.1.1.2
                            npm:babel-core 5.8.35
                         npm:babel-runtime 5.8.35
                  npm:bootstrap-datepicker 1.6.0
                               npm:core-js 1.2.6
                              npm:inherits 2.0.1
                                npm:jquery 2.2.1
                                npm:moment 2.11.2
                       npm:path-browserify 0.0.0
                               npm:process 0.11.2
                                  npm:util 0.10.3
```

**Comment by williamokano** [comment]
Hey guys, any updates on this thread?

**Comment by EisenbergEffect** [comment]
The best way to handle this is to make "empty" fragment redirect to a non-empty route.

**Comment by williamokano** [comment]
I did that indeed, but it didn't worked as I expected.

What I'm trying to accomplish is when I hit the route `#/login` I have one template and when not, fallback to the default route, which have a common template, and then match the routes against the child router. The child router will have other routes like blog, portifolio and I want to reach them through the url `#/blog` or `#portifolio`.

Is this the better way to achieve that or there are more elegant ways to do this?

**app.js**
```javascript
    configureRouter(config: RouterConfiguration, router: Router) {
        config.title = "Blog d'Okano";
        config.map([
            {route: '', redirect: 'site', nav: false},
            {route: 'login', moduleId: 'pages/login/login', nav: true, name: 'login'},
            {route: 'site', moduleId: 'pages/default/main', nav: true, name: 'site'}
        ]);

        this.router = router;
    }
```

**main.js**
```javascript
    configureRouter(config: RouterConfiguration, router: Router) {
        config.map([
            {route: '', moduleId: './home', nav: true, name: 'home'},
            {route: 'blog', moduleId: './blog', nav: true, name: 'blog'},
            {route: 'sobre', moduleId: './sobre', nav: true, name: 'sobre'},
            {route: 'portifolio', moduleId: './portifolio', nav: true, name: 'portifolio'},
            {route: 'contato', moduleId: './contato', nav: true, name: 'contato'}
        ]);

        this.router = router;
        console.log(router);
    }
```

**Comment by smithaitufe** [comment]
This is a very important need. I have this same issue. If this can be achieved today, my project will be completed tomorrow. Please @bryanrsmith what is the state of this enhancement?

**Comment by EisenbergEffect** [comment]
You just need to have the parent route redirect to a non-empty route and you should be good to go.

**Comment by smithaitufe** [comment]
@eisenbergeffect
Thanks a lot but I tried it and it didn't work. 
Look at the app.js configureRouter
```
import { inject } from 'aurelia-framework';
import { EventAggregator } from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class App {
  constructor(events){
    events.subscribe('router:navigation:complete', this.navigationComplete);
  }
  configureRouter(config, router) {
    config.title = 'Delta State Polytechnic';
    config.map([   
      { route: '', name: 'public-section', moduleId: './sections/public/public-section', nav: true, title: ''},
      { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
      { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }

    ]);


    this.router = router;
  }

  navigationComplete(){
    Waves.displayEffect();
  }
}
```
and look at the public-section.jjs configureRouter. This is not working for me

```
import { inject } from 'aurelia-framework';
import { EventAggregator } from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class App {
  constructor(events){
    events.subscribe('router:navigation:complete', this.navigationComplete);
  }
  configureRouter(config, router) {
    config.title = 'Delta State Polytechnic';
    // config.map([
    //   { route: ['', 'home'], name: 'home', moduleId: './sections/home/home', nav: true, title: 'Home', layoutView: 'layouts/default-layout.html', layoutViewModel: 'layouts/default-layout'},
    //   { route: 'about', name: 'about', moduleId: './sections/about/about', nav: true, title: 'About', layoutView: 'layouts/default-layout.html', layoutModel: './layouts/default-layout' },
    //   { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
    //   { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }
    // ]);

    //  config.map([
    //   { route: ['', 'home'], name: 'home', moduleId: './sections/home/home', nav: true, title: 'Home' },
    //   { route: 'about', name: 'about', moduleId: './sections/about/about', nav: true, title: 'About' },
    //   { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
    //   { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }
    // ]);

    config.map([
     
      { route: '', name: 'public-section', moduleId: './sections/public/public-section', nav: true, title: ''},
      { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
      { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }

    ]);


    this.router = router;
  }

  navigationComplete(){
    Waves.displayEffect();
  }
}

```

Your suggestion is highly valued

**Comment by smithaitufe** [comment]
@eisenbergeffect
Thanks a lot but I tried it and it didn't work. 
Look at the app.js configureRouter
```
import { inject } from 'aurelia-framework';
import { EventAggregator } from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class App {
  constructor(events){
    events.subscribe('router:navigation:complete', this.navigationComplete);
  }
  configureRouter(config, router) {
    config.title = 'Delta State Polytechnic';
    config.map([   
      { route: '', name: 'public-section', moduleId: './sections/public/public-section', nav: true, title: ''},
      { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
      { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }

    ]);


    this.router = router;
  }

  navigationComplete(){
    Waves.displayEffect();
  }
}
```
and look at the public-section.jjs configureRouter. This is not working for me

```
import { inject } from 'aurelia-framework';
import { EventAggregator } from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class App {
  constructor(events){
    events.subscribe('router:navigation:complete', this.navigationComplete);
  }
  configureRouter(config, router) {
    config.title = 'Delta State Polytechnic';
    // config.map([
    //   { route: ['', 'home'], name: 'home', moduleId: './sections/home/home', nav: true, title: 'Home', layoutView: 'layouts/default-layout.html', layoutViewModel: 'layouts/default-layout'},
    //   { route: 'about', name: 'about', moduleId: './sections/about/about', nav: true, title: 'About', layoutView: 'layouts/default-layout.html', layoutModel: './layouts/default-layout' },
    //   { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
    //   { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }
    // ]);

    //  config.map([
    //   { route: ['', 'home'], name: 'home', moduleId: './sections/home/home', nav: true, title: 'Home' },
    //   { route: 'about', name: 'about', moduleId: './sections/about/about', nav: true, title: 'About' },
    //   { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
    //   { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }
    // ]);

    config.map([
     
      { route: '', name: 'public-section', moduleId: './sections/public/public-section', nav: true, title: ''},
      { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
      { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }

    ]);


    this.router = router;
  }

  navigationComplete(){
    Waves.displayEffect();
  }
}

```

Your suggestion is highly valued

**Comment by smithaitufe** [comment]
@eisenbergeffect
Thanks a lot but I tried it and it didn't work. 
Look at the app.js configureRouter
```
import { inject } from 'aurelia-framework';
import { EventAggregator } from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class App {
  constructor(events){
    events.subscribe('router:navigation:complete', this.navigationComplete);
  }
  configureRouter(config, router) {
    config.title = 'Delta State Polytechnic';
    config.map([   
      { route: '', name: 'public-section', moduleId: './sections/public/public-section', nav: true, title: ''},
      { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
      { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }

    ]);


    this.router = router;
  }

  navigationComplete(){
    Waves.displayEffect();
  }
}
```
and look at the public-section.jjs configureRouter. This is not working for me

```
import { inject } from 'aurelia-framework';
import { EventAggregator } from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class App {
  constructor(events){
    events.subscribe('router:navigation:complete', this.navigationComplete);
  }
  configureRouter(config, router) {
    config.title = 'Delta State Polytechnic';
    // config.map([
    //   { route: ['', 'home'], name: 'home', moduleId: './sections/home/home', nav: true, title: 'Home', layoutView: 'layouts/default-layout.html', layoutViewModel: 'layouts/default-layout'},
    //   { route: 'about', name: 'about', moduleId: './sections/about/about', nav: true, title: 'About', layoutView: 'layouts/default-layout.html', layoutModel: './layouts/default-layout' },
    //   { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
    //   { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }
    // ]);

    //  config.map([
    //   { route: ['', 'home'], name: 'home', moduleId: './sections/home/home', nav: true, title: 'Home' },
    //   { route: 'about', name: 'about', moduleId: './sections/about/about', nav: true, title: 'About' },
    //   { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
    //   { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }
    // ]);

    config.map([
     
      { route: '', name: 'public-section', moduleId: './sections/public/public-section', nav: true, title: ''},
      { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
      { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }

    ]);


    this.router = router;
  }

  navigationComplete(){
    Waves.displayEffect();
  }
}

```

Your suggestion is highly valued

**Comment by smithaitufe** [comment]
@eisenbergeffect
Thanks a lot but I tried it and it didn't work. 
Look at the app.js configureRouter
```
import { inject } from 'aurelia-framework';
import { EventAggregator } from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class App {
  constructor(events){
    events.subscribe('router:navigation:complete', this.navigationComplete);
  }
  configureRouter(config, router) {
    config.title = 'Delta State Polytechnic';
    config.map([   
      { route: '', name: 'public-section', moduleId: './sections/public/public-section', nav: true, title: ''},
      { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
      { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students', layoutView: 'sections/students/students-layout.html' }

    ]);


    this.router = router;
  }

  navigationComplete(){
    Waves.displayEffect();
  }
}
```
and look at the public-section.jjs configureRouter. This is not working for me

```
import { inject, inlineView } from 'aurelia-framework';
import { Router } from 'aurelia-router';

@inlineView(
    `
    <template>
        <router-view></router-view>
    </template>
    `
)
@inject(Router)
export class PublicSection {
    constructor(router){
        this.router = router;
    }
    configureRouter(config, router) {
        config.map([
            { route: '', redirect: 'home'},
            // { route: '', name: 'home', moduleId: './sections/home/home', nav: false, title: 'Home'},
            { route: 'home', name: 'home', moduleId: './sections/home/home', nav: false, title: 'Home'},
            { route: 'about', name: 'about', moduleId: './sections/about/about', nav: false, title: 'About'}
        ]);
        this.router = router;
    }
}

```

Your suggestion is highly valued

**Comment by EisenbergEffect** [comment]
You need the parent route to redirect, not the child route.

**Comment by smithaitufe** [comment]
app.js

```
config.map([
      { route: '', redirect: 'public-section', nav: false},
      { route: '/', name: 'public-section', moduleId: './sections/public/public-section', nav: false, title: ''},
      { route: 'login', name: 'login', moduleId: './sections/login/login', nav: true, title: 'Login Page' },
      { route: 'students', name: 'students-section', moduleId: './sections/students/students-section', nav: true, title: 'Students' }

    ]);
```
public-section.js
```
configureRouter(config, router) {
        config.map([            
            { route: '', name: 'home', moduleId: './sections/home/home', nav: false, title: 'Home'},            
            { route: 'about', name: 'about', moduleId: './sections/about/about', nav: false, title: 'About'}
        ]);
        this.router = router;
    }
```

It loads the home page. But when I attempted to go about page, It is showing the below error

![image](https://cloud.githubusercontent.com/assets/12886859/19521323/17f6dfce-960b-11e6-9ff3-c68d96672adb.png)

**Comment by EisenbergEffect** [comment]
You still effectively, have an empty route because you have '/' as a route. Change that to 'public-section'.

**Comment by alvarezmario** [comment]
This is a recurring issue, perhaps we should have a working example on the
docs?

**Comment by smithaitufe** [comment]
@eisenbergeffect

Of course that will cause the url to look like this http://localhost:8008/#/public-section/about. It doesn't look nice at all.
I will try another approach.

**Comment by williamokano** [comment]
+1

Em qua, 19 de out de 2016 12:06, Samuel Smith <notifications@github.com>
escreveu:

**Comment by EisenbergEffect** [comment]
Yes, it is a workaround. It's not perfect but it will work.

**Comment by smithaitufe** [comment]
@EisenbergEffect @bryanrsmith I was hoping the last update will include a solution to this issue. Please what is the state now? I wish I know how to help in this regard. If I can be exposed once, I will contribute greatly to this amazing framework.

**Comment by EisenbergEffect** [comment]
Just start reading the router code and then start thinking about how this might be implemented.

**Comment by smithaitufe** [comment]
@EisenbergEffect 
Thanks a lot. I have cloned the router repo. I will look through. I wish there is a flowchart of the router. It will help a lot in contributing. Because one can easily know the entry point and how the other codes are connected. I will try though

**Comment by thomas-darling** [comment]
@EisenbergEffect @PWKad 
We're still having problems on `aurelia-router` version 1.3.0.

Basically, if we have a root router with an empty route, pointing to a child router with the route `/foo`, we cannot navigate to `/foo` - it just throws a `Route not found` error.

This appears to be the same issue described by @smithaitufe in https://github.com/aurelia/router/pull/470#issuecomment-287543082 on the pull request.
This is pretty critical for us, and having poked around in the router code, I have to say, I'm a bit lost as to where this is failing... is there any chance you could take a look and maybe prioritize a fix for this?

**Comment by EisenbergEffect** [comment]
Have you tried using a redirect route?

**Comment by thomas-darling** [comment]
Yeah, we can't do that, unfortunately - the thing is, we have multiple front pages, one for each of our products. Until now, they were each on their own path, so we had `/flights`, `/hotels`, etc.

But now we have a requirement that the "primary" front page, `/flights` must be on an empty route, but we can't really start changing the way things are nested at this point.

I suppose, upon further investigation, that we could maybe get around this by having two routes pointing to the same module id - but then I'm a little bit in doubt about how that would affect the lifecycles of the views, especially with named router views. Meaning, if we have two separate routes, one empty and one for `/flights`, both pointing to the same module id - then what happens when a user navigates from the flights home page, i.e. the empty route, to a flights sub page such as `/flights/search`? Wouldn't this cause the `flights` view to be destroyed and recreated?
