### ISSUE TITLE
Can't navigate directly to route when pushState is true

### ISSUE THREAD

**Issue by lzonjic** [aurelia/router#270]
If pushState=true then when navigate to Welcome via menu (mouse click on nav-bar) everything is ok, but when I try to reach http://localhost:3000/welcome I'm getting error in browser `Cannot GET /welcome`.

This is my config:
```
  configureRouter(config: RouterConfiguration, router: Router) {
    config.title = 'Aurelia Test';
    config.options.pushState = true;
    config.map([
      { route: ['', 'welcome'], name: 'welcome', moduleId: './welcome', nav: true, title: 'Welcome' },
      { route: 'subjects', name: 'subjects', moduleId: './subjects/subjects', nav: true, title: 'Subjects' }
    ]);

    this.router = router;
  }
```

**Comment by EisenbergEffect** [comment]
It sounds like you may not have configured your server. When you have push state on, you will need to ensure that your server sends back the same SPA page for all the client-side routes. Usually the server framework has a way to do this with a wildcard route pattern...just make sure you don't configure it so it can't return the SPA page's static assets or so your API calls don't work.

**Comment by lzonjic** [comment]
That's it. Thank you!

**Comment by stuartbloom** [comment]
@EisenbergEffect sorry if this is a very late question about the same thing; I have an application that has the following router config
```
    config.options.pushState = true;
    config.options.root = "/";
    config.options.hashChange = false;
```
Running the application works great, but after deploying it to IIS I run into issues when manually entering a url, or hitting F5 to refresh the page; they both result in a 404 error.

You mention configuring the server; could you be a bit more specific?

Thanks

**Comment by stuartbloom** [comment]
Figured it out.  need to install the iis url rewrite extension and include the appropriate rules.

Hope I didn't waste any ones time
