### ISSUE TITLE
What is right way to configure routes implemented in separate module? 

### ISSUE THREAD

**Issue by shabalin** [aurelia/router#274]
We are splitting our frontend app into modules or features/plugins(in terms of aurelia).
Basically we want "module/feature" be an independent set of view-models, components and services that could be plugged in to main application. 
Example:
```
plugin A:
   components:
    ....
   services:
        user-api.js
   vm
        users.js
        users.html
        user-edit.js
        user-edit.html    
```    
in the configure function of the plugin we add list of routes provided by the module to the main app:

```
        aurelia.use.plugin('user-management', (config) => {
            // this thing just add plugin routes to the registry
            routesFactory.registerModuleRoutes(config.routes);
        });
```

the issue we run into is how to specify **moduleId** for modules located in plugins?
I we specify `moduleId: "./vm/users"` router attempts load a file from apppath/vm/users.js which obviously does not exist. How to tell loader to load from jspm_packages instead?

**Comment by EisenbergEffect** [comment]
Please ask questions in our public gitter channel. gitter.im/aurelia/discuss

**Comment by shabalin** [comment]
Just in case someone will have a same question, the answer is pretty simple - just prefix module path with jspm dependency name, e.g.
`moduleId: "user-management/vm/users.js"`

where 
- `user-management`  is a module name
- `vm/users.js` path to view model within a module 

Basically  there is RouteLoader implementation that constructs viewModel name

```javascript

//TemplatingRouteLoader.loadRoute (in templating-routing)

relativeToFile(config.moduleId, Origin.get(router.container.viewModel.constructor).moduleId)
```
`relativeToFile` resolves moduleId relatively viewModel that router belongs to.

so in case router is configured in `dist/app.js` and moduleId starts with "." (dot)  viewModel will be `dist/moduleId`.

then
CompositionEngine.ensureViewModel get called and actuall loading is happening in loadModule (aurelia-loader-default) where System.normalize resolve moduleId into the module path
```
      var newId = System.normalizeSync(id);
      var existing = this.moduleRegistry[newId];
```
