### ISSUE TITLE
Allow empty routes

### ISSUE THREAD

**Issue by jebbench** [aurelia/router#276]
### Use case
I have a `<router-view>` element in my search results page (`/search/:searchTerm`) which I don't want to populate until the user has selected a search result - currently I achieve this with a "blank" module which is simply a module with no content.
Once the user has selected a item (`/search/:searchTerm/item/:itemKey`) the `<router-view>` loads the `ItemDetails` module which displays the item.

#### Search Results Module
```
configureRouter(config, router){
        config.map([
            {
                route:      ['/search/:searchTerm'],
                name:       'search-no-item',
                moduleId:   'blank',
                nav:        false,
                title:      'Search Results'
            }, {
                route:      ['/search/:searchTerm/item/:key'],
                name:       'search-item',
                moduleId:   'item-details',
                nav:        false,
                title:      'Search Results'
            }
        ]);
        this.router = router;
    }
```
#### Item Details Module
```
configureRouter(config, router){
        config.map([
            {
                route:      [''],
                name:       'item-general',
                moduleId:   'item-general',
                nav:        false,
                title:      'View Item'
            },{
                route:      ['settings'],
                name:       'item-settings',
                moduleId:   'item-settings',
                nav:        false,
                title:      'View Item Settings'
            },{
                route:      ['edit'],
                name:       'item-edit',
                moduleId:   'item-edit',
                nav:        false,
                title:      'Edit Item'
            }
        ]);
        this.router = router;
    }
```

I'm having to load a blank module simply so Aurelia has something to drop into the `<router-view>` element.

**Comment by jdanyow** [comment]
Seems like an edge case- deferring to @bryanrsmith of course

Here's a few lines of code you can add to your `main.js` to create the `blank` module and it's view:

```js
import {InlineViewStrategy} from 'aurelia-framework';

System.set('blank', System.newModule({
  Blank: function Blank() {
    this.getViewStrategy = () => new InlineViewStrategy(`<template></template>`);
  }
}));
```

http://plnkr.co/edit/E9xeIIto3QBO12tO9cmB?p=preview

**Comment by bryanrsmith** [comment]
I agree with @jdanyow. I don't think it makes sense for the router to support this. One thing I would like to support in the future is directly providing the view model class instead of a module ID, which could simplify this case a little.
