### ISSUE TITLE
Invalid parameters 

### ISSUE THREAD

**Issue by iicaisin1** [aurelia/router#277]
on activate() passed in parameters are invalid. Please note that two equal signs are removed:

querystring:

*"code=CfDJ8EhAU4TRx49JlmV2229anSM8B2SLsaftgPZAImouLHtusGF2NGEWIbSyanN6evXArBgn/+eTdv+ErHDqQxaj0sFR4HnJmN56P3E9B2TUs3yXzS6fIYR5Pu3BORiKVCNrURuwIppKChaQMuDCkzlyDUO91HRZEXMa7XxSUao+lpPg8GYvit6/31u4SRWhCTvfQARV9iCuEWMJ+lSjp7QA0WSpG1MFr/zmN6tXqnmThOa7IG+8rupHnE8itS7M75dFbg==&username=TEST"*

params:

*code:"CfDJ8EhAU4TRx49JlmV2229anSM8B2SLsaftgPZAImouLHtusGF2NGEWIbSyanN6evXArBgn/+eTdv+ErHDqQxaj0sFR4HnJmN56P3E9B2TUs3yXzS6fIYR5Pu3BORiKVCNrURuwIppKChaQMuDCkzlyDUO91HRZEXMa7XxSUao+lpPg8GYvit6/31u4SRWhCTvfQARV9iCuEWMJ+lSjp7QA0WSpG1MFr/zmN6tXqnmThOa7IG+8rupHnE8itS7M75dFbg"
username: "TEST"*

**Comment by Mordred** [comment]
You have to escape URL valid characters. In your case .. replace `=` with `%3D` when generating your querystring.

**Comment by iicaisin1** [comment]
Of course! Thank you, i used the wrong encoding from .net
