### ISSUE TITLE
Parent's deactivate and activate is called on every child navigation.

### ISSUE THREAD

**Issue by pankajya** [aurelia/router#278]
Hi,

Recently we updated one of our applications from 2.0.1 to 2.1.0 and we're seeing some very different behavior with a child and grand child router. when we navigate between child routes in same parent, the parent's deactivate, activate then finally child's activate is getting called.

Same if i am navigating between child and grand child then first deactivate and activate of main parent is called then deactivate and activate of child page is called after all these things grand child's actual activate is called.

I've tried looking through all of the documentation, the router code, and the activator code and I can't find anything relevant.

Here's the grand child router configuration:

**empDetails.js**

```
this.router = childRouter.createChildRouter()
  .makeRelative({
    moduleId: 'viewmodels/EmpFolder/emp/',
    route: 'emp/:id/'
  }).map([{
    route: ['details1', ''],
    moduleId: 'details1',
    title: 'details1',
    nav: true
  }, {
    route: 'details2',
    moduleId: 'details2',
    title: 'detail2',
    nav: true
  }]).buildNavigationModel();
```

Thanks in Advance...!!!!

**Comment by mbenedyk** [comment]
I have observed same behavior. In my opinion parent router "pipilene" shouldn`t be called if we are operating on it`s child routes

**Comment by mbenedyk** [comment]
consider setting activation stategy for route:
activationStrategy: "no-change"
