### ISSUE TITLE
Router generated URLs not honoring updated params

### ISSUE THREAD

**Issue by jsobell** [aurelia/router#279]
If a child route tries to generate an href for a parent route and a param is specified, that generate() incorrectly returns the unmodified URL.
This is reflected in the .navigate collections of the router too.
Including a parameter of any sort to .navigate() causes the URL to be generated correctly, suggesting there is a caching of the calculated route that should presumably not apply if there is a parameter in the route.
For example:
A parent router contains a route of `account/:accountid` named `main`
A child router contains a route of `home` named `child`
If a VM from the child requests router.generate("main") it will *always* give back the same URL, regardless of whether accountid has changed
However, if a VM from the child requests router.generate("main", { x: 1}) the new value of accountid is used (although a superfluous &x=1 is obviously added), presumably because it's reevaluated.

**Comment by jsobell** [comment]
Possibly a duplicate of #246 ?

**Comment by jsobell** [comment]
Actually (I think) caused by https://github.com/aurelia/route-recognizer/issues/11

**Comment by bryanrsmith** [comment]
Yes, this is aurelia/route-recognizer#11. Closing this one for now.
