### ISSUE TITLE
Add `redirect` support to the router

### ISSUE THREAD

**Issue by Alxandr** [aurelia/router#28]
Allow the router to recognize `redirect` keys in routes, and perform the redirect action.

Example:

```js
config.map([
  { route: 'blog',      moduleId: './blog/routes/index', nav: true, title: 'Blog' },
  { route: '',          redirect: '/blog' }
]);
```

This would make the empty route `''` actually redirect to `#/blog` (with path changes). This could be added quite early to the router pipeline, to reduce the overhead of having to go through the entire pipeline.

**Comment by EisenbergEffect** [comment]
Added in master. Going out in next release.

**Comment by nathanchase** [comment]
How would one utilize this for more complex URL rewriting purposes from within the Aurelia router? ala regex pattern matching, or other common redirections?
