### ISSUE TITLE
Route-appending for global modules

### ISSUE THREAD

**Issue by larsfjerm** [aurelia/router#281]
Consider a sidebar that can slide in/out with a module containing account-profile data.

Would it be possible to tell the router to append a global route `/account` to the current URL and state of the application? So when the the URL equals `/home/account` the state of the sidebar is set to active. 

This should also apply for other routes that inherits from the account route and all child routes. Routes like `/home/second/account` and `/info/account` should activate the sidebar.

**Comment by EisenbergEffect** [comment]
The best way to handle this is to make the sidebar work independent of routing. Simply have the sidebar subscribe to a message on the event aggregator. Whenever a screen needs to show the sidebar with some data, it simply publishes the message.
