### ISSUE TITLE
Better navigation failure logging

### ISSUE THREAD

**Issue by cehoffman** [aurelia/router#282]
Right now on a failed navigation the logic will reach [this logging statement](https://github.com/aurelia/router/blob/9f48f6bedbab867f9865c2bd6d41d84323efa8e9/src/app-router.js#L187) which for the current errors I'm seeing say `[app-router] Error: Error invoking SetupWelcome. Check the inner error for details` The inner error referenced here I don't know of a good way of getting a handle on in order to inspect the stack.

Is there some process I'm missing to get this or is there some extra logging parameters that could be added to this call to put the error in the console, e.g. `result.output.innerError.stack`.

**Comment by EisenbergEffect** [comment]
Can you not see it in the console? You might need to expand the ... It will depend on the browser.

**Comment by bryanrsmith** [comment]
Closing for now. @cehoffman Please follow up if we've missed something.
