### ISSUE TITLE
System tries to load template with no name when routing

### ISSUE THREAD

**Issue by netaisllc** [aurelia/router#284]
The following error message results when my app routes between two views.  

`Unhandled rejection Error: XHR error (404 Not Found) loading http://104.236.190.18:8080/dist/matrix/.html`

It's odd because it looks like a process is trying to load an unnamed module(?) And further, the routing action succeeds.

This just cropped up in an app I've been working on for a little while now so I suspect I broke a special setting somewhere.  Can anyone provide clues as to where I can investigate this further?

**Comment by netaisllc** [comment]
This is not an issue; the problem resulted from 'cockpit error'.

The view template contained a `compose` instruction to another template that had no view model of its own. Removing that instruction resolved this error.

**Comment by EisenbergEffect** [comment]
Well...I have to say...I'm relieved. I had no idea what would cause that ;)

**Comment by bryanrsmith** [comment]
@EisenbergEffect Is there a good place to detect this error and log a helpful message instead of actually making the request for the empty module name?

**Comment by EisenbergEffect** [comment]
I'm not sure. If I could have a repro we could probably do something about it though.

**Comment by netaisllc** [comment]
@EisenbergEffect Yeah, _same here_. Total brain-fade on my part!!
I will try to repro in a micro project, but no promises :)
