### ISSUE TITLE
Declare RouteConfig.navModel for TypeScript projects

### ISSUE THREAD

**Issue by heruan** [aurelia/router#285]
I'm porting my projects to TypeScript, and I was used to dynamically set the page title in the `activate` function:
```javascript
activate(params, routeConfig, navigationInstruction) {
    routeConfig.navModel.setTitle("My Title");
    // This is simplified, the title will be set after retrieving server side info
}
```
but using TypeScript I've found the `RouteConfig.navModel` property isn't declared and the compiler complains:
```
Property 'navModel' does not exist on type 'RouteConfig'.
```

**Comment by jedd-ahyoung** [comment]
@heruan Thank you for the contribution. I can verify that the property exists in the ES2016 skeleton. The Typescript definition files are generated from the codebase itself, so feel free to submit a pull request with the necessary file changes for this fix.

@EisenbergEffect This may need the bug tag.
