### ISSUE TITLE
Tests are broken in 1.0.0-beta.1.1.0 release

### ISSUE THREAD

**Issue by wichert** [aurelia/router#288]
Ever since @EisenbergEffect commited b473fec the tests have been failing. I was looking at trying to modify the router so we can solve aurelia/i18n#23, and it would be nice to be able to start from a clean build where the tests all pass.

**Comment by wichert** [comment]
It looks like karma can not load peer dependencies, only direct dependencies.

**Comment by bryanrsmith** [comment]
Tests have since been fixed.
