### ISSUE TITLE
Missing baseUrl when entering application at child route

### ISSUE THREAD

**Issue by cehoffman** [aurelia/router#290]
I have a child router that comprises the steps for a wizard. When I enter the application from the default route of the parent router the canActivate callbacks in the wizard child routes all have baseUrl set correctly to the containing parent route.

If the user reloads a page here I want to redirect them to the first step of the child router and I'd like to make this not depend on the name of the route the wizard is attached to on the parent router.

Looking at the router on the navigationInstruction supplied in the canActivate callback of the child route models I saw that baseUrl was set correctly and any redirects within the wizard steps worked by only knowing sibling route names. There was no dependency on knowing the parent route. This is great and what I expect, but now for what doesn't work.

In the page reload situation the baseUrl on the router is an empty string which causes any redirects based on child route names to try and resolve using the parent router. I investigated the arguments to configureRouter for the child router and saw that the 4th argument had a route property that I could reconstruct the baseUrl from. I'm getting around the problem with `this.router = route.replace('*childRoute', '')`, but I'd like to not rely on something that seems to have a better option.

So is the missing baseUrl a bug or is there another way I should be looking to use router?

**Comment by bryanrsmith** [comment]
Sounds like #113. The base URL isn't set until the navigation is committed, so it can't be used correctly during activation. We need to figure out a good way to set or expose the base URL for the instruction being processed.
