### ISSUE TITLE
Navigation Pipeline as normal middleware pipeline rather than specific hooks

### ISSUE THREAD

**Issue by no1melman** [aurelia/router#295]
So I've just used the `config.addPipelineStep('authorize', AuthRouterPipelineStep);` in the `configureRouter` function.

I initially tried to do:

```config.addPipelineStep('authorise', AuthRouterPipelineStep);```

That didn't work, and it was until I changed the name to `authorize` till it worked. This seem very unintuative to me. I was informed there are different hooks in the navigation pipeline, and that `authorize` was a specific hook.

I don't fully understand these hooks. It would seem better to me that you have a normal middleware pipeline. Named, or unnamed. 

I come from a C# background using WebApi and ASPNET core where the middleware have an injectable constructor and injectable invoke function. The Aurelia pipeline steps follow the same pattern. They seem to slot in in exactly the same way. This is probably what led to my confusion because they don't actually work in the same way at all. 

Now I do see the point in the hooks, but the current way seems weird to me.

It would seem to me that it would be better to do something like this:

```
config.insertIntoAuthoriseStep(AuthRouterPipelineStep)
config.insertIntoModelBindStep(SomeBindPipelineStep)
```

Here it's clear at what stage you want to hook into, and a little bit of documentation saying that you can have multiple middleware inserted into each step makes so much more sense to me.

I don't know if this is way out from what you guys were planning with this, or if I'm way off the mark here.

But either way, the fact that there are these "magic' strings defining navigation hooks is not ideal.

**Comment by EisenbergEffect** [comment]
This seems very reasonable to me. We need to make sure we've got the pipeline nailed down and then we can add a nicer API on top of that. @jedd-ahyoung Since you were discussing this with @no1melman on gitter, would you be interested in doing a bit of work on this?

**Comment by CasiOo** [comment]
+1 confused me as well. I too tried to add my own step instead of 'authorize'.

**Comment by lor3** [comment]
+1 did the same thing (custom step name).

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect Sure. I'll try to take a look at this next week. For what it's worth, when I first worked with pipeline steps, I made the same mistake.
