### ISSUE TITLE
Wildcard routes not working?

### ISSUE THREAD

**Issue by Souldrinker** [aurelia/router#297]
I'm trying out to switch my login logic to an external identity server to whom I pass in a redirect url back to my application which means I get a call like ```http://localhost:4703/#id_token=atoken&scope=openid%20profile&state=somestate&session_state=somesessionstate```.

In this case I wanted to catch it with a wild card route like ```{ route: "id_token*token", moduleId: "views/login/oauth-check/oauth-check", nav: false, title: "Validation" }```
...in which I expected to get in the rest of the url after ```id_token=``` passed in as <param>.token to my activate method in the oauth-check class from which I could strip out my token and use it for further calls to my web api. But no matter what I try I only get route not found errors.

The workaround I did for now is to configure mapUnknownRoutes  in which I check the fragment for id_token and in that case returns my module id. In that way I get the whole path as a property on the indata parameter in my activate method which is fine for me. But shouldn't wildcard routes have worked like I described above?

**Comment by bryanrsmith** [comment]
Wildcard segments can be used to match the "rest" of the path, but they only work with complete segments. I.e., `foo/*path` would match `/foo/bar/baz`, with the `path` parameter holding `'bar/baz'`. partial segment matchign with wildcards, like `foo/bar*path`, is currently not supported.

Also note that routing only inspects the path portion, not the query string. The URL in your example looks like it's storing a query string in the hash (though the `?` is missing).  Are you able to change the URL structure and use something like `/auth?id_token=atoken&scope=...`, and then match the route on `auth`? If not, then your `mapUnknownRoutes` solution may be the best option.

**Comment by Souldrinker** [comment]
Ok, thanks for the quick response. Then I'll stick with my mapUnknownRoutes that works fine with a few lines of code.

The reason I asked was that I had Google authentication working in one of my old Durandal projects with the following setup and thought it worked the same in Aurelia:
```
import router = require("plugins/router");

class Shell {
    activate(): any {
        var routes = new Array<DurandalRouteConfiguration>();
        routes.push({ route: "", moduleId: "viewmodels/login", nav:false });
        routes.push({ route: "login", moduleId: "viewmodels/login", nav: false });
        routes.push({
            route: "selfRegistration(/:email/:firstName/:lastName)",
            moduleId: "viewmodels/SelfRegistration/SelfRegistration", nav: false
        });
        routes.push({ route: "access_token=*token", moduleId: "viewmodels/OauthCheck/OauthCheck", title: "Validation", nav: false });
        router.map(routes).buildNavigationModel();
        return router.activate();
    }
}

export = Shell;
```
