### ISSUE TITLE
Trigger rebind on router.navigation to reflect effect of value converter for auth

### ISSUE THREAD

**Issue by Jaans** [aurelia/router#298]
We use a custom value converter `authFilter` to update the visible navigation items when a user logs in with different roles which gives access to different areas in the site. This works beautifully, and Aurelia allows this to be clean and elegant. 
(PS: Yes we enforce security server side first and foremost).

```
<li repeat.for="row of router.navigation | authFilter" class="${row.isActive ? 'active' : ''}">
  <a data-toggle="collapse" data-target="#navigation-navbar-collapse.in" href.bind="row.href">${row.title}</a>
</li>
```

With the event aggregator we receive notification of an authentication event (e.g. log in, log out, etc), and at some point we know that the navigation menu could be different based on the change in authentication state.

The problem is that we aren't actually changing the router's navigation model data, it's just the `authfilter` value converter that will include / exclude different navigation items due to the change in authentication state. Therein lies the rub, the binding doesn't refresh and re-apply the value converter, because it doesn't need to (in that the model data is still the same as before). This makes sense behaviourally and is consistent with expectation.

There doesn't seem to be anything on the AppRouter instance API that allows us to do "signal a property / value change" for the binding to respond to. (We've tried the refreshNavigation, and other bits, against the guidance from the docs). Our workaround for this is the following hack to trigger it:

```
// Refresh the navigation if we have an authentication event to make the navbar reflect the correct information and retrigger the authFilter
this.router.navigation = this.router.navigation.reverse().reverse(); // HACK: This is a crude way to force a refresh of the authFilter
```

So that works just fine by us, but I suspect that our use case isn't all that unique or uncommon. 

Unless there is a better solution that we are not aware of, this issue is to request to have an enhancement added to the AppRouter to allow for this efficiently and purposefully.

Thanks to everyone for all the hard work - Aurelia is brilliant and we're not even Beta 2 yet!

**Comment by EisenbergEffect** [comment]
There's a couple of ways you could solve this:

* You can keep things as they are and use a `signal` binding behavior to signal the specific bindings to update. You can read about that in the docs here: http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.1.3/doc/article/binding-binding-behaviors/5
* Or, you could add a `settings` property to your route config items and include a property on that which was intended to be used to indicate visibility of an item. Your auth mechanism could just toggle those values and your binding could simply bind visibility based on the state.

**Comment by Jaans** [comment]
Thanks Rob, I'll look at the `settings` property approach and "invert" the design. 

I forgot to mention (proably key), that our routes include a `Role` property which the `authFilter` inspects. Hmm... that gives me some ideas. Thanks again.

**Comment by Jaans** [comment]
Then again, the `BindingSignaler` is a shoe-in for this. Thanks for the reminder of that - it would be very useful elsewhere too.

Damn, it just gets better and better. I really like what you guys have done with Aurelia!!!

**Comment by adriatic** [comment]
The link to the `signal` binding behavior referenced **[above](https://github.com/aurelia/router/issues/298#issuecomment-190030640)** is http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-binding-behaviors/5

**Comment by datvm** [comment]
The link is now: https://aurelia.io/docs/binding/binding-behaviors#signal
