### ISSUE TITLE
Should RouterConfiguration be a transient?

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/router#299]
```javascript
import {AppRouter, RouterConfiguration} from "aurelia-router";

export function configure(config) {
  const router = config.container.get(AppRouter);
  const routerConfig = config.container.get(RouterConfiguration);
  routerConfig
    .map([{
      route: "test",
      moduleId: "features/test/test",
      name: "test",
      nav: true,
      title: "test"
    }])
    .exportToRouter(router);
}
```
If you have multiple plugins/features doing this it will add up the same route multiple times. Sure you can do
```javascript
const routerConfig = new RouterConfiguration();
```
but it would make more sense to have it marked as transient.

**Comment by EisenbergEffect** [comment]
This is an interesting usage of the APi...I can see how that would be handy for plugins that want to configure routes. However, is there any reason you don't just instantiate the RouterConfiguration with its constructor?

**Comment by stoffeastrom** [comment]
Not really. I stumbled on this after a copy paste :). It can be a bit confusing but as long as it's well documented I don't see a problem with it.
