### ISSUE TITLE
specify Viewmodel at runtime

### ISSUE THREAD

**Issue by zewa666** [aurelia/router#3]
It would be great if we could decide at runtime which moduleId to load, based on whatever condition is provided. The current route entry looks like this where you have to provide the moduleId as a string during configuration phase.

`````
{ route: ['','welcome'],  moduleId: 'welcome',      nav: true, title:'Welcome' },
````

Lets say though the welcome screen shows a dashboard for all users (incl. anonymous), but as soon as you login you get a different screen.

So same route path but different model implementation, as of separation of concerns. So in this case it would be helpful if the moduleId could accept a function.
As of the gitter discussion it was proposed to introduce another property, e.g. moduleStrategy, which if set would override the moduleId definition. so an example would be

````
{ route: ['','welcome'],  moduleStrategy: (options) => { 
  if(options.whatever) {
    return  "welcome";
  } else {
    return "welcome2";
  }
 }, nav: true, title:'Welcome' },
````

Perhaps even make moduleStrategy accept a Promise, which is resolved later on

**Comment by EisenbergEffect** [comment]
Would you need any inputs to that function?

**Comment by zewa666** [comment]
hmm maybe you're right maybe just add a object parameter (like activationData) passing all necessary information. Who knows what this could be used for.

**Comment by tyrsius** [comment]
the `currentInstruction` seems reasonable

**Comment by kristianmandrup** [comment]
Yes, we need this for sure :) Would be awesome to integrate this with net http-client using Fetch API :) to load modules over the wire asynchronously and thus enhance the app dynamically given some business rules/data, such as the user being logged in, upgraded to VIP member or navigating to specific part of the app etc.

**Comment by EisenbergEffect** [comment]
This is implemented in master and going out in the next release.
