### ISSUE TITLE
Hash '#' in URL path

### ISSUE THREAD

**Issue by bhaeussermann** [aurelia/router#303]
Hi,

In the getting started kit, the router adds a '#' in all URL paths (eg. `http://127.0.0.1:8080/#/users` ).  
Is there a way to get rid of the '#'?

**Comment by EisenbergEffect** [comment]
See the section on "Configuring Push State" here: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/cheat-sheet/7

**Comment by bhaeussermann** [comment]
Thanks! I will have a look.

**Comment by bhaeussermann** [comment]
So to my understanding all that I should do is add
```
config.options.pushState = true;
```
The '#' is gone now, but I don't understand what's going on. As far as I can tell this makes the browser use relative URL paths. But why was the '#' there in the first place? Is there an article somewhere that explains this?

Furthermore, this seems to break the routing a bit. Without `pushState`, I can go to the *users* page and refresh the page. However, with `pushState`, when I refresh on the *users* page, I get 404. Is there something else I need to change?

**Comment by jedd-ahyoung** [comment]
@bhaeussermann What you're seeing is part of the way that URIs are implemented in web browsers - it's not an Aurelia-specific thing. The hash symbol is part of the (fragment identifier)[https://en.wikipedia.org/wiki/Fragment_identifier]. It has a lot of uses, but it's used by single-page applications for history purposes, explained here: https://en.wikipedia.org/wiki/Single-page_application#Browser_history

Pushstate simply uses a different method of storing history in the browser that doesn't use the fragment identifier. You'll have to configure your server accordingly. There's a (StackOverflow question)[http://stackoverflow.com/q/17954888/677526] on the topic, and although it deals with Ruby on Rails, the principle is the same across all server types. Essentially, your server needs to serve your application page for all routes that the application itself could receive.

**Comment by bhaeussermann** [comment]
@jedd-ahyoung Thanks for the explanation! It seems that the approach with the fragment identifier (with `pushState = false`) is pretty standard among single-page apps anyway, so we should probably stick with that.  

What does bother me is that it seems Aurelia adds an unnecessary `/` after the #. As in `http://localhost:43804/#/users` instead of just `http://localhost:43804/#users`. The latter URL certainly looks much nicer to me.
