### ISSUE TITLE
router.navigation is not triggering computed gets

### ISSUE THREAD

**Issue by AStoker** [aurelia/router#304]
FYI, might be related to https://github.com/aurelia/router/issues/246

Repro repository: https://github.com/AStoker/AureliaBindingIssues

This repo was created to try and initially test out issues on a custom element that was receiving the `router.navigate` property, modifying it to group navs together, and then use them on the view. What is happening is that when the router is configured with elements inside a promise inside the `configureRouter` function, when any additional route is finally added to the router, even though `router.navigation` is updated, it doesn't trigger the update in anything else it's bound to in other views.

The situation in the repo. The nav-bar is bound to `router.navigation`, and inside nav-bar there is a get that is computed from that `router.navigation` variable (called `navigation` inside nav-bar). This works the first go around when the router is configured with the first 2 routes. But when the 3rd route is added later, the nav-bar doesn't recompute, even though `router.navigation` has been updated and has it's 3rd route.
I am expecting that when the `app.js` finishes it's `configureRouter` function's promise and the 3rd route is added, that the changes would be shown in the nav-bar as well.

This might belong in the binding repo's issue list, but I'm not entirely sure.

Strangely enough, this all worked a few weeks ago before Aurelia removed the dependency of `core-js`.

**Comment by EisenbergEffect** [comment]
If you suspect it's related to polyfills. Please do a `jspm update` to make sure you have the latest polyfills. There have been updates almost every day, including today.

**Comment by AStoker** [comment]
I did that today with no luck. I also tried bringing back core-JS  which seem to work two days ago, but today I had no luck with it either

**Comment by AStoker** [comment]
Doing some more research. If I do all of my route configs inside a promise and we return that promise in `configureRouter`, then everything works fine. This makes sense because the router isn't going to publish the navigation array until everything is finished.
Now if I am adding dynamic routes later (i.e. I config some base routes and then make an async request and add a route later), it's this case that the router navigation is not notifying getters that are computed off that property.

**Comment by AStoker** [comment]
Perhaps then as a simpler fix I need to find a different way to add routes dynamically?

**Comment by AStoker** [comment]
Another update, my initial issue seems to be related to the core-js promise library. There's still the issue of creating dynamic routes and those routes not being updated however. The repo has been updated and comments added to the `app.js` to document what needs to happen to see the case.

**Comment by AStoker** [comment]
Perhaps then as a simpler fix I need to find a different way to add routes dynamically?

**Comment by EisenbergEffect** [comment]
Have you tried calling router.refreshNavigation()?
