### ISSUE TITLE
Rounting issue in Safari In Windows

### ISSUE THREAD

**Issue by ne0guille** [aurelia/router#307]
Hey, i have a really browser specific issue using aurelia router, 

i have this anchor tag and the navigate method like this

> <a if.bind="col.template === 'link'" href="#" click.trigger="navigate(item[col.name].route)" 
navigate(param){
	    this.router.navigateToRoute(param.route, param.param);
	}

> > 

its working ok in all browsers but Safari running on Windows, working in IOS.
The routing is working ok, but the data is not been displayed, i tried ading an /#/ to the url on the browser  and then the data is displayed.

Do you know is this might be a know issue using the router like this in this very specific situation?
thanks,

**Comment by EisenbergEffect** [comment]
Safari on Windows is not supported. That is a dead browser and hasn't been updated in many years.

**Comment by ne0guille** [comment]
thanks you very much for ur reply we will doom this browser
