### ISSUE TITLE
Spelling mistake 'delcared'

### ISSUE THREAD

**Issue by vdangwal** [aurelia/router#308]
Not sure but i think there is a spelling mistake in below message from aurelia.

it says 'delcared' instead of 'declared'. 

ERROR [app-router] Error: Change handler selectedProvidersChanged was specified but not delcared on the class.
    at BindableProperty.createObserver

**Comment by bryanrsmith** [comment]
Issue moved to [aurelia/templating #291](https://github.com/aurelia/templating/issues/291) via [**ZenHub.io**](https://www.zenhub.io/)
