### ISSUE TITLE
URL encode results incorrect baseUrl of child router in Firefox

### ISSUE THREAD

**Issue by balazsmeszegeto** [aurelia/router#309]
I have a router in app.js and then a child router, which has route-parameters.
App router config:
`    config.map([
      { route: 'child-route',  name: 'child', moduleId: 'child-router' }
    ]);`

Child router config:
`	config.map([
      { route: 'my-route/p1/:param1/p2/:param2', name: 'my-route', moduleId: 'my-route' }
    ]);`

If `:param1` or `:param2` contains non-URL characters (which has to be URL-encoded), then navigation fails in Firefox. Example of such URL is:
`#/child-route/my-route/p1/foo bar/p2/foo bar baz` (non-URL character is _space_)

_Reason:_
Upon navigation, the baseUrl of the child-router gets recalculated (see `_refreshBaseUrl()`). The bug is in `getBaseUrl()` (navigation-instruction.js). In `getBaseUrl()`, the parent router's current instruction is checked and being "subtracted" from the fragment:
`return this.fragment.substr(0, this.fragment.lastIndexOf(path));`.

At this point, fragment is URL-encoded (`#/child-route/my-route/p1/foo%20bar/p2/foo%20bar%20baz`), while path (which comes from `params`) is not (`/my-route/p1/foo bar/p2/foo bar baz`). Therefore, `substr` will return `""`, which sets the baseUrl of the child router to `""` instead of `"/child-route/"`. Thus AppRouter will try to load `#/my-route/p1/foo bar/p2/foo bar baz` (instead of `#child-route/my-route/p1/foo bar/p2/foo bar baz`), which results in "Error: Route not found".

Tested in v1.0.0-beta.1 and v1.0.0-beta.1.1.3. All other browsers work fine, the issue is only in Firefox.

**Comment by EisenbergEffect** [comment]
@balazsmeszegeto Seems like you've got it figured out. Would you be interested in contributing by submitting a PR to fix the issue?

**Comment by balazsmeszegeto** [comment]
@EisenbergEffect I would be interested, but seems like you've already solved it (I was on vacation)
