### ISSUE TITLE
Add Arbitrary Meta To a Route

### ISSUE THREAD

**Issue by paullryan** [aurelia/router#31]
It would be great to be able to add and then access arbitrary meta such as a sub-title or icon reference without having to maintain a separate map (one that is likely to get out of sync).

**Comment by zewa666** [comment]
Hi there,

you can add any meta you wan't to the route mappings like here the `myMeta` property
``` javascript
config.map([
    { route: ['','welcome'],  moduleId: 'welcome',      nav: true, title:'Welcome', myMeta: 'HelloMeta' },
    { route: 'flickr',        moduleId: 'flickr',       nav: true },
    { route: 'child-router',  moduleId: 'child-router', nav: true, title:'Child Router' }
]);
```

and access it via the config object of the iterated route
```
<li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">
    <a href.bind="row.href">${row.title} (${row.config.myMeta})</a>
</li>
```

**Comment by EisenbergEffect** [comment]
There's a dedicated `settings` property you can set on a route config. This will be copied over to the nav model as well and is guaranteed not to conflict with future Aurelia apis.

**Comment by paullryan** [comment]
Thank you both. Might be worth documenting this feature.
