### ISSUE TITLE
eventAggregator subscribe 2x router:navigation:complete

### ISSUE THREAD

**Issue by flieks** [aurelia/router#310]
Hi,

How can i subscribe in 2 different places to an event from the router ?
The second subscription is overriding the first one now..
so the first one is never called

Greetings
Felix

**Comment by jedd-ahyoung** [comment]
@flieks Can you create a test case for this, using the router navigation event and a separate event? This may be an issue with the event aggregator.

**Comment by jedd-ahyoung** [comment]
Issue moved to [aurelia/event-aggregator #20](https://github.com/aurelia/event-aggregator/issues/20) via [**ZenHub.io**](https://www.zenhub.io/)
