### ISSUE TITLE
Bug: The Bind method is not called if the navigate to same page but different URL parameter

### ISSUE THREAD

**Issue by ppn2** [aurelia/router#311]
If you navigate from a page to same page with different parameter (e.g. from #/user/1 to #/user/2), the bind method is not called for main component or any of the child component. So that means if a user is navigating to #/user/2 from #/users it takes a different execution path versus if the user were to navigate to #/user/2 to #/user/1.

Please see the example on [plunker](http://plnkr.co/edit/WPNtHB?p=preview)

When you run this example, browser to users page. click on "View Aurelia", which will navigate to #/user/aurelia and the bind method in the user.js will be fired. From there click on "View Abc", which will navigate to #/user/abc and the bind method in the user.js will not be triggered.

**Comment by EisenbergEffect** [comment]
By default the router tries to preserve the UI if only the parameters changed, by simply calling activate again with the new values. If you want to completely re-instantiate the component, you can implement a method called `determineActivationStrategy` and return `activationStrategy.replace`. You can read more in the cheat sheet under the router section here: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/cheat-sheet/7

**Comment by ppn2** [comment]
thanks @EisenbergEffect. it does resolve the issue.
