### ISSUE TITLE
Navigation fails when refreshing or press enter on the url.

### ISSUE THREAD

**Issue by ne0guille** [aurelia/router#316]
Hello, im having issues in our DEV or QA enviroments when refreshing a page after a navigation.
In these enviroments i can see that we dont have the # in the url as i have in my local enviroment, and if i add the # manually it works ok.

examples: `http://localhost/url/#/general/1038` work ok if i hit enter or refresh.
              `http://DEV/general/1076` fails after hitting enter on the url or refreshing the page.

on fiddler i can see that is looking for the vendor but not on the app root.
`http://dev/general/app/vendor.js`

the correct url would be: `http://root/app/vendor.js`

Is this a know issue ? is there a fix for this? Thanks!

**Comment by EisenbergEffect** [comment]
Have you set a base element in your html?

**Comment by EisenbergEffect** [comment]
Take a look at the cheat sheet, in the router section: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/cheat-sheet/7  Scroll down to the part titled "Configuring Push State". Make sure you've set everything up as described there. Also, make sure your server is configured properly for push state scenarios.

**Comment by ne0guille** [comment]
i made the configurations and set the base with a url. so now to make it work i have to add this url to the router, but i dont think its the right thing, what should i change to make it work without this url on the router config.

> 

	config.map([
		  { nav: true,	route: ['','cases'],		name: 'home',			moduleId: 'case/list',			    title: 'Cases',			settings: { auth: true, role: '' } },
		  {				route: 'cases/:id',			name: 'case',			moduleId: 'case/detail',			title: 'Case Detail',	settings: { auth: true } },
          {				route: 'URL/general/:id',

>

**Comment by ne0guille** [comment]
added config.options.root and its works now. thanks
