### ISSUE TITLE
Autorize Pipeline Step

### ISSUE THREAD

**Issue by hmarcelodn** [aurelia/router#317]
I am using the authorize pipeline step posted in the Aurelia.io site in order to redirect unauthorized users to login page.

I can see how the unathorized users access certain route which needs authotization and they are being redirected to login page. 

The problem is that Aurelia is activating viewmodels even if you are not authorized and the pipeline rdirects you back to login page. Its running all my AJAX requests inside the view model.

How can I avoid such behaviour? Is that a limitation?

Thanks.

**Comment by jedd-ahyoung** [comment]
@hmarcelodn This behavior shouldn't happen. To verify, are you returning the redirect action as the return value of your pipeline? If not, the behavior you're describing could be possible. You'll need to make sure that your pipeline returns either a Promise or a navigation instruction.

Can you post your pipeline code, and can you provide a plunkr or a gist.run showing the issue?

**Comment by EisenbergEffect** [comment]
Closing this since there was no response in three weeks and the source code of the pipeline provider seems to indicate this should not happen if the step is implemented correctly.
