### ISSUE TITLE
navigateToRoute doas not reload same page

### ISSUE THREAD

**Issue by denimaaark** [aurelia/router#318]
I have problem with navigateToRoute.
I am trying to reload current page localhost:9000/#/contacts with

this.router.navigateToRoute('contacts', { groupId: 25 }, { replace: true})
but it is not working. 

It is wotking only if i call another route like "users", but not from same.

Url is changed to localhost:9000/#/contacts?groupId=25 but it is not reloading current page, no network activity.

Please how to do reload current page with additional parameters, thanks

**Comment by jedd-ahyoung** [comment]
@denimaaark See https://github.com/aurelia/router/issues/255 - this can be controlled by changing the activation strategy.
