### ISSUE TITLE
Router ignore <base/> tag when use pushState = true

### ISSUE THREAD

**Issue by tolemac** [aurelia/router#321]
Router ignore `<base/>` tag when `pushState = true` I have to add:

```javascript
   config.options.root = document.getElementsByTagName('base')[0].href.replace(location.protocol + "//" + location.host, "");
```

To get work it.

The documentation says nothing about it.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you include this in the router docs you are working on?

**Comment by stephenlautier** [comment]
Unless this is something which was changed, I don't have to do this in order to get it working. However the base has to be as:

```html
<base href="/" />
```

**Comment by tolemac** [comment]
I have: 

    <base href="/au/">

But doesn't work if I don't set `options.root`.

**Comment by EisenbergEffect** [comment]
@tolemac To clarify, are you saying that if you set a `base` tag you expect the options.root to be set automatically from that?

**Comment by tolemac** [comment]
The documentation (http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/7 section `Configuring PushState`) says you have to add a `base tag` and configure the router this way:
````
export class App {
  configureRouter(config) {
    config.title = 'Aurelia';
    config.options.pushState = true;
    config.map([
      { route: ['welcome'],    name: 'welcome',     moduleId: 'welcome',      nav: true, title:'Welcome' },
      { route: 'flickr',       name: 'flickr',      moduleId: 'flickr',       nav: true, auth: true },
      { route: 'child-router', name: 'childRouter', moduleId: 'child-router', nav: true, title:'Child Router' },
      { route: '',             redirect: 'welcome' }
    ]);
  }
}
````

Setting `options.pushState` to `true`, it says nothing about `options.root`.
Then I had understood that it should be enough, therefore Yes, I expect the options.root to be set automatically.

The framework is ignoring `base` tag or the docs are wrong ... IMHO ;)

**Comment by EisenbergEffect** [comment]
Updated the docs concerning this setting. It will go out in the next docs update release this week.
