### ISSUE TITLE
Customizing the Navigation Pipeline

### ISSUE THREAD

**Issue by ppn2** [aurelia/router#324]
Using the example in the cheat sheet, I customized the router pipeline. It works as expected normally.  
Now I tried a different use case, where I want to navigate to the same page but with different query string. e.g. ```/product?size=1``` to ```/product?size=2```. In that case the activation lifecycle events are not fired, which is expected. However I would also expect the custom steps are not fired too but they are being fired. 

In above situation, Ideally I would like aurelia to have logic to not invoke the custom steps. Or it should provide a mechanism to detect this situation so the custom pipeline code can react to it. I did tried out the CanActivateNextStep class but when I call its run method it errors out.

**Comment by ppn2** [comment]
@jedd-ahyoung thanks for looking into this issue. Don't you think this is bug rather than enhancement. In my view, no body would expect that half of the pipeline is not executed and rest half is executed.

**Comment by EisenbergEffect** [comment]
You can control this using activation strategy. See the router docs. You can also control this with the options you pass to the navigate method, for example `{ trigger: false }`.
