### ISSUE TITLE
Mapping imported VM

### ISSUE THREAD

**Issue by heruan** [aurelia/router#325]
I have built a module to reuse common VMs in different apps. How can I map those VM in the router? I tried to use the imported type in `moduleId`, but it seems to accept only strings.

I tried this:
```javascript
import {MyViewModel} from "my-module";

// ...
    public configureRouter(conf) {
        conf.map({
            route: "my-vm",
            moduleId: MyViewModel
        });
    }
}
```
but I get ` TypeError: name.trim is not a function`.

**Comment by EisenbergEffect** [comment]
You don't provide a type there, you provide a module id. Using that, it can load the view model from anywhere.

**Comment by heruan** [comment]
Thank you Rob, I understand now. So I can use `moduleId: "my-module"`, but which VM is used if "my-module" exports more than one type?

**Comment by EisenbergEffect** [comment]
That is indeterminate at present because the system is built to work with one export per module. So, code like that should not be pre-bundled and should be distributed as a collection of independent modules. In the future we may open up more possibilities, but that's the way it is today.

**Comment by heruan** [comment]
Okay, I'll work that out and try to keep the module split where necessary to adhere to this convention.
