### ISSUE TITLE
Type Definition issue : Cancelling navigation

### ISSUE THREAD

**Issue by maverix** [aurelia/router#326]
Hi All,

I have implemented a PipelineStep in order to intercept navigation and cancel the navigation in certain situations.  It is working well, except I had to edit the typescript definition for aurelia-router.d.ts.

In the current version (1.0.0-beta.1.2.1) the definition for Next expects a value to be passed into the cancel method.  i.e. 

  export interface Next {
    
    /**
      * Indicates the successful completion of the entire pipeline.
      */
    complete(result: any): Promise<any>;
    
    /**
      * Indicates that the pipeline should cancel processing.
      */
    cancel(result: any): Promise<any>;
    
    /**
      * Indicates that pipeline processing has failed and should be stopped.
      */
    reject(result: any): Promise<any>;
    
    /**
      * Indicates the successful completion of the pipeline step.
      */
    (): Promise<any>;
  }

In order for typescript to be happy I changed the Cancel method to 
cancel(result?: any): Promise<any>;

I'm not exactly sure how you are generating your typescript definitions, otherwise I would make a PR to fix this.

Cheers.

**Comment by EisenbergEffect** [comment]
You can make a PR directly to the source code to add the typing info there.

**Comment by maverix** [comment]
Ok, I got around to trying to make a pull request.  But I couldn't for the life of me workout where in the api.json to indicate that a parameter was optional.  Any pointers?

**Comment by EisenbergEffect** [comment]
No need to edit the api.json. That is generated from the code itself. You just need to indicate that the param is optional in the code using a `?`, for example `method(param?: string)`

**Comment by maverix** [comment]
@EisenbergEffect does this look right?

**Comment by EisenbergEffect** [comment]
Closing since the fix was merged :)
