### ISSUE TITLE
Observables in Router Activation Lifecycle

### ISSUE THREAD

**Issue by Ixonal** [aurelia/router#328]
I was thinking, it would be nice to have behavior similar to that of Promises in the activate hook, but for Observables (https://github.com/zenparsing/es-observable), with the whole not showing until the first value comes through. 

I figure it'd be something similar to this...
```javascript
let result = context.activate();
if(result && result.then instanceof Function) {
  //existing promise stuff
} else if(result && result.subscribe instanceof Function) {
  result.subscribe({
    next: (val, sub) => {
      sub.unsubscribe();
      completeActivate();
    }
  }); 
} else {
  //existing synchronous value stuff here
}
```

Admittedly, the unsubscribe part would require a modification to the spec to allow the subscription to be undone in the case of a synchronous first value. (https://github.com/zenparsing/es-observable/issues/83). Any thoughts?

**Comment by EisenbergEffect** [comment]
We would be interested in a PR to add this if you find it useful.

**Comment by Ixonal** [comment]
I'll look into it in a few days.

**Comment by Ixonal** [comment]
Alright, found a way to handle the synchronous first value in subscriptions and made a fork using that https://github.com/Ixonal/router/blob/master/src/activation.js#L205

Any comments or concerns, or does it look good? If it's good, I'll set up the tests and put in a pull request.

**Comment by EisenbergEffect** [comment]
That seems pretty reasonable. @bryanrsmith What do you think?

**Comment by bryanrsmith** [comment]
Sounds reasonable to me, too. I haven't spent much time with observables, so I do have a few questions:

1. Is waiting for the *first* value the right thing to do, or will anyone want to wait for the sequence to complete?
1. Do we need to unsubscribe on error?
1. Do we need to observe sequence completion to cover the case where an observable produces no value?

**Comment by Ixonal** [comment]
1. Considering that the Observable may never actually complete, waiting for that could be problematic. My thinking on this feature was in the way of using Observables with AJAX requests (like how Netflix and Angular 2 use them to get request cancellation support) and WebSockets. If it's for an AJAX request, the first value is the whole response and then it'd be complete anyways. If it's for a WebSocket, it'll most likely not complete for the duration of the page. In that case, the assumption is that the first message through means it's working and there should be enough information to render.

2. For error and complete, so far as I can tell in the listed source, will both clean the subscription, which runs that subscription's cleanup callback. The default cleanup function is to unsubscribe. I suppose it would be more proper to explicitly unsubscribe on error and complete, but I don't think it's necessary. At least, according to the spec. It could be implemented differently in different libraries, so it may be of benefit to unsubscribe explicitly.

3. I hadn't really thought about that... I would think that'd depend on the decision for 2, since both error and complete will try to run the unsubscribe function.

**Comment by Ixonal** [comment]
I made a change that should cover points 2 and 3. I thought more about point 1, and if they need all values from an Observable, they can convert it to a promise. In the es-observable spec, the forEach method returns a promise when the Observable completes. Other libraries have additional ways to do that too. For example, RxJS has the toPromise instance method. Then the existing promise handling code would kick in.

**Comment by Ixonal** [comment]
@EisenbergEffect @bryanrsmith I'm assuming the silence means you have no objections?

**Comment by EisenbergEffect** [comment]
Seems pretty reasonable. Go ahead and create a PR and we cn have @bryanrsmith  do a final review.

**Comment by Ixonal** [comment]
Just realized this never got closed when the pull was integrated. Going to go ahead and close now.

**Comment by davidlav** [comment]
If this feature was implemented, is it documented anywhere?  I couldn't find anything about it in the routing or Aurelia Store docs.

I was looking for a way to activate a component routed to upon a state change in Aurelia Store (if that can be done with a promise, I don't know how) and landed here.

**Comment by Ixonal** [comment]
@davidlav Not sure if this feature was ever added to the documentation, but so far as I can tell, it's still there. Unfortunately, I'm not particularly familiar with Aurelia Store, so I'm a bit limited on what I can say regarding that.
