### ISSUE TITLE
Binding attributes in <router-view>

### ISSUE THREAD

**Issue by hadrienl** [aurelia/router#330]
I have a route hierarchy like that: `/accounts/1/foo/bar` so I have a first router on `/accounts/:id` which will load the account #1 then I have two levels of child routers `/foo` and `/bar`. Each loads many views which will have to work with the loaded account of the parent router.

I have two ways to handle this :
1 - On upper router, I set `this.router.account = account` and then, on child router, I read `this.router.parent.account`, and `this.router.parent.parent.account`. It's ugly and dangerous if someday I have to remove or add levels of routing. And then, I'll have to observe `this.router.parent` to know when account object will change.

2 - I load the account on every views from the dedicated service which will cache the data to avoid too many request on server but, then, I have to repeat some logic on each views, in my case, I'll have :

```
 await activate(routeParams) {
  if (!routeParams.id) {
    return false;
  }

  this.user = await this.usersFetcher.getCurrent();

  this.account = await this.user.getAccount({ id: routeParams.id });
```

for each views.

So, I'm looking for a way to pass data to <router-view></router-view> like we can do in Angular.
`<router-view account.bind="account"></router-view>` should be so easy to use.

**Comment by EisenbergEffect** [comment]
We recommend to not tie this type of data to the navigation structure as that will cause structural coupling throughout your app and make it difficult to change your app's UX.

Instead, consider creating a mediator service that can enable storage and lookup of data that is shared by different levels of the hierarchy.
