### ISSUE TITLE
Return a Promise for a navigation command on canActivate

### ISSUE THREAD

**Issue by diegograsso** [aurelia/router#331]
Hello,
I know that canActivate should return a boolean value, a promise for a boolean value, or a navigation command like a Redirect or RedirectToRoute.
But I have a case where I need to return a Redirect after an async call in a promise.
I tried that but realised that when the router process the canActivate callback and gets a Promise it expects it to resolve to a boolean and ignores my redirect.
I would like to be able do something like:
```
canActivate(params) {
  return this._api.checkMyCondition(params.x)
    .then(result => {
      if(result.shouldRedirect){
        return RedirectToRoute('myOtherVM');
      } else {
        return true;
      }
    }).catch( error =>{
      console.log(error);
      return false;
    });
}
```

**Comment by EisenbergEffect** [comment]
This definitely sounds like a bug. @bryanrsmith Can you look into this?

**Comment by bryanrsmith** [comment]
I think you have to *reject* with the redirect. Try `throw RedirectToRoute('myOtherVM)`. It's a bit odd & I think it'd be better to respect a navigation command in the resolution as well.

**Comment by EisenbergEffect** [comment]
I agree. Can we make that improvement?

**Comment by stsje** [comment]
In the meanwhile you could manually call either resolve or reject
```
canActivate(params) {
  return new Promise((resolve, reject) => {
    this._api.checkMyCondition(params.x)
        .then(result => {
          if(result.shouldRedirect){
            reject(RedirectToRoute('myOtherVM'));
          } else {
            resolve(true);
          }
        }).catch( error =>{
          console.log(error);
          resolve(false);
        });
  });
}
```

**Comment by diegograsso** [comment]
Thank you for your quick response. I've just tried it seem to be returning
the navigation command but it's still not working. I think now it has a
problem because it's in a child router.

It I created a plukr with an example:
https://plnkr.co/edit/UrewdjNS7EUfNfyA4wQA
In the example, I'm using the old Redirect because it's not at the latest
version, my real code is up to date and has the same issue.

The urls to test it are:

http://run.plnkr.co/plunks/UrewdjNS7EUfNfyA4wQA/#/child-router/redirect?shouldRedirect=YES
http://run.plnkr.co/plunks/UrewdjNS7EUfNfyA4wQA/#/child-router/redirect

**Comment by cehoffman** [comment]
I can offer a bit of empirical evidence on **canActivate** and navigation commands. I've used **Redirect** and **RedirectToRoute** extensively and it works without a problem in a no child router application. I don't have to reject the promise with the navigation command and with is with release **beta.1.2.2** of the router.

**Comment by EisenbergEffect** [comment]
I can also confirm that it works in various scenarios. @diegograsso is the problem still present? If so, can you tell if you are getting a route not found? What exactly happens?

**Comment by EisenbergEffect** [comment]
Looks like it can't find the route. This is probably an issue with route generation in child routers. We are tracking this elsewhere, so I'll close this for now.

**Comment by jsobell** [comment]
@EisenbergEffect Where is this being tracked?

**Comment by thinkOfaNumber** [comment]
I'm having the same problem - child routers don't listen to `return new RedirectToRoute(...)` nor `throw new RedirectToRoute(...)`, using aurelia-router 1.3.0.

Was this tracked / fixed somewhere?

thanks :)

**Comment by thinkOfaNumber** [comment]
A little bit more of an update: I _can_ `return new RedirectToRoute()` from a child router, but only if it's _not_ a fresh page load.

e.g.

`my.app/some/route` has a `canActivate()` method that calls `return new RedirectToRoute()` for some condition

- navigate to `my.app/some/route` as the very first page visited
- I get navigated back to `my.app` (I'm guessing the root fallback route)

but

- navigate to `my.app/some/something` as the very first page visited
- follow a menu or link to `my.app/some/route`
- I get navigated back to the route specified in `RedirectToRoute`

I guess this is a bug. Do you want me to open a new bug or stay here?

**Comment by nvtin** [comment]
Hi guys,
I also get this issue.
I want to redirect to route in canActivate. 
I've tried using 
`reject(new Redirect('home'))`
like code below:
```
canActivate(params) {
  return new Promise ((resolve, reject) => {
      this.myFunction(params, function(err, result){
        if (err){
          return reject(new Redirect('home'))
        } 
        resolve(true);
      })
    });
}
```
I got the error: ` Route not found: /home` and `Warning: a promise was rejected with a non-error: [object Object]`

So I've changed it to `reject (this.router.navigateToRoute('home'))`
```
canActivate(params) {
  return new Promise ((resolve, reject) => {
      this.myFunction(params, function(err, result){
        if (err){
          return reject (this.router.navigateToRoute('home'))
        } 
        resolve(true);
      })
    });
 }
```
But the bugs was still there: `Warning: a promise was rejected with a non-error: [object Object]`
How can I force it redirect to home in canActivate?
Thanks!
