### ISSUE TITLE
Pipeline steps are not reset when changing roots

### ISSUE THREAD

**Issue by z-brooks** [aurelia/router#332]
I'm using roots to separate the login/register parts from the rest.  The login root doesn't need the auth step used in the main root.

Pipeline steps added in `configureRouter` are not removed when switching roots with `setRoot`.  Any steps added will remain and will be added again when switching back.
* [skeleton repro](https://github.com/z-brooks/pipeline-repro)
* [gist.run](https://gist.run/?id=099a2fe7a6d5d82d9830e04c3f1c15b3)

Something like [this](https://github.com/aurelia/router/compare/master...z-brooks:pipeline-reset) would fix it, but I'm not sure if it's the best way.

**Comment by EisenbergEffect** [comment]
Pipeline steps are not managed by the router, but by a separate pipeline provider service. I would recommend that you just reference that and remove the steps you don't want as needed.

**Comment by z-brooks** [comment]
Yeah, that's fine. I'm currently using the modified fork linked in the top post. 

The concern is that when switching back and forth the steps accumulate so there are multiples of the same step in the pipeline being applied when routes change.
Updated the [gist.run](https://gist.run/?id=e0a6204fd698f5597328acc992293ce6) to illustrate. Click the `switch` button a few times and the steps will add up. Then click the link and in the console there will be output for each duplicate step in the `pipelineSlot`.
This could be worked around by setting a var indicating the steps have been added, but that seems hackish.
If resetting the pipelineSlot steps isn't desirable then a check for existing steps might be needed before adding a step. If steps need to be manually removed then it might be helpful to have `removeStep`/`clearSteps`  methods.
[check existing / removing](https://github.com/aurelia/router/compare/master...z-brooks:pipeline)

The best place to remove steps might be the root `deactivate` method, but that doesn't get called when switching. Perhaps adding something in the `setRoot` method around https://github.com/aurelia/framework/blob/master/src/aurelia.js#L118 to call the viewModel deactivate if it exists?

**Comment by EisenbergEffect** [comment]
Perhaps we can just have a reset method on the provider to set it back to the default configuration?

**Comment by z-brooks** [comment]
That's what I'm doing now. Either way is fine, just rambling ideas. As long as there's a way to clear out unneeded/duplicate steps. Duplicates could be prevented with a simple check though.

**Comment by EisenbergEffect** [comment]
Sounds like a nice PR opportunity. Any interest in submitting an improvement to the pipeline provider?

**Comment by z-brooks** [comment]
Sure.  Are you looking for a single method to reset everything to as it is right after construction? Or, something to reset a specific slot like https://github.com/z-brooks/router/blob/pipeline/src/pipeline-provider.js#L90?
