### ISSUE TITLE
previousInstruction on currentInstruction

### ISSUE THREAD

**Issue by cehoffman** [aurelia/router#335]
I finally got the chance to upgrade from the 1.1 beta (roughly 2 months ago) to the most recent release as of today. Most everything appears to be working just as expected except **previousInstruction** on the **currentInstruction** of the router instance no longer has the last route's information. It is always null.

The following snippet from the **attached** callback on a viewPort view model used to work. The basic action that I was using previousInstruction for was to scroll the list such that the just visited item is in view.

``` javascript
    let {currentInstruction} = this.router;
    if (currentInstruction && currentInstruction.previousInstruction) {
      let {alarmId} = currentInstruction.previousInstruction.params;
      if (alarmId) {
        setTimeout(() => {
          this.scroller.scrollToElement(`li[data-alarm-id="${alarmId}"]`);
        });
      }
    }
```

This worked on release of aurelia-router@1.0.0-beta.1.1.1 and is not working on aurelia-router@1.0.0-beta.1.2.2.

Full changelog of aurelia component versions updated

``` diff
-    "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
-    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.1.2",
-    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
-    "aurelia-dialog": "npm:aurelia-dialog@0.5.6",
-    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.1.1",
-    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.1.3",
-    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.1.2",
-    "aurelia-i18n": "npm:aurelia-i18n@0.4.7",
-    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.1.2",
-    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.1.4",
-    "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.6",
-    "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
-    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.1.1",
-    "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
-    "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
-    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.1.1",
-    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.1.1",
-    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.1.1",
+    "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.5",
+    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.2.1",
+    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.3",
+    "aurelia-dialog": "npm:aurelia-dialog@0.5.10",
+    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.1",
+    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.3",
+    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.1",
+    "aurelia-i18n": "npm:aurelia-i18n@0.5.2",
+    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.2",
+    "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.1",
+    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.1",
+    "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.1",
+    "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.2",
+    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.2.1",
+    "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.2",
+    "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.1.4",
+    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.2",
+    "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.1",
+    "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.6",
+    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.4",
+    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.5",
+    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.1",
```

**Comment by cehoffman** [comment]
It appears that the 3rd argument to the activate callback has the expected previousInstruction. It never makes its way to the currentInstruction on the router.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you look into this?

**Comment by bryanrsmith** [comment]
7fa6e0b97370f08a4e3b1c08bad2ea1eded330f4 removed the `previousInstruction` at the end of the activation cycle to plug a memory leak. You will need to read the name of the previous route during activation and store it for later use. I believe this happened around version 0.13. I'm not sure why it would have worked with any beta version.

**Comment by cehoffman** [comment]
Maybe this other bit of behavior change I've noticed is related then. Previously it appears attached related items were available in the activate callback that no longer are. Perhaps attached was being called prior to activate and that is why `router.currentInstruction` still had the previousInstruction set. Was there a change in the callback ordering? Specifically we had in the template a call like `<tag custom-attribute custom-attribute.ref="handle">` and were able to use that handle within the activate callback in our promise resolution chain. Now it is an undefined reference. This new behavior does make sense though and allows for faster routing when activate and canActivate redirect to other locations.

I can understand the reasoning, but I have a few reservations about not allow *any* history. What about allowing 1 item of history? Removing all history neuters some of routing's usefulness outside of the view models that can hook into the activate callback. Would you be open to changing the line to
`instruction.previousInstruction && instruction.previousInstruction.previousInstruction = null`?

**Comment by EisenbergEffect** [comment]
The `attached` callback has fired after the `activate` callback for a very long time. If it worked the other way, it was some sort of accidental regression in an old version.

@bryanrsmith Let's see if we can give "some" sort of previous instruction info. Maybe as @cehoffman we can provide a cleaned up instance that won't have the memory leak issues.

**Comment by EisenbergEffect** [comment]
@cehoffman Any interest in submitting a PR for this?

**Comment by Alexander-Taran** [comment]
stale since 2016

**Comment by davismj** [comment]
There's very little interest, and there are other ways to get this information. I'm with Alex.

**Comment by ricardograca** [comment]
> ... there are other ways to get this information. I'm with Alex.

Can you provide an example of one of these other ways? Because @bryanrsmith's comment above only says that: 

> You will need to read the name of the previous route during activation

But that's not possible since the third argument to `activate()` does not include the `previousInstruction` any more.

**Comment by davismj** [comment]
@ricardograca 

```js
activate(params, config, instruction) {
  const previousInstruction = instruction.previousInstruction;
}
```

**Comment by ricardograca** [comment]
@davismj It's always `null`, so that doesn't work.

**Comment by davismj** [comment]
Sounds like a separate issue. If you can open up an issue with a repro I'll look into it.
