### ISSUE TITLE
Hide detached element

### ISSUE THREAD

**Issue by ejsmith** [aurelia/router#338]
We have a view that has a google map on it which is expensive to draw. The UI is setup in such a way that the user would be switching back and forth between the map view and a grid view frequently. Is there some way that we can load the map the 1st time the view is shown and then just hide it when the user navigates out of the view so that it can just be marked visible when the user goes back to it instead of having to re-render the entire thing each time?

**Comment by ejsmith** [comment]
Any ideas on this?

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Can you provide guidance here? I know you've done this exact thing...

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Please ping me after responding so I can close this out.

**Comment by dpinart** [comment]
Would be nice to have this topic on the cheat sheet...

**Comment by EisenbergEffect** [comment]
It's not merely a topic but an advanced customization of the router-view. It's probably better for some sort of "recipes" section though...

**Comment by ejsmith** [comment]
Yeah, would definitely be great to document this.

**Comment by ejsmith** [comment]
Any code you can point me at?

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Please respond here. Also, it would be worth it to put together a sample solution to show you did it for future reference.

**Comment by ejsmith** [comment]
Attempting to wait patiently. :-) I guess I should dig into the router source code and see if I can figure out how to change the behaviour.

**Comment by cmichaelgraham** [comment]
hi sorry for the delayed response.

[here](http://cmichaelgraham.github.io/skel-nav-esri4-vs-ts/index-release.html#/esri-globe) is a link to a running sample with the esri map.  notice that if you zoom in, change to a different route, and change back, it snaps right in...

implementation is [here](https://github.com/cmichaelgraham/skel-nav-esri4-vs-ts)

doesn't mess with the router.  hides/shows the map when you visit/leave the associated map route...

> * [map visible property](https://github.com/cmichaelgraham/skel-nav-esri4-vs-ts/blob/master/skel-nav-esri4-vs-ts/views/app.ts#L7)
> * [map html](https://github.com/cmichaelgraham/skel-nav-esri4-vs-ts/blob/master/skel-nav-esri4-vs-ts/views/app.html#L6-L18)

for a cool view of the globe, zoom in, then right-click-drag-up and you'll see the globe as if you were a satellite.  pretty cool :smile:

let me know if you need more info...

probably the quickest way to get ahold of me is to mention me [here](https://gitter.im/cmichaelgraham/aurelia-typescript)

ping @EisenbergEffect @ejsmith

**Comment by ejsmith** [comment]
Ok, I took a look at your example and at first I saw the ResourcePool code and was thinking that was how you were doing it, but upon further investigation, it looks like that code isn't being used. Was that a different attempt of trying to get this behaviour?

So basically, you just have an element at the app level that is shown or hidden over top of a blank view and then it's visibility is toggled on attach / detach?

**Comment by EisenbergEffect** [comment]
@cmichaelgraham This isn't the demo I was referring to. There was an implementation with a custom router-view that showed how to do this more generically wasn't there?

**Comment by ejsmith** [comment]
Yeah I was hoping for something a little more generic as well.

**Comment by dpinart** [comment]
I also expected another thing, it seems like a hack of mines :). Anyway, I have tried this solution and it works like a charm.

**Comment by ejsmith** [comment]
@EisenbergEffect it sounds like @cmichaelgraham tried to build a more generic version of doing this, but ended up doing a simpler solution. It seems like this would be a generally useful feature to have in the router. Any ideas how you would go about implementing it?

**Comment by EisenbergEffect** [comment]
Yes, you start by forking our router-view implementation from templating-router. If you look at that code, you will see a process method, you need to cache some of the data that is created there instead of creating it each time.

We have an issue tracking adding this as a feature. It's difficult to add in a generic way, which is why it hasn't been added yet. We are considering it and will probably have something built-in eventually, but haven't finished our research yet.
