### ISSUE TITLE
router.hasOwnRoute & router.hasRoute both return false but the navigate works and the route exists in the routes array

### ISSUE THREAD

**Issue by bobpardoe** [aurelia/router#340]
`
// will dynamically add the routes from the menu data
    addRoutes() {
        this.router.addRoute({route: "nbrm11", moduleId: "nbrm11", nav: true, title: "Test Page 1"});
        this.router.addRoute({route: "test-page2", moduleId: "test-page2", nav: true, title: "Test Page 2"});
        this.router.addRoute({route: "test-page3", moduleId: "test-page3", nav: true, title: "Test Page 2"});
        
        // always add the error routes manually
        this.router.addRoute({route: "error-404", moduleId: "./errors/error-404", nav: true, title: "ERROR - 404"});
        
        // forces the collection to rebuild
        this.router.refreshNavigation();
    }

    // invoked from the view
    menuSelection (menuItem) {
                
        console.log ("Menu Selected : " + JSON.stringify(menuItem));    
        
        var programName = String(menuItem.name).toLowerCase();

        console.log("programName : " + programName);
        console.log("this.router.hasOwnRoute(programName) : " +  this.router.hasOwnRoute(programName));
        console.log("this.router.hasRoute(programName) : " + this.router.hasRoute(programName));

        for (var i = 0; i < this.router.routes.length; i++)
        {
            console.log ("route.name : " + JSON.stringify(this.router.routes[i].route));
        }

// this works OK
this.router.navigate(programName);
}
`

console output : 

`
Menu Selected : {"name":"NBRM11","title":"BRANCH ENQUIRY","tooltip":"","type":"P","library":"NEXT","breadcrumb":"/SL00/SL01/NBRM11"}

programName : nbrm11
this.router.hasOwnRoute(programName) : false
this.router.hasRoute(programName) : false
route.name : ""
route.name : "welcome"
route.name : "users"
route.name : "child-router"
route.name : "menu"
route.name : "nbrm11"
route.name : "test-page2"
route.name : "test-page3"
route.name : "error-404"
`

The router navigates to the route (programName) but it does not exist when testing for it's existence.

Me doing it wrong or a bug?

**Comment by EisenbergEffect** [comment]
You need to give your routes a `name` property and then check by that name.
