### ISSUE TITLE
Localizing title

### ISSUE THREAD

**Issue by henning-krause** [aurelia/router#343]
This is somewhat related to #218. 

Currently, I'm using some kind of resource identifier the page title in the router config:
`
config.map([
            {
                route: ["", "home"],
                name: "home",
                moduleId: "dashboard/home",
                nav: true,
                title: "home"
            },
`
I'm localizing the title in the nav-bar.html using t.bind, and this works. 

However, this does not work with the title of the website, which Aurelia builds up automatically from the NavigationInstructions using the title field from the config.

Is there any way to localize the page title?

**Comment by EisenbergEffect** [comment]
We could add a translate hook that the router passed all title information through before setting the actual document title. This sounds like a nice user contribution and we'd be happy to take a PR for that. I think it would mean adding a `titleTransform` setting and using that throughout.

@zewa666 may have some thoughts on this as well as @bryanrsmith

**Comment by stsje** [comment]
How about letting the title either be a string or a function?

**Comment by stsje** [comment]
I don't like the i18n to know about the router, and the router shouldn't know about i18n, so I see no option atm. to update the title on language change without coding it yourself. Should be a one-liner if title could be a function (as suggested above).
`this.eventAggregator.subscribe('i18n:locale:changed', this.router.updateTitle.bind(this.router));`

**Comment by EisenbergEffect** [comment]
I think we just need to implement a function that each "title" value for each route gets passed through when it builds the full title. This would allows the developer to supply any function they want, including one that invokes i18n APIs.

**Comment by CasiOo** [comment]
How would that work when a page needs to show a product name in the title? Would you replace the transform function, or have a title-parameter property on the route?

**Comment by EisenbergEffect** [comment]
You can currently use the nav model's `setTitle()` api to dynamically set the route for any router. I would imagine, you would just call that api today with the translated product name.

**Comment by CasiOo** [comment]
I see, so you don't add a transform function to routes which title are dynamic. For those you must set the title in the VM, passing any parameters to i18n that would be needed. I'm thinking titles that have placeholders `{{category}} - {{productTitle}}`.

I can see it working out :) Would be great to know what title requirements people have in their projects.

**Comment by kristianmandrup** [comment]
I assume this in `Router` class of `router.js` is the key

```js
  /**
  * Creates a [[NavModel]] for the specified route config.
  *
  * @param config The route config.
  */
  createNavModel(config: RouteConfig): NavModel {
    let navModel = new NavModel(this, 'href' in config ? config.href : config.route);
    navModel.title = config.title;
```

and this in `NavModel` class of `navmodel.js` (both can be found in `aurelia/router`)

```js
  /**
  * Sets the route's title and updates document.title.
  *  If the a navigation is in progress, the change will be applied
  *  to document.title when the navigation completes.
  *
  * @param title The new title.
  */
  setTitle(title: string): void {
    this.title = title;

    if (this.isActive) {
      this.router.updateTitle();
    }
  }
```

So perhaps introducing a `title` setter/getter in `NavModel`

```
  set title(title : string) {
    title = this.transformTitle ? this.transformTitle(title) : title;
    this._title = title;
  }

  get title() : string {
    return this._title;
  }
```

Then add it in your app as follows?

```js
import { NavModel } from 'aurelia-router';
import { I18N } from 'aurelia-i18n';

NavModel.prototype.transformTitle = function(title) {
  return this.i18n.tr(title);
}
```

Then the only question is how to inject the I18N singleton into NavModel or otherwise make it accessible!? I'm someone else could answer that :)

**Comment by CasiOo** [comment]
@kristianmandrup I don't think the router is supposed to know about the i18n plugin, if that's what you're asking.

**Comment by 7Pass** [comment]
I'd suggest that we allow setting title to either a string or a function when configuring routes, and expose a method in `Router` to refresh titles, which will re-evaluate titles. This way, it's the responsibility of the route config to know how to return the correct title in the correct language, and the application have the ability to refresh the title as and when needed.

Going one step further, allow the view models to update its title, using a bindable property or some property of `RouteConfig`. This will allow refreshing just the title needed so not all titles need to be refreshed.

**Comment by kristianmandrup** [comment]
@7Pass Sounds like a great solution to me ;)

**Comment by stsje** [comment]
Having the title be a function, as I mentioned earlier in the issue, isn't completely painless. Will need to think through every use case where the developer might change the title. Using parameters and what not.
I'm interested in knowing the reasoning behind @EisenbergEffect preferring a transform function over having the title be a function.

**Comment by EisenbergEffect** [comment]
If the title isn't a simple property, then it becomes difficult for us to efficiently data-bind to it and/or know when it might have changed.

**Comment by dmoebius** [comment]
@EisenbergEffect @stsje What do you think of manuel-guilbault's commit? Sounds good to me...

**Comment by stsje** [comment]
I don't think it is completly worked out how the title generation should be done.
See the issue about route separators, the suggestions there will probably have an effect on this issue https://github.com/aurelia/router/issues/419

**Comment by dmoebius** [comment]
I see. I like the suggestion of rmja there. Ok, I will just wait for the resolution of #419 then.

**Comment by gronostajo** [comment]
Solution introduced in #409 works fine with one-time translation, but switching language doesn't update title. Obviously, router is unaware of locale change and doesn't refresh title. Is it possible to force title refresh?

**Comment by zewa666** [comment]
@gronostajo you could hook up onto the translation event https://github.com/aurelia/i18n/blob/master/src/i18n.js#L57 and manually correct the title accordingly in lieue with the feature introduced in #409

**Comment by gronostajo** [comment]
@zewa666 I figured that part out, but I don't know how to trigger title refresh in the router.

**Comment by zewa666** [comment]
@gronostajo I'm not 100% sure what the right way is, but currently I'm using the private API `_updateTitle` exposed by the NavigationInstruction object.

So the setup part of your app would look like this:

```javascript
return instance.setup({
      backend: {                                   // <-- configure backend settings
        loadPath: '../locales/{{lng}}/{{ns}}.json' // <-- XHR settings for where to get the files from
      },
      lng: 'de',
      attributes: ['t', 'i18n'],
      fallbackLng: 'en',
      ns: ['translation', 'foo'],
      debug: false
    }).then( () => {
      const router = aurelia.container.get(AppRouter);
      const eventAggregator = aurelia.container.get(EventAggregator);

      router.transformTitle = title => instance.tr(title);
      eventAggregator.subscribe('i18n:locale:changed', (payload) => {
        router.currentInstruction._updateTitle(instance.tr(router.title));
      });
    });
```

Keep in mind as it is a private API it might change. @EisenbergEffect any chance we can make this one public?

**Comment by zewa666** [comment]
I'll update the docs to include that example: https://github.com/aurelia/router/pull/450

**Comment by obedm503** [comment]
is it possible to get route params and pass the along to the `transformTitle` function?
