### ISSUE TITLE
configureRouter from a feature view-model

### ISSUE THREAD

**Issue by TGMorais** [aurelia/router#345]
Hi,

I have been trying to setup a child router inside a feature, with no success.

As the docs say, to setup a child router one only has to call `configureRouter()` from the intended view-model.
However when I do this from a feature view-model, `configureRouter` is never called.
 I wonder if this is intended behaviour.

I have something like this:

`src/features/my-feature/index.js`
```javascript
export function configure(config) {
  config.router();
  config.globalResources('./elements/my-feature');
}
```

`src/features/my-feature/elements/my-feature.html`
```html
<template>
    Hello from my feature!
   <router-view></router-view>
</template>
```
`src/features/my-feature/elements/my-feature.js`
```javascript
export class MyFeature {
  configureRouter(config, router) {
      //this is never called
  }
}
```

I include the feature as ` aurelia.use.feature('features/my-feature')`, and use it in my app.

`src/my-component.html`
```html
<template>
    <my-feature></my-feature>
</template>
```
`my-feature` template render fine, (except for the router) as I can't setup the child router in it.

I have tried importing the Router and creating a child router manually inside `my-feature.js` `contructor`, but it dosen't seem to work :/.

Thank you.

**Comment by EisenbergEffect** [comment]
Calling `config.router()` installs the router plugin. That's not what you want here. You need to map the parent router to your feature's view model.

**Comment by TGMorais** [comment]
@EisenbergEffect Hmm, I'm not sure I follow.
I need a new (child?) router with it's own mapping for my feature, so I can have my own child routes.
How would I go that ? By importing the AppRouter into my feature?

**Comment by EisenbergEffect** [comment]
The "feature" feature and "routers" don't have anything to do with one another. The problem you have is that you just haven't configured routing correctly. You can see how to set up child routers in the getting started guide. I'd recommend you look through that again as well as the section on routing in the Cheat Sheet.
