### ISSUE TITLE
route-href does not take into account the href on the route config

### ISSUE THREAD

**Issue by cosminonea** [aurelia/router#347]
I've got a route like this:

```javascript
      {
        route: 'charts/:name',
        name: 'chart',
        title: 'Charts',
        moduleId: 'common/resources/custom-elements/chart',
        href: '#/some/data/'
      },
```

Notice the href there. In the view I have something like this:
```html
        <ul>
          <li repeat.for="view of dataViews" class="${view.isActive ? 'active' : ''}">
            <a route-href="route.bind: view.type; params.bind: { name: view.name }">
              <div>
                <h2>${view.title}</h2>
              </div>
              <div class="list-snippet">
                <p>${view.description}</p>
              </div>
            </a>
          </li>
        </ul>
```

The dataViews looks like this: 
```javascript
{
  description: "some chart"
  name: "some-chart"
  title: "Some Chart"
  type:"chart"
}
```

If I am on a deep URL like `#/some/data/charts/[chart-name-here]` and refresh the browser all the items in the list have a URL like `#/charts/[chart-name-here]` without the `#/some/data/` prefix. If I navigate to the page via navigation links however, all the links in the list are generated properly.

If this a bug or am I missing something?

**Comment by EisenbergEffect** [comment]
Is this with the latest release of the router? If so, can you see if it exists in the previous release?

**Comment by cosminonea** [comment]
This is a snapshot of my config.js file:

```javascript
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.1",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.1",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.1",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.0",
```

Not sure if this is the latest.

**Comment by cosminonea** [comment]
well, the reason I am trying to use the href on the route configs is because if I browser-refresh a "deep" url, none of the URL generation works. It looks like the whole context of the current route/router is lost and I am trying to get around that using the href which is not ideal but that doesn't work either.

**Comment by cosminonea** [comment]
This happens using the latest router release as well:
```
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.4",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.1",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.1",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.1",
    ```

**Comment by EisenbergEffect** [comment]
Are you using push state?

**Comment by cosminonea** [comment]
No, not explicitly. I guess it's off by default.

**Comment by cosminonea** [comment]
Is this an issue with the router?

**Comment by EisenbergEffect** [comment]
Ok, this seems like two issues here:

1. The refresh of a deep link isn't working.
2. The route-href doesn't use an explicit href is provided.

Issue one has only occurred when using push state in my experience, if the base and root aren't configured properly. Other than that, we can't reproduce that problem.

The second issue seems like an oversight in the route-generation code. I'll look into that.

**Comment by EisenbergEffect** [comment]
@cosminonea We've had to make a change to the way this works, coming in tomorrow's release. When you want route generation to use a hardcoded href, on your route config, you need to set the property `generationUsesHref: true`
