### ISSUE TITLE
doc outline

### ISSUE THREAD

**Issue by shannonhorn** [aurelia/router#348]
Can we get an outline of the topics to cover in the Router: Basics doc? Thank you!

**Comment by EisenbergEffect** [comment]
* Router Configuration
    * title
    * map
    * options (push state)
    * Async Config
    * handle unknown routes
* router-view
* Child Routers
    * relative href and module id
* Link Generation with router-href
* Router Pipeline customization

This would be a good start.

**Comment by HIRANO-Satoshi** [comment]
I am confused with route, href and name. I cannot figure out their relationship.

**Comment by EisenbergEffect** [comment]
`route` is the pattern to match. `name` is just a name used to reference the route configuration so you can generate routes throughout your application without hardcoding urls. `href` isn't used unless you need to hardcode an href associated with a route for the purpose of generating a navigation structure. Normally the router would generate the route. Setting this overrides the generated value.

**Comment by Alexander-Taran** [comment]
can be closed

**Comment by davismj** [comment]
Would be good to add docs for name on the route config to the official docs.
