### ISSUE TITLE
Customizing the Navigation Pipeline in Typescript: "Property 'cancel' does not exist on type 'Function'."

### ISSUE THREAD

**Issue by vaags** [aurelia/router#349]
Hi. I'm trying to customize the Navigation pipeline in my main router, as described in the docs:(http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/securing-your-app).

I'm using TypeScript with the latest [typescript-webpack skeleton](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack) (1.0.0-beta.1.2.6).

I've entered `config.addPipelineStep('authorize', AuthorizeStep);` to add an authorization step inside the configureRouter function.

The step (AuthorizeStep) is being called just as expected. But, inside AuthorizeStep, when I call `return next.cancel(new Redirect('login'));`, I get a squiggly red line underneath "cancel" (in VS Code), and the following error:

`[ts] Property 'cancel' does not exist on type 'Function'.`

Any ideas? This might just be a rookie mistake, but I really just pasted in the code from the docs - which should be valid.

**Comment by EisenbergEffect** [comment]
The code is correct, but our d.ts files might not be, which is causing TS to complain.

**Comment by vaags** [comment]
Ah. I see. Could this be related to #326? I tried changing the aurelia-router.d.ts, like @maverix did there, but still got the squiggly.

**Comment by EisenbergEffect** [comment]
Typings should be all fixed up now.

**Comment by andrewtobin** [comment]
@EisenbergEffect I've just installed the cli, and tried this and still getting the same problem.  I've made sure to do an npm update on the aurelia-router but same.

**Comment by andrewtobin** [comment]
It looks like the sample code on the site should read more like:
  class AuthorizeStep {
    run(navigationInstruction: NavigationInstruction, next: Next): Promise<any> {

But I _think_ that auth needs to be added onto the RouteConfig interface? Not sure - I'm pretty new to TypeScript. https://github.com/aurelia/router/blob/master/dist/aurelia-router.d.ts#L87

**Comment by EisenbergEffect** [comment]
We need to update the samples there. Any custom settings, like auth, should be added onto the `settings` property.
