### ISSUE TITLE
Router silently fails

### ISSUE THREAD

**Issue by AStoker** [aurelia/router#352]
### Enhancement Request

There are cases when the router will swallow errors during the navigation process, leaving the user with a blank page, and the console with no indication what went wrong.  
I've found that most cases (for me at least) involve failing on some kind of `deactivate` or `detached` method, and every time I get this behavior, I have to go into the code and wrap the navigation inside a try-catch block to output the error.  

**It would be beneficial to have some kind of error logging for these errors.**

**Comment by EisenbergEffect** [comment]
Since you have figured out how to catch them, perhaps you can make a PR for the fix? @bryanrsmith can review and provide any guidance you need.

**Comment by AStoker** [comment]
Sure. What I had done was just wrap the code at https://github.com/aurelia/router/blob/master/src/router.js#L143 inside a try catch. I can make a PR with just that, but I'm not sure if that's something that should just be thrown into the console, or interact with the aurelia logger (which I'm not as familiar with)?

**Comment by EisenbergEffect** [comment]
@AStoker Since navigation is asynchronous, it's not clear to me how wrapping the line you reference in a try catch will actually catch any real errors that happen. Are you sure that's the correct location? Can you tell me how I can reproduce the unreported error? That would enable me to find the best place to put the error reporting logic.

**Comment by AStoker** [comment]
@EisenbergEffect, I think the router has changed a bit, so that line number isn't accurate anymore. What was happening was one of the view model's `deactivate` method was throwing an error, and that method is called during the router lifecycle. But somewhere along the way, the error was being swallowed and not writing the error to the console, so wrapping the navigate logic was all I needed to at least get the error to be caught. I'll see if I can't get a simple repro-repo with the skeleton navigation project for you this week.

**Comment by genne** [comment]
I have a similar issue, not sure it's exactly the same, but seems to have happened in the last release.

If something goes wrong when activating a route I get no error reporting at all, see child.js in the following gist:
https://gist.run/?id=e8e3c7fcc68957a9a11d24c4535f2c04

**Comment by jon123** [comment]
I don't know if this will catch all silent router errors, but the trick I managed to find is to put a breakpoint in bluebird's [util.js](https://github.com/petkaantonov/bluebird/blob/master/src/util.js). 
```
function tryCatcher() {
    try {
        var target = tryCatchTarget;
        tryCatchTarget = null;
        return target.apply(this, arguments);
    } catch (e) {
        errorObj.e = e;  // ******* break point here ****** 'e' typically contains the error that is silently failing
        return errorObj;
    }
}
```
I use the CLI so to debug silent failures, I search for the tryCatcher() function in the vendor-bundle.js and break point there.  You'll typically see an error like `Error invoking [TheNameOfOneOfYourViews]. Check the inner error for details.` 

The inner details typically is not helpful, so from there my strategy is to breakpoint the code related to the view and look for errors and/or remove parts of the template's HTML until it starts to work. 

I have not been able to find what is swallowing the error.

**Comment by gheoan** [comment]
Hero is an example of this: https://gist.run/?id=921f733f75d7c0658ab1bdf0cf534858. `Router.prototype.generate` is eventually callled with undefined which throws [here](https://github.com/aurelia/router/blob/c45b91c4fdc03e1487d78609bd0546717120e36b/src/router.js#L224) but there is no error in console. I will send a PR that adds a `logger.error` call but I don't know if that is the most elegant solution.

**Comment by Alexander-Taran** [comment]
This is stale
Could not find a PR merged
for gist  https://gist.run/?id=e8e3c7fcc68957a9a11d24c4535f2c04 there is now an error log with stack and error message

I augmented said gist with another child and an expception thrown on deactivate() of first
https://gist.run/?id=cfd7bc9a2dafcdab7701632beb7e906b

error is also being logged

can be closed, I guess

**Comment by gheoan** [comment]
How about [this comment](https://github.com/aurelia/router/issues/352#issuecomment-319489299)? I never managed to assemble a fix. Should I open another issue?

**Comment by Alexander-Taran** [comment]
@gheoan did you have any progress?

**Comment by davismj** [comment]
@gheoan Please do, especially if you can show a more common use case example. I closed this since the original gist.run is now working properly.
