### ISSUE TITLE
Route not found not firing EventAggregator event error

### ISSUE THREAD

**Issue by talski** [aurelia/router#354]
Hello guys,
In the app that I've been developing I wanted to handle route not found, and redirect to home page, the default behaviour is to restore the previous location, but when I direct open a invalid link (http://localhost:3000/#/somewrongroute), I get this error:

```
aurelia-logging-console.js:54 ERROR [app-router] Error: Route not found: /somewrongroute
aurelia-logging-console.js:54 ERROR [app-router] Router navigation failed, and no previous location could be restored.
```
I've found that aurelia-router fire the following events in EventAggregator:

> router:navigation:processing
> router:navigation:error
> router:navigation:canceled
> router:navigation:success
> router:navigation:complete

So lets use the EventAggregator to solve my problem:

```javascript
eventAggregator.subscribe('router:navigation:error', response => {
  console.log('Route not found, redirecting to root');
  this.router.navigate('');
});
```

But seems that `Route not found` don't fire a `router:navigation:error` event, so, searching the source code I've found where this error was throwed and added the following code to workaround:

```javascript
// fire a event when a route is not found, so I can handle this error subscribing it
this.events.publish('router:navigation:error', url);
// aurelia-router/src/router.js, line 407
return Promise.reject(new Error(`Route not found: ${url}`));
```

Now, when a user open a page with wrong params, the page won't get stuck and we can go on, there is another way to get this result? Maybe this could be added to the project.

Another issue, I could not get the Router class inside my `main.ts`:

```javascript
const rootElem = document.body;
var authService = aurelia.container.get(AuthService);
// I have two aurelia shell's or root, one for login and one to app itself
var root = authService.isAuthenticated() ? 'app' : 'auth';
var eventAggregator = aurelia.container.get(EventAggregator);

// when I add the line bellow to be able to redirect to another route, my app won't boot up
var router = aurelia.container.get(Router);

eventAggregator.subscribe('router:navigation:error', response => {
  console.log('Route not found, redirecting to root');
  this.router.navigate('');
});

aurelia.start().then(() => aurelia.setRoot(root, rootElem));

//if I define aurelia-app in the index.html file, and remove the rootElem.setAttribute the app boot up but everything in the console get duplicated, like `INFO [aurelia] Aurelia Started`
rootElem.setAttribute('aurelia-app', '');
```

So I've injected the router and the eventAggregator into my app.ts and auth.ts to subscribe to the event, but this way I need to have the same code in two places, not the best approach. Any suggestion?

**Comment by StrahilKazlachev** [comment]
Why don't you use `mapUnknownRoutes` when configuring the router?

**Comment by talski** [comment]
Oh, thank you, it looks way better
