### ISSUE TITLE
Setting "routeConfig.nav = true" from within a route does not update the router view

### ISSUE THREAD

**Issue by vaags** [aurelia/router#355]
(I don't know if this really is an issue with the router. I might just be missing something, but couldn't find an answer to this anywhere.)

I have a router with some routes. One of the routes have its `nav` property set to `false`. This prevents the route from showing in my navigation-bar - as expected.

What I want to do is to make this route shown in the navbar whenever a user has navigated to it.

This should be possible to do (I think) by setting `routeConfig.nav = true` from the viewmodel of the route, inside its `activate` function.

When I do this, however, nothing changes in the navbar (probably because the route in question is not actually present in the DOM).

Do I have to pass some kind of "update"-function to the router make this change visible?

Another way to do this would be to omit the route initially (in `configureRouter`), and then add it "on demand", using `this.router.addRoute`.

This works, but it's also a much more "dirty" solution to my problem. I really just want to define all my routes in the router, and then change the `nav` property from within the route to make it visible.

**Comment by EisenbergEffect** [comment]
Usually, I would just make `nav: true` when you initially configure the route and then add a custom setting that you use to toggle its visibility.

**Comment by TylerBrinkley** [comment]
To get around this issue I manually pushed my NavModel into the router's navigation property and then assigned the router's navigation property to itself to initiate an update of the view.
