### ISSUE TITLE
Routing to an AMD module

### ISSUE THREAD

**Issue by AStoker** [aurelia/router#357]
### Help Wanted/Possible Issue
I have an Aurelia project that is currently in the process of upgrading a segment of the site from Durandal. In particular, I have a section where I have an Aurelia View/ViewModel routing to an AMD module using the `<router-view>` syntax. The AMD module is returning a function to keep with AMD spec, and right now is just returning an empty object: 
``` javascript
define([], function () {
    return function() {
        return { }
    }
});
```
This causes some strange issues with Core-JS trying to find `_iobject.html` (which doesn't exist, but `_iobject.js` does...). As I'm stepping through the code, it seems that the AMD module is evaluated to an empty object, and then starts having trouble because it's looking for constructor functions and the like.  
Is there some special code or specific way I need to try and route to an AMD module?

**Comment by EisenbergEffect** [comment]
Nothing special, no. Aurelia is usually used as AMD modules and I have plenty of projects set up to transpile to that format. Perhaps check with the CoreJS people to see if they have some thoughts on this. FYI Aurelia no longer needs CoreJS unless you are using special features not supported by our baseline.
