### ISSUE TITLE
Declare NavModel.router for TypeScript projects

### ISSUE THREAD

**Issue by Costo** [aurelia/router#359]
Hi,

I'm using a singleton view model inside a child router.  When the view model is instantiated, the wrong router is injected (it's the AppRouter instead of the child router).
One workaround I found is to get the router from `routeConfig.navModel.router` in the activate method.
However, the router property is not declared in TypeScript so I have to use a cast to `any`.

It is possible to add `NavModel.router`in TypeScript? 

See code sample below:  

```ts
@singleton()
@autoinject()
export class OrderList {
  orderService: OrderService;
  orders: Order[];
  router: Router;

  constructor(router: Router, orderService: OrderService) {
    this.orderService = orderService;
    //this.router = router; // <-- Not the router I want
    
  }

  activate(params: any, routeConfig: RouteConfig, navigationInstruction: NavigationInstruction): void {
      this.router = (routeConfig.navModel as any).router as Router; // This is the router I need
     
  }
}
```

**Comment by EisenbergEffect** [comment]
The reason for this is that you've made a singleton, which lives at the root container where the root router also lives, so the child router can't be injected (because it's not existing at that level of the DI).

I've added the router property to the nav model as requested.
