### ISSUE TITLE
Ensure rejected promise message from activation failure propagates properly

### ISSUE THREAD

**Issue by PWKad** [aurelia/router#36]
This enhancement is referenced from Durandal 2.1 issue -  https://github.com/BlueSpire/Durandal/issues/595#issuecomment-76047279

**Comment by devmondo** [comment]
!!First!! 
i really like ravendb docs style http://ravendb.net/docs/article-page/3.0/csharp/welcome
good parts
- you can choose a version and docs will reflect that
-the left navigation has collapsible sub topics

**Comment by jdanyow** [comment]
dupe of https://github.com/aurelia/router/issues/2

**Comment by EisenbergEffect** [comment]
This issue has been addresses via the duplicate.
