### ISSUE TITLE
child router not navigating correctly until another parent route has been visited

### ISSUE THREAD

**Issue by rekna1** [aurelia/router#361]
I created an application using the rc cli.

app.ts
```
import {RouterConfiguration, Router} from 'aurelia-router';

export class App {
  router:Router;
  configureRouter(config:RouterConfiguration, router:Router):void {
    this.router = router;  
    config.title='Aurelia';
    config.map([
      { route:['','klant'],name:'klant',moduleId:'klant',nav:true},
      { route:'klantcode',name:'klantcode',moduleId:'klantcode',nav:true}
    ]);
  }  
}
```
app.html
```
<template>
 
 <div>
   <h1>App</h1>
   <a route-href="route:klant">Klant</a> |
   <a route-href="route:klantcode">KlantCode</a>
 </div>

 <router-view></router-view>
 
</template>
```
klant.ts
```
import {RouterConfiguration,Router} from 'aurelia-router';

export class Klant {
    message="This is klant";
    router:Router;
    configureRouter=(config:RouterConfiguration,router:Router)=>{
        config.map([
            {route:['','selectklant'],name:'selectklant',moduleId:'klant/selectklant',nav:true},
            {route:'deploymentsforklant',name:'deploymentsforklant',moduleId:'klant/deploymentsforklant',nav:true}
        ]);
        this.router = router;
    }
}
```
klant.html
```
<template>
    <p>klanttemplate : ${message}</p>

    <a route-href="route:selectklant">select klant</a> |
    <a route-href="route:deploymentsforklant">deployments for klant</a>

    <router-view></router-view>
</template>
```
deploymentsforklant.ts
```
export class DeploymentsForKlant {
    
}
```

deploymentsforklant.html
```
<template>
    <h2>deployments for klant</h2>
</template>
```
selectklant.html and selectklant.ts are just like deploymentsforklant, simple template, class with no code.

When I start the application, you get as expected:

> App
> **Klant** | **KlantCode**
> klanttemplate : This is klant
> **select klant** | **deployments for klant**
> Select klant

When i click on the link "deployments for klant" I get an error 
Error : Route not found: /deploymentsforklant

If however I first navigate to "KlantCode" then back to "Klant" and the to "deployments for klant" I do not get an error and routing works as expected...

So what is wrong with this code ?

update :
1. tried redirect '' to 'klant' but then get an warning about promise being rejected with a non-error, not sure what it means, and if it matters.
2. I can make it work (more or less) when I add another view, say klantindex, which I define as the default route (['','klantindex']) and klantindex.html does not contain a router-view. Then when navigating to other routes, I don't get any errors.

**Comment by EisenbergEffect** [comment]
The issue is child route navigation from parent default, empty routes. We have this tracked in another issue. A cleaner way to handle this would be to make the empty route redirect to the patterned route. That will fix your problem.

```
{ route:'', redirect:'klant'},
{ route:'klant', name:'klant',moduleId:'klant',nav:true},
{ route:'klantcode',name:'klantcode',moduleId:'klantcode',nav:true}
```

**Comment by chrisprobst** [comment]
@rekna1 I had the same issue, I succeeded by removing nav: true, I also have no clue what these mean. The doc is pretty thin about that.

**Comment by MOHAN-T** [comment]
Actually I am facing the similar issue, 
Ex : I have parent page which has records list and i have child route for the same parent to display the details of parent record. The child route doesn't have any models but from html it invoke multiple view-models through compose, but in this case without revisiting parent route if i tried to revisit the child with diff parameters it is not invoking the life cycles of the respected view-models.

**Comment by bigopon** [comment]
@MOHAN-T I think you can use `determineActivationStrategy` hooks on child view model to always invoke lifecycle, or replace it entirely every time. https://aurelia.io/docs/routing/configuration#reusing-an-existing-view-model

Did you try that?

**Comment by MOHAN-T** [comment]
Yes, I have tried that also, still no change. As I see this, it's issue in routing itself, because i checked the same scenario in angular it works as expected. So do you have any other choices or anyone has ans, I would really appreciate.

**Comment by bigopon** [comment]
I think I misunderstood you. Is the following template close to what you are having:

```html
<!-- this is the child view of router -->
<template>
  <compose view-model.bind="vm1"></compose>
  <compose view-model.bind="vm2"></compose>
  <compose view-model.bind="vm3"></compose>
</template>
```

When you change the selected record in parent, you want all existing `<compose/>` to reevaluate?

If it's hard to explain, can you give an reproduction based on this template https://codesandbox.io/s/y41qjr36j

**Comment by MOHAN-T** [comment]
yes that is exactly what i want, because i have written db calls in activate method but that method is not at all invoking. if u could be helpful to resolve this, it will be a great help

**Comment by davismj** [comment]
In order to get the activate() methods to fire on `vm1`, etc., you need to add a model binding that updates:

`<compose view-model.bind="vm1" model.bind="data1"></compose>`

Lets say you have this:

```
export class VM1 {
  activate() { 
    this.loadDataFromTheDatabase();
  }
}
```

The best thing to do is pass in some or all of the data from the parent vm through the activate function.

```
<compose view-model.bind="vm1" model.bind="{ data: someData }"></compose>
```
 
```
export class VM1 {
  activate({ data }) {
    this.data = data; 
    this.loadDataFromTheDatabase();
  }
}
```

If you don't have any data to pass in, then pass the parameter of your route in. This parameter will update every time you navigate to a new route, so it will force the compose elements to update as well.

```
<compose view-model.bind="vm1" model.bind="routeParams"></compose>
```

**Comment by MOHAN-T** [comment]
I tried, but this doesn't work. Any other options?

**Comment by davismj** [comment]
The problem is somewhere else. Try reaching out to support@aurelia.io to get more specific and direct help on your individual project.

**Comment by MOHAN-T** [comment]
Actually the problem was for empty route, instead of modelId, I used Viewport: {default: {modelId: null}} once i changed this to a dummy empty view-model it started working. So I think is the reason or else it may be because of other issue altogether i don't know.

Anyway thanks bigopon and davismj. U guys have been very helpful.
