### ISSUE TITLE
Strange Rendering Behavior since 1.1.4 release

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/router#365]
@devteamexpress commented on [Sun Mar 13 2016](https://github.com/aurelia/templating/issues/294)

I understand as part of the new aurelia release there was some work done on minimizing the visual popping

We have code which looks like this
    <i show.bind = "router.isNavigating"  class="fa fa-spinner fa-spin"></i>
    <div show.bind = "router.isnavigating"></div>

This has served us well in the past. Now we are experiencing that when the router.isNavigating becomes false meaning the view is shown it's the old view and it takes a noticeable amount of time till the new view comes into play. Is this a bug or is their a different way to code to support the scenario?

---

@EisenbergEffect commented on [Sun Mar 13 2016](https://github.com/aurelia/templating/issues/294#issuecomment-195999478)

I can't see your code, but first please run `jspm update` to make sure you have the latest. There were a few fixes in that area. If that doesn't fix the problem, then we will need you to create a simple reproduction on the skeleton repo and attach it here so we can run it, see the problem and identify a fix.

---

@devteamexpress commented on [Sun Mar 13 2016](https://github.com/aurelia/templating/issues/294#issuecomment-196028628)

I only ran the jspm update today so unless there were releases since then its still broken. I guess I will need to roll back till this is resolved since this is rather noticeable.

---

@EisenbergEffect commented on [Sun Mar 13 2016](https://github.com/aurelia/templating/issues/294#issuecomment-196046314)

It won't get fixed unless you can provide a repro. We need that to see the bug in action and track down the cause. If you can put that together, I can take a look at it myself early this week.

---

@devteamexpress commented on [Mon Mar 14 2016](https://github.com/aurelia/templating/issues/294#issuecomment-196141731)

I will try to get this to you this morning. If this helps it seems to happen whenever i navigate to a view which contains a compose element in which the acitvate function of that compose element returns a promise. 

---

@devteamexpress commented on [Mon Mar 14 2016](https://github.com/aurelia/templating/issues/294#issuecomment-196170823)

I got it to happen

Basically i moved all the code from the users page into another view called additionalview and just used a component element instead. I added a promise delay to simulate a call.

If you start on the welcome page and switch to the users page you will see the loading sign comes on but when it finishes it first shows the welcome page again and then jumps to the user page. 

https://github.com/GrocerKey/skeleton-navigation

Meanwhile I have rolled back our code base. Please let us know when you have more information.

Thanks

---

@devteamexpress commented on [Tue Mar 15 2016](https://github.com/aurelia/templating/issues/294#issuecomment-197009698)

Any update on this?

---

@devteamexpress commented on [Wed Apr 13 2016](https://github.com/aurelia/templating/issues/294#issuecomment-209221686)

Anything guys over here? Still waiting to upgrade

---

@devteamexpress commented on [Wed Apr 20 2016](https://github.com/aurelia/templating/issues/294#issuecomment-212583155)

So after playing around with it a bit more this is what i find- the parent viewmodel waits for all composed elements to activate before rendering , but the router doesn't respect that and only waits for the parent viewmodel to activate. So as soon as the viewmodel activates the router shows the screen but since the children haven't activated yet the new view hasn't rendered
does this make any sense to anybody

---

@EisenbergEffect commented on [Wed Apr 20 2016](https://github.com/aurelia/templating/issues/294#issuecomment-212604405)

This is odd. It seems like you've got a mixture of new and old stuff happening. I'll take a look atyour example above shortly and see if we can get to the bottom of this.

---

@devteamexpress commented on [Wed Apr 20 2016](https://github.com/aurelia/templating/issues/294#issuecomment-212723244)

It seems to be related to a composition transaction. If a view has a
compose tag within it where the compose tags activate function takes time .
The router navigation complete event will not wait till all compose tags
activate. Using router.isNavigating doesn't work in this scenario because
it becomes false right away, but the view only actually shows up  once all
compose tags have activated.

I have tried on the latest aurelia and will provide a screen cast of the
issue shortly
On Apr 21, 2016 00:01, "Rob Eisenberg" notifications@github.com wrote:

This is odd. It seems like you've got a mixture of new and old stuff
happening. I'll take a look atyour example above shortly and see if we can
get to the bottom of this.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
https://github.com/aurelia/templating/issues/294#issuecomment-212604405

---

@devteamexpress commented on [Wed Apr 20 2016](https://github.com/aurelia/templating/issues/294#issuecomment-212726673)

Here is a screencast of what happens

https://temp-temp-grocerkey.s3.amazonaws.com/Untitled%20Screencast%20%281%29.webm

---

@EisenbergEffect commented on [Thu Apr 21 2016](https://github.com/aurelia/templating/issues/294#issuecomment-213130950)

Ok, the issue is coming from the fact that the router.isNavigating is changing to false before the actual view has been swapped. The router is done with it's work but I think we aren't aggregating all the way through to the end of the view swap and its animation. @bryanrsmith Is there a way we can easily fix this?

---

@bryanrsmith commented on [Tue Apr 26 2016](https://github.com/aurelia/templating/issues/294#issuecomment-214625551)

@EisenbergEffect Sorry, I don't know how the animation is set up. Looks like the router runs the swap as part of the last pipeline step here: https://github.com/aurelia/router/blob/master/src/navigation-instruction.js#L215. `isNavigating` is updated after that step completes. Does `viewPort.swap()` kick off async work that should delay the completion of the pipeline? If so we can probably just `Promise.all()` the swap promises.

---

@EisenbergEffect commented on [Wed Apr 27 2016](https://github.com/aurelia/templating/issues/294#issuecomment-215122404)

We could fix up the swap an process methods of the router-view to return a promise. @bryanrsmith If we did that would it be an easy fix on your end to just drop a Promise.all? That should delay the update to the isNavigating flag, correct?

---

@bryanrsmith commented on [Wed Apr 27 2016](https://github.com/aurelia/templating/issues/294#issuecomment-215301357)

Yep

---

@EisenbergEffect commented on [Thu Apr 28 2016](https://github.com/aurelia/templating/issues/294#issuecomment-215464542)

Ok, i'll make some of the fixes in the templating-router piece and then ping you here so you can fix up the router itself.

---

@devteamexpress commented on [Wed May 25 2016](https://github.com/aurelia/templating/issues/294#issuecomment-221468909)

Is their any update here. We received a report that this bug is always happening on the iphone. 

---

@EisenbergEffect commented on [Wed May 25 2016](https://github.com/aurelia/templating/issues/294#issuecomment-221539699)

The issue hasn't been fixed yet but we believe we have a way to do it. It should be fixable for the Release Candidate.

**Comment by devteamexpress** [comment]
Is their an update here?

**Comment by devenson** [comment]
Was this ever fixed? We cannot rely on router.isNavigating reliably at this point.

**Comment by meash-nrel** [comment]
marked enhancement, seems like it should be bug as this worked before

**Comment by Alexander-Taran** [comment]
stale since 2016

**Comment by EisenbergEffect** [comment]
I think we fixed this via router updates as part of the SSR work. I haven't seen any issues like this since then.
