### ISSUE TITLE
Better error message for Invalid route config

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/router#370]
```
ERROR [app-router] Error: Invalid route config: dynamic routes must specify an href to be included in the navigation model.
```

I can't know which route config is wrong. Could you show a better error message?

Could _route_ or _name_ in the config be printed?

**Comment by EisenbergEffect** [comment]
Sounds like a good opportunity for a PR.

**Comment by HIRANO-Satoshi** [comment]
No problem. I did.

**Comment by Alexander-Taran** [comment]
@HIRANO-Satoshi can you close the issue?

**Comment by HIRANO-Satoshi** [comment]
Sure. Thanks.
