### ISSUE TITLE
Child router doesn't navigate

### ISSUE THREAD

**Issue by hadrienl** [aurelia/router#372]
Hi,

I have a root router in app.js with this config:

```
config.map([{
      route: '/',
      name: 'connect',
      moduleId: 'connect/connect'
    }, {
      route: '/not-allowed',
      name: 'not-allowed',
      moduleId: 'main/not-allowed'
    }]);
```

In connect.js I have this config:

```
config.map([{
      route: '/',
      name: 'connect-list',
      moduleId: './list'
    }, {
      route: '/connect/:app',
      name: 'connect-app',
      moduleId: './connect-app'
    }]);
```

I can navigate to / and /not-allowed, views are correctly displayed but when I try to navigate to /connect/something I can see the url in browser flashing by going to /connect/something and going back to / very quickly, and never display the correct view. I can't see nothing in console and if I subscribe to router events, it tells that everything is alright.
I have the same issue with a child route without parameter.

**Comment by EisenbergEffect** [comment]
This issue has already been reported. There's a problem with child routes attached to "emtpy" parent routes. To work around it, you should have your root `/` route redirect to a route with a fragment. Just create another route and then have the empty route add a `redirect` property that points to the non-empty route.

**Comment by smithaitufe** [comment]
@eisenbergeffect 

Do you mean something like this

```
configureRouter(config){
  config.map([
{ route: '', moduleId: './public-section'}
])
}
```

then in public-section viewmodel we can have

```
configureRouter(config){
   config.map([ {route: '', redirect: 'home'}, { route: ['','home'], name: 'home', moduleId: './home'} ])
}
```
