### ISSUE TITLE
Add TypeScript ViewModel Interface

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/router#375]
@TylerBrinkley commented on [Fri Jul 22 2016](https://github.com/aurelia/framework/issues/481)

It would be nice if a TypeScript ViewModel interface was added for better visibility of available features. It might look something like the below. There's probably more methods that could be specified but I just haven't discovered them yet which would just show the utility of adding this.

    export interface ViewModel {
        activate?(): void;
        canActivate?(): boolean|Promise<boolean>;
        deactivate?(): void;
        canDeactivate?(): boolean|Promise<boolean>;
    }

---

@EisenbergEffect commented on [Fri Jul 22 2016](https://github.com/aurelia/framework/issues/481#issuecomment-234561320)

This is specifically related to the Router, so I'm moving it there. I'm not entirely sure the benefit since it wouldn't affect the runtime at all and it would force a deeper dependence in your code on our framework by making you implement the interface. I'd favor someone just creating it in their own project if they want.

**Comment by TylerBrinkley** [comment]
Thanks Rob, obviously all methods defined in the interface would be optional which means users wouldn't need to implement the interface explicitly but it might help them to better discover what features are available to them. Are there more than just these 4 methods that a ViewModel can implement?

**Comment by AshleyGrant** [comment]
Over in NG2 world, they do stuff like this. I've been thinking it wouldn't hurt to have this, as long as the framework doesn't require a user to implement this interface and it just serves as a reminder.

Here's the docs form ng2: https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html their interfaces are optional, and I actually prefer the strategy @TylerBrinkley is suggesting.

Maybe the name of the interface could be different `Routable` or `RoutableComponent` or something?

**Comment by EisenbergEffect** [comment]
`RoutableComponent` I think would be the name. If someone wants to submit the PR to router, that would be great. Perhaps a similar interface `Component` should be added to templating. I'd accept a PR for that as well.

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect Do you consider:
- `determineActivationStrategy()` part of `RoutableComponent` ?
- `RoutableComponent` extends `Component` ?

**Comment by EisenbergEffect** [comment]
No way to extend from Component because that is part of templating and router has no hard dependency on that. So, they should be independent.

You can include `determineActivationStrategy()` as well as `getViewStrategy()` as part of `RoutableComponent`

**Comment by atsu85** [comment]
I've created my own interfaces for TypeScript, but I've taken slightly different approach. I created one interface for each method (instead of single interface for all optional methods) so that when i add the interface to the class, then TypeScript compiler actually checks the correctness of the method signature as well.

**Comment by StrahilKazlachev** [comment]
@atsu85 Could you look at the PR and tell me what you think? I don't mind splitting the interface.

**Comment by atsu85** [comment]
I've commented @StrahilKazlachev's [PR](https://github.com/aurelia/router/pull/376#issuecomment-234718035) and added gist to my solution

**Comment by EisenbergEffect** [comment]
Done
