### ISSUE TITLE
Load route viewModel module from external location or via alternative resolve strategy

### ISSUE THREAD

**Issue by kristianmandrup** [aurelia/router#379]
Currently the Router only seems to support loading a ViewModel module for a route given a moduleId which is resolved relative to `/src` in the main project, ie. via `moduleRoot` config. 

`moduleRoot: path.resolve('src').replace(/\\/g, '/'),`

Would be awesome if the module could also be resolved using normal module resolution strategies, such that we can split up an application in a modular fashion per main route, much like Rails engines. Perhaps just by adding an overridable `moduleResolveStrategy` function?

I guess a workaround (and more scalable solution) would be to use the nested Routers concept and simply attach a sub-router from an external (engine) module ;)

I see that the `moduleRoot` is defined in the router but not used here. 
I've since  found that it is resolved in the [route-loader](https://github.com/aurelia/templating-router/blob/master/src/route-loader.js)

So I guess anyone could just replace the route loader with a custom implementation of `loadRoute(router, config)` for now

**Comment by kristianmandrup** [comment]
Made a [PR](https://github.com/aurelia/templating-router/pull/35) for this change 

```js
@inject(CompositionEngine)
export class TemplatingRouteLoader extends RouteLoader {
  constructor(compositionEngine) {
    super();
    this.compositionEngine = compositionEngine;
  }

  viewModelLocation(router, config) {
    return relativeToFile(config.moduleId, Origin.get(router.container.viewModel.constructor).moduleId);
  }

  loadRoute(router, config) {
    let childContainer = router.container.createChild();
    let instruction = {
      viewModel: this.viewModelLocation(router, config),
      // ...
```

**Comment by EisenbergEffect** [comment]
The router should be resolving modules relative to the router, not src. What build system are you using?

**Comment by kristianmandrup** [comment]
Yeah, whatever, `src` or relative to router. The question is whether it can be made relative to something else?

**Comment by EisenbergEffect** [comment]
Gotcha. I'll review the PR. Thank you!

**Comment by kristianmandrup** [comment]
Thanks. Basically, the current way that routing works is "mysterious", ie. not very well documented.  Also going beyond the default Routing strategy... such as this section on the [hub](http://aurelia.io/hub.html#/doc/article/aurelia/router/latest/router-configuration/3)

How can I access the location of the project root, so as to calculate a file location relative to there?

**Comment by kristianmandrup** [comment]
I suggest the ability to attach a a module resolution strategy on the router itself as perhaps a more sensible approach:

```
  viewModelLocation(router, config) {
     router.findViewModelLocation ? router.findViewModelLocation(config) || relativeToFile(config.moduleId, Origin.get(router.container.viewModel.constructor).moduleId);
  }
```

But then I think it would be much better like:

```
  viewModelLocation(router, config) {
     router.findViewModelLocation(config);
  }

// Router.js

class Router { 
  // ...

  findViewModelLocation(config) {
    return relativeToFile(config.moduleId,   Origin.get(router.container.viewModel.constructor).moduleId);
}
```

Which also makes it "clear" that view models are resolved relative to the router.

**Comment by kristianmandrup** [comment]
I believe the above is a much more sensible approach. I have made changes and PRs in both `router` and `template-routing`. Not sure how I go about building the `dist` folders as part of PR and testing...

**Comment by kristianmandrup** [comment]
This PR is in preparation for an easier way to structure an app into truly independent, reusable modular components instead of having a monolithic app, important for scaling the size of an app.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect added to vNext router use cases
Can be closed
