### ISSUE TITLE
"Customizing the Navigation Pipeline" Documentation source code is broken.

### ISSUE THREAD

**Issue by Awaken6389** [aurelia/router#38]
Installed the Aurelia according to instructions, copied the code from the documentation and get 

	index.js:174 Uncaught TypeError: undefined is not a function

**Comment by EisenbergEffect** [comment]
I think you might have an older version of the router. Try `jspm update aurelia-router` and see if that makes a difference. Also, I'll be making sure everything is all up to date for the next release.
