### ISSUE TITLE
Support external routes in router configuration

### ISSUE THREAD

**Issue by mohsenasfia** [aurelia/router#380]
**I'm submitting a feature request**

When building an app that links to external/legacy pages, it would be really handy if the URL's for those external pages could be configured and generated the same way as the app routes.

Example:

``` typescript
public configureRouter(config: RouterConfiguration, router: AppRouter): void
{
    config.options.pushState = true;
    config.map(
    [
        { route: "/", name: "home", moduleId: "./home", nav: true, title: "Home" },

        // External route
        { route: "http://other-domain.com/:some-parameter", name: "external", title: "External", nav: true }
    ]);
}
```

The idea is, that routes starting with `http://` or `https://` would be used as-is, without prepending the base URL of the app. When navigating to the route, the browser location should just be set, instead of replaced, thus navigating out of the app. The `route-href` attribute would also need to be aware of this, so it sets the correct value for `href`.

The reason it would be nice to have it as part of the router configuration, is that it would allow us to generate navigation links, and have the external routes mixed in between the app routes. It would also allow us to generate those external URL's, with parameters, based on the route name, thus keeping the route definitions in one place.

Thoughts?

**Comment by mohsenasfia** [comment]
Conceptually, this seems to be the changes needed to make this work:

`RouteRecognizer.prototype.add`
Should not recognize the first ":" as an `EpsilonSegment` if the path starts with "http" or "https".

`RouteRecognizer.prototype.generate`
Should be changed such that 
```typescript
if (output.charAt(0) !== '/') {`
```
Becomes
```typescript
if (output.charAt(0) !== '/' && !output.startsWith("http:") && !output.startsWith("https:")) {
```

`Router.prototype.generate`
Should be changed such that
```typescript
var rootedPath = _createRootedPath(path, this.baseUrl, this.history._hasPushState, options.absolute);
return options.absolute ? '' + this.history.getAbsoluteRoot() + rootedPath : rootedPath;
```
Becomes
```typescript
if (!output.startsWith("http:") && !output.startsWith("https:"))
{
    var rootedPath = _createRootedPath(path, this.baseUrl, this.history._hasPushState, options.absolute);
    return options.absolute ? '' + this.history.getAbsoluteRoot() + rootedPath : rootedPath;
}
else
{
    return path;
}
```
Finally, it should be allowed to define routes without a `moduleId`, `redirect` or `navigationStrategy`, like:
```typescript
{ route: "http://other-domain.com/:some-parameter", name: "external", title: "External" }
```

**Comment by mohsenasfia** [comment]
It looks like Aurelia can also be monkey-patched to support this with the code:
```typescript
let generate = router.generate;
router.generate = (...args) =>
{
    return generate.apply(router, args).replace("/http:/", "http://");
};
```
And route definitions written as:
```typescript
{ route: "http://other-domain.com/:some-parameter", name: "external", title: "External", navigationStrategy: () => undefined }
```

**Comment by mohsenasfia** [comment]
Actually, it should probably also support routes defined as:
```typescript
{ route: "//other-domain.com/:some-parameter", name: "external", title: "External" }
```

**Comment by egeland** [comment]
I swear I had a route to a _absolute_ URL working before, which is somewhat related to this.

The code I thought was working:
`{ route: 'bloglink', redirect: '/blog', href: '/blog', nav: true, title: 'Blog' }`

But this sends me to `/#/blog` instead of `/blog` :crying_cat_face: 

Any ideas, anyone?

**Comment by AStoker** [comment]
Any progress on this?

**Comment by sday** [comment]
Is this possible yet?

**Comment by diegohb** [comment]
is this still being worked on ? any alternative way to accomplish other than window.location ?

**Comment by AStoker** [comment]
I'm not aware of anyone actively working on this (doesn't mean there isn't somebody in the shadows doing it though). Would love it if someone from the community would help out with this feature!

**Comment by ordinaryorange** [comment]
I just tried this in one of the skeletons. I added a `route: 'http://www.somedomain.com'` and it worked. So I assume it has been patched in ?

**Comment by smoore4moma** [comment]
I can confirm that @mohsenasfia solution below works. It lacks the ability to set the target to _blank (true?) but otherwise works well.

{ route: "http://other-domain.com", name: "external", title: "External", navigationStrategy: () => undefined }

**Comment by Alexander-Taran** [comment]
I'd love to see how you guys use it.
Because from where I'm standing I don't see the use case for having a route for external link
might as well be href.bind="http://domain/path/${param1}/path/${param2}"
It will also be clearer for those who will read this, that the link is external

Would love to know what am I missing

**Comment by davismj** [comment]
As OP stated, it is a feature for those relying on the nav model.

**Comment by smoore4moma** [comment]
The use case for an external route: a menu.  The second link here is an external url so the route nav is defined like this:
```

      { route: ['','home'], moduleId: 'routes/home', title: 'Home', nav: true, name:'home', settings:{ glyph: 'fa fa-home fa-fw' }},
      { route: 'search', moduleId: 'routes/search', title: 'Search', name:'search', settings:{ glyph: 'fa fa-search fa-fw' }},
      { route: 'https://www.moma.org/.../archives-contact', name: 'contact', title: 'Contact', nav: true, navigationStrategy: () => undefined, settings:{ glyph: 'fa fa-envelope fa-fw' }},
      { route: 'help', moduleId: 'routes/help', title: 'Help', nav: true, settings:{ glyph: 'fa fa-question-circle fa-fw' }},
      { route: 'list', moduleId: 'routes/list', title: 'List', name: 'list', settings:{ }},
```
etc...

![image](https://user-images.githubusercontent.com/4989910/37475658-96a7d7d4-2849-11e8-9dab-b1d64c5495af.png)

**Comment by davismj** [comment]
While I understand people like the nav model and I'd like to look at making it more robust in the future, my current recommendation is that when you get to this level of complexity, don't rely on the nav model.

**Comment by Alexander-Taran** [comment]
@smoore4moma sorry, I missed that about nav model

**Comment by chethandb** [comment]
> Actually, it should probably also support routes defined as:
> 
> ```ts
> { route: "//other-domain.com/:some-parameter", name: "external", title: "External" }
> ```

Is this still possible to declare the one as mentioned above? I just tried having a route to localhost and it error-ed.
