### ISSUE TITLE
router isActive property not correct

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/router#383]
**I'm submitting a bug report**
- **Library Version:**
  major.minor.patch-pre1.0.2
- **Node Version:**
  4.4.7
- **NPM Version:**
  3.10.3
- **JSPM OR Webpack AND Version**
  webpack 
- **Language:**
  TypeScript 

**Current behavior:**
Using the typescript-webpack skeleton.

When programmatically routing to a route using `me.router.navigateToRoute('community');`, for a route defined like so:
`{ 
        route: 'community',   
        name: 'community',  
        moduleId: './community',  
        nav: true,      
        className: 'ico-users',   
        title: this.i18n.tr('router.nav.community') 
      },
`

the 'isActive' property in the navModel object does not seem to be set properly; it is not set to active as expected.  In the Chrome debugger, I see this:

`navigationInstruction:Object

**observers**:Object

className:"ico-users"

get className:()

set className:()

moduleId:"./community"

name:"community"

nav:true

navModel:NavModel

**observers**:Object

config:(...)

get config:()

set config:()

href:(...)

get href:()

set href:()

isActive:false

get isActive:()

set isActive:()

order:104

relativeHref:"community"`

Notice that the navModel's 'isActive' property is showing the value false, after we have navigated to this route.

**Expected/desired behavior:**

The navModel's 'isActive' property should be true if we have navigated to the associated route.
- **What is the motivation / use case for changing the behavior?**

I am using the skeleton, and the nav-bar.html has this code, which relies on the 'isActive' property:

`<li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">`

This code is not functioning properly due to this bug.

**Comment by EisenbergEffect** [comment]
Can you create a gist.run demo of this? or a basic cli project that you can upload here where we can see the behavior. We haven't observed this happening elsewhere.

**Comment by mslonina** [comment]
Hi,

I'm struggling as well with this bug. In my application I have to create some routes dynamically using `router.addRoute()`, i.e.:

```
this.router.addRoute(
          {   
            route: item.id,
            moduleId: "views/item-dashboard",
            href: '#/item/' + item.id + '/dashboard',
            generationUsesHref: true,
            name: item.id,
            nav: true,
            auth: true,
            title: item.id,
            settings: {
              subtitle: "Overview of the item",
              icon: "fa fa-circle-o",
              type: 'item',
              item: item 
            }   
          }   
        );  

this.router.refreshNavigation();
```

When the route is defined normally, without `href`, the `isActive` works as expected.

I'm using aurelia-router 1.0.0-beta.2.0.0, since I cannot upgrade right now...

**Comment by mslonina** [comment]
I found that in my setup, the `isActive` works, however, on the other route - I have a route config as follows:

```
{   
          route: 'item/:id/dashboard',
          moduleId: "views/item-dashboard",
          name: "item",
          nav: false,
          auth: false,
          title: "Item dashboard",
          settings: {
              subtitle: "Overview of the item",
              icon: "fa fa-server"
          }   
        }  
```

which is loaded **before** the dynamic routes, and it is not included in the nav. Once the item route is loaded, i.e. by going to `item/1234`, the route `item/:id/dashboard` is set active, and not the item route that is specified dynamically. 

How to make the opposite, so that, the dynamic route is made active instead of the pattern-like route shown above (kind of `isActive` override)?

**Comment by davismj** [comment]
@don-bluelinegrid Is the route you're navigating to one that you've added dynamically as well?

**Comment by diegogarcia28** [comment]
Same problem here and the route i'm navigating to is not dinamically added.

**Comment by don-bluelinegrid** [comment]
> @don-bluelinegrid Is the route you're navigating to one that you've added dynamically as well?

No, it is a standard route, constructed in the Router config object.

**Comment by davismj** [comment]
A gist.run or sample repo would be really helpful, and I can take a look and see what's up.

**Comment by Steffeng87** [comment]
I have an issue with the isActive property.

I have a route like this:
`route: 'category/:title'`

I then have five more routes with the same route property, but with href set (to set a title) and nav: true.

When i am on any of these pages the router always says the last in the route table is active no matter which of the pages I am on.
Not sure which router version I am on, jspm folder says 1.0.6 but in my package.json i specified 1.1.0

**Comment by AustinBrunkhorst** [comment]
I am also experiencing this issue, specifically in any routes that are not in the root navigation model.

I (painfully) created a Gist.Run using @jagonalez recursive menu example that can be found below

**Gist.Run**
https://gist.run/?id=766b653db2020b300c9b62524940972e

**Original GitHub Repo**
https://github.com/jagonalez/aurelia-menu/

It demonstrates the issue pretty clearly - only the root `Router`'s `NavModel`'s have `isActive` assigned. I have been trying to solve this issue using the default navigation model stuff for a few days now. I'm still new to Aurelia, but it looks like when navigating, the root most module is resolved and the child modules are automagically handled from there, without recursively setting `isActive` at each children's `NavModel`.

**Comment by jagonalez** [comment]
@AustinBrunkhorst if you add an activate method within one of the child router's viewModels, isActive is set to true on the navModel. It's just not updating on the view. I'll need to take a look and try to fix it in the demo.

**Comment by gheoan** [comment]
@Steffeng87 your comment describes https://github.com/aurelia/router/issues/433.

Other then that, there are not enough details to reproduce this.

**Comment by davismj** [comment]
The original issue was that programatically navigating to a route does not update the isActive property. Here is a gist demonstrating that this is no longer a problem: https://gist.run/?id=2da65567f2df138c8cd626a7895d675c
