### ISSUE TITLE
Router goes into endless redirection loop when navigating to a page containing a react-router element

### ISSUE THREAD

**Issue by Zensavona** [aurelia/router#388]
**I'm submitting a bug report**

* **Library Version:**
1.0.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.4

* **Node Version:**
5.6.0

* **NPM Version:**
3.6.0

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.20

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
I have a route pointing to a page which has an embedded react router component, which should then handle further routing. For example `aurelia-router` knows about the route `/users` which is declared in the top level router, but then `react-router` knows about `/users/:id` and `/users/new`. I had this working fine in my application until upgrading to `1.0.0` (all my aurelia-* libraries, IIRC we were at beta-x at the time it last worked as expected).

What's happening is that when I navigate to this route (e.g. `/users`) and try to navigate to one of the sub-routes which are handled with `react-router`, `aurelia-router` navigates me back and I see an error like this:

```
aurelia-logging-console.js:54 ERROR [app-router] Error: Route not found: /users/new at AppRouter._createNavigationInstruction
```

FWIW I am using a strategy of having an empty VM at `/users` with a html file that just requires from a jsx file containing my react component.

**Expected/desired behavior:**
The router shouldn't care what happens after it's last known route is reached. If there is no router present in the child VM, then it should be free to navigate as it pleases.

Any thoughts on a way to better architect this or a switch I am unaware of to turn this aggressive behaviour off is more than welcome :)

**Comment by EisenbergEffect** [comment]
Your probably want to use a wildcard route pattern for aurelia's router. Have you tried that?
