### ISSUE TITLE
Feature request: open in new tab

### ISSUE THREAD

**Issue by jods4** [aurelia/router#389]
**I'm submitting a feature request**

**Expected/desired behavior:**
It would be nice if we could pass `router.navigate` an option to navigate to a new tab.
Maybe like so: `router.navigate('url', { target: '_blank' })`

**What is the motivation / use case for changing the behavior?**
I would like to support Ctrl+Click on data table rows to open details.
Because they are `<tr>` I can't use a regular `<a>` which would work fine.
Instead, I have to use a `click` event, which calls into `router.navigateToRoute()`.
This is working fine, but users are unable to do Ctrl+click to open details in a new tab, which is bad.

My thinking was that I could check the click event to see if Ctrl key is pressed and call pass an option accordingly to `router.navigate`. Don't know if there is another way to achieve that.

**Comment by BBosman** [comment]
Maybe you can use `router.generate()` combined with `window.open()` to achieve that behaviour?

**Comment by jods4** [comment]
Yes, this can be worked around rather easily. I just felt it would fit nicely into the router API.

**Comment by EisenbergEffect** [comment]
Trying to keep the codebase small by not adding too many features, especially those that can be handled by combining exsiting apis. Closing this for now in favor of using the solutoin that @BBosman suggests.
