### ISSUE TITLE
Ability to create a multi-tab interface, with multiple views open at the same time. 

### ISSUE THREAD

**Issue by BringerOD** [aurelia/router#391]
I believe this has been discussed before, to some degree.  I believe I could pull this off if I used components and show and hide them, but this does not affect the browser history.  

Here is a basically what we are looking for.

![new mockup 4](https://cloud.githubusercontent.com/assets/7971305/17781799/a4585252-6525-11e6-9565-dd70489bbf78.png)

Each tab is a view and each view is loaded and active.  When the user closes the tab by clicking on the [x] the view is then destroy and removed.  Also,  a single view can be loaded multiple times with a different variable, or id.  Think multiple documents of the same type.

After reading it seems the only way to accomplish this is to create your own router.  Although I am not new to Aurelia,  I am not confident enough to create my own router.

Is this a feature others are looking for?

Does anyone know how to accomplish this?

**Comment by PWKad** [comment]
This isn't really an issue so it needs to be closed but if you wanted to accomplish this some pseudo code -

tabbed-example.js
```
import {Router, RouterConfiguration} from 'aurelia-router'
export class TabbedExample {
  router;
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.map([
      { route: ['', 'tabOne'], name: 'tabOne',      moduleId: 'tabOne',      nav: true, title: 'One' },
      { route: 'tabTwo',         name: 'tabTwo',        moduleId: 'tabTwo',        nav: true, title: 'Two' }
    ]);
    this.router = router;
  }
}
```

tabbed-example.html
```
<template>
  <ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="#">Home</a></li>
    <li role="presentation"><a href="#">Profile</a></li>
    <li role="presentation"><a href="#">Messages</a></li>
  </ul>
    <router-view></router-view>
</template>
```

**Comment by BringerOD** [comment]
Thanks!

**Comment by BringerOD** [comment]
> Patrick Walters @PWKad 09:34
Take a look at routing configuration which shows you how to set up parameters. Your route can pass these parameters in to the view-model which can decide on what to show or hide (or remove completely) without relying on the router to do it for you.
Then your behaviors (such as the x button on the tab) would just need to make sure the route updates and you have the ability to use the back button to control the behavior of your application.
If you get to the point where you have a bunch of parameters being passed in I would look at serializing those to something else though instead of having too many in the URL, have something that decodes back down to JSON perhaps

I will give this a shot.  Thanks for your help!
