### ISSUE TITLE
Router lifecycle - avoid user from leaving the page

### ISSUE THREAD

**Issue by lcustodio** [aurelia/router#392]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11

* **Node Version:**
v4.1.1

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
webpack 1.13.0

* **Browser:**
Chrome 51

* **Language:**
ESNext

**Current behavior:**

Giving the scenario where when leaving the page unsaved data will be lost, the idea is to ask the user for a confirmation.

Using the `canDeactivate` hook I can easily avoid the user from leaving the page (confirm dialog for instance).

**However**, as soon the user press back on the **second** time, he can leave without a problem. It seems that the state is lost and the canDeactivate hook is no longer called. 

*This applies to all pipeline steps (I tried them all, none saves the state after the first next.cancel)

Is there a  better way to avoid the user leaving the page?

```
    canDeactivate() {
        
        return Promise.resolve(false);
    }
```

**Expected/desired behavior:**

* **What is the expected behavior?**

Every time the user tries to leave the page again, `canDeactivate` should be called.

* **What is the motivation / use case for changing the behavior?**

**Comment by bdelville** [comment]
I do not reproduce this issue with router 1.0.2

**Comment by EisenbergEffect** [comment]
Cannot reproduce.

**Comment by TonyLugg** [comment]
I am having this issue.  In my App view I have a button that performs a router.navigateBack().  In my page view (that is loaded into the App's router-view) I am using the canDeactivate hook, and if there are unsaved changes return false in canDeactivate.  If I subsequently press the back button a second time, the canDeactivate route is not called, even though it returned false the first time.  The router performs the back navigation (and in fact navigates completely away from my app).
