### ISSUE TITLE
Property 'router' does not exist on type 'NavigationInstruction'.

### ISSUE THREAD

**Issue by danhowitt** [aurelia/router#397]
**I'm submitting a bug report**
- **Library Version:**
  1.0.2
- **Operating System:**
  Windows10
- **Node Version:**
  6.2.0
- **NPM Version:**
  3.8.9
- **JSPM OR Webpack AND Version**
  Requirejs
- **Browser:**
  all
- **Language:**
  TypeScript 1.8.1

**Current behavior:**

Property 'router' does not exist on type 'NavigationInstruction'.

TypeScript definition doesn't exist for:

``` javascript
event.instruction.router.currentInstruction.config.name
```

as per workaround https://github.com/aurelia/router/issues/177#issuecomment-237198080

**Expected/desired behavior:**

- **What is the expected behavior?**
  NaigationInstruction definition should define router.

**Comment by gheoan** [comment]
@davismj This can be closed.
