### ISSUE TITLE
`navigationStrategy` Example doesn't match TS declration

### ISSUE THREAD

**Issue by atsu85** [aurelia/router#399]
**I'm submitting a bug report**

* **Library Version:**
1.0.2

* **JSPM OR Webpack AND Version**
all

* **Browser:**
n/a
* **Language:**
TypeScript *

**Current behavior:**
"Using A Function For Unknown Routes" [example in documentation](http://aurelia.io/hub.html#/doc/article/aurelia/router/latest/router-configuration/6) returns `string` if `instruction.config === null` - that isn't valid according to [TypeScript declarations file](https://github.com/aurelia/router/blob/master/dist/aurelia-router.d.ts#L116) where returning `string` isn't accepted based on return type:
> `navigationStrategy?: (instruction: NavigationInstruction) => Promise<void> | void;`

**Expected/desired behavior:**
if documentation is correct, update the declaration from:
`navigationStrategy?: (instruction: NavigationInstruction) => Promise<void> | void;`
to
`navigationStrategy?: (instruction: NavigationInstruction) => Promise<void> | void | string;`

* **What is the motivation / use case for changing the behavior?**
Correctness

**Comment by EisenbergEffect** [comment]
@atsu85 Would you be interested in confirming the behavior in source and submitting a PR to fix the types if necessary?

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect see  #408
@atsu85 `navigationStrategy` is correct - you have to augment the passed instruction and return `void | Promise<void>`. The function passed to `mapUnknownRoutes` has to return `string | {moduleId: string} | Promise<string | {moduleId: string}>`.

**Comment by EisenbergEffect** [comment]
@StrahilKazlachev Thanks for assisting with this. I had forgot that we just had that conversation :)
