### ISSUE TITLE
Route Helper: Expose current route to view

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/router#4]
Feature request for a `route.current` method or something similar to be used within a view. Currently, relative hyperlinks inside a child view do not respect parent/child router relationships (for good reason) but this breaks encapsulation.

Use cases for this include nested views and viewmodels where relative links would update the view relative to its parent (rather than relative to the app).

**Comment by jedd-ahyoung** [comment]
Per gitter conversation, a variant of this may be possible by setting the `baseUrl` property on the router object, and using this in an A tag:

    <a href='router.baseUrl + ${object.id}'>

This, however, requires the view to have an injected router.

**Comment by jedd-ahyoung** [comment]
For handling relative hrefs, there are a few options:

 1. Modify the `handleLinkClick` method in app-router to support relative paths.
 2. Add a custom behavior for hrefs. The behavior could look like this:

    <a router-href=“name: myRoute; params.bind: { id:object.id }”>Something</a>

While option 1 is a quick fix, option 2 is definitely more powerful.

**Comment by EisenbergEffect** [comment]
Option two shouldn't be too hard either though, since all the building blocks are in place now.
