### ISSUE TITLE
mapUnknownRoutes weird behaviour

### ISSUE THREAD

**Issue by Narven** [aurelia/router#404]
First of all, I'm not a javascript guru.

I've been trying to implement some routing system (for the last month) for a new project built on AureliaJS.

Since I need some custom routing to load specific view-models based on url params, I'm trying to use `config.mapUnknownRoutes`. After following documentation and books that say exactly the same thing in all of them (copy and paste), and absolutely no help form Gitter, I decided to put here my problem.

>If this is not the best place to put this (besides forums, or gitter, please let me know, or delete the issue)

##Problem

Every where seen, that tries to explain how to use `config.mapUnknownRoutes` to change the view-model (change the moduleId) dynamically uses something like this:

```
config.mapUnknownRoutes(instruction => {
    console.info('INSTRUCTION', instruction);
    instruction.config.moduleId = 'foo/bar.js';
    return instruction;
}
```

Please correct me, but for me this is impossible to do, because first `instruction.config` does not exist, so it will return an js error `TypeError: Cannot set property 'moduleId' of null`.

Also following this code... if we put a break point on this line: [https://github.com/aurelia/router/blob/master/src/router.js#L450](https://github.com/aurelia/router/blob/master/src/router.js#L450) that is in the middle of the loop that goes through all routing configuration... we can see that a normal 'config' object (any of the other predefined routes) is something like this:

```
{
  auth: true,
  moduleId: "[activity/index",
  name:"activity",
  route:"",
  settings: {
    
  },
  title: "Activity"
}
```

But on the `mapUnknownRoutes` I get something like this (by continuing till the last breakpoints on the loop):

![screenshot 2016-09-20 08 02 46](https://cloud.githubusercontent.com/assets/123594/18660506/c2d43e9c-7f08-11e6-98a7-f1d7cf9a6ed0.png)

> Link here if you cannot see the image [https://www.dropbox.com/s/hx5syxj7vm05wx4/Screenshot%202016-09-20%2008.02.46.png?dl=0](https://www.dropbox.com/s/hx5syxj7vm05wx4/Screenshot%202016-09-20%2008.02.46.png?dl=0)

I understand that those are 2 diferent objects... the second is a NavigationInstruction object... but my point is that part of the code [https://github.com/aurelia/router/blob/master/src/router.js#L450](https://github.com/aurelia/router/blob/master/src/router.js#L450), is not reading the property config, but directly the property `moduleId`.

To finalize, I think that:

`instruction.config.moduleId = 'foo/bar.js';`

should be:

`instruction.moduleId = 'foo/bar.js';`

But again, I'm not a js developer.

Was this something that recently changed? Thanks

PS:  If I use `instruction.moduleId = 'foo/bar.js';` does not give any errors.. and actually works.... I think.

**Comment by EisenbergEffect** [comment]
Have you tried this?

```
instruction.config = { moduleId: 'foo/bar.js' };
```

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect Didn't this change [here](https://github.com/aurelia/router/commit/4aa9bc9ed57e9655db6d37d5a52dd16577bf2b33)? If you pass a function to `mapUnknownRoutes` you have to return `string | RouteConfig`.

**Comment by Narven** [comment]
@EisenbergEffect still does not work. I keep getting:

```
aurelia-logging-console.js:54 ERROR [app-router] Error: Invalid Route Config for "/sad": You must specify a "moduleId:", "redirect:", "navigationStrategy:", or "viewPorts:"
```

**Comment by Narven** [comment]
@StrahilKazlachev `string | {moduleId: string}` did not work also ...

**Comment by EisenbergEffect** [comment]
Looks like we had a change to behavior a while back and the docs didn't get updated. Let me check on that and post an answer here.

**Comment by EisenbergEffect** [comment]
@Narven You need to return the config object itself from your custom handler. Like this:

```javascript
config.mapUnknownRoutes(instruction => {
    return { moduleId:  'foo/bar.js'};
});
```

**Comment by Narven** [comment]
i will try it later, and give some feedback.. but think i tried that option.

**Comment by Narven** [comment]
Sry for the delay.

Its seams to be working now. I'm having another issue. but is not related to this one.

thanks

**Comment by adriatic** [comment]
I have a different problem - as I want to capture the unknown route so it does not show up on the Chrome console as an error, but rather as my application's message explaining the user how all is fine.

I added the code
```
       var handleUnknownRoutes = (instruction) => {
            return { route: 'not-found', moduleId: 'home/not-found' };
        }
```

then added the route
```
            {
                route: 'not-found',
                name: '',
                moduleId: 'home/not-found',
                nav: false,
                title: ''
            }            
```

and provided the dummy component (where I want to create my own console message). 

With all this in place, I am still getting the original error message like
```
aurelia-logging-console.js:54 ERROR [app-router] Error: Route not found: /bad-route
    at AppRouter._createNavigationInstruction (aurelia-router.js:1040)
    at AppRouter.loadUrl (aurelia-router.js:1635)
    at BrowserHistory._loadUrl (aurelia-history-browser.js:301)
    at BrowserHistory._checkUrl (aurelia-history-browser.js:294)
```

**Note** I am doing this to prevent the error messages caused by the processing of Auth0 authentication reponse - see more **[here](https://github.com/aurelia-auth0/auth-templates/issues/18)**.
