### ISSUE TITLE
Cannot listen to click when a href is et

### ISSUE THREAD

**Issue by hadrienl** [aurelia/router#407]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
CLI

* **Browser:**
all

* **Language:**
all

**Current behavior:**
I have a link with a `href.bind` attribute which is enhanced by router. I add a `click.delegate` attribute to it because I want to execute something before navigating. The `click` listener is well excuted but no navigation occurs.

**Expected/desired behavior:**
I want the click.delegate to be executed then, I want the navigation occurs.

A workaround is to use `mousedown` instead of `click`.

**Comment by Alexander-Taran** [comment]
Do you return true from your delegate?
check this one out https://github.com/aurelia/binding/issues/336

**Comment by hadrienl** [comment]
Oh ! Ok… I don't know if it is in the documentation but it should be highlighted…

**Comment by EisenbergEffect** [comment]
@jdanyow Do we have this detail in the documentation with respect to `trigger` and `delegate`?

**Comment by jdanyow** [comment]
@EisenbergEffect it is now ☝️ :+1:

**Comment by shahidkarimi** [comment]
Please answer this
https://stackoverflow.com/questions/47441179/aurelia-href-bind-is-not-working
