### ISSUE TITLE
Reusing view models in routes doesn't call activate

### ISSUE THREAD

**Issue by badunk** [aurelia/router#41]
I'm trying to reuse a view model that switches behavior based on the settings passed in router.

When navigating between the two routes that reuse the same view model, however, it does not call activate twice, so I can't get the metadata for subsequent routes.

Specifically for my use case, I'm trying to create a routable view model that takes some model from an API and allows someone to perform CRUDL operations on it - like an admin view.  In this case, each model has its own route, but those all route to the same view model.

Thanks

**Comment by EisenbergEffect** [comment]
Try this:

```javascript
import {INVOKE_LIFECYCLE} from 'aurelia-router';

export class YourViewModel {
  determineActivationStrategy(){
    return INVOKE_LIFECYCLE;
  }
}
```

If you add the `determineActivationStrategy` callback, you should be able to force the activation to run.

**Comment by badunk** [comment]
that worked - thanks!

**Comment by mreiche** [comment]
@EisenbergEffect Can you point to the documentation please? I've found another article https://zombiecodekill.com/2016/07/03/aurelia-routing-beyond-the-basics/ which explains this a little bit more. And im looking for the constants for activationStrategy.invokeLifecycle
