### ISSUE TITLE
Option to specify page title separator

### ISSUE THREAD

**Issue by fracz** [aurelia/router#419]
**I'm submitting a feature request**

The default separator of the page title [is set to pipe `|`](https://github.com/aurelia/router/blob/master/src/navigation-instruction.js#L235). However, the parameter cannot be currently overridden in any way. [The only place](https://github.com/aurelia/router/blob/master/src/navigation-instruction.js#L229) that uses this function does not use this argument.

The issue has already been discussed [in gitter](https://gitter.im/aurelia/Discuss?at=57f6b25a68f560d80ce32f7d) with a suggestion that the separator could be configured on child-router basis, too.

**Comment by CasiOo** [comment]
Any suggestions where the separator should be defined?
Adding a `titleSeparator` to `RouterConfiguration` seems obvious to me, but the property probably also needs to be added to `NavModel`?

I would like the following implementation:
- Each child has the option to specify its own separator. If none is set, then use the parent separator. If none is set and at the root, then use the default value `' | '`.
- A globally set `titleSeparator` on the root RouterConfiguration that can be overriden in any child

Example configuration
```
export class App {
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.titleSeparator = ' - ';
    config.map([
      { route: ['', 'welcome'], name: 'welcome',      moduleId: 'welcome',      nav: true, title: 'Welcome' },
      { route: 'users',         name: 'users',        moduleId: 'users',        nav: true, title: 'Github Users' titleSeparator: ' > ' },
      { route: 'child-router',  name: 'child-router', moduleId: 'child-router', nav: true, title: 'Child Router' }
    ]);

    this.router = router;
  }
}
```

**Comment by EisenbergEffect** [comment]
@CasiOo That sounds great. We've got a PR we are reviewing to make title generation pluggable. I think this would be a nice addition as well. Are you interested in working on it and submitting a PR?

**Comment by CasiOo** [comment]
@EisenbergEffect  Yes I will find time to work on a PR :)
I'm not yet confident with child routes, as I have just kept using a single router, but I'll put some time into it.

**Comment by nichgalea** [comment]
Any updates regarding this, please?

It's a good nice-to-have enhancement.

**Comment by CasiOo** [comment]
I've started some initial work on this feature.
The interesting part is how the title should be built, you can see my updated logic here: https://github.com/CasiOo/router/blob/feat-title-separator/src/navigation-instruction.js#L236

I have some questions that need to be answered before I can move on with the implementation.
1) If a RouteConfig has specified a title separator, should this title separator be used when building the title from parent -> route, or route -> route's children?

Example:
```
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.titleSeparator = ' - ';
    config.map([
      { route: ['', 'child-router'],  name: 'child-router', moduleId: 'child-router', nav: true, title: 'Child Router', titleSeparator: ' / ' }
    ]);

    this.router = router;
  }
```
Should the above result in the title `Child Router - Aurelia` or `Child Router / Aurelia`? 

2) What should happen when there is specified a title separator on the RouteConfig, but the child router itself has too a title separator?

Example:
```
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.titleSeparator = ' - ';
    config.map([
      { route: ['', 'child-router'],  name: 'child-router', moduleId: 'child-router', nav: true, title: 'Child Router', titleSeparator: ' / ' }
    ]);

    this.router = router;
  }
```
```
  configureRouter(config, router) {
    config.title = 'Children';
    config.titleSeparator = ' > ';
    config.map([
      { route: ['', 'child-route1'], name: 'childRoute1',       moduleId: 'child-route1',       nav: true, title: 'child-route1' },
      { route: 'child-route2',       name: 'childRoute2',       moduleId: 'child-route2',       nav: true, title: 'child-route2' }
    ]);

    this.router = router;
  }
```
When should the separators `' / '` and `' > '` be used?

**Current implementation in feature branch**
Url: http://localhost:9000/#/child-router/
Title: `child-route1 > Children / Child Router - Aurelia`

Configuration:
```
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.titleSeparator = ' - ';
    config.map([
      { route: ['', 'child-router'],  name: 'child-router', moduleId: 'child-router', nav: true, title: 'Child Router', titleSeparator: ' / ' }
    ]);

    this.router = router;
  }
```
```
  configureRouter(config, router) {
    config.title = 'Children';
    config.titleSeparator = ' > ';
    config.map([
      { route: ['', 'child-route1'], name: 'childRoute1',       moduleId: 'child-route1',       nav: true, title: 'child-route1' },
      { route: 'child-route2',       name: 'childRoute2',       moduleId: 'child-route2',       nav: true, title: 'child-route2' }
    ]);

    this.router = router;
  }
```

**Comment by CasiOo** [comment]
I have also thought about why Aurelia forces child titles first, what if you wanted it the other way around?

So instead of flipping it,
`Issue #419 - Aurelia Router - GitHub`
You would append them in the order they appear in the router
`GitHub - Aurelia Router - Issue #419`

Isn't that a feature that may be requested at some point?

What if the child router title is the only title that should be shown, is that possible? GitHub for example doesn't show GitHub in the title for this issue page, but on the homepage it says GitHub.

**Comment by rmja** [comment]
Instead of having a titleSeparator on the router, how about allowing for at configurable callback that gets as input all the instructions to generate the current route, and from that returns the title as a string. In that way you have full flexibility to reorder and change the separator.

**Comment by EisenbergEffect** [comment]
That sounds like a good idea, if we can do it in a backwards compatible way.

**Comment by stsje** [comment]
@rmja Do you have an example of what you are trying to do? I'm not sure I've understood your suggestion.

**Comment by CasiOo** [comment]
I would like to continue my work on this feature this weekend, if you can explain your suggestion to me @rmja . You can also find me on gitter.

**Comment by rmja** [comment]
Sure. The reasoning behind the proposal is, as you pointed out, that the number of different flavors of configuration may vary alot from use case to use case. If we instead go in a direction where there is only one configuration option, namely a callback to generate the title, then the developer has full flexibility in generating the title.

To be more concrete. You are defining in your proposal a property named titleSeparator. If you instead defined a property called, say generateTitle. Then in the router, refactor out the code that currently generates the title into a local function _generateTitle and assign the function to the the generateTitle property. The places where the function should be called, then call the configured generateTitle function instead of the local.

Just ping me back if you have any questions.

**Comment by CasiOo** [comment]
@rmja If we put a `generateTitle` property on the RouteConfig, then it wont be the component deciding on the title, but instead a method that you'll have to import into the file implementing `configureRouter`.
Would you then have to copy-paste this `generateTitle` property onto all your routes, or do they inherit somehow?

At first I thought you talked about implementing it as part of the router screen life cycle. I'm not a fan of that idea:
```
buildAppTitle(navigationInstructions) {
    return 'my title';
}
```

We have a backwards compatibility problem. The term `title` refers to the current instruction's title, and not the fully generated app title. A solution could be to have a new method `setAppTitle`, which doesn't do any transformations behind the scene.
```
activate(params, routeConfig, navigationInstruction) {
    let title = 
        this.titleBuilder
            .withInstruction(navigationInstruction)
            .withSeparator(' / ')
            .reverse()
            .build();
        
    this.router.setAppTitle(title);
}
```
I like the idea of removing the title generation logic from the instruction itself. In my head it shouldn't be the instructions responsibility to generate it. Therefore a new title builder object.
The above is an idea of what a title builder could look like. Still have to put more thought into it, like what would a clean way be of defining multiple separators.
```
import {DefaultTitleBuilder} from 'aurelia-router';

export class FooViewModel {
    activate(params, routeConfig, navigationInstruction) {
        let title = 
            DefaultTitleBuilder
                .new()
                .withInstruction(navigationInstruction)
                .build();
        this.router.setAppTitle(title);
    }
}
```
Developers are then free to implement their own title builders or however they want to generate the title. Just set the title with `router.setAppTitle(title)`

**Comment by rmja** [comment]
Well my proposal is to put it here on the AppRouter config. Maybe some of the framework authors should comment on if it is a good suggestion or not:)
```
configureRouter(config, router) {
    config.title = 'Children';
    config.generateTitle = instructions => 'the title';

    this.router = router;
  }
```

If you need the title to depend on the current view model, which I think is a rare scenario, then you always have the option to implement it through a shared service, on which your app.js can take a dependency. Then assign the generateTitle property with a generateTitle callack in the service. Then you can configure the title through the service, (instead of the the current router) from any view model that needs to redefine the title on a per view basis.

**Comment by EisenbergEffect** [comment]
This makes sense to me. @bryanrsmith Any thoughts on this?

**Comment by CasiOo** [comment]
@rmja That could work. If people really need special title logic, then they can put hints on the route configs and adjust their own generateTitle function to suit their needs.

So I guess a `titleSeparator` property will still be needed to make it an easy change? If so, can anyone comment if what I've asked/done thus far is correct https://github.com/aurelia/router/issues/419#issuecomment-258287872 ?

**Comment by rquast** [comment]
@rmja I just hit this issue with my app and thought of the same approach as you mentioned. I need it for particular routes where the title can be controlled for notifications (like (1) or 1 unread message, etc).

**Comment by fracz** [comment]
Great use case, @rquast. I will definitely hit this problem in near future. Therefore, the title should be also updatable without route change (i.e. new message arrives and the title should be updated).

Probably, we could post some event through `EventAggregator` to update the title?

**Comment by RichiCoder1** [comment]
@fracz Another addition would be that `router.navigate(samePage)` as well as the similiar ways of navigating to the same page without a refresh would trigger a title update, as well as maybe a `router.updateTitle()`.

**Comment by obedm503** [comment]
anything new on the `titleSeparator` option?

**Comment by pndewit** [comment]
What's the status? I'm running into the same issue and would really like to be able to change the separator. Even something like `config.titleSeparator = ' - ';` inside the `configureRouter` function would be enough for me.

**Comment by fracz** [comment]
https://xkcd.com/974/

**Comment by istrau2** [comment]
+1 can this be solved please?

**Comment by Alexander-Taran** [comment]
anyone willing to provide PR for this?

**Comment by davismj** [comment]
PRs welcome.

The right thing to do is to add a function that generate titles and implement the current behavior as the default function.
