### ISSUE TITLE
RouteConfig settings changes not retained

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia/router#420]
**I'm submitting a bug report**
- **Library Version:**
  1.0.6

**Please tell us about your environment:**
- **Operating System:**
  Windows 8.1
- **Node Version:**
  6.5.0
- **NPM Version:**
  3.10.8
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.22
- **Browser:**
  all
- **Language:**
  TypeScript 2.0.3

**Current behavior:**
I have a child route where I want to pass changes on route settings data, but the changes are not stored. My use case it's a wizard form that passes the model into each step and incrementally fill up the data.

**Expected/desired behavior:**
Changing arbitrary data should be handled by retaining the new values.

**Comment by EisenbergEffect** [comment]
Can you provide an example?

**Comment by enrico-padovani** [comment]
Hi Rob,

I'll try to do that ASAP. Just a question: is the settings property statically defined inside the route config? I mean, every changes made to it at runtime will be lost?

**Comment by EisenbergEffect** [comment]
The settings property on the route config should be preserved.

**Comment by enrico-padovani** [comment]
Ok, I've noticed that the settings are lost when determineActivationStrategy is replace, [here](https://gist.run/?id=3633c285ee05441199779aa3509490af) is the example. Click on "Wizard" -> "Arrow right" and should write "Changed!"

Is that wanted, as far as I understand it creates a new instance of the vm right?

**Comment by enrico-padovani** [comment]
Just to give a better picture: I've changes determineActivationStrategy to replace because I'm handling different routes with the same viewmodel. In the standard way, the activate method will fire only the first time. In my scenario I need to apply a filter using the parameter that i'm expecting to receive in the activate. I don't know either if this is intended (that activate fire only once) or a "sort of bug".

So I'm a bit stuck! Any Idea?

**Comment by Alexander-Taran** [comment]
@enrico-padovani is this still relevant to you?
