### ISSUE TITLE
Unable to set activationStrategy in routeConfig

### ISSUE THREAD

**Issue by VMBindraban** [aurelia/router#423]
**I'm submitting a bug report**

* **Library Version:**
1.0.6

* **JSPM**
JSPM 0.16.15

**Current behavior:**

I tried setting the activationStrategy with @zewa666 and we concluded to make a issue for it.

Basically setting the `activationStrategy` in the routeConfig doesn't work.
We tried:

```js
  {
    route             : 'foo',
    name              : 'bar',
    moduleId          : 'page/foo',
    title             : 'Bar',
    activationStrategy: 'invoke-lifecycle',
    nav               : true,
  },
```

```js
import {activationStrategy} from 'aurelia-router';

 // routes is a array with.. routes.
  routes.map(route => {
    route.activationStrategy = activationStrategy.invokeLifecycle
  });
```

```js
  var navStrat = (instruction) => {
    instruction.config.activationStrategy = "invoke-lifecycle";
  }

  routes.map(route => {
    route.navigationStrategy = navStrat;
  });
```

What @EisenbergEffect is using:
```js

import {activationStrategy} from 'aurelia-router';

  {
    route             : 'foo',
    name              : 'bar',
    moduleId          : 'page/foo',
    title             : 'Bar',
    activationStrategy: activationStrategy.invokeLifecycle,
    nav               : true,
  },
```

I tested this by setting `a=1` in the url and hitting the back button.
It does work when setting the `determineActivationStrategy` in the VM.

@zewa666 I found the docs for it.
http://aurelia.io/hub.html#/doc/api/aurelia/router/latest/interface/RouteConfig
I was looking in http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/7

**What is the motivation / use case for changing the behavior?**
Our application works with parameters, i want to avoid setting the `determineActivationStrategy` in every VM.

**Comment by EisenbergEffect** [comment]
Submit a sample that I can run please which shows that it works in the view model but not in the route config. The code I shared (not exactly what is above) is from a real application.

It sounds like your issue is related to query params. Perhaps try it with normal routes first vs. those with query params.

**Comment by VMBindraban** [comment]
I can't reproduce the issue on the skeleton-navigation.
Seems to be on my side.
