### ISSUE TITLE
Page refresh reverts to App configureRouter

### ISSUE THREAD

**Issue by smithaitufe** [aurelia/router#429]
I noticed that if I use

login.js contains the snippet below. It uses private-section as the root if the login is successful
```
this.router.navigate("", {replace: true, trigger: false});
this.router.reset();
this.aurelia.setRoot("sections/private/private-section")
```

However, when you hit f5 or reload the page, the root is reverted to the app.js as the root.
Is this the expected behavior?

**Comment by EisenbergEffect** [comment]
I don't think I have enough information/context to answer the question. But, setting the root isn't persistent across refreshes. That doesn't have anything to do with the router and doesn't affect the history state.
