### ISSUE TITLE
Change routes titles in activate method

### ISSUE THREAD

**Issue by hadrienl** [aurelia/router#43]
Hi,

I have a dynamic route without title, but I'd like to set the title after loading the displayed resource. So I've tried this :

In parent component's router :

```
{
   route: [':id'],
  moduleId: 'accounts/account',
  nav: false,
  title: ''
}
```

And in `accounts/account` controller :

```
canActivate (params, queryString, routeConfig) {
  return new P((resolve, reject) => {
    this.AccountsService
      .getById(params.id)
      .then(account => {
        this.account = account;
        routeConfig.title = account.name;
        console.log(routeConfig);
        resolve(true);
      })
      .catch(() => reject(false));
  });
}
```

In console, `routeConfig.title` is well set, but `document.title` does not change :(

**Comment by EisenbergEffect** [comment]
Use `routeConfig.navModel.title` instead.
