### ISSUE TITLE
router-view should render template attributes

### ISSUE THREAD

**Issue by fracz** [aurelia/router#430]
**I'm submitting a feature request**

Consider simple component

```js
export class SomeComponent {
}
```
```html
<template class="some-class">
  <h1>Foo</h1>
</template>
```

When you use it in the markup

```html
<require from="some-component"></require>
<some-component></some-component>
```

it properly adds the class from the template (the `some-class` is added to the element):

```html
<some-component class="au-target some-class" au-target-id="54">
  <h1>Foo</h1>
</some-component>
```

However, if you link to the component from router, it becomes:

```html
<router-view class="au-target" au-target-id="53">
  <h1>Foo</h1>
</router>
```

There is no `some-class` added to the `router-view`. IMO, it should be there (i.e. the `router-view` should render all the attributes added to the template as it does when you use the component directly).

* **What is the motivation / use case for changing the behavior?**
You can properly scope the styles to the views, i.e.

```css
.some-class {
  background: pink;
}
```

**Comment by Alexander-Taran** [comment]
duplicates: https://github.com/aurelia/templating/issues/505

can't find it at the moment, but sure it came up recently and was closed

**Comment by EisenbergEffect** [comment]
No plan to do this in the current version of Aurelia. It's possible in vNext, which would involve breaking changes.

**Comment by davismj** [comment]
I wouldn't recommend this as a feature at all..
