### ISSUE TITLE
If the router has multiple routes using the same route and different hrefs then rowActive does not work.

### ISSUE THREAD

**Issue by glennpierce** [aurelia/router#433]
**I'm submitting a bug report**

* **Library Version:**
1.0.2

**Please tell us about your environment:**
* **Operating System:**
Linux Fedora23

* **Node Version:**
6.2.2

* **NPM Version:**
3.9.5

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

2.1.0-beta.22

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView
Chrome 52

* **Language:**
all | TypeScript X.X | ESNext
typescript 2.0.0

**Current behavior:**

I have routes defined like

{ route: "shimmy_section/:id", href:'shimmy_section/yourcommunity', name: 'yourcommunity', moduleId: "./shimmy_section", nav:true, title: 'Your Community'},
      { route: "shimmy_section/:id", href:'shimmy_section/yourtravel', name: 'yourtravel', moduleId: "./shimmy_section", nav:true, title: 'Your Travel'},
      { route: "shimmy_section/:id", href:'shimmy_section/yourenergyandwater', name: 'yourenergyandwater', moduleId: "./shimmy_section", nav:true, title: 'Energy & Water'},
      { route: "shimmy_section/:id", href:'shimmy_section/yourneighbourhood', name: 'yourneighbourhood', moduleId: "./shimmy_section", nav:true, title: 'Your Neighbourhood'},

Ie they are handled by the same module hence I used href.
However, row.isActive does not work with this setup. The last item is always active

**Expected/desired behavior:**

The following example shows the issue

https://github.com/glennpierce/test

* **What is the expected behavior?**

rowActive should work with this setup.

* **What is the motivation / use case for changing the behavior?**
I wan't to show the active select in the nav bar.

**Comment by a-jackson** [comment]
I'm see this issue as well. Any progress on it? I'd be willing to do the PR myself if someone could point me in the right direction

**Comment by EisenbergEffect** [comment]
How should it determine which route is active?

**Comment by a-jackson** [comment]
I would expect it to match the href.

I tried to look for an answer myself but got lost in the route-recognizer and its states. I can't tell where it matches a NavigationInstruction to a config. I know this lands somewhere in the route-recognizer.

**Comment by johot** [comment]
@EisenbergEffect I just ran into this as well. Is there any way to have multiple routes using the same `moduleId`? When using the same `moduleId` the activate() method will not be called when moving between routes. The only workaround I found was to use token parameters instead (which is probably more "correct") but then I can't use the `row.isActive` feature anymore since it can't tell the difference between my different routes.

How should using multiple routes with the same view-model be handled? The docs doesn't mention this at all.

**Comment by jfstephe** [comment]
+1 I've got the same problem.

Agree documentation on this is poor - you have to guess/investigate moduleId and name if you want to see what the consequences of setting them are etc (but I suppose that's a different issue ;-).

Can someone of authority please respond?

**Comment by dweggemans** [comment]
I ran into this problem as well and I've made myself a dirty hack that I'd love to get rid of. I hope this helps someone until it is fixed

```
this.ea.subscribe("router:navigation:complete", response => {            
            this.router.navigation.forEach(x => x.isActive = false);
            var href = `/products/${response.instruction.params.category}`;
            var navModel = this.router.navigation.find(
                x => x.relativeHref === response.instruction.config.redirect || x.relativeHref === href);
            navModel.isActive = true;
        });
```

**Comment by gheoan** [comment]
I am looking for feedback on #520 regarding:

- Is `href` the only property that can differentiate between multiple `RouteConfig` with same `route` property?
- Should `router` or `route-recognizer` be responsible for differentiating based on `href`? `route-recognizer` is [capable](https://github.com/aurelia/route-recognizer/blob/bbb929f5c2250df21660775bd77ebd2e10a97bec/src/route-recognizer.js#L178) of returning multiple `RouteConfig`. In #520`router` is responsible.
- Should the `href` be normalized? If so, is there any existing API that can do that?
- What to do when `href` is not available. Curently the first result from `route-recognizer` is selected.
- Are there other edge cases?

**Comment by dweggemans** [comment]
This is how I do the routing so I have different values for properties `settings`, `name` and `title`.
```
 config.map([
            {
                route: '', redirect: '/categories/cat1'
            },
            {
                route: 'categories/:type',
                href: '/categories/cat1',
                name: 'cat1',
                settings: { icon: 'file-text' },
                moduleId: PLATFORM.moduleName('../categories/categories'),
                nav: true,
                title: 'cat1'
            },
            {
                route: 'categories/:type',
                href: '/categories/catN',
                name: 'catN',
                settings: { icon: 'envelope' },
                moduleId: PLATFORM.moduleName('../categories/categories'),
                nav: true,
                title: 'catN'
            }           
```

Is there any ETA on getting this fixed or else a proper workaround? This has been open for a year already...

**Comment by gheoan** [comment]
@dweggemans Feel free to contribute if you need this. You can use my fork of the route-recognizer library which contains the PR to add this feature (https://github.com/aurelia/route-recognizer/pull/30) and provide feedback. Install it from the `fork` branch of `https://github.com/gheoan/route-recognizer` (if you are using npm execute `npm install --save github:gheoan/route-recognizer#fork`). Note that the `href` property needs to have a leading `/` for my PR to work.

**Comment by huochunpeng** [comment]
Just learnt here how to use "href" with parameterized route. It's pity it doesn't work with isActive at least for now.

One possible workaround I can see, is to avoid parameterized route.
```
{ route: 'shimmy_section/one', moduleId: "./shimmy_section", settings: {id: 'one'},...},
{ route: 'shimmy_section/two', moduleId: "./shimmy_section", settings: {id: 'two'},...},
```

**Comment by Alexander-Taran** [comment]
Would be interesting to know what problem are you trying to solve with this multiple identical routes

**Comment by dweggemans** [comment]
For example product categories. The module is the same but you use category parameter for filtering, title etc.

**Comment by huochunpeng** [comment]
@Alexander-Taran if you read from top, parameterized route currently doesn't support isActive natively, my proposed workaround just uses rigid route definition to bypass the issue.
