### ISSUE TITLE
%(encoded value) in route parameter, then child routes does not calculate correctly

### ISSUE THREAD

**Issue by neolivz** [aurelia/router#435]
When you have an escaped value in route parameter (i.e. with %) and with child routes then the href generated values does not have a proper hierarchy.

Eg: [Modified Skelton Typescript Webpack](https://github.com/neolivz/skeleton-navigation/tree/master/skeleton-typescript-webpack).

[With %](http://localhost:9000/#/child-router/child-router/welcome/child-router/%23A/welcome
) All the parent routes are getting routed to top level ignoring the whole hierarchy.

<img width="848" alt="screen shot 2016-11-23 at 2 18 34 pm" src="https://cloud.githubusercontent.com/assets/754818/20555807/e704bac2-b189-11e6-9569-d13b05c21456.png">

[Without %](http://localhost:9000/#/child-router/child-router/welcome/child-router/#A/welcome
) When you don't have % in URL parameter it works fine
<img width="785" alt="screen shot 2016-11-23 at 2 19 04 pm" src="https://cloud.githubusercontent.com/assets/754818/20555838/106df09a-b18a-11e6-9023-edc2cfdcd595.png">

Check the URL generated.

**Comment by EisenbergEffect** [comment]
@neolivz Would you be interested in submitting a PR to fix this issue? It sounds like it would be a nice contribution.

**Comment by neolivz** [comment]
Sure :) I will look into it.

**Comment by gheoan** [comment]
@davismj this can be closed.
