### ISSUE TITLE
route-href binding too late

### ISSUE THREAD

**Issue by fkleuver** [aurelia/router#438]
**I'm submitting a bug report**

* **Library Version:**
1.0.7

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
4.0.2

* **Aurelia-CLI**
0.22.0

* **Browser:**
all

* **Language:**
TypeScript 2.0.10

**Current behavior:**
Given an application with a recursive route `'app'` (but it seems to apply to nested child routes in general) where navigation occurs through `a` tags with `route-href` attributes, the following happens:
- Click on the first route and it navigates to `'#/app'`
- Click on the second route and it navigates to `'#/app/app'`
- Click on the third route and it navigates to `'#/app/app/app'`

Then after a refresh:
- Click on the third route and it navigates to `'#/app'`

**Expected/desired behavior:**
After the refresh:
- Click on the third route and it navigates to `'#/app/app/app'`

**repro**
This is from a question in gitter.
The person who asked about this (@cabarney) pinpointed it down to a wrong order of sequence in which the `route-href` is databound when refreshing:
1. _refreshBaseUrl on the first level route
2. _refreshBaseUrl on the second level route
3. generate on the router for the third level route
4. _refreshBaseUrl on the third level route

So I tried to force step 3. to come after step 4. by moving `this.processChange();` from `bind()` to `attached()` in `route-href.js` and that seems to solve this particular problem.

I've made a minimal repro here:
https://github.com/fkleuver/aurelia-route-href-issue

You can see the difference by clicking `App` several times, refreshing, then clicking the last `App` again. The normal `route-href` will fail, but the `route-href-attached` will work.

I don't know if moving `this.processChange()` to `attached` will break anything else though.

**EDIT**
Sorry, this issue was meant to go to `templating-router`. Is it possible to move it?

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/templating-router #46](https://github.com/aurelia/templating-router/issues/46) via [**ZenHub**](https://www.zenhub.com/)
