### ISSUE TITLE
Fail to use multilevel path in System.baseUrl

### ISSUE THREAD

**Issue by olegstepura** [aurelia/router#44]
Hi!

If I try to use multilevel directory in `System.baseUrl` for having my templates and `js` files being stored several levels deep from the root, I got an error in console and nothing works. With this:
```js
    System.baseUrl = '/assets/app';
    System.import('aurelia-bootstrapper');
```
and 
```html
<body aurelia-app="test">
````
I got an error: `Uncaught TypeError: Illegal module name "/assets/app/test"`

If I do this modification: 
```js
//    System.baseUrl = 'assets';
    System.config({
        "baseURL": "/assets/app/"
    });
    System.import('aurelia-bootstrapper');
```
`/assets/app/test.js` file is loaded, but `/assets/app/test.html` one is not. In console network tab i see browser trying to load `/test.html`

Tried using `<base href="/assets/app" >` as @goranobradovic suggested in gitter, but with no luck.
It may be not an issue of aurelia itself, but I actually cannot tell what's responsible, so please report this elsewhere if required.

Thanks!

**Comment by EisenbergEffect** [comment]
The problem relates to an issue with Aurelia's template loader not fully leveraging system.js and its path resolution mechanism for views. We have fixed that and it will go out in the next release this week.
