### ISSUE TITLE
Add router.removeRoute() - again

### ISSUE THREAD

**Issue by krostkowski** [aurelia/router#445]
It's a problem similar to #129 

I have used  [@jdanyow solution](http://stackoverflow.com/questions/33458274/how-to-switch-between-login-page-and-app-with-aurelia) but now I see that after the logout, where I call

``` 
setRoot('login');
```

router is not reset. It is still possible to paste the url of existing subpages and activate them (activate() is invoked, backend requests are sent, page title changes, only view doesn't change and shows login form).

What is your recommendation to handle this simple scenario with user relogin?
Should I reset the router manually and reregister routes available for user roles after successful login or use navigationStrategy for every route instead of setRoot methods as @bryanrsmith  suggests in #129 ?

**Comment by EisenbergEffect** [comment]
I'd try resetting the router and re-registering the appropriate, role-based routes.
