### ISSUE TITLE
 `layoutView`, `layoutViewModel` and `layoutModel` are not in present in the `RouteConfig` interface

### ISSUE THREAD

**Issue by dkent600** [aurelia/router#447]
I find that although the current Aurelia documentation states, I believe correctly, that one can supply `layoutView`, `layoutViewModel` and `layoutModel` in javascript on the route configuration, I find that these three properties are not represented in the `RouteConfig` interface in the router module index.d.ts.

**Comment by EisenbergEffect** [comment]
Feel free to submit a PR to add those properties so that they show up in the dts.

**Comment by gheoan** [comment]
@EisenbergEffect , @davismj this can be closed.
