### ISSUE TITLE
New router properties: explicitNavigation and navigatingBack

### ISSUE THREAD

**Issue by jwx** [aurelia/router#449]
**I'm submitting a feature request**

Durandal's router had two properties, explicitNavigation and navigatingBack, that were very useful in activate() and deactivate(). Could they be implemented in Aurelia as well?

**Comment by jwx** [comment]
I'm looking into this.

**Comment by RichiCoder1** [comment]
Just saw this in the release and didn't realize I really wanted this until now. 🎉

**Comment by EisenbergEffect** [comment]
😃

**Comment by jwx** [comment]
:)
