### ISSUE TITLE
config.mapUnknownRoutes and views

### ISSUE THREAD

**Issue by vizo** [aurelia/router#46]
I want to use 
```javascript
      config.mapUnknownRoutes(instruction => {
        instruction.config.moduleId = '/en/main-router';
        instruction.config.view = 'main-router.html';
        return instruction;
      });
```
but it is searching for '/en/main-router.html' view.

Any idea?

**Comment by EisenbergEffect** [comment]
Views are relative to the view model. Try using `../main-router.html`.

**Comment by vizo** [comment]
Sorry maybe i wasn't clear ... instruction.config.view is ignored no matter what is it. It always requests for "http://localhost:9000/dist/en/main-router.html "

**Comment by jdanyow** [comment]
@vizo here's another thing you could try:

add a `getViewStrategy` to your view model as described [here](http://aurelia.io/docs.html#compose):  

> What if you want to determine the view dynamically based on data though? or runtime conditions? You can do that too by implementing a getViewStrategy() method on your view-model. It can return a relative path to the view or an instance of a ViewStrategy for custom view loading behavior. The nice part is that this method is executed after the activate callback, so you have access to the model data when determining the view.

**Comment by vizo** [comment]
Thanks for your help. But i want simply redirect to "locale" /en or /sl. I want to use existing view-model.

I have router config
```javascript
      config.map([
        { route: 'en',  moduleId: 'en/main-router', view: 'main-router.html', nav: true, title: 'En' },
        { route: 'sl',  moduleId: 'sl/main-router', view: 'main-router.html', nav: true, title: 'Sl' }
      ]);
```
and i want simply redirect to "locale" route:
```javascript
      config.mapUnknownRoutes(instruction => {
        var locale = en; // detect locale from browser, session, ...
        instruction.config.moduleId = locale + '/main-router';
        instruction.config.view = 'main-router.html';
        return instruction;
      });
```

**Comment by Narven** [comment]
@vizo did you manage to find a way? thanks

**Comment by vizo** [comment]
@Narven no sorry, i was just trying what can be done with Aurelia that time ...
