### ISSUE TITLE
Unable to set Activationstrategy

### ISSUE THREAD

**Issue by LaevaertK** [aurelia/router#463]
**I'm submitting a bug report**

* **Library Version:**
Aurelia CLI 0.24.0

* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
3.10.10

* **Browser:**
Chrome 55

* **Language:**
TypeScript 2.1.5

**Current behavior:**
We want to set the activationStrategy to invokeLifecycle, but it does not work.

**Reproduce**
We created a new application through the Aurelia CLI, created a new page under src with contents:
```html
<template>FOO</template>
```
it's .ts file: 
```ts
export class tst{};
```

In our app.ts we define:
```ts
 import { Router, RouterConfiguration, activationStrategy } from 'aurelia-router';

export class App {
  message = 'Hello World!';

  determineActivationStrategy() {
    alert("tst");
    return activationStrategy.invokelifecycle;
  }

  public configureRouter(config: RouterConfiguration, router: Router) {
    config.map([
      { route: ['', 'foo'], name: 'foo', moduleId: 'tst', title: 'FOO', nav: true, }
    ]);
  } 
}
```
When navigating to the website, Hello word is displayed, as well as FOO. So the routing worked.
But we never hit the alert which is in our determineActivationStrategy function.

**Comment by EisenbergEffect** [comment]
That method is per-screen. So, you need to place it on the `tst` module, not on `app`.
