### ISSUE TITLE
deactivate and activate callbacks not triggered if reuse same moduleId on different routes

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/router#467]
**I'm submitting a bug report**

* **Library Version:**
1.1.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.3

* **Node Version:**
6.9.4

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
N/A

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Use same moduleId on different routes. Switching between routes doesn't trigger `deactivate` and `activate` callbacks.

**Expected/desired behavior:**
https://gist.run/?id=24bddb1ca8e502bcac280fbb3368dd30

* **What is the expected behavior?**
Expect `deactivate` and `activate` callbacks being called during switching route.

* **What is the motivation / use case for changing the behavior?**
To reuse same module with different routes, need to acquire dynamic route settings in `activate` callback.

**Comment by huochunpeng** [comment]
Right now, I bypass this issue by subscribe to event 'router:navigation:complete'.

**Comment by gbreeze** [comment]
have the same issue...

**Comment by Kukks** [comment]
try adding this in your VM:
```
  public determineActivationStrategy() {
    return activationStrategy.replace;
  }

```

**Comment by johot** [comment]
I found this the hard way today also... It must be a common scenario. I created a movie list page and wanted to have my navbar contain different categories. All should render using the same view-model. First tried to use different routes but found that `activate(...)` didn't fire. Then found a workaround using token parameters but then `row.isActive` stops working, I commented this in an existing issue https://github.com/aurelia/router/issues/433

This must be a common scenario and it's really hard to know how to do this "correctly". We should really update the docs if you need to do something special to get working. Will try the activation strategy tip but I would never find that method if I didn't come here, a person new to aurelia will easily get stuck.

**Comment by johot** [comment]
Just wanted to update and say that the `activationStrategy.replace` solved the problem! 

However... this is not mentioned in the documentation and I definitely think it must be emphasized!

You can read about it in the API documentation for now: `http://aurelia.io/hub.html#/doc/api/aurelia/router/1.2.1/interface/RoutableComponentDetermineActivationStrategy`

Hope this can be made easier or more clear in the future!
