### ISSUE TITLE
route-href params.bind parsing

### ISSUE THREAD

**Issue by erdoll** [aurelia/router#468]
'0B955A54-DC1D-46DB-8593-1D762E1AEBBB'

**I'm submitting a bug report**

* **Library Version:**
1.1.1 Aurelia Router
* **Operating System:**
Windows 8.1
* **Node Version:**
69.5
* **NPM Version:**
4.1.2
* **JSPM OR Webpack AND Version**
JSPM 0.16.51
* **Browser:**
Chrome 56 
* **Language:**
TypeScript 2.1 

**Current behavior:**
If you use route-href as:
  route-href="route: content; params.bind: {navigationId: 1234}"
it works just fine.  The 1234 is shown in the route URL and the param navigationId is available in the activate screen lifecycle hook as a string property of the params object

If you use route-href as: 
  route-href="route: content; params.bind: {navigationId: AAAA}"
The route URL does not contain the AAAA

If you use route-href as:
  route-href="route: content; params.bind: {navigationId: 0BCD}"
the following exception is thrown:
  Unhandled rejection Error: Parser Error: Missing expected } at column 17 in [{navigationId: 0BCD }]
which is not a helpful message for this problem.  The '0' is numerical zero.

If you use route-href as:
  route-href="route: content; params.bind: {navigationId: '0CDE'}"
then the route behaves correctly in the route URL and the params object in activate hook

**Expected/desired behavior:**
* **What is the expected behavior?**
1) I would have expected the parser to give the same parsing error for the AAA and 0BCD cases above.  
2) I would have expected a more informative error message for the 0BCD case.

* **What is the motivation / use case for changing the behavior?**
Motivation is to prevent a developer losing time figuring this out for themselves, (to add the quotes)  like I had to.

**Comment by EisenbergEffect** [comment]
AAAA is a valid property name. Since you are using a binding, it's looking for that property on the vie- model. So, no error. The second case, you've got an invalid JavaScript symbol, so it produces an error.
