### ISSUE TITLE
App refresh on url change via address bar, when pushState active

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/router#473]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.3

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Webpack**
webpack 2.1.0-beta.17

* **Browser:**
Chrome 56.0.2924.87

* **Language:**
ESNext

**Current behavior:**

Following the documentation I activated the pushState in latest aurelia-cli or skeleton:

```javascript
config.options.pushState = true;
config.options.root = '/';
```

```html
<base href="/">
```

When pushState **not** activated, I can change the url in address bar, press Enter and the page/route transition happens without app refresh, `http://localhost:9000/#/welcome` to `http://localhost:9000/#/users` for example.

With pushState activated, when the route changed in address bar, the full refresh of the app happens before transition.

**Expected/desired behavior:**

The refresh should not happen when pushState activated.

**Comment by PWKad** [comment]
Need a repro here I've just tested this and it works fine with pushState **provided you are using proper ways of generating href and not manually setting window.location properties**

Putting bold there in case anyone is doing that and stumbles upon this.

**Comment by matik12** [comment]
Hi @PWKad,

I found the same problem as @bsrdjan noticed related to pushstate and router. 
Here is a simple repo project based on aurelia-cli => [project.zip](https://github.com/aurelia/router/files/1051566/project.zip) .
Just install dependencies via **npm** and then run app with **au run** or **with --watch**. There are 2 simple links welcome and users, when clicking on these links everything works, but when you change route in browser and press enter then the whole app is reloaded i.e. change welcome to users. 
I checked this in chrome browser and with aurelia-router 1.3 to be more specific.  

Thanks for checking up on this,
Mat

**Comment by matik12** [comment]
Guys,

full page reload after changing url in browser bar - is this an issue or the expected behaviour when using push state? Yes, it works differently than in case of hash bang mode and window _hashchange_ event, so it may work as designed.

I am currently considering going with pushstate approach and I am not sure if it is working as the end user expects.

Thanks and take care,
Mat

**Comment by EisenbergEffect** [comment]
Yes. If you type it in like that, the browser has to refresh.

**Comment by matik12** [comment]
@EisenbergEffect thanks for your note. I updated my previous answer to include an explanation if someone else is checking up on this.

This issue can be close.
