### ISSUE TITLE
canDeactivate lifecycle callback invoked multiple times

### ISSUE THREAD

**Issue by simonfox** [aurelia/router#475]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

After upgrading to 1.2.0, the canDeactivate lifecycle callback is being invoked multiple times on the same VM instance. This commit is the cause 89ccf6e (if I rollback that change in my local aurelia-router 1.2 package the problem is resolved).

I can put together a repro later tonight if required?

**Comment by EisenbergEffect** [comment]
If you just want to create a PR to revert that, I can get the patch release out asap.

**Comment by EisenbergEffect** [comment]
Pushed a fixed out in 1.2.1.

**Comment by simonfox** [comment]
Awesome thanks @EisenbergEffect, too quick for me!

**Comment by simonfox** [comment]
Thought I should tag #464 here for anyone wondering what happened to that PR....
