### ISSUE TITLE
Can't navigate from child router configuration to an other child router configuration

### ISSUE THREAD

**Issue by dweber019** [aurelia/router#478]
**I'm submitting a bug report**

**Current behavior:**
Setup: I have a root router configuration with two routes `child-1` and `child-2` defined. Additionally `child-1` and `child-2` have also a router configuration with one additional route.

Here the example https://plnkr.co/edit/gGtBk8LAsu8KbUwLOEyE?p=preview
> Open dev-tools to the the error as not everything is loaded because of the bottom error.
> If the link in `child-1-sub.html` and `child-2-sub.html` is removed, then everything is working.

If I like to navigate from the sub route of the `child-1` route to the sub route of `child-2`, I'm having the following error:
```javascript
There is no route named child-2-sub
```

Also if I try to generate the URL with `router.generate(...)`, I'm having the same error.

I had a look into the router source code and there is the following line 220 in https://github.com/aurelia/router/blob/master/src/router.js#L220 and there is only parent handling.
So it will bubble up the router configuration tree but will not find anything because the desired route is in a other branch of the router configuration.

Conclusion: child route A routes aren't aware of child route B routes and therefor we have to use un save link paths.

**Expected/desired behavior:**
I like to use the router API like `navigateTo(..)` or even attributes like `route-href="..."` in the above situation/setup.

**Comment by dweber019** [comment]
Duplicate of #89

**Comment by EisenbergEffect** [comment]
Closing as duplicate.
