### ISSUE TITLE
Unable to redirect with params

### ISSUE THREAD

**Issue by nym** [aurelia/router#483]
**I'm submitting a feature request**
Redirecting with parameters does not work in the same way that directing with query parameters do.

**Given:**
{route: "path/to/:id/old", redirect: "path/to/:id/new"} 

**Expected:**
/path/to/9000/old ->
/path/to/9000/new

**Actual:**
/path/to/9000/old ->
/path/to/:id/new

From the source, it appears that query parameters are passed along as part of redirectLocation, but parameters are not being replaced despite being available in instruction.params.

https://github.com/aurelia/router/blob/90b1183648b804d52a57090e3a9ba34982a22097/src/navigation-plan.js#L28

**Comment by EisenbergEffect** [comment]
I agree, this would be a great feature. Any interest in working on a contribution to add it?

**Comment by nym** [comment]
@EisenbergEffect sure- is there an approach you would recommend? My initial thought was that parsing / replacing params in the section I listed would make sense, but a) want to make sure that is correct and b) is there something that is designed to do this already that I should reuse instead of writing regex to replace by :param/ with ${param}/ ?

Finally, what are the requirements for getting a PR accepted? I am going to try to do this over the weekend and want to do it right the first time.

cc @devanp92

**Comment by EisenbergEffect** [comment]
There are some existing APIs to help you out. You shouldn't need to mess with RegEx. Have a look at what happens with the basic route and you should be able to emulate the same thing.

**Comment by balazsmeszegeto** [comment]
@nym I'm interested in creating a PR for this, if you'd need help

**Comment by Alexander-Taran** [comment]
Can be closed
