### ISSUE TITLE
Issue with router when installed in as a sub site

### ISSUE THREAD

**Issue by stuartbloom** [aurelia/router#488]
I have the following setup; <My application is running off a sub site from the Default Web site in IIS.

I have the following:

`<base href="http://quality2012/portal/">`

```
  config.options.pushState = true;
  config.options.root = window.location.pathname;

  config.map([
    { route: ["", "dashboard", window.location.pathname], name: "dashboard", moduleId: "dashboard/index", nav: false, title: "Dashboard" },
    { route: ["requirements"], name: "requirements", moduleId: "requirements/index", nav: true, title: "Requirements", generationUsesHref: true, href: "requirements" },
  ]);
```
I am using generationUsesHref and href in the route as I need to set the correct URL based on the sub site; note that the application cnould and will be deployed on a number of sub sites so I need it to navigate to the correct site.

This works fine, so when I navigate to http://quality2012/portal my application loads, using navigation I can navigate to http://quality2012/portal/requirements.

The issue occurs when I hit F5.  Lets say I used navigation and I am currently here: http://quality2012/portal/requirements.  If I then hit F5, the application loads as expected, however, it has loaded the starting page and the url is as it was.  If I then use navigation to browse to requirements, the url shows as http://quality2012/portal/requirements/requirements, and I can continue adding requirements by hitting F5 and navigating to the page using the nav-bar.

I would expect that when I hit f5, the application will load and return to the page that was currently active and when I navigate i am navigating to the correct URL.

**Comment by EisenbergEffect** [comment]
Please ask this question in the gitter channel.
