### ISSUE TITLE
Call `setRouter` (if it exist) instead of setting `command.router` on `NavigationCommands`

### ISSUE THREAD

**Issue by Alxandr** [aurelia/router#49]
Currently, in the activation sequence of the router, if you return a `NavigationCommand` from any of the VM methods, the current router gets attached by way of `command.router = router`. This should instead be made into a optional method call, something like

```javascript
if (typeof command.setRouter === 'function') {
  command.setRouter(router);
}
```

**Comment by EisenbergEffect** [comment]
Got this fixed in 1e1c4d3b0389ad3725051a4c04c2482ea595eac1
