### ISSUE TITLE
feat(NavModel, AppRouter): Add DI container accessor

### ISSUE THREAD

**Issue by stsje** [aurelia/router#494]
**I'm submitting a feature request**

* **Library Version:**
1.3.0

**Expected/desired behavior:**
We would like to have custom DI configuration for each route, setting up each route as its own module.
We do not want to setup instances on the root DI container.

Custom module configuration could be made possible by adding a `moduleConfiguration` option to the RouteConfig.

It would be nice having a way of accessing the child DI container of the component being navigated to, could be added to the NavModel.

* **What is the motivation / use case for changing the behavior?**
Example of what we would like to accomplish:
```
import { module1Configuration } from 'module1-configuration';
import { module2Configuration } from 'module2-configuration';

export class App {
  configureRouter(config, router) {
    config.map([
      { route: 'module1', name: 'module1', moduleId: 'module1', moduleConfiguration: module1Configuration },
      { route: 'module2', name: 'module2', moduleId: 'module2', moduleConfiguration: module2Configuration },
    ]);
  }
}

export function module1Configuration(navigationInstruction) {
  let container = navigationInstruction.config.navModel.container;
  // ... setup module
}
```

**Comment by stsje** [comment]
I guess an even better way, would be if you could just add a decorator to your component like `@fooModuleConfiguration`

**Comment by jmvtrinidad** [comment]
You can use a [createChild](https://github.com/aurelia/dependency-injection/blob/master/src/container.js#L429) method to create a child container then use [registerSingleton](https://github.com/aurelia/dependency-injection/blob/master/src/container.js#L225) to register it. After you created and registered a new child container, now you can access it to your module. Somehow it can creates a namespace each route. I think this [issue](https://github.com/aurelia/framework/issues/427#issuecomment-221284897) is related on this.

**Comment by stsje** [comment]
@jmvtrinidad Each component already has its own child container as far as I know. It is this container that I would want to configure before the route is navigated to.
A solution using decorators would most likely be the best/easiest for the developer.

The suggested feature solution mentioned in the link you provided, does not just configure the child container as far as I can see.

**Comment by jmvtrinidad** [comment]
Do you have any idea on how to get those childContainer? as for now I do it using loaderStep, see pull #491. As I understand it, if I can get childContainer that is responsible for that route, I can pass it instead on loaderStep.

**Comment by EisenbergEffect** [comment]
Can you give a more concrete example of what you want to do with the container? Each route is created with a separate child container. It's possible with decorators to do some things already.

**Comment by jmvtrinidad** [comment]
As I understand it @stsje  he wants to configure per route so every plugin or element could only be available to that route. Maybe to avoid naming [collision](http://stackoverflow.com/questions/43012682/aurelia-how-to-add-binding-behavior-in-a-custom-element-and-within-its-own-names/43317977#43317977). 

@EisenbergEffect if per route creates a seperate child container, is it includes ViewResources per route? And also what do you mean by using decorators? Any link or code, thanks.

**Comment by EisenbergEffect** [comment]
The ViewResources is a dictionary of registered view-visible resources that are shared across all instances of the same view. So, that's not the best way to handle this.

What you would want to do is register certain items in the child container. You can control this by using Resolvers and the decorators that go with them, assuming this is related to objects being injected into the route view-model itself. Documentation on resolvers is here: http://aurelia.io/hub.html#/doc/article/aurelia/dependency-injection/latest/dependency-injection-basics/6 If none of the existing resolvers work for your scenario, you can create your own. It's a designed extensibility point.

If you need something somehow different, not related to view-model injection, the i need a few more details to understand the scenario and advise a course of action.

**Comment by jmvtrinidad** [comment]
For code example [given](https://github.com/aurelia/router/issues/494#issue-225917454) by @stsje , it is possible to access the child container per route (or child container) created by aurelia?

So aurelia knows how to identify where to add certain key in container (child) provided that it is the view-model for that route? How about component that created inside that route view-model itself, is all dependencies are created/added on that same child container?

**Comment by EisenbergEffect** [comment]
The child container creates the route vm. The vm itself can gain access to the child container by simply declaring a constructor dependency of `Container`. All components inside the view associated with the vm are created inside that same child container. The items that are injected into the constructor of the vm may be created in different ways depending on how they were registered and what, if any, resolvers were used in the declaration.

**Comment by jmvtrinidad** [comment]
@EisenbergEffect That was awesome, I never thought that it can be simple as that. Just like injecting Element in a custom attribute. (Although it seems there's no documentation that states that behaviour, or maybe it was not clear or I totally not understand when I've read it somewhere.)

One last thing, If I inject `ViewResources` on the same route view-model, does aurelia creates another child ViewResources or aurelia gives the same shared ViewResources?

**Comment by EisenbergEffect** [comment]
It's the shared resources.

**Comment by stsje** [comment]
I've tried to put together a gist that is a workaround for what we want.
https://gist.run/?id=c4c38922efde338f6d3d6148738d0f28

We don't want singletons. Every time the route is navigated to, we want a new instance of our models, services, whatever might contain route specific state.

We could use bindables, and bind our dependencies all the way down the DOM tree, but that can get messy.

**Comment by EisenbergEffect** [comment]
Have you tried using the `NewInstance.of()` resolver?

**Comment by jmvtrinidad** [comment]
@stsje You can also use [transient](http://aurelia.io/hub.html#/doc/article/aurelia/dependency-injection/latest/dependency-injection-basics/5) decorator as an alternative.

**Comment by stsje** [comment]
`NewInstance.of()` and `transient` will work as long as each component needs its own instance, but I need to share the same instance across all child components for this route.

**Comment by EisenbergEffect** [comment]
You can just use `singleton(Type, true)` on the classes that you want to be injected as singletons in the child container.

Example:

```javascript
@singleton(SomeService, true)
export class SomeService {
}

@inject(SomeService)
export class ARouteViewModel {
  constructor(service) { ... }
}
```

**Comment by stsje** [comment]
I'm not sure that will work. Each child component will have its own child container, in which you are registering the service. You then wont have a shared `SomeService` across child components for the route.

**Comment by EisenbergEffect** [comment]
Apologies, you are correct. What you want is a per-route scope. We don't provide that out of the box, but you can build that by creating a custom resolver. You basically want to create your own version of the `singleton` decorator and `SingletonRegistration` but that is route-based.
