### ISSUE TITLE
activationStrategy and determineActivationStrategy have no impact

### ISSUE THREAD

**Issue by stuartbloom** [aurelia/router#499]
I am attempting to get a VM to be replaced when the same VM is being navigated to.  however, adding either `activationStrategy` to the route in the configurations map or implementing a `determineActivationStrategy` method have no impact.  In-fact, the `determineActivationStrategy` method within the VM does not appear to be even called.

**Comment by stuartbloom** [comment]
Here is an example VM that does not work:
```
import { activationStrategy } from "aurelia-router";

export class TestVM {
    constructor() {
        console.log("in constructor");
    }

    determineActivationStrategy(params: any, routeConfig: RouteConfig, navigationInstruction: NavigationInstruction): string {
        console.log("in determineActivationStrategy");
        return activationStrategy.invokeLifecycle;
    }
}
```

and the route is configured as:
`{ route: ["testvm"], name: "testvm", moduleId: "testvm/index", nav: true, title: this.appService.i18n.tr("common:navigation.testvm"), generationUsesHref: true, href: "testvm" }`

**Comment by EisenbergEffect** [comment]
This is odd. I just built an app this week that uses this and had no issues. Can you double check to make sure that all your libraries are up to date?

**Comment by stuartbloom** [comment]
@EisenbergEffect I can certainly do that when I get to my coffee on the morning. Any library in particular?

**Comment by EisenbergEffect** [comment]
Definitely check router, templating-router, history-browser and route-recognizer. Those are all the pieces typically related to the routing infrastructure. You might want to check templating and binding as well. If that doesn't fix it, then I'll see if I can repro it in a fresh project. Let me know.

**Comment by stuartbloom** [comment]
@EisenbergEffect here are the versions of my libraries:
router: 1.3.0
templating-router: 1.1.0
history-browser: 1.0.0
route-recognizer: 1.1.0
templating: 1.4.2
binding: 1.2.1

I have even deleted my node_modules and installed everything again, but no joy :(

**Comment by StrahilKazlachev** [comment]
@stuartbloom If you prepare a repro I can take a look - preferably a github repo.

**Comment by stuartbloom** [comment]
thanks @StrahilKazlachev that is exactly what I am doing :)

**Comment by stuartbloom** [comment]
@StrahilKazlachev @EisenbergEffect I have greated a repo [here](https://github.com/stuartbloom/TestVM/tree/master)  it only has three views and models.  a very simple navigation.  click on any of the routes and they work fine; clicking on the route that is currently selected and nothing changes and no output from the `determineActivationStrategy` method.

Thanks for your assistance

**Comment by stsje** [comment]
The thing is that the VM won't be replaced when the url isn't changed. You are navigating to the same route without changing any parameters, which will have no effect.
A possible solution might be having the `replace` option available on the `route-href` attribute?

**Comment by stsje** [comment]
Also, are there any difference in behaviour when using push-state and hash in this case?

**Comment by stuartbloom** [comment]
@stsje I think you may have just given me a hint.  i have updated the repo, and now I do see the determineActivationStrategy get called and then the constructor for the VM. I will leave this open until I move the code to my actual project, but thanks for the hint :)

**Comment by stuartbloom** [comment]
@stsje Thank you so very much. I now have it working :)

in the nav, i have the following:
`<a href="#" click.delegate="goToRoute(row.href)">${row.title.toUpperCase()}</a>`

and then in the navs vm I have
```
    private goToRoute(route) {
        this.router.navigateToRoute(route, {}, { replace: true });
    }
```
Now  the determineActivationStrategy does get called and my VMs get reset.

Thank you :)

@EisenbergEffect @StrahilKazlachev Thank you also for looking into this guys; most appreciated :)
