### ISSUE TITLE
Router refactoring

### ISSUE THREAD

**Issue by Alxandr** [aurelia/router#50]
I named this issue rather ambiguously because it will be covering a few points that I find somewhat hard to take apart, or name properly.

Currently, when you call `router.navigate` it does all of the work, and builds a instruction that is sent through the router pipeline. The `Redirect` navigation command is a simple wrapper around this call.

I propose inverting this relationship, and renaming `Redirect` to `NavigateCommand`, and adding a new method to the router named `process`, that would work as following:

The `router.navigate` would be turned into a simple convenience method, simply calling

```javascript
navigate(url, opts) {
  var cmd = new NavigateCommand(url, opts, this);
  this.process(cmd);
}
```

The `process` command would simply forward the call to the App Router, which in turn would invoke

```javascript
process(navigationCommand) {
  navigationCommand.navigate(this);
}
```

And the functionality that is currently in the `navigate` method would be moved to the `NavigateCommand` class instead. This would enable one to create their own navigation commands, that did other things (and could even extend `NavigateCommand` to make things such as `NavigateToLoginCommand` that handled capturing return address etc.).

**Comment by Alxandr** [comment]
Oh, and btw, `RedirectCommand` should also be added (given that it does redirect, instead of navigate). However, with this architecture it could be created really simple like this:

```javascript
class RedirectCommand extends NavigateCommand {
  constructor(url) {
    super(url, { trigger: true, replace: true });
  }
}
```

**Comment by Alxandr** [comment]
Oh, and a point that just popped up from a user that was trying to call `navigate` from within `activate`, any call to `process` should cancel out any currently ongoing navigation commands.

**Comment by EisenbergEffect** [comment]
@bryanrsmith After the current set of changes you are working on, I'd like to look again at this issue and see if this would be advantageous and what the level of effort would be.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Please make a final review of this and see if we want to do this re-design or if you think it's ok the way things are.

**Comment by bryanrsmith** [comment]
I do like the proposal, and we could do it fairly easily, but I think it's relatively low value at this point. router.navigate doesn't really have much control either-- it delegates directly to the history implementation. I think we can leave it the way it is for now. We can make it a nonbreaking change if we decide to do it in the future.
