### ISSUE TITLE
Allow navigation from to be executed from the app router

### ISSUE THREAD

**Issue by Alxandr** [aurelia/router#51]
Currently, if you do `router.navigate('foo')`, it redirects you relative to that router (as it logical), but there should be some way to tell it to redirect you to `foo` relative to root. I suggest this can be done in two manners. One, with the options object passed to navigate (something like `router.navigate('foo', {useAppRouter: true})`), and `router.navigate('/foo')` where the slash at the beginning indicates I want it to be from the root.

I also think that the `useAppRouter` should take precedence over the slash start though, so that if you explicitly set `useAppRouter: false`, and pass in `/foo` it would still redirect relative to the router. I can't really picture a use-case for it, but I'm sure somebody can, and I don't really see a reason it shouldn't be supported.

**Comment by Alxandr** [comment]
As far as I can see, your commit does not deal with `navigate('/foo')` (url's starting with `/`).

**Comment by EisenbergEffect** [comment]
No, I'm not changing the '/' aspect at this time. I will consider this for the future.

**Comment by Alxandr** [comment]
Fair enough. I'll make a new issue for it then, so it at least get's tracked.
