### ISSUE TITLE
router.Navigate returns a promise, not a boolean

### ISSUE THREAD

**Issue by niemyjski** [aurelia/router#518]
I'm using latest stable versions of Aurelia...

I'm seeing the router.navigate('route') return a promise and not a boolean result. Is this to be expected? From what I've seen doing research it returns what ever is returned by the history implementation. Should the typescript definition be updated? It's a bit hard to work with atm.

**Comment by niemyjski** [comment]
@EisenbergEffect do you have any idea on this one? Seems like it either returns a promise and in some cases a boolean? Still trying to track down the use cases where each one is returned differently..

cc: https://github.com/aurelia/framework/issues/226

**Comment by niemyjski** [comment]
Using Html5 push state causes `Aurelia-history-browser` to always set a route handler 

```
    config.options.pushState = true;
    config.options.root = '/';
```

```
  AppRouter.prototype.activate = function activate(options) {
    ....
     this.options = Object.assign({ routeHandler: this.loadUrl.bind(this) }, this.options, options); //<-- Promise
  };
```

```
  BrowserHistory.prototype._loadUrl = function _loadUrl(fragmentOverride) {
    ...
    return this.options.routeHandler ? this.options.routeHandler(fragment) : false; <-- Promise
  };
```

**Comment by davismj** [comment]
@niemyjski Were you able to create a repro of the issue?

**Comment by Alexander-Taran** [comment]
can be closed
https://github.com/aurelia/router/pull/544
