### ISSUE TITLE
Set default for view-port or programmatically set view-port?

### ISSUE THREAD

**Issue by djensen47** [aurelia/router#526]
I have a view-port for the toolbar in my application. Several of my routes use the same toolbar and I would like to remove the redundancy in route config.

1. Is there a way to set a default moduleId for a view-port (if not I might open a new issue for this one). So if it's not defined, instead of an error, it fills in with the default.

2. Can I programmatically insert a view-port?

I tried this one but unsuccessfully. I added a preActivateStep and tried both `navigationInstruction.addViewPortInstruction` and `navigationInstruction.config.viewPorts.toolbar = ` but it didn't work.

Thanks in advance!

**Comment by djensen47** [comment]
BTW, I tried asking on the gitter channel with no response. Also, maybe I should've tried Stackoverflow but I kinda feel like that's a blackhole unless it's for a popular framework. If there were a forum, I would ask there. Thanks for the great project and community around it!

**Comment by davismj** [comment]
This isn't exactly a duplicate, but as we discussed in chat, I think this dovetails with this issue: https://github.com/aurelia/router/issues/482. Moving the conversation there.
