### ISSUE TITLE
Missing a way of accessing child routes

### ISSUE THREAD

**Issue by tbnovaes** [aurelia/router#537]
**I'm submitting a bug report**

* **Library Version:**
1.4.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13

* **Node Version:**
8.1.3

* **NPM Version:**
5.4.2

* **JSPM OR Webpack AND Version**
aurelia-cli 0.31.3

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
There is no way to access the child routes. If I use `repeat.for="row of router.navigation"`, the only routes available are the main routes.

**Expected/desired behavior:**
Be able to access the children routes. For instance, if I want to create a top navbar with the parents, and list the children routes on a sidebar.

I would expect to be able to do something like

```
<ul repeat.for="row of router.navigation">
    <li repeat.for="child of row.children" if.bind="row.isActive"><a href.bind="child.href">${child.name}</a></li>
</ul>
```        

* **What is the expected behavior?**
Be able to easily iterate on the children routes marked with nav:true

* **What is the motivation / use case for changing the behavior?**
Had to do it the other day to create a really simple menu using parent/child, and the only workaround was to bind the child route to the owningView. Which takes much more time, it is much harder to keep track when you have many routes, and generates duplicated code.

**Comment by gheoan** [comment]
This has been discussed in https://github.com/aurelia/router/issues/90.
