### ISSUE TITLE
Consider using "URI" instead of "URL" for consistency with other projects

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#54]
This project and aurelia/templating both use the term "URL" in API properties and methods, but aurelia/http-client uses "URI". It would be great to pick one and use it consistently across all projects.

**Comment by bryanrsmith** [comment]
@EisenbergEffect What do you think about this? I can rename things if we pick one. I think most Aurelia projects are using "URL", but HttpClient uses "URI". The inconsistency is bothering me ;-)

**Comment by EisenbergEffect** [comment]
It would be nice to be consistent. Do you have a list of the places where URL is used in stead of URI?

**Comment by bryanrsmith** [comment]
http-client is the only project using "URI". browser-history, loader, loader-default, path (private variables only), router, and templating all use "URL". Most of these projects only use it in a couple identifier names for public properties or method parameters. router has quite a few, though.
