### ISSUE TITLE
Nothing is passed to a child router's layout's activate method's 'param' parameter

### ISSUE THREAD

**Issue by thinkOfaNumber** [aurelia/router#546]
**I'm submitting a bug report**

* **Library Version:**
aurelia-router 1.4.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
v8.6.0

* **NPM Version:**
5.4.2

* **JSPM OR Webpack AND Version**
webpack 2.5.0

* **Browser:**
Chrome 61.0.3163.100

* **Language:**
TypeScript 2.2 & JS

**Current behavior:**
When using layouts in child routers, and `layout-model.bind=...` nothing is passed to the child router activate method's 'param' parameter. (It works for the base layout).

**Expected/desired behavior:**

To reproduce:
1. Create a root router and a child page with `configureRouter()`
1. create layouts for both the root page and the child page
1. in each router-view element, include the `layout-model.bind="something"` attribute and bind to a property of the view-model containing the layout
1. in each layout view-model's activate method, get the 'param' as bound

Currently, the root layout activate param is passed, but child layout activate params are undefined.

Gist run here:
https://gist.run/?id=74d33945221dd5fa6aa01b42d310f097

* **What is the expected behavior?**
I would expect all layouts to work the same.

* **What is the motivation / use case for changing the behavior?**
To make layouts consistent, regardless of use in "root" or "child" routers.

**Comment by rdemetrescu** [comment]
I don't if it is related, but I am also having issues with child routes && router-view with layout.

Attaching a demo project. Try enabling "custom layout" and clicking on Page 1-4 from Child 1-2.

`Error:  ERROR [app-router] Error: Unexpected token`

[test.zip](https://github.com/aurelia/router/files/1415494/test.zip)

**Comment by thinkOfaNumber** [comment]
@rdemetrescu a gist would be super-useful...

**Comment by rdemetrescu** [comment]
@thinkOfaNumber , I hope this help:

https://gist.run/?id=6548f9f63d484175b8182c83520bc5e7

You should see errors on console when trying to access pages 1-4 with custom layout enabled.

**Comment by rdemetrescu** [comment]
Now here is the funny thing. The same demo, but with a flatten structure. Everything runs fine.

https://gist.run/?id=2cbb0255f2077c30921810bff766de3c

**Comment by thinkOfaNumber** [comment]
I think it's a different issue. I couldn't figure out why and I use slightly different paths.

I've also just realised I've linked to the wrong gist in my bug report...

**Comment by thinkOfaNumber** [comment]
OK something is going wrong with gist.run and gists... I create a new fork of my own gist and it somehow overwrites an old one, so I create a new fork of the original gist, and now my original is gone! With no history... sorry, it took me a while to build that gist, so I'll have to try again when I have time.

**Comment by thinkOfaNumber** [comment]
I think I was misunderstanding the activate() params on a layout view-model. They're not "page" params, it's a model property like a dialogs activate method.

i.e. if I specify the route like this:

    config.map([
        {
            route: '', name: '...',
            layoutView: 'split-form-layout.html', layoutViewModel: split-form-layout', layoutModel: 3,
            moduleId: '...', nav: true, title: "..."
        }
    ]);

then the class in `split-form-layout.ts` should have an activate method that get's the number 3 as the first parameter.
