### ISSUE TITLE
Bind model data to Aurelia route in router config

### ISSUE THREAD

**Issue by nashwaan** [aurelia/router#549]
Suppose I have following 2 routes configurations that are using same module `./foo`.html:

```js
export class App {
  configureRouter(config, router) {
    config.map([
      {route: 'foo1', name: 'foo1', moduleId: './foo.html', nav: true, title: 'Foo1'},
      {route: 'foo2', name: 'foo2', moduleId: './foo.html', nav: true, title: 'Foo2'}
    ]);
  }
}
```

And I have `foo.html` custom element:

```html
<template bindable="grade">
  Grade is: ${grade}
</template>
```
Then, how can I bind `{grade: 'A'}` model to `foo1` route and bind `{grade: 'B'}` model to `foo2` route?

I was expecting that there is something like `model` property that I can bind my model to each route like the following:

```js
{route: 'foo1', name: 'foo1', moduleId: './foo.html', model:{grade: 'A'}, nav: true, title: 'Foo1'},
{route: 'foo2', name: 'foo2', moduleId: './foo.html', model:{grade: 'B'}, nav: true, title: 'Foo2'}
```
But this didn't work.

----------

Note, I don't want to pass any data via `settings` property of a route config because I will lose some advantages that comes with `bindable` technique. For example, the above `foo` component can be reused as an element in html view like:

```html
<div>
  blah blah
  <foo grade.bind="'C'"></foo>
</div>
```

If this is not supported already, then may I ask to support this as a new feature.

**Comment by bigopon** [comment]
With the current behaviour of `router-view` (striping container element) you will likely have unwanted result anw. Maybe wrap foo in a lightweight route element ?

```html
<template>
  <require from="foo.html"></require>
  <foo></foo>
</template>
```

**Comment by powerbuoy** [comment]
I've done exactly this by checking inside activate() whether the routeConfig (second argument to activate) has any modelData and if so assigning it to my bindable properties.

**Comment by davismj** [comment]
@nashwaan You wouldn't want to use a custom element view for a route, in general. You might find a special case where this makes sense, but in general it's a bad idea and should be avoided. Instead, keep your routes and custom elements separate.

**app.js**
```
export class App {
  configureRouter(config, router) {
    config.map([
      {route: 'foo1', name: 'foo1', moduleId: './foo1', nav: true, title: 'Foo1'},
      {route: 'foo2', name: 'foo2', moduleId: './foo2', nav: true, title: 'Foo2'}
    ]);
  }
}
```

**foo1.js**
```
export class Foo1ViewModel {
  activate() {
    this.grade = 'A';
  } 
}
```

**foo1.html**
```
<template>
  <foo grade.bind="grade"></foo>
</template>
```
