### ISSUE TITLE
Support navigating to named routes

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#55]
Possibly related to #4. I think it's relatively rare to actually have a URI when you need to navigate within an app, and building URIs is a pain. It would be great if the router provided a convenience method similar to `router.navigate()` that took a route name and a route params object and built the URI for you.

```javascript
router.navigateToRoute('user-details', { userId: '123', foo: 'bar' }, { replace: true });
```

This would probably require a new (optional?) `name` property on configured route objects.

**Comment by EisenbergEffect** [comment]
It already exists actually. It called `generate`. It takes a route name and a params object :) What we need is to build an attached behavior on top of that so we can generate routes into the html easily, based on the current scoped router. We've got an issue tracking that.

**Comment by bryanrsmith** [comment]
Sure enough. I'm not sure how I missed that. Thanks!

**Comment by teejdotme** [comment]
Sorry to comment on a closed issue, but I've run into confusion around this same topic.  I did find the generate function some time ago, but it seems that it will never produce a URI.  The route recognizer always has a names object with no properties, so every call to generate results in an exception.  I've tried checking the recognizer for every parent up the chain (I have a number of child routers configured) and none of them have names configured.  I've spent time digging through the code, trying to understand how the recognizer will come to have names associated with routes, and it seems the I'm missing something.  Could somebody please explain how the router should be configured such that  generate calls will be successful?

**Comment by bryanrsmith** [comment]
Actually, I can't get it working either. `RouteRecognizer.add(routes, options)` [looks for `options.as`](https://github.com/aurelia/route-recognizer/blob/master/src/index.js#L366), but the router doesn't seem to ever include that parameter. It looks like the router [ensures each route does have a name](https://github.com/aurelia/router/blob/master/src/router-configuration.js#L100), but from what I can tell it's never used.

@EisenbergEffect This seems like a bug. Can you confirm, or are we just misunderstanding? What route configuration would you expect to result in properly named routes?

I could probably work on fixes if necessary, and [tests](https://github.com/aurelia/route-recognizer/blob/master/test/route-recognizer.spec.js#L4). :-)

**Comment by bryanrsmith** [comment]
@EisenbergEffect Great, thanks. I'll try to dig in to it tonight or this weekend.

**Comment by teejdotme** [comment]
Thanks guys for looking into this!
