### ISSUE TITLE
Router options are reset after configuring

### ISSUE THREAD

**Issue by gheoan** [aurelia/router#550]
**I'm submitting a bug report**

* **Library Version:**
1.4.0

* **Browser:**
tested in Chrome 62 | Firefox 57

* **Language:**
TypeScript 2.6

**Current behavior:**
`router.options` are reset after configuring.

```javascript
export class App {
  configureRouter(config, router) {
    this.router = router;
    router.options.compareQueryParams = true;
    config.mapRoute({
      route: '',
      moduleId: 'home'
    });
  }
  
  attached() {
    console.log(this.router.options.compareQueryParams); // undefined
  }
}
```

**Expected/desired behavior:**

* **What is the expected behavior?**
Here is a demo: https://gist.run/?id=3f3b4a9e1116c29fb09bb67c7a7435d2.
Options is `undefined` in console. It should be an object with the options.

* **What is the motivation / use case for changing the behavior?**
Changing the router options.

**Comment by gheoan** [comment]
The route recognizer fails this simple test. Should this scenario be supported?
```javascript
  it(`matches paths with query`, () => {
    let recognizer = new RouteRecognizer();
    recognizer.add([
      {
        path: '?a',
        handler: { name: 'a' },
        caseSensitive: true
      },
      {
        path: '?b',
        handler: { name: 'b' },
        caseSensitive: true
      }
    ]);

    let result = recognizer.recognize('?b');
    expect(result.name).toBe('b'); // result is undefined
  });
```

**Comment by fkleuver** [comment]
@davismj Can close this one then :)

**Comment by davismj** [comment]
@fkleuver thanks!
