### ISSUE TITLE
useViewPortDefaults already in docs but not in 1.4.0 stable release

### ISSUE THREAD

**Issue by thomaskonrad** [aurelia/router#567]
The `useViewPortDefaults` feature is [already documented](http://aurelia.io/docs/routing/configuration#rendering-view-ports) but it is not shipped with the 1.4.0 release, which is kind of weird and inconsistent.

**Comment by AlainBaslter** [comment]
Hi @thomaskonrad 
Why are you trying to use this?
Is it because you ran into the issue that moduleId: null throws an error like I did?
I thought of using useViewPortDefaults as a work around but if this also does not work we are stuck.

**Comment by thomaskonrad** [comment]
@AlainBaslter, no, I just wanted to create a master-detail view with two router outlets and wanted to set a default content for the detail view.

**Comment by davismj** [comment]
@thomaskonrad Sorry Thomas. There have been changes to the way docs are generated. I wrote the docs for 1.5.0 but committed them too soon. This change is getting prepped for release as we speak. Stay tuned.
