### ISSUE TITLE
ERROR [app-router] Error: Invalid argument.

### ISSUE THREAD

**Issue by sagomanoj** [aurelia/router#569]
My **Aurelia** application is working fine Chrome, Firefox and NOT working in IE. 
I'm getting **ERROR [app-router] Error: Invalid argument**. and also **ERROR [app-router] Router navigation failed, and no previous location could be restored.**

Thanks in advance.

**Comment by davismj** [comment]
This is likely not related to the router. This error means that the router tried to load the module but an error was thrown. Try debugging into the module you're trying to load.
