### ISSUE TITLE
Router.title is used but not defined in the Router class

### ISSUE THREAD

**Issue by dkent600** [aurelia/router#573]
**I'm submitting a bug report**

* **Library Version:**
current, see permalink in expected behavior

**Current behavior:**

This line in `RouterConfiguration` sets `Router.title`:

https://github.com/aurelia/router/blob/c1720c4fc911f58fb9233ae88f182f2256a19d67/src/router-configuration.js#L165

**Expected/desired behavior:**
`Router.title` is not defined in the Router class, nor is it mentioned in the d.ts or Aurelia APi documentation.

* **What is the expected behavior?**
`Router.title` should either not be used anywhere, or it should be defined in the Router class, and be mentioned in the d.ts and Aurelia APi documentation.

* **What is the motivation / use case for changing the behavior?**
So I can reference Router.title in my typescript code without compiler/intelliense errors and hacking my code.

**Comment by Alexander-Taran** [comment]
What kind of help is wanted?
Seems like a simple case if help wanted in adding typings.

**Comment by davismj** [comment]
Just needs to be added to the jsdoc.

Here:

https://github.com/aurelia/router/blob/c1720c4fc911f58fb9233ae88f182f2256a19d67/src/router-configuration.js#L165

Like this:

https://github.com/aurelia/framework/blob/master/src/framework-configuration.js#L118-L121

**Comment by dkent600** [comment]
@davismj would your suggested fix result in `title` winding up in the d.ts?

**Comment by davismj** [comment]
Yes. You can test it by running gulp doc.
