### ISSUE TITLE
util Functions Missing from TypeScript Definition File

### ISSUE THREAD

**Issue by alienriver49** [aurelia/router#581]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.2

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
all

* **Language:**
TypeScript 2.7.1

**Current behavior:**
I feel kind of silly opening this ticket, but the utility functions (in util.js) are missing from the TypeScript definition file. So, when attempting to import them into a TypeScript file within my project, I get the "no exported member" TS error. I know they are there, are exported, and available for use, but when building my application it's going to throw an error.

**Expected/desired behavior:**

* **What is the expected behavior?**
util.js function definitions are exported with the TypeScript definitions file.

* **What is the motivation / use case for changing the behavior?**
I've written a light-weight router, which uses Aurelia history, for an application framework I've been developing and would like to use the router util functions for helping to form URLs to pass to history's navigate function.

**Comment by Alexander-Taran** [comment]
@alienriver49  Would you be willing to provide a PR for that?

**Comment by alienriver49** [comment]
Most certainly! I was playing around with getting those function definitions into the .d.ts file earlier, so I'll see what I can come up with. I'll get a pull request out tomorrow.

**Comment by Alexander-Taran** [comment]
@alienriver49 and also don't hesitate to ask if you need any help with that (-:

**Comment by alienriver49** [comment]
@Alexander-Taran Awesome thanks! So it looks like this repo is using babel-dts-generator to generate the .d.ts files and that has a memberOutputFilter to not output members beginning with '_', which explains why those functions aren't exported in the type definitions. Most Aurelia repos seem to use babel-dts-generator with the same settings, the one repo I've seen not use it (where useTypeScriptForDTS is set to true) is aurelia-dependancy-injection. Instead of filtering all _ members, that restricts it by marking members with an @internal JSDoc flag and they are then excluded from the type definition. I've started down that road of setting useTypeScriptForDTS to true, but wanted to make sure that seems right. I'm going to try to get the .d.ts file to be close to the same, but there are certainly differences between that babel-dts-generator and the TS one.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect  I guess now is the time we ask someone from the core team to chime in.

If the team is ok with changing the process of generating d.ts?

What would be sensible exports from util useful for more than just you @alienriver49?
could we wrap those internal properties with public getters?

I'd be sad to see you invest your time in something that would not get merged.

**Comment by alienriver49** [comment]
@Alexander-Taran I agree, I think that changing the type declaration file might be overkill. I would also be fine with the exporting of a resolveUrl which just calls _resolveUrl or just renaming _resolveUrl to resolveUrl.  I would be interested in the core teams input as well. We internally use _'s to denote private functionality as well, so I understand, maybe there is another route (haha) I should be taking.

**Comment by EisenbergEffect** [comment]
For the router, the original code was written with Babel as the target transpiler. We used flow types and then wrote a plugin to generate d.ts files. We had a convention that private members/exports were named with a `_` prefix and so would be filtered out of the public API. We can add these to the API, but I'd want to defer to @davismj on whether he is ok with supporting that.

**Comment by jemhuntr** [comment]
On a related note, `RouterConfiguration.titleSeparator` also isn't on the type definitions.

Not exactly the same as the OP's issue, but I think this is related and could be included in a single PR.

**Comment by bigopon** [comment]
The utility functions aren't supposed to be exported. For typings, it's now fixed with the latest release, I think we can close this.
@alienriver49 may I know what you want the util functions for?

**Comment by alienriver49** [comment]
Hey @bigopon, so we wrote an application portal framework similar in architecture to the Azure portal, but with Aurelia instead of Knockout. One of the early requirements was routing that would simply pass the route change to a command manager that would then execute the command based on the route information.

Due to this, I ruled out aurelia-router due to it's coupling between the routes and view-models, which in our case we don't have in a traditional sense, we just need it to handle route changes and let us know when and what changed. I did this using aurelia-history and created my own router, though as time went by I needed it to handle more scenarios, one of those being to generate URLs which would be acceptable by our router. Since our router was using aurelia-history's navigate function, I figured it would be best to use the same functionality that aurelia-router uses to normalize / resolve / generate it's URLs.

We started this framework around two years ago and that's when we created our initial router and I ran into the need for the URL generation a little over a year ago, so there very well could be functionality in aurelia-router that would allow us to accomplish what we were looking to do with more flexibility. Looking around, I might be able to accomplish my needs using aurelia-router with something like:
```
configureRouter(config, router) {
  config.map([
    { route: '*commands', moduleId: 'command-manager' }
  ]);
}
```

I know that this functionality has been around for a while, but I've learned a lot in two years and didn't quite think about it like this two years ago.

I'd be interested if you have any thoughts and you are good to close this. Thanks!

**Comment by alienriver49** [comment]
So I just gave this a try and that works quite well, I'm able to use the command loader to hook into all my logic for loading of commands. I really like the idea of using the aurelia-router instead of rolling my own. I am running into one issue though, route-href doesn't work with any of my URLs, I get:
```
aurelia-logging-console.js:52 ERROR [route-href] Error: A route with name 'Testing/Extension/Table' could not be found. Check that `name: 'Testing/Extension/Table'` was specified in the route's config.
    at AppRouter.generate (aurelia-router.js:940)
    at eval (route-href.js:71)
```

The HTML looks like:
```
<a title="Table" route-href="Testing/Extension/Table" class="mdc-list-item au-target" au-target-id="20">
    <span class="mdc-list-item__text">Table</span>
</a>
```

In this case, I would assume this would still be a valid route since I'm wildcarding all routes, so it should just take that route above and normalize it. Would you agree with that? I also did some research if I added an extra route like:
```
{ route: 'Testing/Extension/*parts', moduleId: './parts-loader' },
```

This still runs into the same issue, so I'm thinking that the route-recognizer doesn't handle the matching of wildcard routes. If you agree, I can open an issue in aurelia-route-recognizer and we can continue the discussion there.

**Comment by bigopon** [comment]
@alienriver49 `route-href` works based on name, so when you pass a literal string to it, it tries to find the route with that string from injected router.

**Comment by alienriver49** [comment]
Okay that makes sense. I gave my route the name of 'command' and changed the route-href to be:
```
route: command; params.bind: {command: "Testing/Extension/Table"}
```

This works! So, I'm all set.

**Comment by bigopon** [comment]
That's great to hear. I think we can close this issue then @alienriver49 ?

**Comment by alienriver49** [comment]
We can, closing with this comment, thanks for all the help!
