### ISSUE TITLE
How to make responsive design using Aurelia JS. 

### ISSUE THREAD

**Issue by jaipundir** [aurelia/router#584]
I have use CSS for responsive design but now my concern that how it is possible with aurelia js.
I have no code for showing so please help me .

**Comment by Alexander-Taran** [comment]
You better file this one @ https://discourse.aurelia.io

It’s a community forum

**Comment by Alexander-Taran** [comment]
Can be closed

**Comment by EisenbergEffect** [comment]
Closed since questions should go to the discourse rather than via issues.
