### ISSUE TITLE
Multiple instances of aurelia-router installed by npm

### ISSUE THREAD

**Issue by mattgaspar** [aurelia/router#587]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.11.1

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack 3.5.5

* **Language:**
TypeScript 2

**Current behavior:**
Occasionally npm installs 2-3 instances of aurelia-router
One instance at the top level of node_modules and a second/third at the following locations:
\node_modules\aurelia-bootstrapper\node_modules\aurelia-router
\node_modules\aurelia-templating-router\node_modules\aurelia-router

The primary issue this causes is when using `router.navigateToRoute('route-name')`
Error in console: `A route with name 'xxx' could not be found. Check that `name: 'order-details'` was specified in the route's config.`
Problem occurs when being used from a view other than the one that the router is configured in.
A different instance router gets injected into the view model.

* **What is the motivation / use case for changing the behavior?**
This seems like an issue with npm dedupe not working correctly but wanted to list the issue here as maybe having 'aurelia-router' as a peer dependency in aurelia-bootstrapper would be appropriate.
And also to help anyone else that encounters this issue.  I have had this come up 2-3 times now and it creates quite a headache until I realize the issue. (which hopefully I'll spot sooner now!)

The solution is to simply delete the duplicate package(s) from the nested node_modules folders.

Similiar issues on Github under webpack and npm
https://github.com/webpack/webpack/issues/5593
https://github.com/npm/npm/issues/20026

**Comment by davismj** [comment]
Appreciate the heads up.

**Comment by Alexander-Taran** [comment]
@mattgaspar could you recheck with latest stable version of npm?
5.6 is known to have a lot of problems with figuring out the dependency graph etc

**Comment by caseycarroll42** [comment]
I saw this with Axios in one of my company's projects. I was able to import only one instance of axios by setting an alias:

```javascript
...
        resolve: {
            alias: {
                axios: path.resolve(__dirname, 'node_modules/axios'),
            }
        },
...
```
This made all instances where axios is referenced point to the instance of axios that exists at the top level of `node_modules` instead of at the referencing module level. i.e. `node_modules/some_module/axios`.

**Comment by Alexander-Taran** [comment]
@bigopon  can be closed.. I think.
