### ISSUE TITLE
router.navigation includes invalid hrefs when using nav:true on a dynamic route

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#59]
If you fail to specify an `href` on a route using `nav: true`, the default is to [copy the route pattern](https://github.com/aurelia/router/blob/master/src/router.js#L219-L222), which may include dynamic segments. This will result in invalid hrefs being included in navigation links.

Eg, changing [this skeleton-navigation route](https://github.com/aurelia/skeleton-navigation/blob/master/src/app.js#L13) to
```javascript
{ route: 'flickr/:tag', moduleId: './flickr', nav: true }
```
will result in `<a href="/flickr/:tag">Flickr</a>` in the skeleton's navigation menu.

I think the router should protect users from such mistakes, and ideally never return a bad href. We could...

1. Validate the route config and throw an error if  `nav: true` appears on a dynamic route,
2. Silently ignore the `nav: true` on dynamic routes,
3. Maybe try to run `.generate()` on the navigation routes using the current or parent context? This is probably too error-prone to use.

**Comment by EisenbergEffect** [comment]
I like the idea of throwing an error if there's no href on a dynamic router marked with nav:true. What do you think? Want to work on it. Your work has been fantastic so far :)

**Comment by bryanrsmith** [comment]
I agree, and should be able to take care of this tonight. I think stricter validation with helpful errors is better than potentially surprising behavior. What's the reason for allowing a navigation href to differ from the route path? Shouldn't they always be static, and always be the same?

Thank you for the compliment. I've found the codebase very approachable and well-organized :-)
