### ISSUE TITLE
Navigating to a bookmark at the same path, but different query string doesn't re-active the route

### ISSUE THREAD

**Issue by jfstephe** [aurelia/router#593]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre
1.5.0

**Please tell us about your environment:**
* **Operating System:**
Ubuntu

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
jspm 0.16.53

* **Browser:**
all

* **Language:**
typescript 2.3.3

**Current behavior:**
From this Gist: https://gist.run/?id=e659e4d172030613182570ed5f30792f

Bookmark this URL (note query string param 'james')
https://gist.host/run/1525080780447/index.html#/profile/account/username?username=james

Now go to  (note query string param 'john')
https://gist.host/run/1525080780447/index.html#/profile/account/username?username=john

Then open the bookmarked page ('james') in the same tab. The URL changes but no navigation events occur.

**Expected/desired behavior:**
* **What is the expected behavior?**
Activate() on the child router should be called as if it's a standard navigation.

I am expecting something allong the lines of:
```
    window.addEventListener('hashchange', (event: HashChangeEvent) => {
      // Re-evaluate the current URL and navigate accordingly.
    });
```

* **What is the motivation / use case for changing the behavior?**
I would expect this to be standard framework behaviour. If there a workaround for now I'd be happy to use it. Also would create a PR if someone could direct me to where to start looking.

**Comment by CasiOo** [comment]
@jfstephe It is documented here http://aurelia.io/docs/routing/configuration#reusing-an-existing-view-model

**Comment by jfstephe** [comment]
@CasiOo - Thanks, I've used that a while ago but had forgotten it existed.

The documentation is very sparse but my understanding is that in either of the 2 activation strategies 'activate()' should be being called. In the scenario I'm describing it's not.

I'm basing this of [this information](https://stackoverflow.com/questions/39999969/how-to-set-default-activationstrategy-in-aurelia?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

**Comment by Alexander-Taran** [comment]
@jfstephe can this be closed?

**Comment by jfstephe** [comment]
Nope sorry. I don't see how changing the activation strategy would help me.

**Comment by davismj** [comment]
@jfstephe confirmed that @CasiOo's suggestion above works for you. Also, you can grab username from the params argument to activate.

```
import { activationStrategy } from 'aurelia-router';

export class Username {
   activate({ username }) {
     this.username = username;
  }
  
  determineActivationStrategy() {
    return activationStrategy.replace;
  }
}
```

**Comment by jfstephe** [comment]
@davismj - Thanks. Finally managed to confirm that this has fixed the issue.

The documentation around this is really really bad. References to navigation lifecycle (from the link kindly provided by @CasiOo - https://aurelia.io/docs/routing/configuration#reusing-an-existing-view-model) which can't be found in the search etc. If the documentation in that SO lin kI provided is wrong perhaps a link to the documentation that correctly, completely and clearly explains the lifecycle and what is re-run when etc would be useful?

Thanks again,
John
