### ISSUE TITLE
History must implement activate issue error

### ISSUE THREAD

**Issue by lancescole** [aurelia/router#599]
**I'm submitting a bug report**

I saw the same type of error at: https://github.com/aurelia/router/issues/572 
It is closed. I looked at the resolution and it changes some dependancies, so I tried that as well. Has this fix been pushed to production?

* **Library Version:**
1.5.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
9.2

* **NPM Version:**
6.0.0

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
Chrome 66 | Firefox 60 | Edge 41 | IE 11

* **Language:**
TypeScript 2.2

**Comment by Alexander-Taran** [comment]
yep. bootstrapper was released the same day those changes were merged
https://github.com/aurelia/bootstrapper/releases

**Comment by davismj** [comment]
@lancescole should be able to fix this by forcing an install of the latest history-browser. 

```
npm install aurelia-history-browser@1.1.0
```

**Comment by HasanAyan** [comment]
@davismj forcing reinstallation of aurelia-history-browser@1.1.0 didn't work for me. I still get the same error with aurelia-router@1.5.0 and had to revert it back to 1.4.0.

**Comment by davismj** [comment]
I've not heard a word about this since. I'm happy to revisit it if it is still in place. I've recently bootstrapped a few apps when testing other issues and haven't seen it so I'm guessing it was temporary.
