### ISSUE TITLE
Memory Leak in router / di

### ISSUE THREAD

**Issue by fragsalat** [aurelia/router#614]
**I'm submitting a bug report**

* **Library Version:**
1.6.2

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 18.04

* **Node Version:**
10.7.0

* **NPM Version:**
6.1.0

* **JSPM OR Webpack AND Version**
webpack used by aurelia cli

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Custom elements are not cleaned up by the garbage collector because the router / container doesn't release the references. Therefore every time the page is shown a new instance of the custom element is rendered. An example path looks like instruction.viewPortInstructions.default.controller.view.controllers[0].viewModel = CustomElement

**Expected/desired behavior:**
Custom elements should be de-referenced when calling unbind or deactivate so that the garbage collector can clean them up regardless how many times I navigate back and forward.

**Helpful**:
I prepared and tested based on a clean aurelia cli setup and just submitting everything. I uploaded the project here https://github.com/fragsalat/demos/tree/master/aurelia-memory-leak

**How to reproduce:**
- open http://localhost:8080
- take heap snapshot
- navigate to page2
- take heap snapshot
  - search for TestComponent
  - It's still there and referenced even if we left the previous page
- go back to page1
- take another heap snapshot
- compare difference between snapshot 1 and 3
  - search for TestComponent
  - You can see a delta of +1 and a deletion of 0

I hope you know what would be a good solution.
In my application several custom elements have a big tree and every page reload around 3mb are added to the heap^^

**Comment by huochunpeng** [comment]
I am no expert of this, but I think I can reproduce the issue, seeing JS Heap keep growing.

**Comment by fragsalat** [comment]
@EisenbergEffect @davismj ping

PS: @EisenbergEffect it would be nice to have a maintainers file in each repo to know who's responsible and to not ping you for every issue :D

**Comment by fragsalat** [comment]
I actually could find out that the cause of the memory leak is bluebird and not the router. Bluebird holds the navigationInstructions in a CaptureTrace object which is not cleared up.

**Comment by davismj** [comment]
@EisenbergEffect Yes, of course.

@fragsalat Thanks for the update! Appreciate the follow up.

**Comment by huochunpeng** [comment]
@fragsalat do you have a bug report to bluebird? or do you have some work around in aurelia app?
Since majority of aurelia apps use bluebird, this could affect many users.
