### ISSUE TITLE
An easier way to hide and show nav items using the router

### ISSUE THREAD

**Issue by Magrangs** [aurelia/router#65]
I have my main routes in app.js and I wanted a way to hide and show these from the nav based on certain criteria that would change over time (an example of this could be a login/register route which shows in the nav when logged in, but then not shown when you are logged in). When setting up the routes it would be great if the value of nav: boolean could be computed from a function - which is more than likely to be in the same file - (something which you can obviously already do) and then when you call router.refreshNavigation, this function be evaluated again and the value of nav change which would then reflect on the UI. I have a workaround for this in my app but I am not entirely happy with the implementation (using the additional settings you can supply with the router).

**Comment by Magrangs** [comment]
I think this can be done with a step in the navigation pipeline. So probably no need for this now.

**Comment by EisenbergEffect** [comment]
Routes can have custom settings, which is a perfect way to solve this.
