### ISSUE TITLE
Support lazy document.title updates

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#68]
I often want to update the document.title after navigation when data loads in a VM. For example, if I have a blog app with route `posts/:id` that routes to a `Posts` view model, I'll want to fetch the post from the server, and the update the document title with the post's title. It looks like right now the document title is calculated and committed in `NavigationContext.CommitChangesStep`. It would be great to split that logic out a bit so it could be easily run on demand from a `router` consumer, or easily customized if someone doesn't like the way titles are built by default.

**Comment by EisenbergEffect** [comment]
You can do this today by using the navModel. Have a look in the app-contacts sample. You will see in the contact-detail screen's activate how exactly what you describe is done.

**Comment by bryanrsmith** [comment]
Nice! Thanks for the pointer.
