### ISSUE TITLE
generating a sitemap with the router

### ISSUE THREAD

**Issue by mbroadst** [aurelia/router#71]
Hey,
I'm trying to create a sidebar with routes grouped under categories and couldn't find an immediate way to do so. The sidebar would look like:

```
Some Heading
   <route to page 1>
   <route to page 2>

Some Other Heading
   <route to page 3>
   <route to page 4>
```

When I asked this on gitter someone mentioned using nested routers, but it seems as if router.childRecognizer isn't populated until the actual route is activated. There seems to be two logical ways to represent this:

   * nested routers
   * a route config that takes a hierarchical object definition

Personally, I prefer the nested router approach, since I could easy move the definitions of my routes to sub folders where the logic for those specific "modules" exist. In either scenario it would be fantastics to be able to write e.g.

```
<div repeat.for="heading of router.navigation">
   ${heading}
   <li repeat.for="item of router.navigation[heading]">${item.label}</li>
</div>
```

Or something along those lines. Is something like this possible today?

**Comment by jdanyow** [comment]
@mbroadst can this be closed?  Sounded like you came up with a nice solution using the settings property and some converters.  :point_up: [April 20 2015 10:02 AM](https://gitter.im/Aurelia/Discuss?at=553506e90e3138bb6be89b82)

**Comment by mbroadst** [comment]
@jdanyow yeah we can, unless you want to keep this here for reference for potentially enhancing the routers configuration to handle this kind of scenario without valueConverters

**Comment by EisenbergEffect** [comment]
@mbroadst Do you have a blog or could I convince you to write a short article about what you did? I think the community would find it interesting.

**Comment by mbroadst** [comment]
@EisenbergEffect sure give me a couple hours. In the meantime, while this solution works for my needs today I still think it's worth discussing alternatives to this approach. I see a couple potential alternatives off the top of my head:

  * ```nav: true``` is already specified to include a route in some sort of navigation building logic, shouldn't it be able to build hierarchical models?

  * The real dream would be for me to specify child routers in each of my sub pages/modules. So "Some Heading" in the example given above would be in a folder called "some-heading", and "some-heading.js" within would contain a router indicating routes to "page1", "page1", etc.  In turn the top level app.js would be able to iterate through all those child routers to provide the "site map". TBH I haven't read through enough of your routing code to see why this isn't possible, but I gather that it's because you lazily load these child routers?

The problem I'm currently having is now associating an icon with each category. With the current approach it seems that I would have to modify my categories to look like: 
```javascript
   settings: { category: { name: "some heading", icon: "some-icon" } }
```
Which means I'd have to duplicate that data each time I assign a route to a category.

Thoughts?
