### ISSUE TITLE
Unconfigured child-router breaks navigation if named `router`

### ISSUE THREAD

**Issue by CharlesPockert** [aurelia/router#73]
Here's a strange one - so I injected a grandchild `Router` instance into a VM but didn't configure it - I wanted it just so I could call `router.navigate("childroute")` on it without needing to pass a router down from parent -> view - but it didn't work. 

Debugging it looks like in `navigation-plan.js` the plan is built for the child router even though it's not configured. This results in a route of blank "" being inspected by the navigation plan builder.

A similar issue was fixed in #34 but it looks like that fix only works (I may be wrong about this) for scenarios where you aren't calling `navigate` directly on an non-configured child router? 

Changing the name of my grandchild router to something other than `router` on the VM fixes the issue, however, to prevent a difficult to debug situation it might be worth adding a fix to the navigation plan builder code:

Adding a check to see if any child router is configured in `navigation-plan.js` seems to fix the issue:

```
 if (viewPortPlan.strategy !== REPLACE && prevViewPortInstruction.childRouter && prevViewPortInstruction.childRouter.isConfigured) {
 ```

This correctly prevents the unconfigured router from contributing to the navigation pipeline. Not sure if it's the right place though - is the router supposed to delegate any calls across gaps (i.e. should a configured router delegate navigation past an unconfigured router that sits between it and another configured one?)

**Comment by EisenbergEffect** [comment]
We are changing the way the router is configured in the next release, coming early this week. That should fix this issue.

**Comment by CharlesPockert** [comment]
Ah great can't wait! :)
