### ISSUE TITLE
API suggestion: merge params and queryString objects in activate and canActivate

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#74]
```javascript
activate(params, queryString, routeConfig)
```

I don't think there's any advantage to separating route params from query string params here. The view model classes generally aren't aware of the exact route pattern anyway, so I think it'd be better to hide that detail and simply provide a params object containing all route and query parameters. This is similar to how `router.generate()` now accepts a single params object and maps properties first into the path pattern, and then appends remaining params to the query string.

**Comment by EisenbergEffect** [comment]
Let's do it. I like that idea. Any notion of when you might have that ready? I'd like to do a release soon and want to try to stabilize the router's public usage scenarios soon if we can. Let me know.

**Comment by bryanrsmith** [comment]
I can get it done today, though I'm also going to propose a change to `navModel` for #69 that would also affect the signature of these methods, and would take me longer. I'll do my best to prioritize the API change work.
