### ISSUE TITLE
Make the handleLinkClick event listener configurable

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/router#80]
https://github.com/aurelia/router/blob/master/src/app-router.js#L15

This will have a 300 ms delay on touch devices. Would be nice to opt-in a function that could do it's own setup for handleLinkClick. Thoughts?

**Comment by stoffeastrom** [comment]
I guess you could inherit from AppRouter and override this behavior so maybe it's already configurable!

**Comment by bryanrsmith** [comment]
Sounds reasonable. It should be trivial to add a configurable `isLinkNavigationEnabled`, property and reorganize the current implementation to make the navigation logic available to an external consumer.

**Comment by jbellsey** [comment]
Any news on this? My issue (linked above) is awaiting this fix. Thank you!

**Comment by bryanrsmith** [comment]
Thanks for the bump @jbellsey. This will be customizable in the next release by registering a custom `LinkHandler` implementation with the DI container. 

```js
// this would go in your main.js below the aurelia.use.standardConfiguration() bits
aurelia.container.registerTransient(LinkHandler, FancyLinkHandler);
```

Here's the default implementation for reference: https://github.com/aurelia/history-browser/blob/master/src/link-handler.js#L22

**Comment by jbellsey** [comment]
Sweet! Look forward to the release (and the docs!).

**Comment by apatton724** [comment]
@bryanrsmith , (or anyone that can help) Can you please post an example of how to implement this?

I'm using bootstrap navigation and the <a> tag has to have 'href=#' for the data-toggle to work (it will automatically add a .dropdown-open class to the parent element; which is a <ul> tag).

I see you said we have to add that line to main.js. But do I have to import something as well? And how do I say: "If you run into a '#', don't navigate"?

Thanks!

**Comment by bsrdjan** [comment]
I registered the custom link handler and could not get it working as expected, here the [gist](https://gist.run/?id=02fdb05db44b1653dc293ae685a36b71).

When I click on anchor link, that should not be handled by the router, the scroll down to the target happens but the router is also activated and raises the `Error: Route not found: /bazinga`.

I would really appreciate help to get it work as expected.
