### ISSUE TITLE
Detect and avoid infinite redirects

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#84]
Reported via Gitter at https://gitter.im/Aurelia/Discuss?at=5547f7af00544af36bdf8b8f

If a route redirects to a second route, which fails to activate, the router navigates back to the original, entering an infinite redirect loop.

Probably low-priority, but would be good to detect and log a helpful error.

**Comment by bryanrsmith** [comment]
Note that this can also happen if the first route to be activated fails.

**Comment by olanod** [comment]
:+1: maybe add some event or callback when the route fails to activate.
I have a route, lets' say it's called `list` and a redirection from `''` to `'list'`. the list veiw model loads some data in the activate method returning a promise but when the promise is rejected it enters the infinte loop. I should be able to do somthing when the promise is rejected like redirecting somewhere else.   
Redirecting from the catch method of the promise returned in the `activate` callback didn't work
