### ISSUE TITLE
router-view and useShadowDOM

### ISSUE THREAD

**Issue by cehoffman** [aurelia/router#86]
When using elements with useShadowDOM with the router they do not have a shadow root created. I'm unsure of which component is at fault here, but since it happens in conjunction with the router I thought this might be the right place.

Also I noticed that the top level app, when used with aurelia-bootstrapper at least, does not get a shadow root either. Should I open an issue with aurelia-bootstrapper or aurelia-templating?

**Comment by EisenbergEffect** [comment]
Generally speaking, it's not a good idea to put your app inside of a shadow root. Also, you don't want to put "screens" inside of a shadow root either usually. It's something that should be reserved for controls/widgets. Bear in mind that this only really works on Chrome at this point. That said, we can look at improving this in a future iteration.

**Comment by cehoffman** [comment]
Is this true for child routers too? I want to make use of the strong encapsulation of components and css and I can understand the top level app not getting a shadow root with a router but any children should.

I'm currently trying to test, but I haven't gotten the child router to route yet.

**Comment by EisenbergEffect** [comment]
The router doesn't currently support shadow dom on the screens that it activates. We can look at enabling that for sure.

**Comment by cehoffman** [comment]
Ah I see what you were talking about screens now. Ok good to know. I'll look at compose to see if it does uses the shadow dom on the elements it creates. You can close this issue or keep it open to track.

**Comment by EisenbergEffect** [comment]
Compose works the same way. Dynamically created UI doesn't use shadow dom currently. We can make both work, if you want to create an issue for that. Create it on the templating-resources repo.
