### ISSUE TITLE
Support scheme, host, and port in route generation

### ISSUE THREAD

**Issue by davidpeden3** [aurelia/router#88]
It would be great to be able to pass a configuration object to `router.generate` that would enable fully qualified URIs to be rendered. As it is now, you only get a relative path (which is fine by default).

**Comment by EisenbergEffect** [comment]
@bryanrsmith How are we on this?

**Comment by jedd-ahyoung** [comment]
@bryanrsmith Currently, the router can track a baseUrl - but this isn't specifically a fully qualified URI. Do we want to use `window.location.origin` or `document.URL` for this? Using either of those would mean pulling in a dependency for `aurelia-pal`. Of note, certain browsers (IE) may have to be handled a bit differently.

**Comment by bryanrsmith** [comment]
I think we should add a new method to history & history-browser to get the root location. If I remember correctly, there's at least one other place in the router where we read `history._baseUrl` (which will break with any other history implementation). If we add a `history.getRoot()`, or `history.getBaseUrl()` we could use it here too.
