### ISSUE TITLE
Prefer stricter validation of route configs over guessing omitted values

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/router#94]
```javascript
config.map({ name: 'test', route: 'test/:id', moduleId: './test', title: 'Test' });
```

Currently *all* properties of a route config are considered optional.
* If `name` is omitted, it is derived from the title, route pattern, or module ID.
* If `route` is omitted, it is derived from module ID, or name.
* If `moduleId` is omitted, it is derived from the route pattern.
* If `title` is omitted, it is derived from the name (which may have been derived itself).

I think that deriving these values is too likely to cause confusing or undesirable behavior. For example, the error you'd get from a module load failure when we guessed the module ID would be hard to track down. Title is displayed to users, and probably shouldn't be set from code names like module IDs. We probably also shouldn't change the document title when the developer didn't ask us to.

I think it'd be better to remove all route property derivations, and instead validate the route config more strictly so we can provide helpful error messages up front for the required properties, and just omit the ones that should be optional (like title).

Thoughts?

**Comment by EisenbergEffect** [comment]
I agree. That's a hold over from Durandal. It's not much work to configure the route maps, so I think that we should make this more explicit.
