### ISSUE TITLE
Split query string parameters and route parameters.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/router#95]
The inverse of #74.

Unfortunately, I didn't know about #74 when it was being discussed else I would have mentioned this over there.  The problem with merging query string and route parameters is that query string parameters may include user input.  In particular, my user provides me with a set of key/value pairs that I want to encode in the query string (so they can easily link back to the current state).  By combining the query string parameters with the route parameters, the user may unintentionally collide with my route parameters (which they know nothing about).

**Comment by bryanrsmith** [comment]
Good point. Currently if there is a name collision the value from the route params will be chosen over the value from the query string.

`activate()` is passed a third parameter that is the navigation instruction, and the original separate objects are available on that. You should be able to use that to read your user input without fear of a collision. I think the merge simplifies the common case, so I'd like to keep it. This should certainly be documented, though.

```javascript
activate(params, routeConfig, navigationInstruction) {
  // navigationInstruction.params holds the route params
  // navigationInstruction.queryParams holds the query string params
}
```

**Comment by EisenbergEffect** [comment]
I agree, the merge is the common use case, but you can always get the other pieces from the navigation instruction.
