### ISSUE TITLE
Please consider attaching the Router to the NavigationInstruction passed into Activate()

### ISSUE THREAD

**Issue by davidpeden3** [aurelia/router#98]
See [here](https://gitter.im/Aurelia/Discuss?at=5553bb6999ddd5552722d941) for reference. Alternatively, pass the `Router` as a 4th parameter.

The use case is to navigate to another view in `activate()` if the result of an api call returns an error status code (e.g., 401/403/500).

**Comment by davidpeden3** [comment]
After looking at the API that `Router` exposes, it looks like it would be cleaner/better API design to proxy only the `navigate*()` and `generate` methods. Having an actual instance of `Router` would not be appropriate in `activate()`.

**Comment by davidpeden3** [comment]
And diving a bit deeper, it looks like an instance of a [`NavigationContext`](https://github.com/aurelia/router/blob/master/src/navigation-context.js#L4-L9) would be perfect instead of the existing `NavigationInstruction`.

**Comment by bryanrsmith** [comment]
`NavigationContext` has internal data and functionality that I don't think should be exposed outside of the router.

If you return a `Promise` from activate that rejects with a navigation command, the current navigation will be cancelled and the command will be executed.

```js
  activate(){
    return this.http.get(this.url).then(response => {
      this.data = response.content;
    }).catch(error => {
      return Promise.reject(new Redirect('/error'));
    });
  }
```

I do think we can make this a little easier to use -- maybe as part of #50. I also agree that passing a router to `activate` probably wouldn't be appropriate.

If you don't want to return the `Promise` from `activate` and the new navigation would take place after the last one has been committed, then I guess I think that you *should* have to inject the router. The navigation would be unrelated to the previous navigation and doesn't seem like it should be encouraged from the `activate` that ran as part of the previous navigation.

**Comment by bryanrsmith** [comment]
Also, if you don't want the actual router instance until you know you need it, you can use the `Lazy` resolver. http://aurelia.io/docs.html#dependency-injection
